### ISSUE TITLE
[Track2] Add the api.md generated by api extractor to published package

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1003]
api.md generated by api extractor is important for changelog detection tool. So it should be added in published package. However, it's ignored in packed tgz package. The "files" in package.json should includes api.md:

![image](https://user-images.githubusercontent.com/40835867/120438230-af260980-c3b3-11eb-9c96-126b9bf9db94.png)

**Comment by sarangan12** [comment]
Code Complete with https://github.com/Azure/autorest.typescript/pull/1007
