### ISSUE TITLE
Readme for mgmt pkgs should point to mgmt samples repo

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/autorest.typescript#1009]
Link:  https://github.com/Azure-Samples/azure-samples-js-management

This idea was discussed in https://github.com/Azure/autorest.typescript/issues/594

**Comment by deyaaeldeen** [comment]
Although, we would like the approach to samples to be unified between management-plane and data-plane one way or another, this is not yet a reality. JS will follow what Python does at the moment and point to the mono repo of management-plane samples.

**Comment by ramya-rao-a** [comment]
https://github.com/Azure-Samples/azure-samples-js-management is very specific to the mgmt plane packages. Do we already have a flag/argument that can be used to determine that the code generator is being used for mgmt plane packages as we wouldnt want this link to appear for other packages.

What is the plan in the auto rest crew for other languages here?

**Comment by deyaaeldeen** [comment]
@ramya-rao-a  Yes we have a flag for management-plane libraries, I think it is `--azure-arm`.

**Comment by sarangan12** [comment]
Code complete with https://github.com/Azure/autorest.typescript/pull/1098
