### ISSUE TITLE
Avoid `const enum` when generating extensible enums

### ISSUE THREAD

**Issue by maorleger** [Azure/autorest.typescript#1013]
I recently generated `@azure/keyvault-admin` using `v6.0.0-alpha.20210527.9` and the extensible enums were generated as:

```ts
/** Known values of {@link RoleScope} that the service accepts. */
export const enum KnownRoleScope {
  /** Global scope */
  Global = "/",
  /** Keys scope */
  Keys = "/keys"
}

/**
 * Defines values for RoleScope. \
 * {@link KnownRoleScope} can be used interchangeably with RoleScope,
 *  this enum contains the known values that the service supports.
 * ### Know values supported by the service
 * **\/**: Global scope \
 * **\/keys**: Keys scope
 */
export type RoleScope = string
```

Since `const enum`s are erased at compilation (and the TS compiler will inline the strings) it makes them unusable using vanilla JS.

Should we use `enum` instead of `const enum` and pay the extra generated code cost so that vanilla JS can use the known values?

A few areas where I bumped against this:
- V2 samples flow - we write them using TypeScript and dev-tool will generate runnable JavaScript. If we reference an enum value the generated JS samples will not work out of the box.
- I checked and I believe `const enum` is discouraged in our guidelines https://azure.github.io/azure-sdk/typescript_design.html#ts-no-const-enums so we would need to do something else in code before exposing these.

**Comment by sarangan12** [comment]
Code complete with PR https://github.com/Azure/autorest.typescript/pull/1097
