### ISSUE TITLE
Add note to readme pointing people interested in v4 to the right place

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/autorest.typescript#1017]
This repo has been the house for the v4 code generator which has a different package name than our v6 code generator which is now in the master branch.

For those customers landing here looking for v4, we should add a pointer to the readme of the v4 branch.
A small description of the difference would be useful to add in the v6 readme.
Also a disclaimer that v6 is still in preview

And we should do vice versa i.e. add pointer to v6 from v4 for anyone interested in checking out our new work.

**Comment by sarangan12** [comment]
Code complete with PR https://github.com/Azure/autorest.typescript/pull/1107
