### ISSUE TITLE
Question: How to use HMAC signature in generated client code to sign the requests?

### ISSUE THREAD

**Issue by marche0133** [Azure/autorest.typescript#1020]
I used autorest to generate ts client code from swagger definition. I need to sign the requests to REST API using the HMAC signature. The generated signature will be added to each request in a custom authorization header.
How can I achieve this using autorest? set add-credentials: true?

**Comment by sarangan12** [comment]
No more action items pending on this issue. If you still face any issues, please reopen the issue. Thanks
