### ISSUE TITLE
Dropping support for Node.js versions that have reached end of life

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/autorest.typescript#1021]
Our [support policy](https://github.com/Azure/azure-sdk-for-js/blob/master/SUPPORT.md#microsoft-support-policy) does not guarantee support for Node.js versions that have reached end of life.

We have the below generated in the readme when using the v4 code generator

```
### Currently supported environments

- Node.js version 6.x.x or higher
- Browser JavaScript
```

This should be replaced with

```
### Currently supported environments

- [LTS versions of Node.js](https://nodejs.org/about/releases/)
- Latest versions of Safari, Chrome, Edge and Firefox.
```

In the v6 code generator, in addition to the above, the `engines` field in the generated package.json file should use `>=12.0.0` instead of `>=8.0.0`

**Comment by ramya-rao-a** [comment]
@deyaaeldeen Can you update https://github.com/deyaaeldeen/azure-sdk-for-js/blob/master/common/tools/add-identity-mgmt-lib.js as well?

**Comment by deyaaeldeen** [comment]
@ramya-rao-a done: https://github.com/Azure/azure-sdk-for-js/pull/15648.

**Comment by deyaaeldeen** [comment]
code complete
