### ISSUE TITLE
Add CHANGELOG.md to published package

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1028]
This is a new requirements, which similar to https://github.com/Azure/autorest.typescript/issues/1003

- `CHANGELOG.md` will be included to indicate what changes happen in the new released package.

**Comment by dw511214992** [comment]
@ramya-rao-a @sarangan12 please pay attention to this featuer request. thanks

**Comment by ramya-rao-a** [comment]
> CHANGELOG.md will be included to indicate what changes happen in the new released package.

What is the expectation here? Generating a blank file initially if it does not exist? Generating a file with placeholder for the current version? Or generating the changelog contents describing the change?

**Comment by ramya-rao-a** [comment]
> api-extractor.json is used to generate review/xxx.api.md. I think we should include it in the published package and then user can rebuild the package downloaded from NPM.

@dw511214992 Are you saying that after downloading a package from npm, a user might want to go to the the downloaded package in the `node_modules` folder and run our `build` script? Can you provide details on what purpose does this serve?

> _meta.json will be included to record the details of how to generate the sdk, such as git commit id, readme.md, autorest_command, etc.

This information is useful to the package owner. How is this useful to the end user?

**Comment by dw511214992** [comment]
Hi @ramya-rao-a  About the reason of adding `api-extractor.json` and `_meta.json`, I just think it's better to get all the information from the downloaded package. If you think we only need to add necessary files for end user, I also think it's fine and I'll change this issue.
About the `CHANGELOG.md`, we don't need to generate it in Codegen. It will be generated in pipeline, which keeps the same as python sdk. So, in codegen side, we only need to add it to the published package.
Thanks

**Comment by ramya-rao-a** [comment]
Thanks for the clarification @dw511214992!

**Comment by sarangan12** [comment]
Code complete with PR https://github.com/Azure/autorest.typescript/pull/1052. Closing this PR
