### ISSUE TITLE
[Track1] The generated package.json has wrong homepage and misses autoPublish

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1038]
In https://github.com/Azure/azure-sdk-for-js/pull/15767 and https://github.com/Azure/azure-sdk-for-js/pull/15583, the generated package.json has wrong homepage and misses autoPublish. 
To fix it in js sdk, I create a PR: https://github.com/Azure/azure-sdk-for-js/pull/15768

**Comment by ramya-rao-a** [comment]
@dw511214992 Can you share the exact command you used to generate the package? And which version of the code generator did you end up using?

**Comment by dw511214992** [comment]
Hi @ramya-rao-a The PR is generated by @sarangan12. @sarangan12 Could you please provide the command you used?

**Comment by deyaaeldeen** [comment]
@sarangan12 I added some logic in the readme file generator to calculate the this URL, you could use that to populate this field in `package.json` as well.

**Comment by sarangan12** [comment]
I have made sure `autopublish` is correctly generated for Track 2 packages. For Track 1, I agree we need to fix it. But, since we have already decided that the new packages are not going to be released in Track 1 (unless they have exceptions) So, this issue happening in Track 1 is rare. Moving this issue to backlog based on issue priority.

**Comment by deyaaeldeen** [comment]
Oh I did not notice this is for Track1, ignore my comment earlier then.

**Comment by dw511214992** [comment]
@sarangan12 what's value of `autopublish` you set in the track2 sdk? we will use the same release pipeline as dataplane, so I think the value should also be the same as dataplane's. thanks

**Comment by ramya-rao-a** [comment]
We do not need the autoPublish field in Track 2 packages.

@dw511214992 Are you still seeing the issue of missing autoPublish field for Track 1 packages?

**Comment by sarangan12** [comment]
I have checked and able to confirm autoPublish is getting generated correctly for Track 1 packages. Closing the issue
