### ISSUE TITLE
GeneratedClient constructor should not mutate the options bag

### ISSUE THREAD

**Issue by jeremymeng** [Azure/autorest.typescript#1039]
my convenience layer code creates two clients using the same options bag:
```ts
     const authClient = new GeneratedClient(endpoint, internalPipelineOptions);
     this.client = new GeneratedClient(endpoint, internalPipelineOptions);
```
It leads to duplicate library infor in user-agent header for the second client because the generated client's constructor updated  options.userAgentOptions.userAgentPrefix.  I fixed it by

```diff
-    options.userAgentOptions = {
-      userAgentPrefix: userAgentPrefix
-    };
-
     const optionsWithDefaults = {
       ...defaults,
       ...options,
+      userAgentOptions: {
+        userAgentPrefix
+      },
       baseUri: options.endpoint || "{url}"
     };
```

**Comment by sarangan12** [comment]
Code complete with https://github.com/Azure/autorest.typescript/pull/1042. Will be included in the next release.
