### ISSUE TITLE
Update latest version to be v6

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/autorest.typescript#1041]
This repository house 2 packages that work with `autorest` in different branches, both generate TS SDKs for given swagger file input
- The `v4x` and `v5x` branches house v4 and v5 of the [@microsoft.azure/autorest.typescript](https://www.npmjs.com/package/@microsoft.azure/autorest.typescript) package
- The `main` branch houses the new package [@autorest/typescript](https://www.npmjs.com/package/@autorest/typescript)

We started out the new package using the version 6 to ease conversations and discussions around the different versions rather than speaking in terms of different packages themselves and thus started publishing nightly builds to npm using v6-alpha versions. We have used the term v6 in labels, issues and PRs

At some point a few months ago when we were ready to do our first beta for the new package, we chose to start from version 1 because it was a brand new package. This has caused quite some confusion along the lines. After another round of discussions, we have decided to continue with v6.

This issue is to ensure
- We have nightly builds published to npm using v6 for `@autorest/typescript`
- The next preview for `@autorest/typescript` package uses v6
- The [GitHub releases](https://github.com/Azure/autorest.typescript/releases) for this repo reflect the above.

**Comment by sarangan12** [comment]
1. Nightly Builds are set to release to npm.
2. Version is changed to 6.x.x version
3. Removed the Github releases since we have nightly releases directly to npm.

**Comment by ramya-rao-a** [comment]
Thanks @sarangan12 

> Removed the Github releases since we have nightly releases directly to npm.

Does that mean that we will have tags corresponding to each release?

![image](https://user-images.githubusercontent.com/16890566/126409911-c8694091-376e-494b-92c2-9d2e378e3205.png)

**Comment by sarangan12** [comment]
We will not have any tags corresponding to each release in github. It will be released only to github. I time boxed it to two days and the github release code still seems to have issues. So, I disabled that part of the code. If you still want the github tags, I can continue working on it.

**Comment by ramya-rao-a** [comment]
Great!
