### ISSUE TITLE
--enum-types seems dont supported in recent versions

### ISSUE THREAD

**Issue by wingrime** [Azure/autorest.typescript#1047]

**Comment by sarangan12** [comment]
@wingrime With the latest code generator, if the enum is not extensible (i.e. if no new values are to be added to the enum value), the default behavior is to generate it as enum (which is also the behavior of `--enum-types`). 

Is there any specific behavior you are missing with the new generator? If so, Could you please provide a specific scenario/swagger code?

**Comment by TempleOfTemplar** [comment]
i'll try to explain.
Using this config:
`{
  "input-file": "./swagger.json",
  "output-folder": "auto-generated-api",
  "clear-output-folder": true,
  "allow-insecure-connection": true,
  "typescript": true,
  "namespace": "Base",
}
`
Autorest generates enums like this: 
`/** Known values of {@link Currency} that the service accepts. */
export const enum KnownCurrency {
  Rub = "rub",
  Usd = "usd"
}

/**
 * Defines values for Currency. \
 * {@link KnownCurrency} can be used interchangeably with Currency,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **rub** \
 * **usd**
 */
export type Currency = string;`

What do i expect:
`export const enum Currency {
  Rub = "rub",
  Usd = "usd"
}`

**Comment by sarangan12** [comment]
@TempleOfTemplar Thanks for explaining your requirement. With the recent versions, we are not using the `const enum`s anymore. Instead, we have used the `type` approach. 

Let me give an example. If the swagger definition is:

```json
.....
.....
"Currency": {
    "type": "string",
    "enum": ["USD", "RUB"]
},
.....
.....
```

The above code will produce SDK code as:

```js
/** Known values of {@link Currency} that the service accepts. */
export const enum KnownCurrency {
  USD = "USD",
  RUB = "RUB"
}

export type Currency = string;
```

Now, If I modify the swagger as the following:

```json
.....
.....
"Currency": {
    "type": "string",
    "enum": ["USD", "RUB"],
    "x-ms-enum": {
        "name": "Currency",
        "modelAsString": false
    }
},
.....
.....
```

The above code will produce SDK code as:

```js
export type Currency = "USD" | "RUB";
```

Will this be acceptable?

**Comment by TempleOfTemplar** [comment]
@sarangan12 Unfortunately, I can hardly imagine what advantages this approach provides in my case( except for the need for massive rename of enams throughout the code. Maybe for those who would like to use just enams - can you make some kind of flag?

**Comment by TempleOfTemplar** [comment]
@sarangan12 Unfortunately, I can hardly imagine what advantages this approach provides in my case( 
The disadvantage is the requirement for bulk renaming of enums throughout the whole project. Maybe for those who want to use just enam - can you make some kind of flag? Maybe for those who would like to use just enams - can you make some kind of flag?

**Comment by sarangan12** [comment]
@TempleOfTemplar Currently, we do not have plans to add flags for going back to enums. But, I will keep this in our backlog for further discussion with my team. Thanks

**Comment by sarangan12** [comment]
After further deliberation, it has been decided that this flag will not be added back. Resolving this issue
