### ISSUE TITLE
[Track 2] Add sdk-type in package.json

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1049]
This feature request comes from https://github.com/Azure/azure-sdk-for-js/commit/7026a578a61bc4d9332131c9ff47c2f84ed39b05#r52479640

As the `sdk-type` already exsits in dataplane sdk, can we also add it in mgmt plane sdk?

cc: @ramya-rao-a @sarangan12

**Comment by sarangan12** [comment]
Code complete with PR https://github.com/Azure/autorest.typescript/pull/1074
