### ISSUE TITLE
Ability to define custom types

### ISSUE THREAD

**Issue by davidyuk** [Azure/autorest.typescript#1053]
In our project, we have numbers about 32-bytes long, for compatibility reasons they are encoded as strings. We would like to have them wrapped in instances of [BigNumber](https://www.npmjs.com/package/bignumber.js) in the call results and to convert BigNumber to string in call arguments. I'm looking for how to implement it the best way.

As I see, [`getTypeForSchema`](https://github.com/Azure/autorest.typescript/blob/b1d23665ff4f4e292d1f7336125d1dcd370d4d18/src/utils/schemaHelpers.ts#L64-L195) doesn't support custom types as well as [`serializer`](https://github.com/Azure/azure-sdk-for-js/blob/d79be18f1fdd5542189bfa88abbe9da1fec5fc08/sdk/core/core-client/src/serializer.ts#L106-L204) in `@azure/core-client`. So far I got a working prototype by rewriting generated code using regexps, and adding a patch to core-client for the handling of custom mappers. Would be nice to have a way to implement it through the autorest configuration file, without making changes to core-client.

similar to https://github.com/Azure/autorest/issues/2593

**Comment by sarangan12** [comment]
@davidyuk This is really interesting problem. Now, there are 2 options that I can suggest:

1. This option is just as you mentioned. But, it requires changes to `@azure/core-client`. If this is the case, I would recommend you to raise this issue in the https://github.com/Azure/azure-sdk-for-js. Then the generator could make the changes accordingly. But, such changes would be done based on our backlog and priority. 
2. The second option is to create a custom layer on top of the generated code. For example, refer the code generated in https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/search/search-documents/src. The `generated` folder has the generated code. On top of the generated code, you could have a custom layer (where you will do the BigNumber->String mappings and vice-versa). 

Let me know your thoughts on getting a custom layer for your code.

**Comment by sarangan12** [comment]
Closing this issue for now. If you still have any more questions, feel free to reopen the issue.
