### ISSUE TITLE
[Rest Level Client] TestServer coverage for custom-baseurl

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#1057]
https://github.com/Azure/autorest.testserver/blob/main/swagger/custom-baseUrl.json

**Comment by joheredi** [comment]
We need to define what's the UX we want to provide for this scenario where the BaseURL is parametrized:

It takes as a client parameter the `{host}` part and as a method parameter the `{accountName}` part.



In HCL we call it like this

```typescript
const client = new CustomURLClient("host:300");
await client.paths.getEmpty("local")
```


And ends up building http://localhost:3000 as base url.

In RLC I was thinking we can still take the `{host}` part in the client. And the {accountName} as a  `urlParameter` option in the get call


```typescript
const client = CustomUrl("host:3000");
await client.path("/customuri").get({urlParameters: { accountName: "local"} })
```

Maybe we could also add it as a required positional param, but it is not going to the path so it may not be evident where it goes and it may get a bit confusing when the path also has params

```typescript
const client = CustomUrl("host:3000");
await client.path("/customuri", "local").get()
```

**Comment by joheredi** [comment]
@bterlson, @xirzec do you have any preference on the above. I think I like the urlParameters option.

**Comment by xirzec** [comment]
I also like the `urlParameters` option, since it feels more explicit

**Comment by bterlson** [comment]
I like the option approach, but I think `pathParameters` is a more recognizable name for this, if I'm not misunderstanding anything?
