### ISSUE TITLE
[Rest Level Client] Test Server coverage for lro

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#1060]
https://github.com/Azure/autorest.testserver/blob/main/swagger/lro.json

**Comment by deyaaeldeen** [comment]
FYI: `LroEngine` already gets tested against most of the routes in the lro server here: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-lro/test/engine.spec.ts. Note that the tests use a clone of the test server lro routes and does not run the server itself.
