### ISSUE TITLE
[Track2] Generated codes by latest codegen compile failed

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1066]
generated codes: https://github.com/Azure/azure-sdk-for-js/tree/5e3b6d37d570ba71a421c28de58b60a639f3c34e/sdk/iotspaces/arm-iotspaces
command:
```
rush update
node common/scripts/install-run-rush.js build --from @azure/arm-iotspaces --verbose -p max
```
Compile Error:
```
Invoking: tsc && rollup -c rollup.config.js && npm run minify && mkdirp ./review &&  npm run extract-api

src/ioTSpacesClient.ts(1,27): error TS2307: Cannot find module '@azure/core-auth' or its corresponding type declarations.
src/ioTSpacesClientContext.ts(2,27): error TS2307: Cannot find module '@azure/core-auth' or its corresponding type declarations.
src/lro/operation.ts(4,33): error TS2307: Cannot find module '@azure/abort-controller' or its corresponding type declarations.
```

**Comment by dw511214992** [comment]
cc @ramya-rao-a @sarangan12

**Comment by sarangan12** [comment]
@dw511214992 I am investigating this issue. I will get back to you shortly

**Comment by ramya-rao-a** [comment]
@sarangan12 In case you are updating the dev dependencies as part of this issue, also include updating `@types/node` to `^12.0.0` as we are moving away from Node.js 8 support. I am doing this change in the azure-sdk-for-js repo as par tof https://github.com/Azure/azure-sdk-for-js/pull/15996

**Comment by sarangan12** [comment]
@dw511214992 There is an issue with packagefilegenerator code that does not include the core-auth package in the package.json file. I will get the fix in and include it on Tuesday's release. 

One thing that was surprising for me in your code. I am checking the link here: https://github.com/Azure/azure-sdk-for-js/tree/5e3b6d37d570ba71a421c28de58b60a639f3c34e/sdk/iotspaces/arm-iotspaces Here, there is no `lro` folder under `src` folder. (Which is correct and as expected)

But, your error message (in the first comment above), I see the following line:
```
src/lro/operation.ts(4,33): error TS2307: Cannot find module '@azure/abort-controller' or its corresponding type declarations.
```

Where is this line coming from? 

For your reference, I generated the package using the following command:

```
autorest --typescript --input-file=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/iotspaces/resource-manager/Microsoft.IoTSpaces/preview/2017-10-01-preview/iotspaces.json --azure-arm=true --package-name=@azure/arm-iotspaces --generate-metadata=true --clear-output-folder=true --output-folder=C:\Users\sarajama\Projects\azure-sdk-for-js\sdk\iotspaces\arm-iotspaces
```

**Comment by dw511214992** [comment]
sorry @sarangan12 It seems I give you a wrong link and the correct one is: https://github.com/Azure/azure-sdk-for-js/tree/ea962e606c59ee8b075fe5abf971b84dcdf4ad39/sdk/iotspaces/arm-iotspaces.
If you want to reproduce it you local, you need to revert your azure-rest-api-specs to commit id `f7535f8211b7fe9a8d5e5ebdc09830677b55285c` because the swaggers in iotspaces are deleted.

**Comment by sarangan12** [comment]
@dw511214992 Thanks for the link. But, still if I have to reproduce it locally by regeneration, I do not get the lro folder. (And I do not see any lro op in swagger). So, can you tell me how you regenerated this? (Irrespective of that my fix will cover the scenario. But, I just wanted to make sure of the process)

**Comment by sarangan12** [comment]
Code complete with PR https://github.com/Azure/autorest.typescript/pull/1082
