### ISSUE TITLE
[Track2] generated readme.md has a sample link, which is invalid

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1067]
The generated README.md has a sample link, for example:
```
## Next steps

Please take a look at the [samples](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/iotspaces/arm-iotspaces/samples) directory for detailed examples on how to use this library.
```
```
[Samples](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/iotspaces/arm-iotspaces/samples)
```
Actually, management palne sdk doesn't have sample.

**Comment by dw511214992** [comment]
cc @ramya-rao-a @sarangan12

**Comment by ramya-rao-a** [comment]
@dw511214992 That is the expected link for the data plane libraries where we expect the sample to exist in the same folder as the source code.

For mgmt plane packages, we can use #1009 to track the need to use the sample samples link across packages instead.

**Comment by dw511214992** [comment]
@ramya-rao-a agreed.
