### ISSUE TITLE
[Track2] The generated package.json doesn't include "pack" in script

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1068]
This error is reported by pipeline:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=964510&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=4fc2278e-dafd-525f-7501-d396c9a4758e

I make a quick fix manaully:
![image](https://user-images.githubusercontent.com/40835867/123272530-684fad80-d534-11eb-8617-6744424cfc2e.png)
cc: @ramya-rao-a @sarangan12

**Comment by ramya-rao-a** [comment]
Closing in favor of #1072
