### ISSUE TITLE
[Track2] Some commands are missed in "scripts" of package.json

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1072]
Missed commands (Some of them are created github issues to track):
pack https://github.com/Azure/autorest.typescript/issues/1068
lint https://github.com/Azure/autorest.typescript/issues/1069
format https://github.com/Azure/autorest.typescript/issues/1070
check-format
build:samples https://github.com/Azure/autorest.typescript/issues/1071
build:test https://github.com/Azure/autorest.typescript/issues/1071
unit-test:node
echo skipped

Fix Suggestion:
The `pack` should be fixed with correct value. The others' value can be "echo skipped".

**Comment by dw511214992** [comment]
cc: @ramya-rao-a @sarangan12

**Comment by sarangan12** [comment]
Code complete with https://github.com/Azure/autorest.typescript/pull/1074. Will be released on Monday
