### ISSUE TITLE
[Track2] Disscussion: Is there any issues when we change the dependency version of generated codes manually

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1080]
hi @ramya-rao-a @sarangan12 

As we discussed in https://github.com/Azure/autorest.typescript/issues/1048, we will change the dependency version of generated codes manually. However, I worry whether there is any issues because some dependencies' version are bumped and some ones' are downgraded.
I think we need to do some more test with the updated dependency version.

cc: @lirenhe

**Comment by ramya-rao-a** [comment]
@dw511214992 We have already logged #1054 which was linked from #1048 for this purpose. Can we use that issue and close this one instead?

**Comment by dw511214992** [comment]
@ramya-rao-a sure.
