### ISSUE TITLE
[Track2]Depended packages are unpublished to NPM

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1084]
We are testing the latest Codegen. To build it with rush, we update the dependencies manually:\
```
    "@azure/core-client": "^1.0.0"
    "@azure/core-lro": "^2.0.0"
    "@microsoft/api-extractor": "7.7.11"
    "typescript": "~4.2.0"
    "tslib": "^2.2.0"
    "@azure/core-rest-pipeline": "^1.1.0"
```
And then we get the packed package. However, when we try to install the package, we get error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @azure/core-rest-pipeline@^1.1.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@azure/arm-compute'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\weidong\AppData\Roaming\npm-cache\_logs\2021-06-29T08_58_07_461Z-debug.log
```
It seems the depended libraries haven’t been published to NPM.

So when will you publish these packages? Thanks

**Comment by dw511214992** [comment]
cc: @ramya-rao-a @sarangan12

**Comment by sarangan12** [comment]
@dw511214992 In the code generation, I am able to see that `@azure/core-rest-pipeline` package depends only on the `^1.0.4` version. You can find it [here](https://github.com/Azure/autorest.typescript/blob/main/src/generators/static/packageFileGenerator.ts#L150).

Why are you updating it manually as `"@azure/core-rest-pipeline": "^1.1.0"`? That version has not been released yet. Based on my recent discussion with Maor, that version will be released only next week.

**Comment by dw511214992** [comment]
@sarangan12 As we disscussed before, to manage the generated codes with rush, we need to change the dependency version manually to keep consistent with dataplanes' dependencies.

**Comment by sarangan12** [comment]
@dw511214992 I see the problem now. Did you update the package in rush.json file? You should update the package in rush.json, then execute rush update and then rush build. That should resolve this issue.

Could you please try it?

**Comment by dw511214992** [comment]
@sarangan12 yes, I have updated the rush.json and the package can be built and packed successfully under the directory of `azure-sdk-for-js`. However, when I want to install the packed tgz package in another project, it fails. I think customer uses our libraries in this way, instead of using it in  `azure-sdk-for-js`

**Comment by sarangan12** [comment]
@dw511214992 Normally, You are correct. The customer will use the package in the way you just described and he/she will face the problem if they tried it now. But, no package will be/should be released if the underlying dependency is not released. This package should be released only after the core-rest-pipeline package is released. 

Until then it cannot be released. In the meantime, for your testing, you could do `npm pack` on core-rest-pipeline package also and use it in your test project. 

But, You have raised a very valid concern. It might not be possible to keep track of core package releases with lot of management libraries. I will talk with Maor in the morning and see if there is a solution here. Thanks

**Comment by dw511214992** [comment]
thanks @sarangan12 we are planing release track2 js sdk for 4 RPs in next week. so we hope these packages can be released as early as possible.
I think we shouldn't update the dependencies' version of dataplane sdk if the libraries are not published to NPM.

**Comment by ramya-rao-a** [comment]
@sarangan12, @dw511214992 This is no longer a problem, correct? All dependent core packages are now released

**Comment by sarangan12** [comment]
@ramya-rao-a Yes. The dependent packages are released. Closing this issue.
