### ISSUE TITLE
[Track2] The generated codes compile failed

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1085]
When I generate codes for RP network with tag `package-2021-02`, the generated codes compile failed. Before generating codes, please change the readme.typescript.md because of https://github.com/Azure/autorest.typescript/issues/880:
![image](https://user-images.githubusercontent.com/40835867/123810951-67988c00-d925-11eb-9ebd-fc6bacf87582.png)

Also, please set the `typescript-sdks-folder` to the path of `azure-sdk-for-js` when you run autorest command.

The error is following:
```
src/operations/index.ts(98,15): error TS1261: Already included file name 'D:/projects/azure-sdk-for-js/sdk/network/arm-network/src/operations/p2SVpnGateways.ts' differs from file name 'D:/projects/azure-sdk-for-js/sdk/network/arm-network/src/operations/p2sVpnGateways.ts' only in casing.
  The file is in the program because:
    Imported via "./p2SVpnGateways" from file 'D:/projects/azure-sdk-for-js/sdk/network/arm-network/src/operations/index.ts'
    Matched by include pattern './src/**/*.ts' in 'D:/projects/azure-sdk-for-js/sdk/network/arm-network/tsconfig.json'
src/operations/index.ts(100,15): error TS1261: Already included file name 'D:/projects/azure-sdk-for-js/sdk/network/arm-network/src/operations/virtualHubRouteTableV2S.ts' differs from file name 'D:/projects/azure-sdk-for-js/sdk/network/arm-network/src/operations/virtualHubRouteTableV2s.ts' only in casing.
  The file is in the program because:
    Imported via "./virtualHubRouteTableV2S" from file 'D:/projects/azure-sdk-for-js/sdk/network/arm-network/src/operations/index.ts'
    Matched by include pattern './src/**/*.ts' in 'D:/projects/azure-sdk-for-js/sdk/network/arm-network/tsconfig.json'
```
The file name in `index.ts` differs from the file name only in casing.

However, when I delete the folder `arm-network` manaully and re-generate the codes, everything is fine. I cannot understand what happened. 

Does the codegen check the exisiting codes in generating codes?

Please check it. thanks

@ramya-rao-a @sarangan12

**Comment by sarangan12** [comment]
I am looking into this issue. I will update you soon

**Comment by dw511214992** [comment]
it seems git ignores the File name case changes, which leads to this issue. It should be the root cause
