### ISSUE TITLE
Reduce CI validation duration

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#109]
Make the CI go faster. It's a bottleneck right now. Not a big one, but it is a bottleneck.

**Comment by RikkiGibson** [comment]
Wondering if some phases of our CI are parallelizable: https://docs.microsoft.com/en-us/vsts/pipelines/licensing/concurrent-jobs-vsts?view=vsts

18 minutes is rough.

**Comment by daschult** [comment]
I agree that 18 minutes is bad. Doing some things in parallel would be great, but I wonder why our `npm install` is taking about 7 minutes. That was going to be my first thing to check.

**Comment by daschult** [comment]
I'm not really seeing any easy ways to reduce this duration. It looks like we don't have any NPM package dependencies we can easily remove. We could try parallelizing some of our test tasks, but I'd be worried about their console output mixing and making debugging really difficult. I think we're just kind of stuck with a slow CI for now.
