### ISSUE TITLE
[Track2] Change the tsconfig.json, package.json and README.md according to PR comments

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1091]
@deyaaeldeen add some suggestions on changing the package.json and README.md in PR: https://github.com/Azure/azure-sdk-for-js/pull/16170 and https://github.com/Azure/azure-sdk-for-js/pull/16207. Please change the codegen. thanks
cc: @sarangan12 @ramya-rao-a

**Comment by qiaozha** [comment]
close it as pr merged.
