### ISSUE TITLE
[Track2] Shouldn't run "npm install" in prepack

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1094]
We are using rush to  manage our sdks, so we shouldn't run "npm install" in prepack. "npm install" leads to the failure of ci pipeline.
You can refer to this [commit](https://github.com/Azure/azure-sdk-for-js/pull/16170/commits/ad5137bf6566465fbd0ecc7165da048932f7a378) as an example.

@sarangan12 @ramya-rao-a

**Comment by sarangan12** [comment]
Code changes complete with PR
