### ISSUE TITLE
Remove additional licensing comments

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest.typescript#1105]
In the generated SDK, all the files insider LRO folders have 2 sets of License comments on top such as:

```
+/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

// Copyright (c) Microsoft Corporation.
```

The one in the top must be used. The one at the bottom could be removed.

**Comment by deyaaeldeen** [comment]
Just a heads up: the LRO folder will be deleted soon.

**Comment by sarangan12** [comment]
Will wait until the release. After the release, this task can be closed.

**Comment by deyaaeldeen** [comment]
code complete after v6-beta.8 has been released: https://www.npmjs.com/package/@autorest/typescript/v/6.0.0-beta.8
