### ISSUE TITLE
lro can't work correctly with latest @autorest/typescript@6.0.0-beta.8

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1117]
we use the latest beta version 6.0.0-beta.8 to generate @azure/arm-compute package. and found out the lro can not working correctly. we also tried the latest dev version 6.0.0-alpha.8.20210721.1 of @autorest/typescript still not working. 

here's the autorest command and input 
```
{
  "commit": "d241e05b224891ddc0147544213d8edccf53f7d9",
  "readme": "specification/compute/resource-manager/readme.md",
  "autorest_command": "autorest --version=3.1.3 --typescript --modelerfour.lenient-model-deduplication --head-as-boolean=true --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=/Users/zhangqiaoqiao/work/code/azure-sdk-for-js ../azure-rest-api-specs/specification/compute/resource-manager/readme.md --use=@autorest/typescript@6.0.0-beta.8",
  "repository_url": "https://github.com/Azure/azure-rest-api-specs.git",
  "use": "@autorest/typescript@6.0.0-beta.8"
}
```

here's the code for repro:
```
import { ComputeManagementClient, Disk } from "@azure/arm-compute";
import { DefaultAzureCredential } from "@azure/identity";

const subscriptionId =  process.env.SubscriptId;
const credential = new DefaultAzureCredential();


/**
 * Class Test_AvailabilitySets.
 */
class Test{ 
    private client = new ComputeManagementClient(credential, subscriptionId);
    private resourceName = "qiaozhatest";
    private availabilitySetName = "availabilitySetss";
    private location = "eastus";

    //createOrUpdate
    public async test_disks_createOrUpdate(){

        const parameter: Disk ={
            location: "eastus",
            creationData: {
                createOption: "Empty"
            },
            diskSizeGB: 200
        };

        await this.client.disks.beginCreateOrUpdateAndWait("myjstest","disknamex",parameter).then(
            response => {
                console.log(response)
            } 
        )
    }
}

const t = new Test();
console.log(t.test_disks_createOrUpdate());
```

here's the result we get
![image](https://user-images.githubusercontent.com/55688292/126633408-19dc7f03-77f8-451d-bfb0-d5777affee9a.png)

**Comment by joheredi** [comment]
@deyaaeldeen would it be that the body is not being cleared when sending the poll requests?

**Comment by deyaaeldeen** [comment]
@qiaozha thanks for filing the issue and including those details.

@joheredi I think you're right. We used to clear them here: https://github.com/Azure/autorest.typescript/blob/51ed88b0719ce89c001a58330f6566d05b83bb64/src/lro/pollingMethod.ts#L52 but I stopped doing that here https://github.com/Azure/autorest.typescript/blob/c4c682a63a3995addbc5eb4d765416358b43b3c2/src/lroImpl.ts#L133 because tests were passing anyway. I think we should add a route to the autorest test server to check for this behavior.
