### ISSUE TITLE
Profile support - custom packages with models from many services

### ISSUE THREAD

**Issue by xirzec** [Azure/autorest.typescript#1129]
First step is to clarify customer requirements before scoping the design/implementation work. Previous SDKs had a custom configuration where we ran the generator serially to compose profiles.

**Comment by sarangan12** [comment]
@xirzec I have discussed this feature with Laurent on last Thursday. This feature does not have any customer requirement now and would not be worth pursuing investigation. If you are Ok, this issue could be closed.

**Comment by xirzec** [comment]
I'm happy to not support profiles if we don't have to. /cc @mayurid @ramya-rao-a

**Comment by sarangan12** [comment]
This issue can be resolved.
