### ISSUE TITLE
Merge generated Client and ClientContext together

### ISSUE THREAD

**Issue by xirzec** [Azure/autorest.typescript#1134]
Today generated clients have two levels of inheritance to them, but we really don't need to be doing this. By flattening now we will make it easier for convenience clients to extend the generated client without it getting too deep.

As part of this work, we should make sure the generated client doesn't expose any properties that we wouldn't want convenience clients to inherit.

**Comment by sarangan12** [comment]
Yes. This will be a breaking change (to a certain extent). But, we could implement it with deprecate flag/removing its functionality in steps and eventually remove it without much impact to the customer.

**Comment by ramya-rao-a** [comment]
Any use cases where having these two separate is actually better?

**Comment by xirzec** [comment]
> Any use cases where having these two separate is actually better?

I honestly don't understand why they are separate today. It doesn't appear to offer any tangible benefit to developers. What would someone use ClientContext for? Maybe I'm missing a use-case?

**Comment by ramya-rao-a** [comment]
It is definitely something we inherited from track 1 code gen. If this was something that was followed in other languages, then maybe @sarangan12 would know from his ruby times?

**Comment by joheredi** [comment]
Yeah, this is definitely inherited from track1 codegen. I can't think of a scenario where using the context class directly would be useful, it wouldn't even have any operations on it as they are added in the Client class which inherits the Context.

**Comment by xirzec** [comment]
As we regenerate SDKs will this change now start showing up?

**Comment by joheredi** [comment]
Yes! We already have some sdks without the ClientContext class: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/resources/arm-resources/src/resourceManagementClient.ts
