### ISSUE TITLE
readme.md should add a link to how to use app registration docs.

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1138]
In the readme.md there's a section about how to use app registration in @azure/identity. 
Customer suggeests us to put a docs link on how to set up app registration https://github.com/Azure/azure-sdk-for-js/issues/16702#issuecomment-891474532

**Comment by JonathanCrd** [comment]
Fixed in https://github.com/Azure/autorest.typescript/pull/1146
