### ISSUE TITLE
The package.json file should have metadata required by the automation to increment package version after release

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/autorest.typescript#1156]
In the azure-sdk-for-js repo, we have automated PRs that increment the package version after an update for the package is released. This automation updates the version in package.json and changelog files by default. Any other places that hard codes the package version needs to be listed as metadata in the package.json. For example: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/keyvault/keyvault-keys/package.json#L76-L89

https://github.com/Azure/azure-sdk-for-js/pull/16903 is one such PR for the newly generated mgmt plane package that used the v6 code generator. It missed updating the package version at https://github.com/Azure/azure-sdk-for-js/blob/308a805d8f58addfb06cfcf6e225e58fa6bd721a/sdk/sql/arm-sql/src/sqlManagementClientContext.ts#L44

This issue is a feature request to update the v6 code generator to add the metadata section in the pacakge.json file pointing to this file and the package version that needs to be updated here. For example:

```json
"//metadata": {
    "constantPaths": [
     {
        "path": "src/sqlManagementClientContext.ts",
        "prefix": "packageDetails"
      }
    ]
  }
```

**Comment by JonathanCrd** [comment]
File `src/sqlManagementClientContext.ts` does not longer exists, now the `packageDetails` constant is inside `src/sqlManagementClient.ts`.

I'm wondering if there are other places where there's a version specified. From what I found after a little research, it looks like `sqlManagementClient.ts` is the only one.

**Comment by ramya-rao-a** [comment]
The other place is the swagger/readme.md file, but that is not part of the generated code
