### ISSUE TITLE
Generated Code fails to build on Container Service management plane. 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1159]
We found the current v6 code generator fails to generate container service management plane package.
To repo: 
1. use the latest v6 code generator 6.0.0-alpha.8.20210816.1 and checkout the rest api specs main branch. 
2. use this readme.md https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/readme.md 

This is because there's a numeric enum in container service's swagger 
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-07-01/managedClusters.json#L2272-L2286 

And the generated code looks like this 

`export type Count = One | Three | Five;`

But it should be 

`export type Count =1 | 3 | 5;`

I guess it has something to do with x-ms-enum modelAsString: false

**Comment by sarangan12** [comment]
Thanks @qiaozha for reporting this issue. As you have mentioned that this might be a GA Blocker Issue (in the email), I will take this as high priority and started working on this issue. Will update my progress on this issue soon.

**Comment by sarangan12** [comment]
The Code Changes are completed and merged. The changes are available in https://www.npmjs.com/package/@autorest/typescript/v/6.0.0-alpha.8.20210817.4

**Comment by sarangan12** [comment]
A new version https://www.npmjs.com/package/@autorest/typescript/v/6.0.0-beta.9 has been released with this fix. Please check and feel free to reopen this issue if you still face any more issue. Thanks
