### ISSUE TITLE
Critical bug within the last 24 hours

### ISSUE THREAD

**Issue by ffMathy** [Azure/autorest.typescript#1163]
We had a build that succeeded around 5 PM GMT + 1 yesterday, but now that very same build fails, after regenerating our Autorest client.

It looks like the `package.json` of the Autorest package generated has a `types` property, which points to a file `./types/client.d.ts` which isn't there.

That's causing issues in VS Code and at compile-time:

> Could not find a declaration file for module '@anonymized/client'. 'c:/web/node_modules/@anonymized/client/dist/index.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/anonymized__client` if it exists or add a new declaration (.d.ts) file containing `declare module '@anonymized/client';`

Also, it looks like it's trying to look for typings in the `dist` folder, and there are none there. However, there are typings in the `dist-esm` folder, but that doesn't seem to be the path it's using (from the error).

**Comment by ffMathy** [comment]
It appears the issue was introduced in #1123.

Not sure what the intent was.

**Comment by sarangan12** [comment]
@ffMathy 

Thanks for reporting this issue. Yes. We have modified the `main`, `module`, & `types` properties in the `package.json` file. We have done this change so the generated libraries align closely with our existing data plane JS SDKs. 

Now, I have verified the same using the following commands (from the `Azure/autorest.typescript` repository):

```
$ cd test\integration\generated\arrayConstraints
$ npm install
$ npm run build
```

At this point, I could see `dist`, `dist-esm`, `dist-test`, `node_modules`, `review`. `temp` & `types` folders generated. The `types` folder has the file `array-constraints-client.d.ts` file. 

Based on the above logic, I am expecting the same output for your case also. Could you please try out the above steps and tell me where exactly you are seeing a difference. 

(P.S: Until we resolve this issue, you could pin the generator to `6.0.0-beta.8` version)

**Comment by sarangan12** [comment]
Closing this issue as there are no pending action items. If you still face this issue, Please reopen it. Thanks
