### ISSUE TITLE
Error: Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by puscasu-ion-daniel** [Azure/autorest.typescript#1179]
I am getting the following error. I am on the latest version.

`1>   Loading AutoRest core      'C:\Users\MysticMe\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist' (3.1.3)
1>INFORMATION: > Loading AutoRest extension '@autorest/typescript' (latest->6.0.0-beta.11)
1>INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.19.3->4.19.3)
1>node:internal/modules/cjs/loader:930
1>  throw err;
1>  ^
1>
1>EXEC : error : Cannot find module 'fs-extra'
1>Require stack:
1>- C:\Users\MysticMe\.autorest\@autorest_typescript@6.0.0-beta.11\node_modules\@autorest\typescript\dist\src\typescriptGenerator.js
1>- C:\Users\MysticMe\.autorest\@autorest_typescript@6.0.0-beta.11\node_modules\@autorest\typescript\dist\src\main.js
1>    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
1>    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
1>    at Module.require (node:internal/modules/cjs/loader:999:19)
1>    at require (node:internal/modules/cjs/helpers:93:18)
1>    at Object.<anonymous> (C:\Users\MysticMe\.autorest\@autorest_typescript@6.0.0-beta.11\node_modules\@autorest\typescript\dist\src\typescriptGenerator.js:16:17)
1>    at Module._compile (node:internal/modules/cjs/loader:1095:14)
1>    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
1>    at Module.load (node:internal/modules/cjs/loader:975:32)
1>    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
1>    at Module.require (node:internal/modules/cjs/loader:999:19) {
1>  code: 'MODULE_NOT_FOUND',`

An "npm install fs-extra" in  ~/.autorest/@autorest_typescript@6.0.0-beta.11 seems so solve it locally

Seems to have started since this:
#1173 
more exactly:
https://github.com/Azure/autorest.typescript/pull/1173/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R78

Maybe the "fs-extra": "^10.0.0", should've been added under "dependencies" instead of "devDependencies"?
@sarangan12

**Comment by sarangan12** [comment]
Thanks @puscasu-ion-daniel for raising this issue. Yes. The fs-exta should have been added to dependencies. The issue has been fixed with the latest release of https://www.npmjs.com/package/@autorest/typescript/v/6.0.0-beta.12.

Feel free to reopen this issue if you still face any more issues.
