### ISSUE TITLE
arm-containerregistry. fail to build. 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1185]
After we generation packages for arm-containerregistry, we found it's unable to build and report errors like this
![image](https://user-images.githubusercontent.com/55688292/132615741-89e487da-ec9a-4603-9f70-16e00a9d3361.png)

To repro, please checkout latest swagger repo and using code generation command like
`autorest --version=3.1.3 --typescript --modelerfour.lenient-model-deduplication --head-as-boolean=true --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=/Users/zhangqiaoqiao/work/code/azure-sdk-for-js ../azure-rest-api-specs/specification/containerregistry/resource-manager/readme.md --use=@autorest/typescript@6.0.0-beta.12`

After dig into this issue, we found the OS type is an enum type. but the weird part is other enum type works fine. I am not sure why. 
![image](https://user-images.githubusercontent.com/55688292/132615991-12329148-bd14-4dc0-8c97-edc554b136d8.png)

We can generate Architecture type correctly but not OS. 

Another point need to mention here,  how is current code generator handle modelAsString: true enum ? because I saw the generated code for Architecture 

![image](https://user-images.githubusercontent.com/55688292/132616201-04e63918-b986-4ecf-89ae-42986ed6385c.png)
It just a normal string type and though we generated KnownArchitecture, but I never see it was used anywhere. I am not sure if that's expected and users friendly? 

Maybe we should change Architecture definition like:
`export type Architecture = KnownArchitecture | string; `

**Comment by sarangan12** [comment]
I have found a possible solution for this issue. The test suite is currently running. Once it is complete, I will update the issue with the PR.

**Comment by sarangan12** [comment]
@qiaozha The Code changes have been merged for this issue and included in the latest release. It is a corner case where we need to combine modeler overrides + code changes to achieve the desired results. (The code changes are already released) You should use the following override: https://github.com/Azure/autorest.typescript/pull/1193/files#diff-28b3ac85ae60b4ff8454c28fa52401c334e96c650770033a4684dcf681499c7fR11

This will resolve the issue. No more action items on this issue. Feel free to reopen if you still face any more issues.

**Comment by qiaozha** [comment]
@sarangan12 I just tried the latest code generator both beta and alpha build, the containerregistry issue still exists. Could you help take a look at it when you are back.

**Comment by sarangan12** [comment]
@qiaozha I have verified again today. The scenario is working fine. I think you have missed the override part that I have mentioned in my last comment. Here are the steps that I followed for regeneration:

1. Clone `azure-rest-api-specs` repository. 
2. In the path `azure-rest-api-specs\specification\containerregistry\resource-manager\readme.typescript.md`, add the override mentioned at: https://github.com/Azure/autorest.typescript/pull/1193/files#diff-28b3ac85ae60b4ff8454c28fa52401c334e96c650770033a4684dcf681499c7fR11
3. Execute the following command: 
```
autorest --version=3.1.3 --typescript --modelerfour.lenient-model-deduplication --head-as-boolean=true --license-header=MICROSOFT_MIT_NO_VERSION --typescript-sdks-folder=C:\Users\sarajama\Projects\azure-sdk-for-js C:\Users\sarajama\Projects\azure-rest-api-specs\specification\containerregistry\resource-manager\readme.md --use=@autorest/typescript@6.0.0-beta.13
```
4. Open `azure-sdk-for-js\sdk\containerregistry\arm-containerregistry` folder. Execute `npm install` & `npm run build` commands. They execute successully. Please try the steps again and let me know if you still face any issues.

**Comment by sarangan12** [comment]
Based on the offline discussion, @qiaozha has informed that the issue has been resolved. Closing this issue.
