### ISSUE TITLE
Reduce bundle sizes with granular require() and dynamic import

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.typescript#119]
See https://webpack.js.org/guides/code-splitting/#dynamic-imports

**Comment by RikkiGibson** [comment]
Dynamic imports are feeling like something we probably want to avoid due to the ambiguity around node.js usage. Instead let's focus on the a-la-carte usage pattern (fits with granular require()).

Remaining items related to this:
- [ ] Azure/ms-rest-js#130
- [ ] Investigate whether method-level granularity for a-la-carte imports is worthwhile

**Comment by RikkiGibson** [comment]
Up until now we assumed dynamic imports were unavailable in node-- however we've been made aware of @jdalton's [esm](https://npmjs.com/esm) package which makes it available. So we should definitely consider using esm with dynamic import for some parts of our runtime and generated code to help webpack split our users' bundles.

**Comment by daschult** [comment]
Not going to do this for now.

**Comment by jdalton** [comment]
Cool cool.
Was there any issues on the esm loader front?

**Comment by ffMathy** [comment]
@RikkiGibson any plans on this in the future? Getting penalized by Google SEO due to the bundle size of this library.
