### ISSUE TITLE
[RLC] - Handling different body content types

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#1200]
## Context

`@azure/core-rest-pipeline` supports several  types for the body

```typescript
/**
 * Types of bodies supported on the request.
 * NodeJS.ReadableStream is Node only.
 * Blob is browser only.
 */
export type RequestBodyType =
  | NodeJS.ReadableStream
  | Blob
  | ArrayBuffer
  | ArrayBufferView
  | FormData
  | string
  | null;
```

## Input
Its `PipelineRequest` has 2 properties to represent the body, `body` and `formData`. With the help of `formDataPolicy` ([link](https://github.com/Azure/azure-sdk-for-js/blob/667e8bf04eb8ed9fb9102566d9a6d8757dc7e7a7/sdk/core/core-rest-pipeline/src/policies/formDataPolicy.ts#L41)) `core-rest-pipeline` transforms `formData` and assigns it to the body. It has different implementations for Node and Browsers. Once transformed the value is assinged to PipelineRequest.body and the content-type is set (assuming `multipart/form-data` was provided)

**For RLC**
In RLC the Request type has a `body` property of type unknown by default that gets overridden by the type found in the swagger ([sample](https://github.com/Azure/autorest.typescript/blob/cf844d942632fcb2571cebb9228596d536195bd5/test/integration/generated/bodyStringRest/src/parameters.ts#L11))

When sending the request, we are currenlty assuming that the body would be a JSON object so we stringify it directly ([link](https://github.com/Azure/azure-sdk-for-js/blob/667e8bf04eb8ed9fb9102566d9a6d8757dc7e7a7/sdk/core/core-client-rest/src/sendRequest.ts#L31)). However I think we can be a little bit smarter here and use the content-type provided in the request to handle the body a bit differently. For example if we get a contentType `text/plain` instead of `JSON.stringify(body)` we could do `String(body)` and for `multipart/form-data` we could `pipelineRequest.formData = body` or just pass the body as is otherwise to let `core-rest-pipeline` handle ReadableStream and ArrayBuffers.

With this on our side, we could allow Rest Client to model bodies as `UInt8Array` for binary or `FormData` and let `core-rest-pipeline` handle it.

## Output
`PipelineResponse` has 2 additional properties to handle ReadableStream bodies one for Node (`readableStreamBody?: NodeJS.ReadableStream;`) and one for Browser (`blobBody?: Promise<Blob>;`).

Currently core-rest-pipeline relies on the client to provide a set of statusCodes that would expect to receive a StreamResponse. In regular or HLC SDKs this is usually provided by @azure/core-client by using an OperationSpec. If the response matches one of those status codes then the stream body is handled and it is added in the readableStreamBody or the blobBody properties.

**For RLC**
In RLC we have limited information at runtime, so providing a set of status codes that have streamBody is not possible. In my testing, not providing this status codes makes `core-rest-pipeline` to give us the response as a string with the binary content.

I think we could also rely on the response `content-type` to be a bit smart and maybe encode the binary content and give the users a UInt8Array.

@bterlson, @xirzec I would like to hear your thoughts on the proposals above for both input and output handling of multiple contant types. I think if we can just keep a single property `body` in the Rest Clients to represent the body would be great

**Comment by bterlson** [comment]
I think being smart based on content type makes sense in general! Seems like the Rest Way (tm).

**Comment by xirzec** [comment]
I also like being smart, and perhaps for the "I want to get this as a stream" we have a simpler way to ask for this? e.g. "give it to me as a stream if it's a successful response code, rather than making me specify precise codes"

**Comment by qiaozha** [comment]
probably already resolved with .asStream(). may need some verification.

**Comment by MaryGao** [comment]
I will triage this issue first to verify if it's in DPG scope

**Comment by MaryGao** [comment]
It is already supported.
