### ISSUE TITLE
Generated packages should use the latest version of @microsoft/api-extractor

### ISSUE THREAD

**Issue by maorleger** [Azure/autorest.typescript#1204]
Please update the code gen for package.json to pull in the latest version of @microsoft/api-extractor (currently ^7.18.11).

[This PR](https://github.com/Azure/azure-sdk-for-js/pull/17917) is handling updating existing packages.

Suggestion: consider reading and parsing the dependencies / devDependencies sections in https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/template/template/package.json - an intersection of those entries with what is being generated can provide better syncing between the two repos. What do you think?

Might not work for all dependencies (for example core-http vs coreV2) but we can have a allowlist of dependencies that should pull their version from the template project

**Comment by ramya-rao-a** [comment]
Hey @JonathanCrd 

Can you pick this one up?
We need this to ensure that new packages that get added to the azure-sdk-for-js repo do not end up using older version of the api extractor

cc @sarangan12

**Comment by maorleger** [comment]
Feel free to create a separate issue for my suggestion if you think it's worth exploring or ignore it if you think it's a terrible idea 😄

**Comment by ramya-rao-a** [comment]
Let's use this issue to just update the dependency version for api extractor
https://github.com/Azure/autorest.typescript/issues/1054 tracks the generic need to keep the code generator in sync with the dependencies we use in azure-sdk-for-js. @maorleger You can add your suggestion there :)

**Comment by maorleger** [comment]
I noticed in passing that there are a bunch of outdated dependencies assuming I'm looking at the right file https://github.com/Azure/autorest.typescript/blob/cf844d942632fcb2571cebb9228596d536195bd5/src/generators/static/packageFileGenerator.ts#L153-L166

Like core-tracing should be preview.13, core-http should be 2.x etc - should we update those as well in this change? I can edit the issue if so

**Comment by ramya-rao-a** [comment]
@JonathanCrd Yes, please use the same PR to make the updates for the other outdated dependencies.
For reference, you can use the dependency versions in the [template](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/template/template/package.json#L80) and [text analytics](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/textanalytics/ai-text-analytics/package.json#L90) packages
