### ISSUE TITLE
How to specify version of autorest.typescript module to use

### ISSUE THREAD

**Issue by lohals** [Azure/autorest.typescript#121]
How can we specify what version of autorest.typescript to use? 
We have fixed version of autorest (2.0.4262), when running autorest to generate typescript, but the typescript module suddenly updates to newer version internally when running autorest cli.

This results in unexpected breaking changes and have recently forced us to use ms-rest-js preview channel packages, which we do not want.

Is there a way to specify typescript module to use version?

I have tried to do 'autorest --typescript.version=2.0.141', but this doesnt do anything, and still the latest typescript extension version is used.

**Comment by amarzavery** [comment]
autorest --typescript --use=@microsoft.azure/autorest.typescript@2.0.141

**Comment by lohals** [comment]
Thanks.

Actually, i ended up just installing autorest as a local npm package and running through npm scripts and managing dependency versions this way.
