### ISSUE TITLE
Fix API reference docs links generated in v4 code generator

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/autorest.typescript#1212]
As reported in https://github.com/Azure/azure-sdk-for-js/issues/18316, we are linking to the ref docs main landing page instead of linking to the ref docs of the particular package.

This can be either resolved manually by updating the readme after it is generated or it can be fixed in the code generator. This is not a problem in v6 of the code generator.

Assigning to @qiaozha to take the final call on this.

@qiaozha If you prefer to get this fixed in the code generator, please send a PR

**Comment by qiaozha** [comment]
close it as we have released track2 for most RPs.
