### ISSUE TITLE
Provide link to bundling docs when talking about browser support

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/autorest.typescript#1214]
As being discussed in https://github.com/Azure/azure-sdk-for-js/issues/18326, we need to provide a link to the [bundling docs](http://aka.ms/AzureSDKBundling) in the generated readme.

This applies to both v4 and v6 of the code generator

For v4, it can be another bullet point in the below shown section

![image](https://user-images.githubusercontent.com/16890566/138530015-7b43cf1e-375b-4559-8f7d-e25f26cb3aa2.png)

For v6, it should follow the format we used in say https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-blob/README.md#javascript-bundle

**Comment by JonathanCrd** [comment]
This has been solved for v6.
There are some issues with v4 that need a deeper investigation. Issue https://github.com/Azure/autorest.typescript/issues/1245 keeps track of this.
