### ISSUE TITLE
[CDN] generation cdn SDK failed with latest @autorest/typescript beta release.

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1217]
Here's the repo steps:
1. use the latest rest api specs as input
2. run the code generation command: `autorest --version=3.1.3 --typescript --modelerfour.lenient-model-deduplication --head-as-boolean=true --license-header=MICROSOFT_MIT_NO_VERSION --generate-test --typescript-sdks-folder=/Users/zhangqiaoqiao/work/code/azure-sdk-for-js ../azure-rest-api-specs/specification/cdn/resource-manager/readme.md --use=@autorest/typescript@6.0.0-beta.13`

Then you will see errors like this 
![image](https://user-images.githubusercontent.com/55688292/138631083-abe3dfc5-7d68-4ff9-9a25-43f4612d4b0a.png)

And here's the definition of `DeliveryRuleAction` in their swagger.
```
    "DeliveryRuleAction": {
      "description": "An action for the delivery rule.",
      "discriminator": "name",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "description": "The name of the action for the delivery rule.",
          "type": "string",
          "enum": [
            "CacheExpiration",
            "CacheKeyQueryString",
            "ModifyRequestHeader",
            "ModifyResponseHeader",
            "UrlRedirect",
            "UrlRewrite",
            "UrlSigning",
            "OriginGroupOverride"
          ],
          "x-ms-enum": {
            "name": "DeliveryRuleAction",
            "modelAsString": true
          }
        }
      }
    },
```

You can see there's niodel named as DeliveryRuleAction and it has a property 'name' whose type is also marked as DeliveryRuleAction.

The temporary solution for this is to bump modelerfour version to 4.21.3, then `--modelerfour.lenient-model-deduplication ` will work correctly

**Comment by ramya-rao-a** [comment]
>  That;s why we should bump m4 version as 4.21.3 resolved this issue

@qiaozha I see that you have bumped the m4 version in #1234. Can we close this issue?

**Comment by qiaozha** [comment]
yes. we can close it.
