### ISSUE TITLE
[Elastic] generation elastic SDK failed with latest @autorest/typescript beta release. 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1219]
Here's the repro steps:
1. use the latest rest api specs as input
2. run the code generation command: `autorest --version=3.1.3 --typescript --modelerfour.lenient-model-deduplication --head-as-boolean=true --license-header=MICROSOFT_MIT_NO_VERSION --generate-test --typescript-sdks-folder=/Users/zhangqiaoqiao/work/code/azure-sdk-for-js ../azure-rest-api-specs/specification/elastic/resource-manager/readme.md --use=@autorest/typescript@6.0.0-beta.13`

Here's the result I am getting
![image](https://user-images.githubusercontent.com/55688292/138637364-b2a00084-823e-49de-a14d-a3dcdbd80102.png)

I guess we need to do some string escape in the code generator side.

**Comment by ramya-rao-a** [comment]
@sarangan12 Has the fix been shipped already? If so, can we close this issue?

**Comment by sarangan12** [comment]
This can be closed.
