### ISSUE TITLE
[resourceconnector] fail to build the code after generate it with @autorest/typescript@6.0.0-beta.13

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1224]
Here's the autorest command I am using: 
`autorest --version=3.1.3 --typescript --modelerfour.lenient-model-deduplication --head-as-boolean=true --license-header=MICROSOFT_MIT_NO_VERSION --generate-test --typescript-sdks-folder=/Users/zhangqiaoqiao/work/code/azure-sdk-for-js ../azure-rest-api-specs/specification/resourceconnector/resource-manager/readme.md --use=@autorest/typescript@6.0.0-beta.13`

Here's the error I am getting while running `rush build` fpr service connector
![image](https://user-images.githubusercontent.com/55688292/138644847-3851e688-ed09-42c1-8509-2517c1a590ac.png)

Here's the generated code looks like: 
![image](https://user-images.githubusercontent.com/55688292/138644650-d229b384-6418-48e8-9f5e-c607d8ffda7a.png)

I think this is caused by their title and operationId prefix are the same.
![image](https://user-images.githubusercontent.com/55688292/138645276-7d661b86-4fcc-475d-a68f-550f876fe4ef.png)

**Comment by sarangan12** [comment]
@qiaozha I have checked this issue. This needs a command line option `--title=AppliancesClient` which will resolve the issue. This is a really remote corner case and the client name is also not standard. So, we do not want any code fix for this issue. The command line option is sufficient. (Or you can update the title in the readme.typescript.md file also)

**Comment by sarangan12** [comment]
As there are no pending action items, I am closing this issue
