### ISSUE TITLE
How do you abort a request? (typescript)

### ISSUE THREAD

**Issue by jsangco** [Azure/autorest.typescript#1228]
Is there a way to abort an ongoing client request?

I noticed the ServiceClient has the ability to specify RequestPrepareOptions, but I'm unclear how to pass the request options to the outgoing request method.

**Comment by jsangco** [comment]
Can someone provide guidance on this? The C# libraries support the use of `CancellationToken`, so I hope someone can provide guidance on how to do this correctly using Typescript.

**Comment by sarangan12** [comment]
@jsangco,

If you are using the older version of v4 code generator, you can find the example [here](https://github.com/Azure/ms-rest-js/blob/f6f0d92d79a1dfa8d92ff0891b88bc6b7a349e69/test/defaultHttpClientTests.ts#L71)
