### ISSUE TITLE
Provide link to bundling docs when talking about browser support - V4

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest.typescript#1245]
This is the duplicate of issue https://github.com/Azure/autorest.typescript/issues/1214 but only specific to the v4x branch. 

Why am I creating a new issue for v4x alone?
The v4x branch is having some issues and needs deeper investigation. 
1. The VM image for the CI has been deleted. Jose is fixing it in the PR https://github.com/Azure/autorest.typescript/pull/1244 
2. The `npm install` command is failing with reason similar to child process is not completing. 

Considering that this needs deeper investigation and the possibility of v4x to be obsolete in a few months, I am branching out this issue for v4x branch which can be handled later.

**Comment by ramya-rao-a** [comment]
By the end of January 2022, almost all mgmt plane packages would have moved to using v6 code generator. Therefore, it is not worth our time to fix this for the v4 code generator

@sarangan12 Do you want to have a separate issue to investigate any pending issues in the v4 branch related to build or install?
