### ISSUE TITLE
Should subscriptionId be required for some path that don't need subscriptionId at all 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1256]
Take RP resources package-policy as an example.

Their path are looking like this 
![image](https://user-images.githubusercontent.com/55688292/144395905-76c79b23-333b-47d9-9415-a9bdb7c991c0.png)

And the Client constructor is looking like this 
https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/policy/arm-policy/src/policyClient.ts#L34-L37 

For the operation path "/{scope}/providers/Microsoft.Authorization/policyAssignments/{policyAssignmentName}" and "/{policyAssignmentId}" subscriptionId is not required, Then it doesn't quite make sense to require a subscriptionId when construct the Client ?

**Comment by sarangan12** [comment]
This is expected. If you check the older code at https://github.com/colawwj/azure-sdk-for-js/blob/9684a273e8b9143bf2c5b7bef48ac2466a6638df/sdk/policy/arm-policy/src/policyClient.ts#L30, you could see the same behavior. (and has the reference to the same [path](https://github.com/colawwj/azure-sdk-for-js/blob/9684a273e8b9143bf2c5b7bef48ac2466a6638df/sdk/policy/arm-policy/src/operations/policyAssignments.ts#L1004))

So, this behavior is established and seems to be accepted even before the new generator.

**Comment by sarangan12** [comment]
@qiaozha If you are Ok, Please close this issue
