### ISSUE TITLE
Update nyc dependency

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/autorest.typescript#1262]
Currently, we are using v14 of nyc that pulls in certain dependencies that have security vulnerabilities. This needs to be updated to use v15 instead

**Comment by ramya-rao-a** [comment]
@sarangan12 Please add instructions on how to go about this task and add the `help wanted` label

**Comment by sarangan12** [comment]
Reference: https://dev.azure.com/azure-sdk/internal/_componentGovernance/101977?_a=alerts&typeId=7613604&alerts-view-option=active

**Comment by sarangan12** [comment]
I have prepared a small wiki page to resolve the compliance issues in general. Once I have the PR ready for this task, I will update the issue. Wiki Link: https://github.com/Azure/azure-sdk-for-js/wiki/Handling-compliance-issues-with-our-packages

**Comment by sarangan12** [comment]
1. I have notified Praveen about the compliance job(https://dev.azure.com/azure-sdk/internal/_componentGovernance/146576?_a=alerts&typeId=7649860&alerts-view-option=active). Once he provides me an update, I will update it here
2. Notified other Language owners. They are also not aware of these jobs. They will start working on them based on their proroties

**Comment by sarangan12** [comment]
1.  I have deleted the Wiki page
2. Added a section to the contributing document and created a PR for that. https://github.com/Azure/autorest.typescript/pull/1264 Will merge it after approval
3. `nyc` dependency is no part of the SDK generator itself. So, we do not need more changes for this issue
4.
