### ISSUE TITLE
[RLC] Include review/*api.md in publish package

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1273]
I have a change log detection tool, and it's based on `review/*api.md`. So I hope to include this file in published package, which is same as mgmt sdk.

**Comment by joheredi** [comment]
@dw511214992 if I understand correctly for this we'd need to include this in package.files right?

I don't see any downsides, @bterlson is there anything we should consider before including the api-extractor file in the package?

**Comment by joheredi** [comment]
@dw511214992 do you want to send a PR for this?

**Comment by dw511214992** [comment]
This issue is handled in https://github.com/Azure/autorest.typescript/pull/1309. So close it.
