### ISSUE TITLE
There are 2 contributing guides in this repo

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/autorest.typescript#1276]
There are 2 contributing guides in this repo
- https://github.com/Azure/autorest.typescript/blob/main/docs/contributing.md
- https://github.com/Azure/autorest.typescript/blob/main/CONTRIBUTING.md

**Comment by sarangan12** [comment]
Closing this issue with PR https://github.com/Azure/autorest.typescript/pull/1307
