### ISSUE TITLE
Use shared rollup config from dev-tool in generated management libraries

### ISSUE THREAD

**Issue by jeremymeng** [Azure/autorest.typescript#1281]
currently the generated code includes a copy of rollup.config.js.  

We should move to take a dependency on dev-tool

```diff
+    "@azure-tools/test-recorder": "^1.0.0",
```

remove dependencies on rollup and its plugins, e.g.,

```diff
-    "rollup-plugin-node-resolve": "^3.4.0",
-    "rollup-plugin-sourcemaps": "^0.4.2",
-    "@rollup/plugin-commonjs": "11.0.2",
```

and use this code in `rollup.config.js`

```js
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import { makeConfig } from "@azure/dev-tool/shared-config/rollup";

export default makeConfig(require("./package.json"), {
  disableBrowserBundle: true
});
```

**Comment by deyaaeldeen** [comment]
I think this is a duplicate to https://github.com/Azure/autorest.typescript/issues/1259

@joheredi, @sarangan12 I remember we talked before aboyt creating a new tool for adding dev dependencies outside code gen, is that still in the works?

**Comment by jeremymeng** [comment]
ah that's right. closing

**Comment by jeremymeng** [comment]
Since shared rollup is still being discussed. I am going to log an issue to remove `openTelemetryCommonJS()` workaround
