### ISSUE TITLE
Writing DPG customizations documentation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#1303]
As GA requirement for the project, we want to have explicitly written the documentation for service teams on how to grow-up their DPG into an improved SDK.

Documentation should be written with:
- Basics on customizations for this language
- One scenario, one section. Like a FAQ document

Required sections are (at the minimum):
- Change operation behavior (new signature, or any wrapping)
- Change client behavior (default pipeline configuration, etc.)

More sections might be added, and I'll update this initial text with date when I add them (for clarity)

**Comment by lmazuel** [comment]
In the case of TS, we may make this issue as "how to add some helpers to RLC", per discussion of yesterday. I let @bterlson @xirzec and @joheredi decide, we may close the issue with "N/A" if you think that's the case.

**Comment by sarangan12** [comment]
@lmazuel Is this requirement only specific to Rest Client?

@joheredi Could you please check the question from @lmazuel?

**Comment by lmazuel** [comment]
It's a cross language requirement, though RLC is special, so you should check with @bterlson how to do (or not do) this one

**Comment by qiaozha** [comment]
@joheredi @bterlson @xirzec  As we don't have grow up story in JS RLC. I don't think we should have DPG customization document either, right ?  Can we close this issue ?

**Comment by joheredi** [comment]
We will need some customization sometimes. For example, the Metrics Advisor SDK that would need a custom paging helper would be considered a package with customization, we'll need to document the process of writing custom stuff for RLCs. The main strategy for RLCs customization would be to:

* Never try to abstract REST details.
* Any functionality we need to expose as part of customization, would be exposed as helper functions which users can choose to use or not. Similar to how we expose LRO and Paging

**Comment by qiaozha** [comment]
close it as the document has been updated.
