### ISSUE TITLE
[Paging] Expose nextLink/Continuation Token as part of the returned items

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/autorest.typescript#1326]
Some customers need access to it to suspend and resume iterating. See https://github.com/Azure/azure-sdk-for-js/issues/20380#issuecomment-1051410026

**Comment by qiaozha** [comment]
@deyaaeldeen are you going to fix this issue soon ? as this is blocking customer migrate from track1 to track2 https://github.com/Azure/azure-sdk-for-js/issues/17499#issuecomment-1050548699

**Comment by deyaaeldeen** [comment]
@qiaozha I will defer to @sarangan12 and the code gen crew to address this issue but I agree it should take high priority. Also, https://github.com/Azure/autorest.typescript/issues/1199 is related and is equally if not more important since it enables customers to get pages from specific continuation tokens. 

I am happy to offer guidance and to participate in any design discussions for it.

**Comment by sarangan12** [comment]
@deyaaeldeen Thanks for the response (ofcourse I need your input in design :-)) . @qiaozha As this is blocking customer, I will take this as high priority and start working on this.

**Comment by qiaozha** [comment]
@sarangan12 is there any updates for this ? Thanks

**Comment by sarangan12** [comment]
The Prototype code is available at https://github.com/Azure/azure-sdk-for-js/pull/20809/files. But, I can focus on this and test it and deploy it only after the completion of storage task that I am working on. I will soon start implementing the solution. Once I am done, I will update this issue.

Regards
Sarangan Rajamanickam



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by qiaozha** [comment]
@sarangan12 do you need me to review the prototype PR ? or is the design still in discussion ?

**Comment by sarangan12** [comment]
@qiaozha The coding for the generator is still in progress. The scenarios are complicated and I am new to this paging operation. So, it is taking more time (This is the third day I am working on it) So, any help you could provide in that area if you have time would be appreciated, 

Alternatively, you could test the change in any of the SDKs and confirm the code changes will work

**Comment by qiaozha** [comment]
@sarangan12 any updates with the coding change in the code generator ? I am currently working on adding back the sample generation because of audit fix don't have much time to take a look at this feature. Thanks

**Comment by MRayermannMSFT** [comment]
Sad to see this hasn't been getting attention. 😐

**Comment by xirzec** [comment]
@MRayermannMSFT just merged this, let me know if you have any feedback or issues with using it.
