### ISSUE TITLE
[RLC] Clear generated output folder in regenerating codes

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1334]
Currently, codegen doesn't clear src folder in regenerating codes. If there is an existed client file named `AClient.ts`, and the latest swagger changes the client name to `BClient`. Then the new generated client file will be named `BClient.ts`. However, codegen doesn't delete file `AClient.ts`, which leads to build failure.

**Comment by qiaozha** [comment]
see  pr #1355
