### ISSUE TITLE
[Paging] `OperationSpec` for next page of collections should not include `top` and `skip` parameters

### ISSUE THREAD

**Issue by danielortega-msft** [Azure/autorest.typescript#1347]
In API endpoints that return pageable collections, the `nextLink` property generated by the server already includes the `top` and `skip` query parameters that correspond to the next page in the collection. However, the generated `OperationSpec` for retrieving the next page of a collection does include them as query parameters. See example: https://github.com/Azure/azure-sdk-for-js/blob/26d973dba9fa238766ec5ec025ecefb3fdd43948/sdk/communication/communication-phone-numbers/src/generated/src/operations/phoneNumbers.ts#L737

Not only is this unnecessary, but it also causes a bug in which the query parameters from `nextLink` are replaced with their default values for the first page. This makes it impossible to iterate through the collection, as each call to the next page is instead returning the first page.

Considering that the `OperationSpec` for retrieving the next page of a collection is **only** used for that purpose and that the `nextLink` URL should always be generated by the server, the generated code should not include `top` and `skip` in the `queryParameters` array.

Related issue: https://github.com/Azure/azure-sdk-for-js/issues/20923

**Comment by joheredi** [comment]
@sarangan12 would you mind taking a look at this issue. See the related issue in azure-sdk-for-js for more context

**Comment by xirzec** [comment]
@danielortega-msft I'm looking into improving our handling here, but something interesting I have discovered is that you can resolve this today by having a more explicit swagger spec, example here:

https://github.com/Azure/autorest.testserver/blob/0b506ec5426d50d8e439141cd3aa21eb0c32ecee/swagger/paging.json#L205

The key part is when defining your `x-ms-pageable` you can give an `operationName` for the "next" operation

```
"x-ms-pageable": {
          "nextLinkName": "nextLink",
          "itemName": "values",
          "operationName": "Paging_nextOperationWithQueryParams"
        },
```

then when you define that operation you can list all the query paramters that are expected and remove the ones that are in the next link already:

```
"/paging/multiple/nextOperationWithQueryParams": {
      "get": {
        "x-ms-pageable": {
          "nextLinkName": null,
          "itemName": "values"
        },
        "operationId": "Paging_nextOperationWithQueryParams",
        "description": "Next operation for getWithQueryParams. Pass in next=True to pass test. Returns a ProductResult",
        "parameters": [
          {
            "name": "queryConstant",
            "in": "query",
            "description": "A constant. Must be True",
            "required": true,
            "type": "boolean",
            "enum": [true],
            "x-ms-enum": {
              "modelAsString": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Initial response with ProvisioningState='Canceled'",
            "schema": {
              "$ref": "#/definitions/ProductResult"
            }
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      }
    },
```

Unfortunately, I think not many swagger authors are aware of this. /cc @MRayermannMSFT
