### ISSUE TITLE
Samples Generation Feature in @autorest/typescript package

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest.typescript#1373]
In the `@autorest/typescript` package, there was a module to generate samples. This feature was added recently before few months. But, for this feature to work, there is a dependency on the `@autorest/testmodeler` package. Unfortunately, this has caused a security Component Governance issue that needs to be resolved immediately. 

So, I have removed that feature with the PR: https://github.com/Azure/autorest.typescript/pull/1372. I am creating this issue to ensure that we discuss and decide if we should bring the feature back and if so do it without causing any Component Governance Issue.

**Comment by qiaozha** [comment]
@sarangan12 @joheredi Would you mind share some information how the test modeler is violating the component governance issue ? we will work on the fix.
cc @changlong-liu  @lirenhe

**Comment by sarangan12** [comment]
There are dependencies such as `async`, `validator`, `ansi-regex`, `yargs-parser` package dependencies which have Audit violations. You could go to a previous commit and run `npm audit` which will give you a complete list

**Comment by ArcturusZhang** [comment]
This is done per @qiaozha
