### ISSUE TITLE
[RLC]: Provide api description for route for better intelli-sense

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1379]
When we call an path in RLC, the intellisense for the specific path looks like below:

path(path: "/deviceupdate/{instanceId}/updates/providers/{provider}/names", instanceId: string, provider: string): DeviceUpdateListNames

Resource for '/deviceupdate/{instanceId}/updates/providers/{provider}/names' has methods for the following verbs: 

It doesn't provide enough information about the detail of this path.
Can we use the "description" of this API call for better intellisense?

    "/deviceupdate/{instanceId}/updates/providers/{provider}/names": {
      "get": {
        "tags": [
          "Update management"
        ],
        "description": "Get a list of all update names that match the specified provider.",

**Comment by qiaozha** [comment]
close it as operation level can not be put in the path level.
