### ISSUE TITLE
[RLC]generate date format string as string type

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1382]
When the swagger is:
```
        "startDateTime": {
          "type": "string",
          "description": "The deployment start datetime.",
          "format": "date-time"
        },
```
The generated codes is:
```
startDateTime: Date | string;
```
However, it werid to not just pick one, either we're deserializing it or not, since it can't be coming over the wire as a Date object. So it should be changed to:
```
startDateTime: string;
```

**Comment by MaryGao** [comment]
@joheredi Please help comment if I miss something!

@dw511214992 Regarding the `date-time` type, we handle it in different ways if appearing in `Input` or `Output` models, detailed PR is here #1196 .

Swagger file:
"startDateTime": {
          "type": "string",
          "description": "The deployment start datetime.",
          "format": "date-time"
        },

Case1: Appear in the input model e.g parameter or request body, it's easy to stringify JS types to JSON. So we both accept `string` and `Date`.  So the generated code looks like:

```typescript
startDateTime: Date | string;
```

Case2: Appear in the output model e.g response body, considering when we handle deserializing, there is no safe way to deserialize JSON strings into JS types without additional schema at runtime so we keep the type as `string`. The generated code would be:

```typescript
startDateTime: string;
```

**Comment by dw511214992** [comment]
I agree @MaryGao 's comment, and it's enough to change the output model.
