### ISSUE TITLE
[HLC] Fix hard-code parameter issue of client example in readme 

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1388]
Currently in `hlcREADME.md.hbs` we hard coded the client example generation with fixed paramters, but it is not truly for all services.

Sometimes the service constructor don't have the required `subscriptionId`, sometimes others have additional `endpoint` in their contstuctor.

```javascript
const subscriptionId = "00000000-0000-0000-0000-000000000000";
const client = new {{ clientClassName }}(new DefaultAzureCredential(), subscriptionId);
```

So we need to fix this with actual parameter states not fixed ones.

**Comment by lirenhe** [comment]
Need to add a new unit test for this.
