### ISSUE TITLE
[mgmt] the generated mappers for discriminators is incorrect

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1395]
For consumption mgmt plane. we generate the discriminator mappers like this 
//mappers file
```
export let discriminators = {
  LegacyReservationRecommendationProperties: LegacyReservationRecommendationProperties,
  "Resource.UsageDetail": UsageDetail,
  "Resource.ReservationRecommendation": ReservationRecommendation,
  "ProxyResource.ChargeSummary": ChargeSummary,
  "LegacyReservationRecommendationProperties.Single": LegacySingleScopeReservationRecommendationProperties,
  "LegacyReservationRecommendationProperties.Shared": LegacySharedScopeReservationRecommendationProperties,
  "Resource.legacy": LegacyReservationRecommendation,
  "Resource.modern": ModernReservationRecommendation,
  "ProxyResource.legacy": LegacyChargeSummary,
  "ProxyResource.modern": ModernChargeSummary
};
```

Here the UsageDetail, ReservationRecommandation are both subclass of Resources and each of them has subclesses with x-ms-discriminator-value legacy and modern, 

Currently we are not generating the mapper key by using the direct parent class name. instead we are using the very first ancestors' name in this case Resource. which cause both LegacyUsageDetail and LegacyReservationRecommandation have the same key Resource.Legacy. 

we should generate the mappers like 
```
export const discriminators = {
  'UsageDetail': UsageDetail,
  'UsageDetail.legacy': LegacyUsageDetail,
  'UsageDetail.modern': ModernUsageDetail,
  'ReservationRecommendation': ReservationRecommendation,
  'ReservationRecommendation.legacy': LegacyReservationRecommendation,
  'ReservationRecommendation.Nodern': ModernReservationRecommendation,
  'ChargeSummary': ChargeSummary,
  'ChargeSummary.legacy': LegacyChargeSummary,
  'ChargeSummary.modern': ModernChargeSummary,
}
```

This is original from our customer reported issue here https://github.com/Azure/azure-sdk-for-js/issues/20026 

To do work:
1. we need to add some test case in the test server to cover such scenario 
2. we need to fix it in this typescript code generator 
3. re-release a new package of @azure/arm-consumption for our customer.

**Comment by BoostSebastian** [comment]
Hi, do we have any future release on this?

**Comment by qiaozha** [comment]
Hi @BoostSebastian I have a PR to fix it and will let you know when it finishes ?
