### ISSUE TITLE
[RLC Post GA work items] - Guidance for partner teams on when do they need a RLC vs a HLC

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1400]
Guidance on when a service which already has an RLC will need to have an HLC 

Document the upgrade process? 

Add information about error handling and type narrowing in the RLC docs/samples  

# [RLC Archboard Discussions] Guidance for partner teams RLC vs HLC

We need to be clear on the message we share with partner teams to make it easy to determine if they need to release an RLC or an HLC.

The initial thinking of RLC vs HLC is the following

**Releasing RLC vs HLC**
* By default a service onboarding would release an RLC, if any of the following apply we'll consider HLC
  * The service already has a Track1 library with a big user base.
  * The service has released an RLC and is getting feedback about potential benefits of an HLC. For example, if the user base for a given service are not necessarily developers, for example the service has a user base of mostly `Data Scientists` and they have expressed feedback supporting an HLC library.

**Already have RLC now releasing HLC**
* Service teams will follow the current guides for releasing HLC packages, nothing changes at this moment.

## Action items
Identify the scenarios where Service teams would need to do RLC vs HLC
- [ ] Write guidance on the onboarding documents

**Comment by MaryGao** [comment]
This item crosses all languages and we need to follow up with Laurrent or Renhe on this.  We could bring this up in sync-up meeting.

**Comment by qiaozha** [comment]
For now, we will recommand the new service to onboard RLC and won't give them too much options.

**Comment by qiaozha** [comment]
CLOSE IT
