### ISSUE TITLE
[RLC post GA work items] - Guidance for service teams about GA requirements on library testing, documentation and samples

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1401]
# [RLC Archboard Discussions] New library release requirents

In order to ensure the quality and reliability of our SDKs we need to set requirements for all RLCs before they are released.

In general, engineering release requirements will be similar to other DPGs or HLCs we release covering:
- Documentation (Readmes and generated docs)
- Samples
- Tests
- Architecture board Naming approval (general naming and package naming)

## Action items
- [ ] Come up with a unified DPG and RLC exit criteria
- [ ] If there is anything in the DPG+RLC exit criteria that doesn't apply or is missing for RLC, document it clearly in the onboarding guide and guidelines.

### Notes:
* Documentation exit criteria will be be influenced by the outcome of the [docs discussion](https://gist.github.com/joheredi/2a87ad2d9e95a65e1da4b085c25f97a4). In which we'll determine the level of generated documentation we want to offer for RLCs

**Comment by MaryGao** [comment]
This item crosses all languages and we need to follow up with Laurrent on this.

**Comment by qiaozha** [comment]
we should update our onboard document to remind service team update the readme.md accross languages.

**Comment by qiaozha** [comment]
already has this kind of hint in the onboard document.
