### ISSUE TITLE
Clearing src folder doesn't work when output-folder is a relative path

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1411]
How to reproduce:
1. Change the `title` in `sdk/deviceupdate/iot-device-update-rest/swagger/REAME.md` from `DeviceUpdate` to `DeviceUpdateAAA`.
2. Run `autorest README.md` in `sdk/deviceupdate/iot-device-update-rest/swagger`.
3. Find the file `DeviceUpdate.ts` is not deleted.

Expected:
file `DeviceUpdate.ts` should be deleted.

**Comment by MaryGao** [comment]
Considering it's low priority and remove from RLC  v1.1
