### ISSUE TITLE
Add test coverage for security scopes in testserver

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1414]
As we have supported security scopes in the autorest.tyoescript, though we have tests in our own, but we still need to support the test coverage in testserver.  there are already two in the testserver:
https://github.com/Azure/autorest.testserver/blob/main/swagger/security-aad.json
https://github.com/Azure/autorest.testserver/blob/main/swagger/security-key.json
The REST API doc for AAD is not quite right as it is missing the `scopes` … I’ll make a PR to fix that.
 
We should add two more cases:
_Both_ AAD and API Key (either one is allowed).  This is common for Cognitive Services.
Two different API Keys which are both required.  This is not common but Metrics Advisor has this.

**Comment by MaryGao** [comment]
The first part is high priority but the second one we need to check offline maybe low priority
