### ISSUE TITLE
Question: Javascript/Typescript interchangeable? 

### ISSUE THREAD

**Issue by AndrewCS149** [Azure/autorest.typescript#1439]
Is there a specific JavaScript autorest extension? Or does the TypeScript work interchangeably? 

Thank you!

**Comment by qiaozha** [comment]
The Autorest.Typescript will only generate TS code, but then you can compile it into JS code. Also, the generated code support customers to use it in both TS and JS ways.  
cc @xirzec feel free to correct me if I am wrong. Thanks

**Comment by AndrewCS149** [comment]
Thank you!
