### ISSUE TITLE
[CADL in RLC][cadl-ranch]add a few test scenarios in TS cadl emitter

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1446]
including
models with enum properties
models with optional attributes
models with nullable properties
models with read-only properties
models with client default value properties
models with constant values properties

Epic: https://github.com/Azure/cadl-azure/issues/1941

**Comment by qiaozha** [comment]
support some scenarios list here:  https://github.com/Azure/cadl-ranch

**Comment by MaryGao** [comment]
close this one as duplicated with https://github.com/Azure/autorest.typescript/issues/1535
