### ISSUE TITLE
msRest.isStream() doesn't exist

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#145]

**Comment by RikkiGibson** [comment]
is-stream went away: https://github.com/Azure/ms-rest-js/commit/3449be823592ca7b94ae43001a8139ff920d2734#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by RikkiGibson** [comment]
I failed to fix this usage of isStream: https://github.com/Azure/autorest.typescript/blob/fd190df45d51307ed131a3b2559f0f991f56a20c/src/vanilla/ClientModelExtensions.cs#L143

**Comment by RikkiGibson** [comment]
This turns into validation for a request body parameter, right? Doesn't serializer.serialize take care of this? We don't seem to have any test fixtures that actually contain `msRest.isStream`.

**Comment by daschult** [comment]
Yeah, I believe the serializer should take care of this. Can you remove this check from the generator?

**Comment by RikkiGibson** [comment]
This is confirmed to still be a problem in 2.0.304 according to https://github.com/Azure/autorest.typescript/issues/142#issuecomment-394486609
