### ISSUE TITLE
CADL+RLC support of basic types of cadl-azure-core

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#1452]
CADL provides a library of type part of "cadl-azure-core". [This is an example](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvY2FkbC3GEWNvcmUiOwrJJ8UbbGFuZy9yZXN0IjsKdXNpbmcgQcQtLkNvcmUuT3BlcmF0aW9uczsKCm1vZGVsIEVucm9sbG1lbnQgewogIEBrZXnEB0NhZGwuUmVzdC5zZWfEHigiZckqcyIpCiAgaWQ6IHN0cmluZzsKfdJPR3JvdXDMVNUwUmVnaXN05wCV2y5pbnRlcmZhY2UgSW90RHBzUmVzb3VyY2VMaWZldGltZTxUyBI%2BxUZvcCBjcmVhdGUgaXMgyBtDxRJPclJlcGxhY8w0O8YzcmVhZMwxUmVhZNImZGVsZc5ZRMUS0ipsaXN0zChMaXN0zSZ9CgrmAWtIdHRwLnJvdXRlKCIv7gFq6gD76gFdcyBleHRlbmRz%2BAEPyivpARBhdHRl7gCPQWPkAXfLLCwgeyBzb21lUGFyYW3oAYAgfcgXUmVzdWx0yhj%2FAMHpAgb4AMbGHf8Ay%2BsAn8UwPiB71nVy7AJLzXLtAmXqAwTfeTzNN8R3OwoK).

When people are using "cadl-azure-core", it automatically creates a model called `Azure.Core.Operations.Error` which is always the same everywhere. This information should be used to link to an actual SDK `Azure.Core` class to avoid duplication.

This issue should fill two purposes:
- Make sure Azure.Core has what it needs to represent `Azure.Core.Operations.Error`
- Plug the codegen to use Azure.Core and not generated types when those classes are recognized.

This is not AugustMVP scoped.

Example of Swagger generated from those types for clarity:
```
    "Azure.Core.Operations.Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "One of a server-defined set of error codes."
        },
        "message": {
          "type": "string",
          "description": "A human-readable representation of the error."
        },
        "target": {
          "type": "string",
          "description": "The target of the error."
        },
        "details": {
          "$ref": "#/definitions/Azure.Core.Operations.Error",
          "description": "An array of details about specific errors that led to this reported error."
        },
        "innererror": {
          "$ref": "#/definitions/Azure.Core.Operations.InnerError",
          "description": "An object containing more specific information than the current object about the error."
        }
      },
      "description": "The error object.",
      "required": [
        "code",
        "message",
        "details"
      ]
    },
    "Azure.Core.Operations.ErrorResponse": {
      "type": "object",
      "properties": {
        "error": {
          "$ref": "#/definitions/Azure.Core.Operations.Error",
          "description": "The error object."
        }
      },
      "description": "A response containing error details.",
      "required": [
        "error"
      ]
    },
    "Azure.Core.Operations.InnerError": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "One of a server-defined set of error codes."
        },
        "innererror": {
          "$ref": "#/definitions/Azure.Core.Operations.InnerError",
          "description": "Inner error."
        }
      },
      "description": "An object containing more specific information about the error. As per Microsoft One API guidelines - https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses.",
      "required": [
        "code"
      ]
    },
```

Epic: https://github.com/Azure/cadl-azure/issues/1942

**Comment by qiaozha** [comment]
@lmazuel I wonder if those types are the only types we need to put into the @azure-rest/core-client ? Are there any other types we need to put https://github.com/Azure/cadl-azure/tree/main/packages/cadl-azure-core/lib ?
