### ISSUE TITLE
Please review the links in README.md files in this repo as they are broken

### ISSUE THREAD

**Issue by sharathmalladi** [Azure/autorest.typescript#1488]
Reference Links from this page are broken: https://github.com/Azure/autorest.typescript/blob/main/docs/samples/readme.md
Link referencing [typescript-specific docs](https://github.com/Azure/autorest.typescript/blob/main/docs/docs/migrate/readme.md) from this page is broken: https://github.com/Azure/autorest.typescript

It will be helpful to generally verify the links referenced from README.md files work so the help docs and samples are easier to find to newbie developers.

**Comment by qiaozha** [comment]
close it as this should have been resolved. @sharathmalladi feel free to reopen it if you still found issues in the readme.md link.
