### ISSUE TITLE
Enum propertity disappears when set [Required]

### ISSUE THREAD

**Issue by snys98** [Azure/autorest.typescript#15]
I have a simple dto class like this:
```
    public class UserQueryRequest
    {
        [Required]
        public UserQueryType UserQueryType { get; set; }

        public string Username { get; set; }
    }
    public enum UserQueryType
    {
        ByUsername = 0
    }
```
the generation result in this:
```
/**
 * @interface
 * An interface representing UserQueryRequest.
 */
export interface UserQueryRequest {
  /**
   * @member {string} [username]
   */
  username?: string;
}
```
then I get rid of the `[Required]` attribute, and the result is correct
```
/**
 * @interface
 * An interface representing UserQueryRequest.
 */
export interface UserQueryRequest {
  /**
   * @member {string} [userQueryType] Possible values include: 'ByUsername'
   */
  userQueryType?: string;
  /**
   * @member {string} [username]
   */
  username?: string;
}
```

## infomations
```
1>AutoRest code generation utility [version: 2.0.4215]
1>(C) 2017 Microsoft Corporation.
1>https://aka.ms/autorest
1>No configuration found at 'file:///C:/Users/Lulus/Source/Repos/Dawu.Site/Dawu.Site.Admin/'.
1>   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12)
1>   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (~2.0.0)
```
`[Required]` attribute works well with string propertity

**Comment by amarzavery** [comment]
@syns98 A property or parameter that is required and is modeled as a enum and if the enum only has one value in it then it is a constant. (The service is expecting the client to send the property and it can only be that value). Hence we make it a constant. If it is not required then it is a string.

By the way we have a later version of the generator (2.0.67). Please use that.
Execute: `autorest --reset` and then execute the command to generate a typescript client. The newer version has  better enum support.

**Comment by snys98** [comment]
@amarzavery got it, I'll try the newest  version.

**Comment by snys98** [comment]
@amarzavery emm... I updated to the preview version of **[version: 2.0.4225]**, after I excute `autorest --reset` and generate client, I got **AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12)** didn't get the version of **2.0.67**...

**Comment by amarzavery** [comment]
I think you have the latest version.The ~sign means that it is greater than or equal to 2.0.12. execute `autorest --info` to see the version of all the plugins. Another way to check is to go to C:/Users/lulus/. autorest.
Also check The custom extension for enums that we support. It is called x-ms-enum. https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md

**Comment by snys98** [comment]
@amarzavery Thanks a lot.
