### ISSUE TITLE
report warning in the emitter if doc is missing/empty

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1504]
All Tier-1 language DPG generators will fail generation if a doc tag is missing or empty, rather than generating documentation to fill in the gaps.  And this would should be implemented in emitter side.

https://github.com/Azure/autorest.csharp/issues/2621

Epic: https://github.com/Azure/cadl-azure/issues/1945
CADL Blocking: https://github.com/Azure/cadl-azure/issues/1748

**Comment by annelo-msft** [comment]
Dependent on https://github.com/Azure/cadl-azure/issues/1748

**Comment by MaryGao** [comment]
Move to GA

**Comment by MaryGao** [comment]
I think we can close this one due.Because azure core already reported
