### ISSUE TITLE
isUnexpected function does not work as expected in the generated autorest code

### ISSUE THREAD

**Issue by sharathmalladi** [Azure/autorest.typescript#1513]
The isUnexpected function in sdk\personalizer\ai-personalizer-rest\src\isUnexpected.ts script has the following line:
let pathDetails = responseMap[`${method} ${url.pathname}`];

The issue is that the responseMap has entries with keys that look like the following when inspecting in the debugger:
"GET /configurations/policy"

Where as the url.pathname looks like this: '/personalizer/v1.1-preview.3/model'

This results in the map not finding the correct pathDetails and so isUnexpected() never returns true even if the response is good.

The following manual update addresses this issue.

Before (fix):
  let pathDetails = responseMap[`${method} ${url.pathname}`];

After (fix):
const urlpathname = url.pathname.replace("/personalizer/v1.1-preview.3", "");

**Comment by qiaozha** [comment]
@joheredi has this issue been resolved ?

**Comment by MaryGao** [comment]
I will take into this issue and identify that.
