### ISSUE TITLE
Child objects are not serialized property when building JSON body

### ISSUE THREAD

**Issue by chaholl** [Azure/autorest.typescript#154]
Lets say I have an object that looks like this (C#):

```
public sealed class Performance
    {
        public string Id { get; set; }
        public DateTimeOffset StartDateTime { get; set; }
        public Distance Distance { get; set; }
        public TimeSpan Duration { get; set; }
    }
```
it refers to a property of type Distance that looks like this:
```
    public sealed class Distance
    {
        public enum UnitOfMeasure
        {
            Kilometre,
            Mile
        }
        public double Value { get; }        
        public UnitOfMeasure Unit { get; }
```

If I create a REST API that accepts this as a parameter, it's not properly mapped when the generated typescript client calls the API and builds the JSON body. However, it's mapped fine in the response. There's nothing on interest logged to the console.

Is this an issue or have I missed something?

Generated JSON body looks like this:
`{"startDateTime":"2018-06-06T20:30:30.185Z","distance":{},"duration":"00:00:00"}`

**Comment by RikkiGibson** [comment]
Can you post the swagger definition that gets generated for the Distance class?

**Comment by amarzavery** [comment]
Can you provide a reference to the swagger spec from which you are generating the TS client?. From the provided information, I don't see why the distance property would be an empty object.

**Comment by chaholl** [comment]
Thanks for the prompt, with a bit of digging around in the swagger spec I've found the problem. 
In my C# class I have:
```
 public double Value { get; }        <=note no setter
 public UnitOfMeasure Unit { get; } <=note no setter
```
This results in a definition of:
```
"Distance": {
      "type": "object",
      "properties": {
        "value": {
          "format": "double",
          "type": "number",
          "readOnly": true
        },
        "unit": {
          "enum": [ "Kilometre", "Mile" ],
          "type": "string",
          "readOnly": true
        }
      }
```
The source of the problem is "readonly": true - the generated client is rightly ignoring anything I try to pass as Distance. Actually what I really want is:
```
 "Distance": {
      "type": "object",
      "properties": {
        "value": {
          "format": "double",
          "type": "number"
        },
        "unit": {
          "enum": [ "Kilometre", "Mile" ],
          "type": "string"
        }
      }
    }
```
Easily fixed by adding setters in my view model.
