### ISSUE TITLE
[Cadl RLC] Design the generic/template models and provide user-friendly name for them

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1553]
This issue may split into two issues. We'd like to cover two parts:

- Rethink the current design for generic/template models from Cadl
- Fix the naming issue if underlying template issue don't provide a friendly name

**Comment by MaryGao** [comment]
Regarding the second one we may reference this issue: https://github.com/Azure/cadl-azure/issues/1995

**Comment by weidongxu-microsoft** [comment]
Note that according to Johan, there should not be a new model for request (at least for PUT), as he expect a single routd-trip model. E.g. request and response model both as "Project".
