### ISSUE TITLE
[Cadl RLC] Fix the byte array converted to string issue

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1554]
Currently we generate the `string` type for byte array but it's not perfect so we need to rethink about it.

1. Which type is proper for input?
2. Which type is proper for output?
3. How to handle encodings when serializing?

**Comment by MaryGao** [comment]
Below are confirmed with Time

> The convention we have been following for http:
bytes as a response or body parameter means you are passing a binary body
bytes inside a json object means you need to base64 encode it

**Comment by MaryGao** [comment]
Move to MQ considering we achieve parity now

**Comment by qiaozha** [comment]
This is a probably a candidate for HRLC
