### ISSUE TITLE
Pipeline Build Analyze failed with 404 broken link https://nodejs.org/about/releases/

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#1566]
![image](https://user-images.githubusercontent.com/98569699/190956916-e3fb38e0-7826-4ac0-a3c2-9eafe49e7f7b.png)
The link is in sdk/../arm-../samples/../typescript/README.md, sdk/../arm-../samples/../javascript/README.md and sdk/../arm-../s/README.md

**Comment by MaryGao** [comment]
I am asking the node team to provide the replacement page link here https://github.com/nodejs/node/issues/44719

**Comment by MaryGao** [comment]
closed as fixed

**Comment by MaryGao** [comment]
change to https://github.com/nodejs/release#release-schedule
