### ISSUE TITLE
[RLC] Handle mixed api-versions cross operation groups in parameters.ts

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1572]
In our current design we only filter out the api-version parameter when composing the parameters. This is not correct if the cald inputs have multiple api-versions because we will have no default global api version in generated client. 

So we need to support the case where there are more than one api verions cross op groups.

Please notice this is NOT multiple api version support. Because for separated resource type we will only support one api version .

**Comment by qiaozha** [comment]
does #1565 not clear enough for this case ? And please refrain to use multiple api version if it's not the case that **the same  resource types** has more than one api versions. Different resource types have different api version and each resource types still have one api version is not called multiple api version.

**Comment by MaryGao** [comment]
update the title to reduce confusion

**Comment by MaryGao** [comment]
See example and discussion here: https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1668709231352?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1668709231352&teamName=Azure%20SDK&channelName=Cadl%20Discussion%20%F0%9F%90%AE&createdTime=1668709231352&allowXTenantAccess=false

**Comment by qiaozha** [comment]
needs some verification in cadl emitter.

**Comment by MaryGao** [comment]
Close it as no real case, feel free to re-open it if needed
