### ISSUE TITLE
Compilation errors regarding ServiceClientOptions/OperationSpec with serializer

### ISSUE THREAD

**Issue by felpel** [Azure/autorest.typescript#162]
![carbon](https://user-images.githubusercontent.com/5000004/41197168-3ed6243a-6c22-11e8-8c19-84c5c364d70d.png)

I'm following the instructions mentioned in the README regarding `ms-rest-js` / `ms-rest-azure-js`. As you can see in the previous image, the version also matches the one in the `README`.

```javascript
"ms-rest-azure-js": "~0.5.68",
"ms-rest-js": "~0.9.248"
```

`msRest.ServiceClientOptions` and `msRest.OperationSpec` seems to miss a `serializer` property.

---

I'm also trying to figure out what is the appropriate upgrade path whenever a version of the extension is bumped.

**Comment by RikkiGibson** [comment]
Please try with `autorest.typescript@2.0.330`. The README is based on whatever is merged to master (what you'll find under the preview tag under npm.

**Comment by felpel** [comment]
@RikkiGibson how do I explicitly set a version for the TS extension?

**Comment by RikkiGibson** [comment]
Most direct way I know is with `autorest --use=@microsoft.azureautorest.typescript@2.0.330` but I think others have had success saving the desired version as a devDependency.

**Comment by felpel** [comment]
Should we add `autorest` and `autorest.typescript` as `devDependencies` in our `package.json` ?

**Comment by RikkiGibson** [comment]
I don't personally do it-- I use the ["literate configuration"](https://github.com/Azure/autorest/blob/master/docs/user/literate-file-formats/configuration.md) to specify a version of the extension I want and mostly don't worry about the version of the autorest core I'm using.

You can do that with a README.md structured like this (note that the `> see https://aka.ms/autorest` line tells AutoRest that this is an AutoRest config file). This is just going from memory--I haven't tried running AutoRest with this example config.

````md
# some title, doesn't matter
> see https://aka.ms/autorest

```yaml
typescript: true
input-file:
  - ./spec/my-swagger.json
use:
  - @microsoft.typescript@2.0.330
```
````

**Comment by felpel** [comment]
Thanks for your help @RikkiGibson, problem solved! The only thing that would need to be swapped is your `use` parameter for `@microsoft.azure/autorest.typescript@2.0.330`.
