### ISSUE TITLE
Generate JS client from Autonomous Development Platform Cadl API description

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1625]
This issue tracks validating that a RLC generator can generate the ADP client, models, APIs from https://github.com/Azure/azure-rest-api-specs-pr/pull/9236/files, to achieve parity with what DPG v1.0 can generate from the ADP OpenAPI description from the same PR.

Inputs:
https://github.com/Azure/azure-rest-api-specs-pr/pull/9236/files

**Comment by MaryGao** [comment]
Updated at 11/24:
API view: 
TS emitter config: https://github.com/MaryGao/azure-rest-api-specs-pr/commit/33f140ace9f9e1a7357d9031054faf20f75a82ca
Generated code: https://github.com/Azure/azure-sdk-for-js/pull/23979

**Comment by imakhlin** [comment]
Hi, please note the [ADP PR](https://github.com/Azure/azure-rest-api-specs-pr/pull/9634) has been updated. It finally passes all the validation checks. Please update to the latest commit.

**Comment by MaryGao** [comment]
Close it as APD is deprecated
