### ISSUE TITLE
[RLC] Polling request would fail in testing with polling helper function

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1626]
Currently the v2 recorder has an issue https://github.com/Azure/azure-sdk-for-js/issues/23420.  The would cause the polling status requests would fail in `record` or `playback` mode.

So we need to follow up that issue. The recorder issue is fixed in pr https://github.com/Azure/azure-sdk-for-js/pull/23803/files.

We need to do following:

- [ ] Bump the recorder version to the latest
- [ ] Remove the workaround for this bug existing in current azure-sdk-for-js repo

**Comment by qiaozha** [comment]
@MaryGao  please close this issue if it's resolved.

**Comment by MaryGao** [comment]
Close it as we don't need to upgrade it
