### ISSUE TITLE
GA autorest.typescript v6

### ISSUE THREAD

**Issue by jeremymeng** [Azure/autorest.typescript#1631]
Release a GA version of autorest.typescript v6.  It's currently in RC.

- [ ] bump version
- [ ] update package status in README

**Comment by joheredi** [comment]
@qiaozha, @sarangan12 do you have any concerns about releasing a stable version? We are already GAing libraries generated with the current generator so I think it should be fine to release 6.0.0

**Comment by sarangan12** [comment]
I am fine with the GA

**Comment by qiaozha** [comment]
I think there're still some issues left that I can think of in HLC. Wonder if we should resolve them first and then release the GA version. 
1. Credential scopes in government cloud https://github.com/Azure/autorest.typescript/issues/1597
2. Remove the appended 204 code https://github.com/Azure/autorest.typescript/issues/1537 
3. Tyoe name inconsistent with swagger definition https://github.com/Azure/autorest.typescript/issues/1404
4. Parameter order issue https://github.com/Azure/autorest.typescript/issues/1529

**Comment by qiaozha** [comment]
@MaryGao  @lirenhe Do you think we should start fixing those mgmt sample generation issue before the GA https://github.com/Azure/autorest.typescript/issues/1479

**Comment by qiaozha** [comment]
> I think there're still some issues left that I can think of in HLC. Wonder if we should resolve them first and then release the GA version.
> 
> 1. Credential scopes in government cloud [[HLC] Remove the default credential scope code and update the scope by using options enriched from core lib #1597](https://github.com/Azure/autorest.typescript/issues/1597)
> 2. Remove the appended 204 code [[HLC] Remove the appended 204 response code when the operation is LRO #1537](https://github.com/Azure/autorest.typescript/issues/1537)
> 3. Tyoe name inconsistent with swagger definition [[mgnt] Type choice name is not matched between definition and reference if name is all uppercase #1404](https://github.com/Azure/autorest.typescript/issues/1404)
> 4. Parameter order issue [Update Codegen to generate operation with parameters in the right position #1529](https://github.com/Azure/autorest.typescript/issues/1529)

I think issue #1537 and #1404 and #1529 will cause SDK breaking change.

**Comment by qiaozha** [comment]
> I think there're still some issues left that I can think of in HLC. Wonder if we should resolve them first and then release the GA version.
> 
> 1. Credential scopes in government cloud [[HLC] Remove the default credential scope code and update the scope by using options enriched from core lib #1597](https://github.com/Azure/autorest.typescript/issues/1597)
> 2. Remove the appended 204 code [[HLC] Remove the appended 204 response code when the operation is LRO #1537](https://github.com/Azure/autorest.typescript/issues/1537)
> 3. Tyoe name inconsistent with swagger definition [[mgnt] Type choice name is not matched between definition and reference if name is all uppercase #1404](https://github.com/Azure/autorest.typescript/issues/1404)
> 4. Parameter order issue [Update Codegen to generate operation with parameters in the right position #1529](https://github.com/Azure/autorest.typescript/issues/1529)

@joheredi I think all these issues have been resolved. You may release the GA version of @autorest/typescript now. Just need to make sure you will also release a new version for rlc-common and cadl-typescript.

**Comment by jeremymeng** [comment]
Thanks all!
