### ISSUE TITLE
[RLC] Handle the unknown and never type from CADL in codegen

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1648]
Currently the unknown and never type are directly mapped to TypesScript unknown, never. We have two concerns for this implementation: 
- `never` type tagged on property is wired because end user cannot refer or assign value to it
- `unknown` type is meaningful for input model not for output model, after getting the model details from server end user may adjust values and then re-assign to other models.

So we have new propersals for these two types:
| Cadl Type |  Input Type | Output Type   | 
|---|---|---|
| never| ignore   | ignore  | 
| unknown| unknown | any|

Here we have examples for them:

- `never` in OperationStatus from azure-core: https://github.com/Azure/cadl-azure/blob/307d4c72fe43f87c5eadda5c02901a7760d3cdb9/packages/cadl-azure-core/lib/foundations.cadl#L20-L33
- `unknown` in Cadl-ranch example: https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/arrays/item-types/main.cadl#L85

@joheredi Could you confirm the above design with Brian?

**Comment by qiaozha** [comment]
for unknown, we can treat it as any in the output.
