### ISSUE TITLE
Generate JS RLC client from Anomaly Detector (aka MVAD) Cadl API description

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1659]
This issue tracks validating that a RLC generator can generate the MVAD RLC client from https://github.com/Azure/azure-rest-api-specs/tree/feature/anomaly-detector-cadl/specification/cognitiveservices/data-plane/AnomalyDetector/stable/v1.1/cadl, to achieve parity with what DPG/RLC v1.0 can generate from MVAD OpenAPI description.

Inputs:
https://github.com/Azure/azure-rest-api-specs/tree/feature/anomaly-detector-cadl/specification/cognitiveservices/data-plane/AnomalyDetector/stable/v1.1/cadl

**Comment by MaryGao** [comment]
Detailed issues here: https://github.com/Azure/autorest.typescript/issues/1654

**Comment by qiaozha** [comment]
close it as completed
