### ISSUE TITLE
The property marked as @key should be readonly in the generated models

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1662]
@key - mark a model property as the key to identify instances of that type

So this means the property could not be set at the client level and it is readonly.

Please help to verify this behavior.

**Comment by lirenhe** [comment]
Let's hold this work to get more clarification from CADL team

**Comment by qiaozha** [comment]
depending on issue https://github.com/Azure/cadl-azure/issues/2260
