### ISSUE TITLE
Question/bug: Deal with objects with byte arrays

### ISSUE THREAD

**Issue by felpel** [Azure/autorest.typescript#170]
Hi, 

We've got a bug with an object that has a [JsonWebKey](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.webkey.jsonwebkey?view=azure-dotnet) property. 

The `JsonWebKey` payload returned from the external service seems to show byte arrays as strings (check the payload example). Autorest tries to deserialize the property with the `Window.atob` method and we get the following deserialization error:
```
Error: Error InvalidCharacterError: Failed to execute 'atob' on 'Window': 
The string to be decoded is not correctly encoded. occurred in deserializing the responseBody
```

We could mitigate the problem by nullyfing the key itself since we don't need in the service that consumes the object. At this point, we have the following constraints:

- We can't modify the `JsonWebKey` (C#) itself since it comes from a MS library;
- Maybe we're missing something in our Swagger document;
- Maybe there is a special switch that we are not aware of for the code generation with Autorest;

Thanks in advance for your help 😄 

<details>
<summary>JsonWebKey payload example:</summary>

```js
{"kty":"RSA","n":"3Ab3gTAExSETjhzhcqKI8vxaQguel5ICr-MQA_AlwxfoOd_tgpGbI9WEG3A7b9txjlNDrYD-5_GW9Y_ls5e2X-XUvrg9Bhn91j3kX7lqUssE4Ht0yk8Ua4i4fkNrPuPg9_RhBK4je4NetPChG9potyMMGDTMDfzimseZ6r-xuvMDwMmlvOtEH_vQBckLag3Tf11_wruVA697ZYqskfYPFG-zIQzmQRR6_-qBPmU6033xSWRgyZ6FeOB6lCW16O6UvLVOZnMwkS3IO6_q7RHLXT0_ucM1xIWs18X9S9-3bVg8inFKRNrUEbFRbt6O2rzzPZw8sRHiCcMBAj7SteqWOQ","e":"AQAB"}
```
</details>

<details>
<summary>Swagger definition (swagger.json)</summary>

![image](https://user-images.githubusercontent.com/5000004/41545467-384237c6-72e9-11e8-8437-d77de7d8fc71.png)
</details>

<details>
<summary>JsonWebKey interface (Typescript)</summary>

```ts
**
 * @interface
 * An interface representing JsonWebKey.
 */
export interface JsonWebKey {
  /**
   * @member {string} [kid]
   */
  kid?: string;
  /**
   * @member {string} kty
   */
  kty: string;
  /**
   * @member {string[]} [keyOps]
   */
  keyOps?: string[];
  /**
   * @member {Uint8Array} [n]
   */
  n?: Uint8Array;
  /**
   * @member {Uint8Array} [e]
   */
  e?: Uint8Array;
  /**
   * @member {Uint8Array} [d]
   */
  d?: Uint8Array;
  /**
   * @member {Uint8Array} [dp]
   */
  dp?: Uint8Array;
  /**
   * @member {Uint8Array} [dq]
   */
  dq?: Uint8Array;
  /**
   * @member {Uint8Array} [qi]
   */
  qi?: Uint8Array;
  /**
   * @member {Uint8Array} [p]
   */
  p?: Uint8Array;
  /**
   * @member {Uint8Array} [q]
   */
  q?: Uint8Array;
  /**
   * @member {Uint8Array} [k]
   */
  k?: Uint8Array;
  /**
   * @member {Uint8Array} [keyHsm]
   */
  keyHsm?: Uint8Array;
}
```
</details>

<details>
<summary>JsonWebKey mapper (Typescript)</summary>

```ts
export const JsonWebKey = {
  serializedName: "JsonWebKey",
  type: {
    name: "Composite",
    className: "JsonWebKey",
    modelProperties: {
      kid: {
        serializedName: "kid",
        type: {
          name: "String"
        }
      },
      kty: {
        required: true,
        serializedName: "kty",
        type: {
          name: "String"
        }
      },
      keyOps: {
        serializedName: "key_ops",
        type: {
          name: "Sequence",
          element: {
            serializedName: "stringElementType",
            type: {
              name: "String"
            }
          }
        }
      },
      n: {
        serializedName: "n",
        type: {
          name: "ByteArray"
        }
      },
      e: {
        serializedName: "e",
        type: {
          name: "ByteArray"
        }
      },
      d: {
        serializedName: "d",
        type: {
          name: "ByteArray"
        }
      },
      dp: {
        serializedName: "dp",
        type: {
          name: "ByteArray"
        }
      },
      dq: {
        serializedName: "dq",
        type: {
          name: "ByteArray"
        }
      },
      qi: {
        serializedName: "qi",
        type: {
          name: "ByteArray"
        }
      },
      p: {
        serializedName: "p",
        type: {
          name: "ByteArray"
        }
      },
      q: {
        serializedName: "q",
        type: {
          name: "ByteArray"
        }
      },
      k: {
        serializedName: "k",
        type: {
          name: "ByteArray"
        }
      },
      keyHsm: {
        serializedName: "key_hsm",
        type: {
          name: "ByteArray"
        }
      }
    }
  }
};
```
</details>

**Comment by RikkiGibson** [comment]
Which ms-rest-js version is this happening on? I remember fixing some problems in browser base64 [de]coding 2 weeks ago.

**Comment by felpel** [comment]
@RikkiGibson  We have the following versions:

- Core: `2.0.4280`;
- Modeler: `2.1.23`;
- TS extension: `2.0.330`;
- `ms-rest-js`: `0.9.248`

**Comment by RikkiGibson** [comment]
OK, thanks. I just tried adding basically the value you provided as a test case and it fails, so I'll look into it.

**Comment by RikkiGibson** [comment]
One thing I'm wondering is if perhaps this is not actually a base64 string, but some other kind of encoding. Maybe the Key Vault REST API docs indicate this?

**Comment by RikkiGibson** [comment]
@felpel can you try changing `format: "byte"` to `format: "base64url"` in the Swagger for the failing properties?

**Comment by felpel** [comment]
@RikkiGibson I see what you're saying, but how would I override this if we use `Swashbuckle` to generate our Swagger document?

**Comment by RikkiGibson** [comment]
Possibly this could help? https://github.com/domaindrivendev/Swashbuckle.AspNetCore#override-schema-for-specific-types

**Comment by felpel** [comment]
Allright, we will use a custom input file with your previous hint regarding the `base64url` format. I will let you know if it worked.

**Comment by RikkiGibson** [comment]
Please feel free to reopen if the issue is not resolved @felpel.

**Comment by Eric-Bonneau** [comment]
If anyone encounters this issue using Swashbuckle in the future, you can introduce an `ISchemaFilter` for `JsonWebKey`. That way you can apply a format to the properties with base64 URL encoding after Swashbuckle has already generated the schema.

Something like this (note I'm using `Swashbuckle.AspNetCore` v3.0.0 and the API may be different in a later version):
```
public class JsonWebKeyFilter : ISchemaFilter
{
    public void Apply(Schema schema, SchemaFilterContext context)
    {
        if (context.SystemType == typeof(JsonWebKey))
        {
            schema.Properties["n"].Format = "base64url";
            // do the same thing for the other properties
        }
    }
}
```

The problem is that the `JsonWebKey` class has custom JSON converters for several properties and AutoRest doesn't know about them. So if you introduce a filter like above, you can override the schema generated by Swashbuckle so that way AutoRest knows how to (de)serialize those properties.

**Comment by ffMathy** [comment]
@RikkiGibson this is still an issue.
