### ISSUE TITLE
[Cadl RLC] String enum body reported errors during deserialization in sever side

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1712]
When the body is string the core-client-rest would skip `JSON.stringify`  

https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-client-rest/src/sendRequest.ts#L154-L157.

However if the body is fixed enum the body would be just one of the enum values and has no way to enable the step `JSON.stringify`. 

So finally the content `{body: "Monday"}` would fail to deserialize in server side because this is not valid JSON object. 

https://github.com/Azure/autorest.typescript/blob/afd65aeae278564113c13b65652247cff7408012/packages/cadl-typescript/test/integration/fixedEnums.spec.ts#L23-L32

```
 Error Unexpected token M in JSON at position 0 {"body":"Monday","expose":true,"stack":"SyntaxError: Unexpected token M in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\marygao\\project\\autorest.typescript\\common\\temp\\node_modules\\.pnpm\\body-parser@1.20.1\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Users\\marygao\\project\\autorest.typescript\\common\\temp\\node_modules\\.pnpm\\body-parser@1.20.1\\node_modules\\body-parser\\lib\\read.js:128:18\n
```

**Comment by joheredi** [comment]
What does the service expect? `{"body": ""Monday""}`?

**Comment by MaryGao** [comment]
`{"body": ""Monday""}` would pass in server side but the ""Monday"" would not be a valid enum value.
