### ISSUE TITLE
CI Failing on  @apidevtools/json-schema-ref-parser dependency

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#1733]
>  error: @apidevtools/json-schema-ref-parser@9.1.1: The engine "node" is incompatible with this module. Expected version ">= 17". Got "16.19.0"
  | error: Found incompatible module.

https://dev.azure.com/azure-sdk/public/_build/results?buildId=2137670&view=logs&j=91420f01-9daf-53d3-aec1-75f797de9149&t=3aed5a45-624c-53bb-998d-671906525409

**Comment by qiaozha** [comment]
I think this could be closed. @joheredi let me know if there are still other work items for it.
