### ISSUE TITLE
Support different authentication defined in CADL

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1743]
The supported authentication types are defined in https://microsoft.github.io/typespec/standard-library/rest/authentication

Today, we only support ApiKeyAuth and OAuth2Auth.

We need to figure out how to support other authentication types.

Note:

1. We don't need to generate everything, some kind of the custom code is acceptable and we need to make our framework ready.
2. We should not let codegen to crash for the cadl defined authentication types.

**Comment by MaryGao** [comment]
We have four kinds of auth supported in Cadl
- BasicAuth
- BearerAuth
- ApiKeyAuth
- OAuth2Auth

**Comment by qiaozha** [comment]
close it as we don't need to support bear token auth.
