### ISSUE TITLE
[TypeSpec] Support array format for query/header

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#1756]
By default, TypeSpec means `multi` (a=1&b=2)

You can specify an option by query option:
https://microsoft.github.io/cadl/standard-library/rest/reference/decorators#@Cadl.Http.query
https://microsoft.github.io/cadl/standard-library/rest/reference/js-api/interfaces/http.QueryParameterOptions

For instance, this means csv:
```
  @get list(@query({format: "csv"}) option?: string[]): Widget[] | Error;
```

We should at least make the default `multi` work as this is blocking for translator team

**Comment by lirenhe** [comment]
@qiaozha, i think we already supported this in TS, could you confirm?

**Comment by qiaozha** [comment]
yes, will close it after collection format cadl ranch test enabled.

**Comment by qiaozha** [comment]
pending on https://github.com/Azure/azure-sdk-for-js/pull/24875

**Comment by qiaozha** [comment]
pending on https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/collectionFormat/main.cadl#L52-L57

**Comment by qiaozha** [comment]
pending on https://github.com/Azure/typespec-azure/issues/2591

**Comment by qiaozha** [comment]
If all the above issues get resolved, we can resolve this issue by this PR https://github.com/Azure/autorest.typescript/pull/1768
