### ISSUE TITLE
[DPG] Support of Unknown in models.

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#1798]
`unknown` means that it can be anything. DPG should generate something that would allow anything to be passed (JSON object, array of string, null, etc.).

It's NOT the same thing as `object`, which means JSON object `{}`. It's acceptable for emitters to consider `object` and `unknown` as the same thing, depending of your language constraints.

This issue is focused on models as a success criteria. If the design is easy in query, header, etc. other part, there is no concern to add it. If this requires special design, then it's out of scope for now.

**Comment by MaryGao** [comment]
I think we already support this and here are the UTs:
https://github.com/Azure/autorest.typescript/blob/8e11377517f9577855bd003f9b3e0df8f679e34a/packages/typespec-ts/test/unit/modelsGenerator.spec.ts#L349-L361


https://github.com/Azure/autorest.typescript/blob/8e11377517f9577855bd003f9b3e0df8f679e34a/packages/typespec-ts/test/unit/modelsGenerator.spec.ts#L758-L763

**Comment by qiaozha** [comment]
close it as already supported.
