### ISSUE TITLE
[DPG] Support of Record<unknown> in models 

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#1799]
`Record<unknown>` means any JSON object, but not JSON token. You can pass anything like `{...}`, but not an array of string or null.

It may or may not makes sense to separate this scenario from `unknown` which is more wide

Tests should include a JSON object, input output

**Comment by MaryGao** [comment]
I think we already support this and here are the UTs:
https://github.com/Azure/autorest.typescript/blob/main/packages/typespec-ts/test/unit/modelsGenerator.spec.ts#L349-L361

**Comment by qiaozha** [comment]
close it as already supported.
