### ISSUE TITLE
'Consumes' field on swagger definition is ignored after v2.0.245 for Get/Delete requests

### ISSUE THREAD

**Issue by bernarden** [Azure/autorest.typescript#180]
Before the version 2.0.245 the following was generated for my swagger definition.
```  typescript
    ...
    // Create HTTP transport objects
    const httpRequest = new WebResource();
    // Set Headers
    httpRequest.headers.set("Content-Type", "application/json; charset=utf-8");
    ...
```
So the generated package was specifying Content-Type as application/json for all of the types of requests (GET, PUT, etc.).

Since 2.0.245, autorest.typescript seems to only depend on the autorest schema passed to sendOperationRequest function when it comes to the 'Content-Type'. Eg:
``` typescript
...
operationRes = await this.sendOperationRequest(
        httpRequest,
        operationArguments,
        {
          httpMethod: "POST",
          baseUrl: this.baseUri,
          path: "api/1.0/Controller/Endpoint",
          ...
          requestBody: {
            ...
          },
          contentType: "application/json; charset=utf-8",
          responses: {
           ...
          },
          serializer: this.serializer
        });
...
```
This currently works fine for Patch, Put and Post as far as I can tell but doesn't work for Get and Delete.
For Get and Delete the content type is not set in this autorest schema passed to sendOperationRequest, which makes request coming from a browser default to 'application/x-www-form-urlencoded'. This fails on the server side (415) because controllers are explicitly specified to consume 'application/json'. 

I have checked the swagger definition generated by the server-side. All endpoints contain: 
```JSON
...
"consumes": [ "application/json"],
...
```

Am I missing something? Is there a workaround for this other than downgrading?

**Comment by RikkiGibson** [comment]
We should be able to give you the previous behavior, but it seems odd that GET and DELETE requests contain a Content-Type when there isn't a body (there isn't a body, right?)

**Comment by bernarden** [comment]
@RikkiGibson There isn't a body for those requests. Only query parameters and headers.

**Comment by RikkiGibson** [comment]
Got it. I'll try and have a look tomorrow.

**Comment by RikkiGibson** [comment]
We're working on an update which should resolve this issue-- just taking a little more time to try and minimize the code size impact of the change. In the meantime you can either temporarily stay with the old generator, or pass a custom header with the desired content-type, or create a custom pipeline which automatically applies the content-type header to requests.

**Comment by bernarden** [comment]
Thanks for the update. I already had to temporally downgrade the version we are using, so please take your time.

**Comment by RikkiGibson** [comment]
So, I've had this problem in the back of my head for a bit. [The RFC is not 100% crystal-clear](https://tools.ietf.org/html/rfc7231#section-3.1.1.5), but does imply that only a request with a body should have a Content-Type.

Ultimately it seems like there is no real problem in moving back to the previous behavior which worked for the services we know of and care about. I'm about to update the linked PR to reduce the duplication of the contentType property in the operation specs so that we don't take a size hit from doing this.

**Comment by RikkiGibson** [comment]
@bernarden thanks for waiting so long on this--please give the newest `@microsoft.azure/autorest.typescript@preview` a try.
