### ISSUE TITLE
Issues #2: CADL Generated Code Build Issue in EventGrid SDK

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest.typescript#1819]
While working on the EventGrid SDK, generated from the CADL files, I have noticed the following. The API Extractor is reporting missing imports. These missing imports can be fixed only by exposing several classes from the rest layer of the SDK. This happens because under the `src/rest/azureMessagingEventGridClient.ts` file, we have a method `createClient` which returns `AzureMessagingEventGridClient`. This is the root cause of the issue and must be fixed.

@joheredi @xirzec FYI...

**Comment by qiaozha** [comment]
close it as resolved.
