### ISSUE TITLE
Add nightly CI to test latest TSP releases

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#1824]
The TSP team push to npm a package for every single merge to main. The objective of this issue is that the language repo has a nightly build that:
- Install the latest "next" release from npm for all dependencies (compile, azure-core, etc.)
- Run the testsuite as usual

Implementation detail: using [ncu](https://www.npmjs.com/package/npm-check-updates) with `--target @next` should allow for simple package.json update to latest dev version (not tested at the time of this issue).

ETA should be before the next release of the TSP team (early May)

**Comment by MaryGao** [comment]
Close as done
