### ISSUE TITLE
[RLC] Useless model is generated in outputModels.ts

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1842]
After integrated with v0.44 compiler we generated the useless models in `outputModels.ts` considering these models are not referenced by any response types so it should not be generated.
https://github.com/azure/autorest.typescript/blob/076a34cf00b1fbc3de07a8b9f13a381cac53d831/packages/typespec-test/test/eventgrid_modular/generated/typespec-ts/src/rest/outputModels.ts#L56-L60

**Comment by MaryGao** [comment]
The root cause may be relevant to https://github.com/Azure/typespec-azure/issues/2993.

**Comment by lirenhe** [comment]
Close it as the problem was solved.
