### ISSUE TITLE
Fix the typescript example code missing issue in tsp docs site

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1865]
Fix the typescript code missing issue in tsp docs site.
https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/02client

How to repo:
- Go to https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/02client
- Click `TypeScript` tab
- The code is `FIXME`

**Comment by lirenhe** [comment]
Close it as fixed.
