### ISSUE TITLE
Support generating ApiKey with prefix 

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#1870]
This TypeSpec:
```
@useAuth({
  type: AuthType.http,
  scheme: "SharedAccessKey",
})
```

Means to authenticate using the headers:
```
Authorization: SharedAccessKey <put my key here>
```

TypeScript Azure-Core do not provide support for this, see additional discussion here:
https://github.com/Azure/azure-sdk-for-js/issues/25683

Work item is to recognize the TypeSpec, and configure the AzureKeyCredentialPolicy with a prefix.

Cadl-Ranch test:
https://github.com/Azure/cadl-ranch/pull/262

**Comment by lirenhe** [comment]
Only used in one service,  will consider move the logic to Azure.Core if this is a common pattern.
