### ISSUE TITLE
[Epic][DPG] Adopt to the TCGC code model converter

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1893]
Currently, we have somehow copied the model converter from Python emitter, and they have been moved it into TCGC, we will need to adopt to it, so that we are consistent with them.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2321
- [ ] https://github.com/Azure/autorest.typescript/issues/2322
```

**Comment by MaryGao** [comment]
We agreed that modular would adopt to the tcgc so I label this as p1 items and I think it's better to as early as possible to adopt once tcgc is stable.
