### ISSUE TITLE
RLC: Handle Non-standard special headers for client-Request-Id and return-Client-Request-Id

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1906]
This involves 2 parts of the work:

a. Azure.Core should have a policy to append return-client-request-id and client-request-id.
b. Other SDKs plan to leverage codegen to automatically add this policy to pipeline in client constructors and remove those two head parameters from method signature.   JS RLC should decide what the API signature and payload would look like.

**Comment by MaryGao** [comment]
Batch service has the requirement to custom their request id header.

- `return-client-request-id` ([tsp here](https://github.com/Azure/azure-rest-api-specs/blob/b37ad7f957f0c6f9dd149546e46399308f83b366/specification/batch/Batch/routes.tsp#L2729-L2738)) 
We need to confirm the detailed usage https://github.com/Azure/azure-rest-api-specs/pull/23291/files#r1251427423
- `client-request-id` ([tsp here](https://github.com/Azure/azure-rest-api-specs/blob/b37ad7f957f0c6f9dd149546e46399308f83b366/specification/batch/Batch/routes.tsp#L2719-L2727))

We have a `setClientRequestIdPolicy` with default header `x-ms-client-request-id` for tracing, so I prefer we could add a option `clientRequestIdHeaderName` in PipelineOptions.

setClientRequestIdPolicy: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-rest-pipeline/src/policies/setClientRequestIdPolicy.ts#L19
PipelineOptions: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-rest-pipeline/src/createPipelineFromOptions.ts#L24

**Comment by MaryGao** [comment]
For another header return-client-request-id we need more confirmation.
- `return-client-request-id` ([tsp here](https://github.com/Azure/azure-rest-api-specs/blob/b37ad7f957f0c6f9dd149546e46399308f83b366/specification/batch/Batch/routes.tsp#L2729-L2738)) 

Still pending on confirming the detailed usage case. https://github.com/Azure/azure-rest-api-specs/pull/23291/files#r1251427423
