### ISSUE TITLE
Fix bug where there are missing headers in the deserialized headers object

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#193]

**Comment by XiaoningLiu** [comment]
Added a sample for a generated method. `headers` array has values, but most `parsedHeaders` values are `undefined`.

![image](https://user-images.githubusercontent.com/6889160/42272892-1ad2be62-7fba-11e8-834b-e69b0ba3d1bc.png)

**Comment by RikkiGibson** [comment]
I suspect there is a case sensitivity issue in the mapper. We can try to make sure we preserve the case from the Swagger when creating the mapper, but we probably need to adhere to RFC here:

https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive#5259004
> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.
