### ISSUE TITLE
Update the docs inside https://github.com/Azure/autorest.typescript to remove CADL related info

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1932]
List of the document to update.  Please ensure cadl should not exist in our source code and documentation except for cadl-ranch

- readme.md
- CONTRIBUTING.md
- docs\RLC-generation-Design.md
- packages\rlc-common\README.md
- packages\typespec-ts\CONTRIBUTING.md
- packages\typespec-ts\package.json

**Comment by qiaozha** [comment]
should have been resolved by #1989
