### ISSUE TITLE
Record of any

### ISSUE THREAD

**Issue by heycalmdown** [Azure/autorest.typescript#1940]
What I wanted to do is to have an object that can store any columns from the database. So I've started to use `Record<{}>`, and it wasn't going well. Here's the several cases;

```typespec
model Test {
  recordOfEmptyModel: Record<{}>,
  recordOfUnkown: Record<unknown>,
  recordOfRecordOfEmptyModel: Record<Record<{}>>,
  recordOfRecordOfUnknown: Record<Record<unknown>>,
}

@service({})
namespace TestService {
  op test(): Test;
}
```

## outputModels.ts

```ts
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

export interface TestOutput {
  recordOfEmptyModel: Record<string, Output>; ///< Output?
  recordOfUnkown: Record<string, any>;
  recordOfRecordOfEmptyModel: Record<string, dictionary>; ///< dictionary?
  recordOfRecordOfUnknown: Record<string, dictionary>; ///< dictionary?
}
```

## what I expected

```ts
export interface TestOutput {
  recordOfEmptyModel: Record<string, any>;
  recordOfUnkown: Record<string, any>;
  recordOfRecordOfEmptyModel: Record<string, Record<string, any>>;
  recordOfRecordOfUnknown: Record<string, Record<string, any>>;
}
```

I guess there's a plan to support a virtual dictionary?

**Comment by MaryGao** [comment]
Thanks for reporting this! The nested Record `Record<Record<unknown>>` in your test is not well-supported and I would work on the fix.

To workaround you could try anonymous empty model `{}` directly and we would map it to `Record<string, any>`.

**Comment by qiaozha** [comment]
@heycalmdown Hi, we previously treat `{}` as `Record<string, any>`,  to apply this in your case, we would get a 
```typescript
export interface TestOutput {
  recordOfEmptyModel: Record<string, Record<any>>;
  recordOfUnkown: Record<string, any>;
  recordOfRecordOfEmptyModel: Record<string, Record<string, Record<string, any>>>;
  recordOfRecordOfUnknown: Record<string, Record<string, any>>;
}
```
Does this make sense to you ? 
We use Record<string, any> to express empty object are mostly out of the following considerations:
1. simple type like boolean, number, string can not be expressed by empty object, but can be expressed by any. If we are using any, we will have get some issues if the customer inputs a simple type value, but the service backend doesn't accept it.
2. We could at least do a minimal type check for object value like `{a: 1}`with Record<string, any>. but with any, it just ignore any kinds of type check. 

Let me know how you think :)

**Comment by heycalmdown** [comment]
Ah, I see. I now understand where my initial explanation may have caused some confusion.

My original intention was to define a common SQL record that could contain any columns, including recurring ones like created_at, updated_at, and deleted_at. I attempted to write the specification as follows:

```typespec
model SqlRecord extends {} {
  created_at: string;
}
```

However, I discovered that I couldn't extend an empty object expression in this way. Consequently, I began exploring other possibilities, which led to the discovery of `Output` and `dictionary`.

The actual result I was aiming for is:

```ts
interface SqlRecord {
  created_at: string;
  updated_at: string;
  deleted_at: string;
  [key: string]: any;
}

export interface TestOutput {
  recordOfAny: SqlRecord;
  recordOfRecordOfAny: Record<string, SqlRecord>;
}
```

So, I completely agree with your explanation and have no objections. Thank you for your clarification.

**Comment by lirenhe** [comment]
> Ah, I see. I now understand where my initial explanation may have caused some confusion.
> 
> My original intention was to define a common SQL record that could contain any columns, including recurring ones like created_at, updated_at, and deleted_at. I attempted to write the specification as follows:
> 
> ```
> model SqlRecord extends {} {
>   created_at: string;
> }
> ```
> 
> However, I discovered that I couldn't extend an empty object expression in this way. Consequently, I began exploring other possibilities, which led to the discovery of `Output` and `dictionary`.
> 
> The actual result I was aiming for is:
> 
> ```ts
> interface SqlRecord {
>   created_at: string;
>   updated_at: string;
>   deleted_at: string;
>   [key: string]: any;
> }
> 
> export interface TestOutput {
>   recordOfAny: SqlRecord;
>   recordOfRecordOfAny: Record<string, SqlRecord>;
> }
> ```
> 
> So, I completely agree with your explanation and have no objections. Thank you for your clarification.

@heycalmdown,  for this ask, could you create an issue in https://github.com/microsoft/typespec/issues?  
It would be good to check whether there are some improvement needed for Typespec.
