### ISSUE TITLE
The latest generated OpenAI code can't compile successfully

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1941]
The latest generated OpenAI modular can't compile successfully.

Please refresh the latest tsp by link: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/OpenAI.Inference, and then re-generate codes and run install and build for it.

You would see the compile errors.

Check the details here: https://github.com/Azure/autorest.typescript/pull/1936/files#r1275759865

**Comment by deyaaeldeen** [comment]
What is the current status of this one?

**Comment by MaryGao** [comment]
Duplicated with https://github.com/Azure/autorest.typescript/issues/1965. Close as resolved.
