### ISSUE TITLE
Support new customization process

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1958]
We have finalized the [customization design](https://github.com/Azure/autorest.typescript/issues/1950) for RLC and Modular so we have following tasks:

- [x] Generate code in sources folder in customization case and in src folder in no in codegen

- [x] https://github.com/Azure/autorest.typescript/issues/1811

- [ ] https://github.com/Azure/azure-sdk-for-js/issues/26861

- [ ]  Improve the onboarding guide

**Comment by lirenhe** [comment]
@MaryGao, I updated the description of the issue with checkbox, could you highlight the items that are completed?

**Comment by MaryGao** [comment]
> @MaryGao, I updated the description of the issue with checkbox, could you click for the items that are completed?

Updated!

**Comment by MaryGao** [comment]
Closed as Timo is driving new customization process.
