### ISSUE TITLE
Still in preview?

### ISSUE THREAD

**Issue by aklt** [Azure/autorest.typescript#1961]
I am evaluating autorest as a tool for generation of clients for Typescript and I notice the disclaimer that
autorest.typescript is still in preview for version 6.0.7 here https://www.npmjs.com/package/@autorest/typescript

As far as I can see this is the version that autorest uses but it functions well on the small project I have created.

Would it be unwise of me to base a large investment on this client? 

Can you say something about when this project will be mature for public use?

I have tried to read about this elsewhere, but have not found the right place, so sorry for creating an issue here.

**Comment by qiaozha** [comment]
Sorry, there's a documentation mistake, @autorest/typescript is not in preview, it's already GA.
But I would like to know a little more about what kind of clients you are trying to generate ? And if it's helpful we are putting more resources on generating clients from TypeSpec which is a new API description language https://microsoft.github.io/typespec/ and less effort on generating client from OpenAPI with autorest.

**Comment by qiaozha** [comment]
if you are interested in REST HTTP clients, I think you should read this blog about our Rest Level Client https://devblogs.microsoft.com/azure-sdk/azure-rest-libraries-for-javascript/.  In this repo, we also support generate them from both OpenAPI and TypeSpec.

**Comment by aklt** [comment]
Hello @qiaozha , Thank you very much for pointing to this blogpost, it has some valuable information,
even though we are not planning to use the purview-catalog package right now.

I have looked at some of the examples from Typespec and it looks very expressive.  For us right now the
better more conservative choice is to stick to OpenAPI, I think.

**Comment by qiaozha** [comment]
Hi @aklt, I am not specifically suggesting the use of the purview-catalog package. Just simply noting that we have two types of libraries available: the classical client and the REST level client as of your comment:
> We plan on generating a handful of REST HTTP clients in Typescript (and C#) for an event-based system.

I thought you might be interested in the Rest Level Client, as it is light-weighted and bundle size optimized for web developer experience that closely resembles making direct REST API calls.

**Comment by aklt** [comment]
Hi @qiaozha, thank you for the pointer, I really appreciate it.  I imagine it will be good for me to have a closer look
at how the purview-catalog client is constructed, that might serve as inspiration for how I build our clients.

On a different note (sorry to get off topic...) : I noticed that [Kiota](https://learn.microsoft.com/en-us/openapi/kiota/overview)
provides similar functionality to Autorest.  Do recommendations exist on when to use one vs. the other?

**Comment by qiaozha** [comment]
If it helps, this issue might provide you some context about our earlier discussion. https://github.com/Azure/autorest.typescript/issues/1887 

/cc @xirzec Looks like people have been asked about Kiota a lot.

**Comment by aklt** [comment]
Thank you!  I will have a look there :-)

**Comment by aklt** [comment]
Hello @qiaozha , I have read the thread you pointed to and understand that autorest 
is going more towards a tool using Typespec as the specification.

We have to depend on OpenAPI 3 to generate our APIs, so it might be that Kiota is the right 
tool for us in the long run.   Right now autorest functions well, but at some point we might 
switch to Kiota.

I really appreciate the help you are giving, it is very valuable to receive guidance!

@mikekistler Thank you for also pointing to Kiota, I will have a closer look when time allows.

**Comment by aklt** [comment]
Thanks again for your help in answering my questions.
