### ISSUE TITLE
Throw rest errors in the right shape

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/autorest.typescript#1972]
The modular code generator generates code that checks if the response is unexpected and throws the response body if it indeed is, see https://github.com/Azure/autorest.typescript/blob/28e2087088f15cce2a56f4c971948a1671d50d83/packages/typespec-test/test/openai_modular/generated/typespec-ts/src/api/operations.ts#L57

However this is problematic because the response body in this case is of the following format `{ error: { message: ..., code: ... } }` and the body is not in the correct REST error shape. We need to throw `result.body.error` if the `error` field exists.

**Comment by lirenhe** [comment]
@qiaozha, please follow up about the right behaviour for throwing the error.

**Comment by deyaaeldeen** [comment]
See [here](https://github.com/Azure/azure-sdk-for-js/blob/e61abe47b46139aa8dcce886551ef96d0f0ed806/sdk/core/core-client/src/deserializationPolicy.ts#L294) for how `@azure/core-client` does it.
