### ISSUE TITLE
Generate code on "/swagger/docs/v1" endpoint

### ISSUE THREAD

**Issue by felpel** [Azure/autorest.typescript#198]
Given my backend service has a `/swagger/docs/v1` endpoint:

![image](https://user-images.githubusercontent.com/5000004/42478507-f9301060-83a2-11e8-8675-3f0ab2597d73.png)

When I try to generate the corresponding TS code, I get the following errors:
```
FATAL: swagger-document-override/md-override-loader - FAILED
FATAL: Error: Could not read 'https://localhost:44392/swagger/docs/v1'.
FATAL: swagger-document/loader - FAILED
FATAL: Error: Could not read 'https://localhost:44392/swagger/docs/v1'.
Process() cancelled due to exception : Could not read 'https://localhost:44392/swagger/docs/v1'.
```
The format is fine since I'm able to generate it if I run the tool on a local file with the same content as the one provided by the endpoint. The key difference probably resides in the fact that the endpoint uses the previous Swashbuckle endpoint that was modified in its .NET core associated project to `/swagger/v1/swagger.json` (instead of `swagger/docs/v1` without the `.json` extension).

`autorest --info` output:

```
 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4280     C:\Users\fpelletier\.autorest\@microsoft.azure_autorest-core@2.0.4280
 extension  @microsoft.azure/autorest.modeler        2.1.23       C:\Users\fpelletier\.autorest\@microsoft.azure_autorest.modeler@2.1.23
 extension  @microsoft.azure/autorest.typescript     2.0.304      C:\Users\fpelletier\.autorest\@microsoft.azure_autorest.typescript@2.0.304
 extension  @microsoft.azure/autorest.typescript     2.0.330      C:\Users\fpelletier\.autorest\@microsoft.azure_autorest.typescript@2.0.330
```

**Comment by RikkiGibson** [comment]
Just to rule out the obvious, are you supposed to set the `input-file` to `'https://localhost:44392/swagger/v1/docs'`, or to `'https://localhost:44392/swagger/docs/v1'`?

**Comment by felpel** [comment]
@RikkiGibson the input file is `https://localhost:44392/swagger/docs/v1`, I've updated the issue since I've inverted `v1` and `docs`. I've runned again the command : 
``` yaml
typescript: true
use:
  - "@microsoft.azure/autorest.typescript@2.0.330"
input-file:
  - "https://localhost:44392/swagger/docs/v1"
verbose: true
output-folder: './../serveurFps'
```

**Comment by RikkiGibson** [comment]
OK-- so doing a simple HTTP GET does return you the Swagger document to use for generation, then? I will try to repro when I get a chance.

**Comment by felpel** [comment]
So I was able to do it in the following .NET Web API sample: https://code.msdn.microsoft.com/ASP-NET-Web-API-Tutorial-8d2588b1

After I've installed the `Swashbuckle` extension, I was able to generate the code with a similar endpoint:
`autorest --typescript --input-file="http://localhost:47503/swagger/docs/v1"`

Could it be related that my target repo (not the sample) is **HTTPS**?

**Comment by RikkiGibson** [comment]
Possibly-- I overlooked that earlier, actually. Using https on localhost requires some special effort I've never really undertaken before--and since the data doesn't leave your machine when sending to localhost, the only use of https is to test https-specific code paths in your application if any.

**Comment by felpel** [comment]
We can deal with it by saving a local copy of the content provided by the endpoint for now, but this is not really a long term solution. 

I could also duplicate/move this issue in the parent repository since it doesn't seem to be strictly related to the TS extension. Let me know what you think about this.

**Comment by RikkiGibson** [comment]
If http works but https doesn't that indicates that you need to set up a certificate or something. If you're pointing at a server that has SSL set up correctly then you should be all good.

**Comment by felpel** [comment]
I will close this issue for now since the tool might not be in fault here and maybe we have to setup something on our end in order to have the endpoint available for code generation.
