### ISSUE TITLE
[JS]: Codebase Unification for DPG and mgmt. SDK

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1991]
https://github.com/Azure/typespec-azure/issues/3424

We need to ensure that both mgmt. SDK and DPG SDK could be generated directly from Typespec.
To follow up the recent discussion, let's target to use JS Modular for Track 2 mgmt.SDK work and here are the actions:

- [ ] Provide the plan on what breaking changes could be mitigated and what cannot which we shall provide migration guide.
- [ ] Get the overall plan approved and start solving the each individual item.

**Comment by ArthurMa1978** [comment]
dup with:
https://github.com/Azure/autorest.typescript/issues/2047
https://github.com/Azure/autorest.typescript/issues/2048
