### ISSUE TITLE
[JS RLC]: Codebase Unification for DPG and mgmt. SDK

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1992]
Describe the issue or request
Follow https://github.com/Azure/typespec-azure/issues/3424

This item is for RLC to ensure we could use typespec codeGen to also generate typespecs from mgmt. SDK

Today, we already tried a couple of services for mgmt. plane to generate SDK from Swagger.

This task is created to track the work to generate mgmt. SDK from typespec and solve all issues.

**Comment by ArthurMa1978** [comment]
dup with:
https://github.com/Azure/autorest.typescript/issues/2047
https://github.com/Azure/autorest.typescript/issues/2048
