### ISSUE TITLE
undefined `credentials` is generated for an OpenAPI file which has no authentication required

### ISSUE THREAD

**Issue by zaakn** [Azure/autorest.typescript#2005]
## autorest version

```bash
$ autorest --version
AutoRest code generation utility [cli version: 3.6.3; node: v18.17.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location 
 core       @autorest/core                           3.9.7        /Users/fai/.autorest/@autorest_core@3.9.7
 extension  @autorest/modelerfour                    4.26.2       /Users/fai/.autorest/@autorest_modelerfour@4.26.2
 extension  @autorest/typescript                     6.0.8        /Users/fai/.autorest/@autorest_typescript@6.0.8
```

## generate code

openapi file: [pets.json](https://github.com/Azure/autorest/blob/main/docs/openapi/examples/pets.json) which has no authentication required.

```bash
$ autorest --typescript --input-file=pets.json 
```
<details>
<summary>success</summary>
<pre>
AutoRest code generation utility [cli version: 3.6.3; node: v18.17.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
info    |    Loading AutoRest core      '/Users/fai/.autorest/@autorestcore@3.9.7/nodemodules/@autorest/core/dist' (3.9.7)
info    |    Loading AutoRest extension '@autorest/typescript' (latest->6.0.8)
info    |    Loading AutoRest extension '@autorest/modelerfour' (4.26.2->4.26.2)
warning | PreCheck/CheckDuplicateSchemas | Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
info    | Autorest.Typescript took 464ms
info    | Autorest completed in 6.16s. 10 files generated.
</pre>
</details>

## output

`generated/src/petClient.ts`

```ts
 24   constructor(options?: PetClientOptionalParams) {
...
 67       this.pipeline.addPolicy(
 68         coreRestPipeline.bearerTokenAuthenticationPolicy({
 69           credential: credentials,
 70           scopes:
 71             optionsWithDefaults.credentialScopes ??
 72             `${optionsWithDefaults.endpoint}/.default`,
 73           challengeCallbacks: {
 74             authorizeRequestOnChallenge:
 75               coreClient.authorizeRequestOnClaimChallenge
 76           }
 77         })
 78       );
```

The undefined `credentials` appears unexpectedly (line 69)

## init client

To avoid some execution errors, just make up a meaningless Pipeline.

```ts
const newPetClient = () => {
  const pipeline = coreRestPipeline.createEmptyPipeline()
  pipeline.addPolicy({
    name: coreRestPipeline.bearerTokenAuthenticationPolicyName,
    sendRequest: (request, next) => {
      // ...
      return next(request)
    },
  })

  const client = new PetClient({
    pipeline: pipeline,
    // ...
  })

  return client
}
```

---
see also:

https://github.com/Azure/autorest.typescript/blob/8f5b8a95c7e9f3d202da01e8978592c7e254de25/packages/autorest.typescript/src/generators/clientFileGenerator.ts#L717-L725

**Comment by MaryGao** [comment]
@zaakn Thanks for reporting this! I believe this issue is resolved in [our latest pr](https://github.com/Azure/autorest.typescript/pull/1956). We will release this in recent days and will keep you updated!

**Comment by MaryGao** [comment]
@zaakn Could you try with the latest version to check if this is resolved?
https://www.npmjs.com/package/@autorest/typescript?activeTab=versions
