### ISSUE TITLE
[JS] Mismatch Type for 'file' Property

### ISSUE THREAD

**Issue by minhanh-phan** [Azure/autorest.typescript#2007]
The DPG generation for the latest Whisper feature of @azure/openai is having mismatch type between "string" and "bytes". The type of the `file` property for transcription interface is `string`. This cause a build error because the type in the parameter is `Uint8Array` in all the `getAudioTranscriptions` [here](https://github.com/Azure/azure-sdk-for-js/blob/58ec46d16da3a229140c4e1ae1de7082aa4ed6de/sdk/openai/openai/sources/generated/src/api/operations.ts#L89).  

An example of the function signature is here
```js
export function _getAudioTranscriptionSimpleJsonSend(
  context: Client,
  file: Uint8Array,
  deploymentId: string,
  options: GetAudioTranscriptionSimpleJsonOptions = { requestOptions: {} }
```

But the type definition is `string` [here](https://github.com/Azure/azure-sdk-for-js/blob/58ec46d16da3a229140c4e1ae1de7082aa4ed6de/sdk/openai/openai/sources/generated/src/rest/models.ts#L5C1-L7C16)
```ts
export interface AudioTranscriptionOptionsSimpleJson {
  /** The audio file object to transcribe. */
  file: string;
```
Expectation: We expected the type of the file is `Uint8Array`. The definition in the TypeSpec file is bytes [here](https://github.com/Azure/azure-rest-api-specs/blob/d33d47dc85ef1f2c29c3dd278ded3650df9e49d7/specification/cognitiveservices/OpenAI.Inference/models/audio/commons.tsp#L46).

Reproduce: 
* Use the latest commit for the TypeSpec file `d33d47dc85ef1f2c29c3dd278ded3650df9e49d7`

**Comment by qiaozha** [comment]
which version of typespec-ts emitter are you using ? I feel like this should have been resolved.

**Comment by qiaozha** [comment]
oh no, you are right, this is the serialization, it should be able to resolve after #2006 get merged.

**Comment by minhanh-phan** [comment]
Thank you very much for the quick support. We're using the `dev` version for the emitter.

**Comment by qiaozha** [comment]
@minhanh-phan Could you try the latest emitter to see if this issue has been resolved ? Feel free to reopen if it isn't.

**Comment by minhanh-phan** [comment]
@qiaozha Thank you very much. The issue has been resolved!
