### ISSUE TITLE
[JS] Extensible Enum Generation

### ISSUE THREAD

**Issue by minhanh-phan** [Azure/autorest.typescript#2011]
The DPG generation for OpenAI Whisper feature does not correctly parse enum. The TypeSpec definition is [here](https://github.com/Azure/azure-rest-api-specs/blob/d33d47dc85ef1f2c29c3dd278ded3650df9e49d7/specification/cognitiveservices/OpenAI.Inference/models/audio/transcription_create.tsp#L25)
```tsp
    @projectedName("json", "response_format")
    responseFormat?: AudioTranscriptionFormat = AudioTranscriptionFormat.simpleJson;
```

But the generated code type is string [here](https://github.com/Azure/azure-sdk-for-js/blob/58ec46d16da3a229140c4e1ae1de7082aa4ed6de/sdk/openai/openai/sources/generated/src/rest/models.ts#L18C1-L23C28).
```ts
  /**
   * The format of the transcription output, in one of these options: json, text, srt, verbose_json, or vtt.
   *
   * Possible values: json, text, srt, verbose_json, vtt
   */
  response_format?: string;
```

In the generated code, the enum is present as type `AudioTranscriptionFormat`, but there is no Known enum link to this type. We expected the `response_format` value for this model to be of the type `AudioTranscriptionFormat`. This error is in all of the `AudioTranscriptionOptions` and `AudioTranslationOptions`

Reproduce: 
* Use the latest commit for the TypeSpec file `d33d47dc85ef1f2c29c3dd278ded3650df9e49d7`

**Comment by qiaozha** [comment]
I think it's by design.

**Comment by deyaaeldeen** [comment]
I think the issues are:
- There is no generated `KnownAudioTranscriptionFormat` with the known string values
- The type of `response_format` in `AudioTranscriptionOptionsSimpleJson` should be `AudioTranscriptionFormat` instead of string. At the end of the day `AudioTranscriptionFormat` is just an alias to a string but still we should use the former type to type the propery.

**Comment by qiaozha** [comment]
cadl ranch TypeSpec link: 
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/enum/extensible/main.tsp
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/enum/fixed/main.tsp

**Comment by qiaozha** [comment]
Should also consider enum being used in the following cadl ranch test cases.
```
client/naming
models/propertyTypes
```
