### ISSUE TITLE
[JS] Missing `isUnexpected` Overload

### ISSUE THREAD

**Issue by minhanh-phan** [Azure/autorest.typescript#2013]
The generation `isUnexpected` method is missing multiple overloads. There are 5 different audio formats `json`, `verbose_json`, `vrt`, `stt`, `text  for translation and transcription task, but only 1 format `json` is generated. 

The generated `isUnexpected` method for audio tasks is [here](https://github.com/Azure/azure-sdk-for-js/blob/2ce87a283d531d2b309cd8953467c532ff2092c5/sdk/openai/openai/sources/generated/src/rest/isUnexpected.ts#L37C1-L46C61).

```ts
export function isUnexpected(
  response:
    | GetAudioTranscriptionSimpleJson200Response
    | GetAudioTranscriptionSimpleJsonDefaultResponse
): response is GetAudioTranscriptionSimpleJsonDefaultResponse;
export function isUnexpected(
  response:
    | GetAudioTranslationSimpleJson200Response
    | GetAudioTranslationSimpleJsonDefaultResponse
): response is GetAudioTranslationSimpleJsonDefaultResponse;
```

The TypeSpec definition of these 5 models for translation task is [here](https://github.com/Azure/azure-rest-api-specs/blob/fb4f558b15075826656a3061d332d1a198352dd4/specification/cognitiveservices/OpenAI.Inference/models/audio/translation_create.tsp)

Expected: An overload for each of the interface

Reproduce:
* Use the latest commit `fb4f558b15075826656a3061d332d1a198352dd4` to regenerate for OpenAI package

**Comment by MaryGao** [comment]
Thanks for reporting this! I think we need to improve our help to accept all overloading types.

**Comment by minhanh-phan** [comment]
Hi @MaryGao, I want to check in on the progress of this issue. This is a blocker for OpenAI and would love to have a resolution soon! Thank you.

**Comment by MaryGao** [comment]
May I know if there is any build failure introduced by missing types?

**Comment by minhanh-phan** [comment]
@MaryGao Yes, we were trying to generate with the latest commit `8f13627230772d90c8db09636e88b9a26dc73044` from [this PR](https://github.com/Azure/azure-rest-api-specs/pull/25856). The sources folder cannot be built because there are error types from missing the `isUnexpected` overload in the `operations.ts` file.
