### ISSUE TITLE
[JS] Missing Property From Extension in Deserialize Method

### ISSUE THREAD

**Issue by minhanh-phan** [Azure/autorest.typescript#2014]
There is a missing property in the deserialize method. The `AudioTranscriptionVerboseJson` interface extends from the `AudioTranscriptionSimpleJson` face. In the deserialize method for `AudioTranscriptionVerboseJson`, the property `text` from `AudioTranscriptionSimpleJson` is missing.

For reference, the type definition generated is [here](https://github.com/Azure/azure-sdk-for-js/blob/2ce87a283d531d2b309cd8953467c532ff2092c5/sdk/openai/openai/sources/generated/src/models/models.ts#L15C1-L26C2)
```ts
/** Transcription response containing only the transcribed text. */
export interface AudioTranscriptionSimpleJson {
  /** Transcribed text. */
  text: string;
}

/** Transcription response. */
export interface AudioTranscriptionVerboseJson
  extends AudioTranscriptionSimpleJson {
  /** Audio transcription task. */
  task: AudioTranscriptionTask;
  /** Language detected in the source audio file. */
  language: string;
  /** Duration. */
  duration: number;
  /** Segments. */
  segments: AudioTranscriptionSegment[];
}
```
The generated code for the deserialize method returns this object [here](https://github.com/Azure/azure-sdk-for-js/blob/2ce87a283d531d2b309cd8953467c532ff2092c5/sdk/openai/openai/sources/generated/src/api/operations.ts#L170C1-L186C5)

```ts
return {
    task: result.body["task"],
    language: result.body["language"],
    duration: result.body["duration"],
    segments: (result.body["segments"] ?? []).map((p) => ({
      id: p["id"],
      start: p["start"],
      end: p["end"],
      text: p["text"],
      temperature: p["temperature"],
      averageLogProb: p["avg_logprob"],
      compressionRatio: p["compression_ratio"],
      noSpeechProb: p["no_speech_prob"],
      tokens: p["tokens"],
      seek: p["seek"],
    })),
  };
```

Expect: Return the property `text` from the extended interface `AudioTranscriptionSimpleJson`. The model definition in TypeSpec is [here](https://github.com/Azure/azure-rest-api-specs/blob/fb4f558b15075826656a3061d332d1a198352dd4/specification/cognitiveservices/OpenAI.Inference/models/audio/commons.tsp#L90C1-L103C2)

Reproduce: 
* Use the latest commit `fb4f558b15075826656a3061d332d1a198352dd4` to generate the OpenAI package

**Comment by qiaozha** [comment]
Interesting, I need to take a furthur look at this.

**Comment by qiaozha** [comment]
@minhanh-phan Could you try the latest dev build of the emitter and if it can resolve this issue? feel free to reopen if it isn't.
