### ISSUE TITLE
Should not flatten first layer of payload in Modular.

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2016]
Let's say we have the following TypeSpec
```tsp
    model Foo {
      prop1: string;
      prop2: int64;
      prop3: utcDateTime;
      prop4: offsetDateTime;
      prop5: Bar;
    }
    model Bar {
      prop1: string;
      prop2: int64;
    }
    op read(@body body: Foo): { @body body: Foo };
```

we will get a flattened payload like as shown in the following operations.ts, but we should not flatten it, it maybe only useful when there's some RP migrate from swagger into TypeSpec.
```typescript
import { TestingContext as Client } from '../rest/index.js';
import { StreamableMethod, operationOptionsToRequestParameters } from '@azurerest/coreclient';

export function _readSend(
    context: Client,
    prop1: string,
    prop2: number,
    prop3: Date,
    prop4: Date,
    prop5: Bar,
    options: ReadOptions = { requestOptions: {} }
): StreamableMethod<Read200Response> {
    return context.path('/').post({
        ...operationOptionsToRequestParameters(options),
        body: {
            prop1: prop1,
            prop2: prop2,
            prop3: prop3.toISOString(),
            prop4: prop4.toUTCString(),
            prop5: { prop1: prop5['prop1'], prop2: prop5['prop2'] },
        },
    });
}
export async function _readDeserialize(result: Read200Response): Promise<Foo> {
    if (result.status !== '200') {
        throw result.body;
    }
    return {
        prop1: result.body['prop1'],
        prop2: result.body['prop2'],
        prop3: new Date(result.body['prop3']),
        prop4: new Date(result.body['prop4']),
        prop5: {
            prop1: result.body.prop5['prop1'],
            prop2: result.body.prop5['prop2'],
        },
    };
}
export async function read(
    context: Client,
    prop1: string,
    prop2: number,
    prop3: Date,
    prop4: Date,
    prop5: Bar,
    options: ReadOptions = { requestOptions: {} }
): Promise<Foo> {
    const result = await _readSend(context, prop1, prop2, prop3, prop4, prop5, options);
    return _readDeserialize(result);
}

```

**Comment by qiaozha** [comment]
The expected unflattened operation should look like 
```
export function _readSend(
    context: Client,
    foo: Foo,
    options: ReadOptions = { requestOptions: {} }
): StreamableMethod<Read200Response> {
    return context.path('/').post({
        ...operationOptionsToRequestParameters(options),
        body: {
            prop1: foo.prop1,
            prop2: foo.prop2,
            prop3: foo.toISOString(),
            prop4: foo.toUTCString(),
            prop5: { prop1: foo.prop5['prop1'], prop2: foo.prop5['prop2'] },
        },
    });
}
```
In most of the swagger, this unflattened behaviour is the expected behaviour, only when they have set x-ms-client-flatten in their payload schema, that will be the currrent behavior.

**Comment by qiaozha** [comment]
As this will impact the public interface, @joheredi @xirzec Could you provide some insights here ? Thanks
I am in favor is not flatten the payload mostly out of the following considerations.
1. Do not flatten the payload will make model based serializer and deserialier easier. as mentioned in https://github.com/Azure/autorest.typescript/issues/1971 
2. If there's a lot of first layer required properties in the body schema, the operation signature will look very ugly. 
3. I can see that being useful if we are generating a command line tool like Azure CLI, where it's not easy to specify structure data, they would want everything to be flattened as much as possible. As a SDK, I might not see how much benefit we get from the flattening, as we can provide structure data by natural.  
4. If there's a model property changed from required to non-required, it will be a breaking for us, if we choose to flatten it.

**Comment by xirzec** [comment]
I like the less magical option here (not flattening)
