### ISSUE TITLE
[Epic] - Add cadl-ranch coverage to 25% for Modular end of January 2024

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2102]
Coverage dashboard: https://azure.github.io/cadl-ranch/
Spec repo: https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http
Modular Integration Testing:
- Generated code: https://github.com/Azure/autorest.typescript/tree/main/packages/typespec-ts/test/modularIntegration
- Modular enabling list: https://github.com/Azure/autorest.typescript/blob/main/packages/typespec-ts/test/commands/cadl-ranch-list.ts#L190
- Need to be enabled list:
```
 {
    outputPath: "arrays/itemTypes",
    inputPath: "type/array"
  },
{
    outputPath: "dictionary",
    inputPath: "type/dictionary"
  },
{
    outputPath: "enums/extensible",
    inputPath: "type/enum/extensible"
  },
  {
    outputPath: "enums/fixed",
    inputPath: "type/enum/fixed"
  },
 {
    outputPath: "models/propertyOptional",
    inputPath: "type/property/optionality"
  },
  {
    outputPath: "models/propertyNullable",
    inputPath: "type/property/nullable"
  },
  {
    outputPath: "models/propertyTypes",
    inputPath: "type/property/value-types"
  },
```

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2105
- [ ] https://github.com/Azure/autorest.typescript/issues/2106
```

**Comment by MaryGao** [comment]
- How to generate test SDK?
- How to enable the testing for SDK?

**Comment by qiaozha** [comment]
close it as reached to 41% now
