### ISSUE TITLE
Generator defaults to an empty array for optional array properties

### ISSUE THREAD

**Issue by timovv** [Azure/autorest.typescript#2108]
Encountered when generating the unbranded OpenAI client:

### Context

`CreateChatCompletionRequest` has the following array property declared in TypeSpec with `@minItems(1)`:

https://github.com/Azure/autorest.typescript/blob/8fdc016a9080e6ac9decfb85319503791390c6ab/packages/typespec-test/test/openai_generic/spec/completions/models.tsp#L159-L162

### Expected behavior

When `functions` is not specified in the input, the property should not be present in the request.

### Actual behavior

`functions` has value `[]` in the request. While this makes sense for required array properties, it does not make sense in this scenario, and causes issues, since `[]` does not satisfy the `@minItems(1)` constraint. OpenAI returns an error when passing `[]` here.

**Comment by MaryGao** [comment]
@timovv It should be fixed in the latest codegen, feel free to have a check! Thanks!
