### ISSUE TITLE
Support optional body

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/autorest.typescript#2114]
**Issue description:**
There is an error in the code generated for body optionality. the generated optional body can not be undefined. The detailed error code is shown as following:
![image](https://github.com/Azure/autorest.typescript/assets/20970631/c4f99db4-8e04-43d3-9073-14581e7363ce)
![image](https://github.com/Azure/autorest.typescript/assets/20970631/1384cc2f-4698-492b-b724-ef721a8db04a)

@MaryGao for notification.

**Comment by qiaozha** [comment]
please help check what would happen if there's required properties in optional body parameter. Thanks

**Comment by MaryGao** [comment]
closed as duplicated with https://github.com/Azure/autorest.typescript/issues/2208
