### ISSUE TITLE
Test error in payload-content-negotiation when add rlc in cadl-ranch

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/autorest.typescript#2137]
**Issue description:**
I have add an test file for payload-content-negotiation which is shown as following, the `accpet` header in request is different from the one I put in.
![image](https://github.com/Azure/autorest.typescript/assets/20970631/3ee79252-cf92-423f-9f88-f77490043eda)
when I put `image/png` into the the `accpet` parameter. It returns an error as following and it shows the `accpet` header in request is `application/json`
![image](https://github.com/Azure/autorest.typescript/assets/20970631/80054afe-435d-4379-981b-764cdccff8cd)

@MaryGao for notification.

**Comment by qiaozha** [comment]
@zzhxiaofeng Can you try to pass with contentType ? also, I remember there's a bug in core-client-rest that will ignore headers accept. @MaryGao Can you help check on that ? Thanks

**Comment by qiaozha** [comment]
should complete.
