### ISSUE TITLE
Support model inheritance and polymorphism in Modular

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2143]
Questions to be discussed:
1. add parent base class to the union ?
    current implementation is yes. After discussion in teams, we should add parent base class to the union.
2. can discriminator be optional ?
  ```
      @doc("This is base model for polymorphic multiple levels inheritance with a discriminator.")
      @discriminator("kind")
      model Fish {
        age: int32;
      }
  ```
  vs 
  ```
      @doc("This is base model for polymorphic multiple levels inheritance with a discriminator.")
      @discriminator("kind")
      model Fish {
        kind: string;
        age: int32;
      }
  ```
  TypeSpec treat the first case as optional in OpenAPI3 but required in Swagger emitter.
  And we have a test case in cadl ranch, https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/model/inheritance/nested-discriminator/main.tsp#L207

   update: based on Timothee's response here https://github.com/microsoft/typespec/issues/2710#issuecomment-1834998986, we should not treat discriminator as optional.

3. how to serialize & deserialize in polymorphism case ? 
    see comments https://github.com/Azure/autorest.typescript/issues/2139#issuecomment-1831473074 
4. should we treat discriminator with extensible enum and fixed enum differently ? 
    Current implementation is no, we will add polymorphic base into the union anyway.

**Comment by qiaozha** [comment]
Another proposal is to like C# to introduce an Unknown Type in the union whose discriminator will use NonExhaustive https://github.com/Azure/azure-sdk-for-js/pull/25893

```
    @doc("This is base model for polymorphic multiple levels inheritance with a discriminator.")
    @discriminator("kind")
    model Pet {
      kind: string;
      age: int32;
    }

    model Cat extends Pet {
      kind: "Cat";
      meow: int32;
    }

    model Dog extends Pet {
      kind: "Dog";
      bark: string;
    }
```

we will have a UnknownPet like the below
```ts
interface UnknownPet extends PetParent {
    kind: NonExhaustive<"Cat" | "Dog">;
}
```
the Pet type alias will be 
```ts
type Pet = Cat | Dog | UnknownPet;
```

Pros: 
1. it can be useful for type inference, customer doesn't need to use cast.
2. changing from Parent base into UnknownPet, will probably not be a breaking change at least in RLC layer, as by default, the type inference will fall into Parent base, there's no need to use Parent base to cast a type. And the whole kind scope doesn't change.
Cons:
1. if we add another sub type, it will cause breaking change, as the kind changed from NonExhaustive<"Cat" | "Dog"> into NonExhaustive<"Cat" | "Dog" | "Pig">, which is narrowing the scope.

**Comment by dgetu** [comment]
Is there a way to use unique symbol here? If `UnknownPet` has type `kind: typeof uniqueSymbol`, the user must check each subtype discriminator explicitly.
