### ISSUE TITLE
Enum not getting generated by typespec-ts emitter

### ISSUE THREAD

**Issue by zoeyzuo-se** [Azure/autorest.typescript#2144]
Hi team,

I'm using @azure-tools/typespec-ts emitter to generate typescript clients. We are adding more files on top of the auto-gen clients so that requires us to get access to the all the models. I have encountered an issue where enum is defined in the TypeSpec but not getting generated in the typescript. Please check the code below for reproduce the problem.
```
import "@typespec/http";
import "@typespec/json-schema";
using TypeSpec.Http;
using TypeSpec.JsonSchema;

@service({
  title: "Sample API",  
  termsOfService: "http://swagger.io/terms/",
  version: "0.1",
})
@server("https://example.com", "Single server endpoint")

@route("/")
namespace SampleAPI {
  @route("/cat")
  interface CatOps extends ResourceService<CatResource, CustomResponse> {}
}

interface ResourceService <CatResource, CustomResponse> {
  @doc("Read resource")
  @get read(...CatResource): {@header Schema: string;...CustomResponse};
}

@jsonSchema
model CatResource is Resource <ResourceType.Cat> {}

model Resource<resourceType> {
    @visibility("read") type: resourceType;
    @visibility("read") id: string;
    summary: string;
}  

model CustomResponse {
    body: string;
    id: string;
    name: string;
}

enum ResourceType {
    Cat,
    Dog
}

```

In the above code, I have defined an enum named `ResourceType` and used it to define my model `CatResource`. But in the generated ts client there is no `ResourceType` enum / interface. I'm using tsp version 0.48.1.

It would be appreciated if someone could take a look.

**Comment by MaryGao** [comment]
I will take a look at this issue.

**Comment by MaryGao** [comment]
@zoeyzuo-se This should be fixed in latest emitter, could you re-generate to have a check?

**Comment by MaryGao** [comment]
Close this as resolved and feel free to re-open if still existing.
