### ISSUE TITLE
[Codegen/TypeSpec] missing error response import in source code

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2149]
ci check failure in rush build https://github.com/Azure/azure-rest-api-specs/pull/26702/checks?check_run_id=18990593006

it's caused by missing import in the generated source code https://github.com/azure-sdk/azure-sdk-for-js/pull/7787/files#diff-23670a4188ba7a22ff45baffecb05db777e683c05a5090b1b0edcb83309ac32bR47

another question: 
don't know why codegen generated another [Error response](https://github.com/azure-sdk/azure-sdk-for-js/pull/7787/files#diff-23670a4188ba7a22ff45baffecb05db777e683c05a5090b1b0edcb83309ac32bR353) only for the interface
related code in [typespec](https://github.com/Azure/azure-rest-api-specs/blob/8450f55a6cbd2b67e73d1a5710d6a242cd0498ec/specification/purview/Azure.Analytics.Purview.DataMap/routes.tsp#L717-L725) 
related Error response in [model.tsp](https://github.com/Azure/azure-rest-api-specs/blob/8450f55a6cbd2b67e73d1a5710d6a242cd0498ec/specification/purview/Azure.Analytics.Purview.DataMap/models.tsp#L450-L462)
related Error response in [routes.tsp](https://github.com/Azure/azure-rest-api-specs/blob/8450f55a6cbd2b67e73d1a5710d6a242cd0498ec/specification/purview/Azure.Analytics.Purview.DataMap/routes.tsp#L46-L92)

**Comment by qiaozha** [comment]
close it as won't fix
