### ISSUE TITLE
Type declaration is missing when update rlc for property-value-types in cadl-ranch

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/autorest.typescript#2152]
**Issue description:**
When I update version of `cadl-ranch` to  `0.27.0`, the type of decimal property in the generated code is missing. The detailed code is shown as following:
![image](https://github.com/Azure/autorest.typescript/assets/20970631/8a25e292-1b1e-41ee-a96a-8bbb775bc28e)
![image](https://github.com/Azure/autorest.typescript/assets/20970631/ad365d94-3f55-4ceb-8b96-605479af4c0f)
In main.tsp, the detailed code is shown as following:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/property/value-types/main.tsp#L92
![image](https://github.com/Azure/autorest.typescript/assets/20970631/a498e1e5-a8f7-4b65-a8bb-f59f4638defe)

@MaryGao for notification.

**Comment by qiaozha** [comment]
@zzhxiaofeng Please update the typespec info here. Thanks.
