### ISSUE TITLE
We should not use the Boolean value of 'branded' to decide branding/non-branding

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#2173]
Today, we are using the following option to decide whether to do branding or not:

```
function getBranded(emitterOptions: RLCOptions) {
  return emitterOptions.branded !== undefined ? emitterOptions.branded : true;
}
```

Based on the requirement, we should use the branding value that the user of the generator inputs.
We need to update the implementation of the handling of Branded in typescript code.

**Comment by qiaozha** [comment]
we are using flavor now.
