### ISSUE TITLE
Some node environments are not supported for multipart/form data case in cadl-ranch

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2177]
### Environment
- OS: windows
- Node version: v18.12.0

### Detail

When supporting the `string + bytes` multipart case in cadl-ranch ([pr](https://github.com/Azure/cadl-ranch/pull/452)), we met below two issues that we need to fix.

https://github.com/Azure/autorest.typescript/pull/2175

### Uncaught Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF

The exception happened when we concatenateStreams in core https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-rest-pipeline/src/util/stream.ts#L72-L74. And when we read from the Uint8Array data by `readFile` ([code](https://github.com/Azure/autorest.typescript/pull/2175/files#r1436229400)).
```
     Uncaught Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
      at new NodeError (node:internal/errors:393:5)
      at readableAddChunk (node:internal/streams/readable:285:30)
      at Readable.push (node:internal/streams/readable:234:10)
      at node:internal/webstreams/adapters:496:22
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by v-jiaodi** [comment]
![image](https://github.com/Azure/autorest.typescript/assets/80496810/bb322d62-bf2d-49f5-b774-363a5f660cc7)

![image](https://github.com/Azure/autorest.typescript/assets/80496810/ad268691-4fb1-45d7-ac1d-04903f30fb92)

**Comment by v-jiaodi** [comment]
### Environment
- OS: Linux
- Node Version: 18.12.0

### Detail
>
>Rush Multi-Project Build Tool 5.97.1 - Node.js 18.12.0 (LTS)
> "cross-env TS_NODE_PROJECT=tsconfig.integration.json mocha -r ts-node/register --experimental-specifier-resolution=node --timeout 4000 ./test/integration/*.spec.ts"
(node:56426) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:56426) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
  MultiPartClient Rest Client
/home/jiaoubuntu/autorest.typescript/packages/typespec-ts/temp/assets/image.jpg
    1) client should be created
  0 passing (34ms)
  1 failing
  >1) MultiPartClient Rest Client
       client should be created:
     Uncaught Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
      at new NodeError (node:internal/errors:393:5)
      at readableAddChunk (node:internal/streams/readable:285:30)
      at Readable.push (node:internal/streams/readable:234:10)
      at node:internal/webstreams/adapters:496:22
      at processTicksAndRejections (node:internal/process/task_queues:95:5)


![image](https://github.com/Azure/autorest.typescript/assets/80496810/29875325-2081-4c5a-86be-abd5dfb5eafe)


![image](https://github.com/Azure/autorest.typescript/assets/80496810/2b41cd13-15a1-4fae-b771-275dba07d78b)
