### ISSUE TITLE
Named Union Type Not Emitted In Generated Code

### ISSUE THREAD

**Issue by minhanh-phan** [Azure/autorest.typescript#2185]
For Schema Registry generation, the union type `SchemaContentTypeValues` is not emitted. The TypeSpec definition for the `SchemaContentTypeValues` is [here](https://github.com/Azure/azure-rest-api-specs/blob/496ef847bd63aab7c10b2225701b125ff161ea05/specification/schemaregistry/SchemaRegistry/main.tsp#L133C1-L142C1)
```
union SchemaContentTypeValues {
  avro: "application/json; serialization=Avro",
  @added(ServiceApiVersions.V2022_10)
  json: "application/json; serialization=json",
  @added(ServiceApiVersions.V2022_10)
  custom: "text/plain; charset=utf-8",
  @added(ServiceApiVersions.V2023_07_01)
  protobuf: "text/vnd.ms.protobuf",
}
```

In the [generated file](https://github.com/minhanh-phan/azure-sdk-for-js/blob/490c9850d0837f86c697d872743dec60aa44007e/sdk/schemaregistry/schema-registry/sources/generated/src/parameters.ts#L24C1-L28C1), we have the following generated definition.
```ts
export interface RegisterSchemaMediaTypesParam {
  /** The content type for given schema. */
  contentType: SchemaContentTypeValuesOutput;
}
```
The type `SchemaContentTypeValuesOutput` does not exist anywhere in the generated output, so we have the following error
```
sources/generated/src/responses.ts(92,19): error TS2304: Cannot find name 'SchemaContentTypeValuesOutput'.
```
To reproduce: Use the latest commit from [this PR](https://github.com/Azure/azure-rest-api-specs/pull/25168/files#diff-1b5581b266947b270ea1249cc8c8763c9fc4a7e24b6e01182d84f07241795ee8), commit `496ef847bd63aab7c10b2225701b125ff161ea05`.

**Comment by qiaozha** [comment]
probably can be fixed by #2169

**Comment by qiaozha** [comment]
Just found out it can't, it's specificly related with the named union being used in the contentType parameter.

**Comment by minhanh-phan** [comment]
Hi @qiaozha, can I ask what's the problem with the named union being used in the contentType parameter? We tried to change this union into enum, but currently it will raise an error (see [here](https://github.com/microsoft/typespec/issues/2727))

**Comment by qiaozha** [comment]
Currently, we just assume header parameter type are just primitive types, don't actually generate the model for it.

**Comment by qiaozha** [comment]
I am working on the fix.

**Comment by minhanh-phan** [comment]
@qiaozha Thank you for the explanation & quick response. I'll look out for the fix.

**Comment by qiaozha** [comment]
It should have been resolved with the latest release of the emitter https://www.npmjs.com/package/@azure-tools/typespec-ts/v/0.20.0 @minhanh-phan Could you have a try and let me know if it works ? Thanks.

**Comment by minhanh-phan** [comment]
I can confirm that it works well now. Thank you very much @qiaozha!
