### ISSUE TITLE
TS2339 compile error when using both BearerAuth and OAuth2Auth for authentication

### ISSUE THREAD

**Issue by yufeih** [Azure/autorest.typescript#2186]
`@azure-tools/typespec-ts` version: 0.19.0

When using both `BearerAuth` and `OAuth2Auth`, the generated code results in `TS2339` error.

TypeSpec file:

```tsp
@useAuth([BearerAuth, OAuth2Auth<[{
    type: OAuth2FlowType.clientCredentials;
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token";
    refreshUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token";
    scopes: ["foo/.default"];
}]>])
namespace MyService;
```

Generated code:

```ts
export default function createClient(
  credentials: TokenCredential | KeyCredential,
  options: ClientOptions = {}
): MyServiceClient {
   //...

  const client = getClient(baseUrl, credentials, options) as MyServiceClient;

  client.pipeline.addPolicy({
    name: "customKeyCredentialPolicy",
    async sendRequest(request, next) {
      request.headers.set("Authorization", "bearer " + credentials.key);  // <--- TS2339
      return next(request);
    },
  });
  return client;
}
```

Error:

```
Property 'key' does not exist on type 'TokenCredential | KeyCredential'.
  Property 'key' does not exist on type 'TokenCredential'.ts(2339)
```

**Comment by MaryGao** [comment]
Thanks for reporting and this would be a codegen bug and the `customKeyCredentialPolicy` should only be added when the credential is `KeyCredential`. I will work on the fix.

**Comment by MaryGao** [comment]
@yufeih I'd like to confirm with you one detail, for BearerAuth for the word `bearer ` in `Authorization` header do we care about it is capital case or lower case?

**Comment by yufeih** [comment]
> @yufeih I'd like to confirm with you one detail, for BearerAuth regarding the word `bearer ` in `Authorization` header do we(server side) care about it is capital case or lower case?

Our server should treat is as case insensitive, it seems `Bearer` is more appropriate. Here is the codegen for C#:

```csharp
        private const string AuthorizationApiKeyPrefix = "Bearer";
```

**Comment by MaryGao** [comment]
Thanks for the info! Yes, generally `Bearer` is the convention and server side should treat as case insensitive.
