### ISSUE TITLE
Should we include File type for RLC?

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2196]

**Comment by lirenhe** [comment]
Please follow: https://github.com/microsoft/typespec/issues/2784

For binary content in mutlifart,  please provide the option to let user to input the name of the file, if the name is not provided, we could use the default name.

**Comment by timovv** [comment]
As discussed in our design meeting yesterday, we will be adding the [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) class to the union of accepted types by the RLC, which allows for users to specify the file name and MIME type. To allow support in Node 18 (where the File class is still experimental) and to enable streaming scenarios in Node, we will also re-export the `createFile` and `createFileFromStream` helper functions from `core-rest-pipeline`, which allow for the creation of `File` objects.
