### ISSUE TITLE
refactor the media type inference logic 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2200]
Our current logic of inferring if a type is a binary payload is not robust enough, we should refactor it a little. see https://github.com/Azure/autorest.typescript/pull/2189/files#r1449853521

**Comment by lirenhe** [comment]
Actually, you could reference it directly:  https://github.com/Azure/autorest/blob/faf5c1168232ba8a1e8fe02fbc28667c00db8c96/packages/libs/codegen/src/media-types.ts#L53

**Comment by qiaozha** [comment]
close it as completed.
