### ISSUE TITLE
TypeSpec Azure Core basic scenarios

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2207]
Typespec link 
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/azure/core/basic/main.tsp 

we have several operations un-supported in Modular 
<img width="827" alt="image" src="https://github.com/Azure/autorest.typescript/assets/55688292/2ebc0936-a4d3-4ab2-afd3-b784d57e3f30">

**Comment by v-jiaodi** [comment]
Azure Core BasicClient createOrReplace method request restriction, When add create or replace scenarios for azure core, get error as follow:

![image](https://github.com/Azure/autorest.typescript/assets/80496810/a6323853-8892-4189-b9ae-59169e10b2b6)

**Comment by qiaozha** [comment]
pending core-client-rest 1.2.1 release.
