### ISSUE TITLE
media type payload

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2210]
TypeSpec link https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/payload/media-type/main.tsp 

we need to make sure our generated code can have a way to support customize content type for both request and response

**Comment by v-jiaodi** [comment]
Add modular case,  test error as follow: 

<img width="625" alt="image" src="https://github.com/Azure/autorest.typescript/assets/80496810/56d5a3fb-8606-4eb5-9015-b4d2f337d645">

**Comment by qiaozha** [comment]
it's not done yet, still pending on modular layer integration.
