### ISSUE TITLE
server versioning

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2212]
TypeSpec link: 
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/server/versions/versioned/main.tsp
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/server/versions/not-versioned/main.tsp 

This is not related with multiple api.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2368
```

**Comment by v-jiaodi** [comment]
Add modular test case for server versions, get error as follow:

<img width="623" alt="image" src="https://github.com/Azure/autorest.typescript/assets/80496810/0fd9277f-153b-4d73-ab6c-0db39f011b60">

**Comment by qiaozha** [comment]
Design discussion about api version query parameter.

 General thoughts:
 1. if every operation has api version query parameter, we move the apiVersion to client level
 2. whether the api version is required or not, depends on if it has default value 
 
 Cases to promote api-version to client level
 3. if client level api version has the same default value, we set the default value in RLC clientFactory function, and apiVersion will not be part of the createClient signature
 
 // new
 4. if client level api version doesn't have default value, we will have apiVersion in the createClient signature for both RLC and Modular

 Cases to not promote api-version to client level
 5. if operation level api version has default api version, in RLC, it's a required query parameter, in Modular, it's an operation options, we set the default value while calling RLC layer.
 6. if operation level api version doesn't have api version default value, in both RLC and modular, it's a required parameter
 
 Questions: 
 * how about the case where we have more than one default values or the api version type is different among all operations, but they all do have api version as query parameters? 
   ans:  fall into not promote cases
 * how to pass a different api version in rlc layer if it's has default value as we are not generating it as string?
   ans: use as any for now
 * what if not all rlc layer operations have api version query parameter but all modular layer operations have, in that case, should api version be a client level parameter in modular? 
   ans: not considering this for now
