### ISSUE TITLE
special words in model properties, models, operations, parameters,

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2214]
TypeSpec link: https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/special-words/main.tsp 

Should consideration this issue https://github.com/Azure/autorest.typescript/issues/2084

**Comment by kazrael2119** [comment]
![image](https://github.com/Azure/autorest.typescript/assets/98569699/1cca870a-c51e-4264-bd70-75fe6cc94334)
can't generate code for special-words

**Comment by qiaozha** [comment]
Design Discussion Notes:
1. parameter
    ```ts
    declare function op(await: string): void;
    ```
    we will rename await => awaitParam

2. operation
      ```
      declare function delete(param: string): void;
      ```
      we will rename await => $await, but keep the original name whereever possible.
      
      ```ts
      // for operation options
      DeleteOptions
      FooDeleteOptions
      
      // for classcial client layer
      client.await() {
        $await();
      }
      ```


3. property // new in Modular
      ```ts
      interface Some {
        constructor: string;
      }
      type SomeConstructor = Some & Record<string, unknown>
      function foo(some: SomeConstructor) {
        return some.constructor;
      }
      foo({ constructor: "hello" })
      
      ```
      For normal property proposal: constructor => constructorProperty
      for parameter being used in query parameter: we use as any
      ```ts
      {
         constructor: constructorParam as any
      }
      ```

// newable reserved words
```ts
declare interface Boolean { };
const bool = new Boolean();
```

4. interface or class
     we will rename Boolean => BooleanModel

5. operation groups
     we will rename Boolean => BooleanOperations 


6. operation options

      // content-safety and ClientOptions reserved 
      ```ts
      model BarOptions {
      }
      op bar(@body options: BarOptions);
      ```
      we will rename our options as requestOptions: BarOptions => BarRequestOptions 
      ```ts
      declare interface BarOptions { 
          prop: string;
       };
       declare interface BarRequestOptions { 
          optional1: string;
       };
      declare function bar(options: BarOptions, requestOptions?: BarRequestOptions): void; 
      ```

**Comment by qiaozha** [comment]
For point 6, since I found we have been using OptionalParams in HLC https://github.com/Azure/autorest.typescript/issues/2352 and it can resolved the Options conflicts issue, I just changed the Options to OptionalParams to avoid breaking and extra effort of resolve conflicts.

**Comment by qiaozha** [comment]
For point 5, I am implement it as what we discussed before, but the behavior is not like that for HLC https://github.com/Azure/autorest.typescript/issues/2351 and I think it's probably need furthur discussion for it. so I didn't take care of #2351 in this issue.
