### ISSUE TITLE
all kinds of scalars

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2222]
TypeSpec link: https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/type/scalar/main.tsp

**Comment by v-jiaodi** [comment]
Add modular case error: 
<img width="628" alt="image" src="https://github.com/Azure/autorest.typescript/assets/80496810/a6a4d35a-d3cf-46ad-a3c8-5264cf6e3e4f">
