### ISSUE TITLE
Azure Core BasicClient createOrReplace method request restriction

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/autorest.typescript#2235]
Azure Core BasicClient createOrReplace method request restriction, When add create or replace scenarios for azure core, get error as follow:

![image](https://github.com/Azure/autorest.typescript/assets/80496810/a6323853-8892-4189-b9ae-59169e10b2b6)

@qiaozha for notification.

**Comment by MaryGao** [comment]
closed as duplicated https://github.com/Azure/autorest.typescript/issues/2207
