### ISSUE TITLE
Generated webpack config does not allow "test" or "node_modules" anywhere in path

### ISSUE THREAD

**Issue by nascosto** [Azure/autorest.typescript#225]
Line 19 of the generated webpack.config.js has this: exclude: /(node_modules|test)/
This causes the webpack run to fail if "test" or "node_modules" is anywhere in the parent folder structure (e.g. C:\buildandtest\{folderContainingTypescript} or C:\whatever\testament\youwant\{folderContainingTypescript})

**Comment by RikkiGibson** [comment]
Maybe the best thing is to change it to just `/node_modules/`? @amarzavery

**Comment by RikkiGibson** [comment]
It seems a bit more conceivable that `test` would be in the path and not `node_modules`. But also if the exclude doesn't have some obvious benefit (e.g. making the bundler faster or preventing spurious errors) then maybe we can remove it entirely.

**Comment by RikkiGibson** [comment]
We've removed `exclude` from the generated webpack config. Please give it a try by passing `--use=@microsoft.azure/autorest.typescript@preview` @nascosto.

**Comment by nascosto** [comment]
Works fine out of the box. Thanks!
