### ISSUE TITLE
Revisit our user experience for allow custom headers in Modular: customHeaders v.s. headers

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2268]
https://github.com/Azure/azure-sdk-for-js/pull/27343#discussion_r1471731162 
## Current RLC experience: 
1. with contentType
```ts
      const result = await client.path(somepath, pathParam).put({
        body: {...bodyContent },
        contentType: "application/json"
      });
```
2. with headers
```ts
      const result = await client.path(somepath, pathParam).put({
        body: {...bodyContent },
        headers: { "content-type": "application/json" }
      });
```
## Current Modular experience: 
1. with options.contentType
```ts
      const user = await client.createOrReplace(pathParam, { ...bodyContent }, {
        contentType: "application/json"
      });
```
 **Currently this approach only work when the operation default contentType is not `application/json`**
2. requestOptions.headers
```ts
      const user = await client.createOrReplace(pathParam, { ...bodyContent }, {
        requestOptions: {
           headers: {
                "content-type": "application/json"
           }
        }
      });
```
## Current HLC experience
```ts
      const user = await client.createOrReplace(pathParam, { ...bodyContent }, {
        requestOptions: {
           customHeaders: {
                "content-type": "application/json"
           }
        }
      });
```

**Comment by jeremymeng** [comment]
If we add it to `contentType?: string` to `OperationRequestOptions`, then we don't need to extend OperationOptions anymore? https://github.com/Azure/autorest.typescript/blob/fd3b2301af53644b7902ad001a5d7b54fac8d925/packages/typespec-ts/test/modularIntegration/generated/azure/core/src/models/options.ts#L9

or maybe there's a reason that this would not work but I am not aware of.

**Comment by qiaozha** [comment]
You mean to extend from OperationRequestOptions instead ? I think the reason we have to extend from OperationOptions is that we allow those in current track2 SDK. And we don't want to break our customers for that when they migrate from track2 to Modular. 
The `OperationOptions` in `@azure/core-client` https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-client/src/interfaces.ts#L98-L122 
The track2 SDK operation options extends from `coreClient.OperationOptions` https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/apicenter/arm-apicenter/src/models/index.ts#L340-L341

**Comment by jeremymeng** [comment]
> You mean to extend from OperationRequestOptions instead ? I think the reason we have to extend from OperationOptions

No, we could still extends `OperationOptions` in code gen.  What I mean is that if `contentType?: string` is added to `OperationRequestOptions` then it would be available via `OperationOptions.requestOptions?.contentType` which is optional

**Comment by qiaozha** [comment]
I updated the user experience in the PR description, I would say, it's an option but not sure ?

**Comment by jeremymeng** [comment]
I see, we want to keep some of current customer experiences of specifying contentType in options.  It feels that specifying it via headers would mostly work, but not as convenient as using options?

**Comment by qiaozha** [comment]
the only difference is customHeader and header between HLC and Modular.

**Comment by joheredi** [comment]
TBH if keeping `customHeaders` is the only difference and will save customers from a breaking change, I would say lets keep it. I don't think the name change is worth the breaking change.

@bterlson what do you think? TL;DR: Currently in modular users can set arbitrary headers through `options.headers` whereas in Track2 they can do so through `options.customHeaders`.

**Comment by qiaozha** [comment]
I want to point out that there is a real scenario that customer wants to pass headers in it https://github.com/Azure/autorest.typescript/issues/2481#issuecomment-2083596897

**Comment by joheredi** [comment]
Need to confirm if the following are true:

* When there is a default content type the code generator hard codes "application/json" and there is no way to override it through headers
* The property to set custom headers are different `customHeaders` vs `headers`

**Breaking Change Categorization**
Bug (Unwanted Breaking Changes):

- [ ] Missing data from the spec in the new implementation.
- [x] Incorrect results produced by the new implementation.
- [x] Slight differences in the new implementation that do not improve user experience. If uncertain, categorize as unwanted.

Improvements (Acceptable Breaking Changes):

- [ ] Fixes broken behavior in the new implementation.
- [ ] Offers clear enhancements to user experience.
- [ ] Eliminates or discourages bad patterns.
- [ ] Provides additional functionality.
- [ ] Aligns more closely with TypeSpec standards.

**Comment by qiaozha** [comment]
> When there is a default content type the code generator hard codes "application/json" and there is no way to override it through headers
confirmed that this is resolved by https://github.com/Azure/azure-sdk-for-js/pull/27343

**Comment by qiaozha** [comment]
I change the title to better reflect "The property to set custom headers are different customHeaders vs headers" 
I prefer to accept this breaking because 
1. we already support custom via headers in RLC, it will be a breaking if we want to change it from header to customHeader and we already has GA RLC services.
1. to support both headers and customHeaders are redundant and confusing to our customers.
1. we are using the same core request options from core-client-rest, if we want RLC using headers but Modular using customHeaders, we will either duplicate the operation options definition in core-client-rest or define the operation options in modular code, both doesn't seem to be a nice solution here.

**Comment by qiaozha** [comment]
close it as we accept this breaking.
