### ISSUE TITLE
[OpenAI] Missing `getAudioSpeech` Operation and Response Model

### ISSUE THREAD

**Issue by minhanh-phan** [Azure/autorest.typescript#2281]
The latest generation for OpenAI is missing the `getAudioSpeech` operation and the `AudioSpeechResponse` model in the API layer. The TypeSpec for this operation is defined [here](https://github.com/Azure/azure-rest-api-specs/blob/c862da9a932c5e543573f44b301746451222a154/specification/cognitiveservices/OpenAI.Inference/routes/audio_speech.tsp#L17C1-L25C3)
```ts
@doc("Generates audio from the input text.")
@added(ServiceApiVersions.v2024_02_15_Preview)
@action("audio/speech")
@actionSeparator("/")
op getAudioSpeech is ResourceAction<
  Deployment,
  AudioSpeechOptions,
  AudioSpeechResponse
>;
```

The TypeSpec for the `AudioSpeechModel` is defined [here](https://github.com/Azure/azure-rest-api-specs/blob/c862da9a932c5e543573f44b301746451222a154/specification/cognitiveservices/OpenAI.Inference/models/audio/audio_speech.tsp#L67C1-L77C2)
```ts
@doc("Represents the response for speech synthesis.")
@added(ServiceApiVersions.v2024_02_15_Preview)
model AudioSpeechResponse {
  @doc("The content type of the response.")
  @header
  contentType: "application/octet-stream";

  @doc("The synthesized audio.")
  @body
  audio: bytes;
}
```
The rest layer is emitted correctly [here](https://github.com/Azure/azure-sdk-for-js/blob/be4e1f7a4f3fb1adc515dd8151b693050d034c89/sdk/openai/openai/sources/generated/src/rest/clientDefinitions.ts#L125C1-L132C2), but this method is not generated in the API layer.
```ts
export interface GetAudioSpeech {
  /** Generates audio from the input text. */
  post(
    options?: GetAudioSpeechParameters,
  ): StreamableMethod<
    GetAudioSpeech200Response | GetAudioSpeechDefaultResponse
  >;
}
```
**Expected**: The method should be generated in the client API layer.
**Reproduce**: Use the latest commit from [this PR](https://github.com/Azure/azure-rest-api-specs/pull/27558) (`c862da9a932c5e543573f44b301746451222a154` as of now). The PR with the generation is [here](https://github.com/Azure/azure-sdk-for-js/pull/28472)

**Comment by qiaozha** [comment]
This is because they didn't include this operation in their client.tsp https://github.com/Azure/azure-rest-api-specs/pull/27558/files#diff-de04249595209518b51090ad0bb073948620397625141eaeae658279f3b101c2L19, Modular will honor whatever they want to customized in client.tsp but RLC is not in the business of customization, so RLC's result will not be impacted regardless of what they define in client.tsp.

**Comment by minhanh-phan** [comment]
@qiaozha Thank you for letting me know about it. I'll comment on the TypeSpec file and close this issue. Appreciate your help 😊
