### ISSUE TITLE
Need to handle TypeSpec union type with extensible enums and enum as closed enumeration

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#2287]
We shall apply this  in both RLC and Modular.

Please follow the decision from https://github.com/Azure/typespec-azure-pr/issues/3827.

The latest TCGC 0.39.0 should already contain this change but considering JS codegen only leverage the raw type, we need to figure out how to support this in both RLC and modular.

PR to update https://github.com/Azure/azure-rest-api-specs/pull/27687/files already created, so this is likely to cause breaking change for service team if this work is not handled.

**Comment by qiaozha** [comment]
close it as pr merged and released.
