### ISSUE TITLE
Unable to install/use dotnet framework.

### ISSUE THREAD

**Issue by disophisis** [Azure/autorest.typescript#231]
Related to #27  

I am having this same issue OliverRC was having in the previous issue.  We have kind of a weird configuration though:

We are setting up docker containers that will work as build agents using the teamcity docker image.  We're installing some dependencies inside of that container, one of them being autorest. 

autorest seems to install correctly but upon invoking it during a dotnet build, we receive the following:

```
EXEC : error : Package '@microsoft.azure/autorest.typescript' - '2.0.367' failed to install: [/root/git/services/Api/Api.Client.csproj]
    dotnet-2.0.0@1.4.4 postinstall: node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"
  Exit status 1
```

The real issue seems to be during the post install script for the dotnet-2.0.0 package, so this might be better suited for that github repo.  

Node version: 8.11.3
npm version:  5.7.0
OS:  Ubuntu 16.04

installing dotnet-2.0.0 directly throws the same error. 

I have attempted @fearthecowboy's recommendation from the previous issue and installed autorest globally and ran ```autorest --reset```

**Comment by RikkiGibson** [comment]
Is there any way for us to get more detailed information about the failure?

When we run builds in Travis CI, we have to install libunwind8 as a prerequisite for dotnet. If you don't have that already you may wish to try `sudo apt-get install libunwind8` when setting up the dependencies.

**Comment by disophisis** [comment]
I'd be happy to provide more information.  I do not know specifically what would be needed.  If there are some specific logs that I can retrieve, I'd be willing to do so.

I installed libunwind8 as you mentioned and it hasn't appeared to make any difference.

Here's the full error:
```
root@0c72667033f6:/usr/lib/node_modules# npm install -g dotnet-2.0.0
/usr/bin/dotnet -> /usr/lib/node_modules/dotnet-2.0.0/dist/call.js
/usr/bin/dotnet-run -> /usr/lib/node_modules/dotnet-2.0.0/dist/call.js
/usr/bin/dotnet-run-2.0.0 -> /usr/lib/node_modules/dotnet-2.0.0/dist/call.js
/usr/bin/install-dotnet-runtime -> /usr/lib/node_modules/dotnet-2.0.0/dist/app.js

> dotnet-2.0.0@1.4.4 postinstall /usr/lib/node_modules/dotnet-2.0.0
> node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"

{ Error: spawn EACCES
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.child_process.spawn (/usr/lib/node_modules/dotnet-2.0.0/dist/static-loader.js:150:16)
    at /usr/lib/node_modules/dotnet-2.0.0/dist/app.js:34:33
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/dotnet-2.0.0/dist/app.js:8:58)
```

**Comment by RikkiGibson** [comment]
It's the same error before and after the libunwind8 install step was added, right?

@fearthecowboy is really the guy here--I'm pretty much just trying to guess at what the difference could be between the Travis CI environment and the teamcity environment.

That EACCES seems to mean the code running in dotnet-2.0.0 didn't have permission to run the command it was running. It's not *supposed* to need it but maybe sudo during the dependency installation could get it working?

**Comment by fearthecowboy** [comment]
You probably need to install the generators in the docker image too.

The definitions for the docker containers that we've used are : 

https://hub.docker.com/r/azuresdk/autorest/~/dockerfile/

and 

https://hub.docker.com/r/lmazuel/swagger-to-sdk/~/dockerfile/

Maybe take a look.

**Comment by csinge** [comment]
I had this similar issue on Windows and fixed it by

-  removing dotnet core 2.0 runtime (since I had the 2.1 SDKs anyways) 
- Removed autorest via npm and then used yarn instead

`npm remove -g autorest && yarn add global autorest`

**Comment by disophisis** [comment]
Weirdly, going down the yarn route has worked out for me.  It seems that I had an npmrc folder in ```/usr/etc```.  Deleting that directory seems to have fixed things.  I'm not sure why that directory being there  was causing problems, though.  Yarn's --verbose switch is what led to me discovering that.

Prior to deleting the directory, I tried setting permissions on it, but it didn't seem to make any difference.

**Comment by RikkiGibson** [comment]
That's very strange. I wish I could provide a general recommendation to everyone having problems running autorest in CI environments. Thank you for sharing what you've learned.
