### ISSUE TITLE
multipart form data condition revisit

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2327]
https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-client-rest/src/sendRequest.ts#L166-L168
 in here, we will infer if it's real multipart/form-data from whether the body contains bytes or not, even if we have specified the content type as multipart/form-data clearly, which doesn't make sense because multipart/form-data doesn't necessary need to contain bytes.

**Comment by qiaozha** [comment]
empty array bug ?

**Comment by timovv** [comment]
I don't think this issue applies anymore with the new multipart design. Can you check, and if it still applies could you give me some more detail about what case we're not handling correctly so I can investigate?

**Comment by qiaozha** [comment]
I realize we are generating each property of a model as a part and then body is an array of those parts, so it should never falls into the body is not an array condition, this issue should have been resolved. I think.
