### ISSUE TITLE
Mitigate gaps for common types between swagger and typespec

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2335]

**Comment by kazrael2119** [comment]
1.  model name changed:
TrackedResource->TrackedResourceBase
Resource->ArmResource
ProxyResource->ProxyResourceBase
same issue with https://github.com/Azure/typespec-azure/issues/104
 
2.  model name chagned:
ManagedServiceIdentity->ManagedIdentityProperties
ManagedServiceIdentityType->ManagedIdentityType
same issue with https://github.com/Azure/typespec-azure/issues/278

3.  remove parameter **name** under ArmResource
in swagger , it has name https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json#L20
but in tsp, it doesn't have it https://github.com/Azure/typespec-azure/blob/50e384ce1b0597035b819c9370b1cc8545dafbbe/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L23
same issue with https://github.com/Azure/typespec-azure/issues/378

4.  removed model ErrorResponse

5.  type of createdByType in SystemData under swagger common model has ```modelAsString```https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json#L502-L524
in tsp , it only a string https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L313-L325

6.  in swagger, parameter **id, type** from Resource are optional and readonly https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v5/types.json#L14-L29
in tsp,  **id, type** from ArmResource are required https://github.com/Azure/typespec-azure/blob/main/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L23-L32

**Comment by MaryGao** [comment]
For 6 in swagger we could specify the required or optional in `required` section so the subtypes could change the parent's optionality. but in typespec we can't do that. we would always inheritant this from parent's definition.

For example the DataProduct type didn't specify any required properties in [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/networkanalytics.json#L1603-L1625). So all properties are optional.

In typespec the id and type are required by default so the type DataProduct would have them as required https://github.com/Azure/azure-sdk-for-js/pull/28812/files#r1519701904.

**Comment by MaryGao** [comment]
> For 6 in swagger we could specify the required or optional in `required` section so the subtypes could change the parent's optionality. but in typespec we can't do that. we would always inheritant this from parent's definition. We may need the tsp team's help to resolve this and issue is tracked [here](https://github.com/Azure/typespec-azure/issues/131).
> 
> For example the DataProduct type didn't specify any required properties in [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/networkanalytics.json#L1603-L1625). So all properties are optional.
> 
> In typespec the id and type are required by default so the type DataProduct would have them as required https://github.com/Azure/azure-sdk-for-js/pull/28812/files#r1519701904.

Convertion tool could mitigate this breaking by overriding the exisiting optionality of model's parent.

**Comment by kazrael2119** [comment]
7. DataProducts_create operation now is not lro

**Comment by MaryGao** [comment]
Add `HoldOn` label cause we need tsp team to resolve common types' breakings.

**Comment by qiaozha** [comment]
need to upgrade the typespec compiler version and verify it.

**Comment by kazrael2119** [comment]
> Updated as May 20,
> 
> 1. fixed
> 2. not verify
> 3. fixed
> 4. fixed
> 5. breaking is introduced by extensible enum design change and tracked here: [[JS] Redesign Extensible Enum generation #2420](https://github.com/Azure/autorest.typescript/issues/2420)
> 6. fixed
> 7. [New] @kazrael2119 could you verify this also? [[TCGC] [ARM]  Expected client code on definition `model UserAssignedIdentities is Record<UserAssignedIdentity>;`  typespec-azure#825](https://github.com/Azure/typespec-azure/issues/825)

2. fixed
7. not a breaking in JS

**Comment by MaryGao** [comment]
the item 7 is tracked here https://github.com/Azure/autorest.typescript/issues/2535
