### ISSUE TITLE
Do we prompt shared apiVersion param in operation level to client level?

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2337]
Currently we only generate client level apiVerison if it is defined in path parameter in RLC, I was wondering if we need to prompt apiVersion in operation level to client level if all operations share the same apiVersion ?

**Comment by qiaozha** [comment]
I don't think we need a new issue for this https://github.com/Azure/autorest.typescript/issues/2148

**Comment by lirenhe** [comment]
close it as duplicate of https://github.com/Azure/autorest.typescript/issues/2148
