### ISSUE TITLE
Cannot distinguish between a validation error and a REST error (e.g. 404 error)

### ISSUE THREAD

**Issue by co3k** [Azure/autorest.typescript#234]
I think that there is no certain way to distinguish between a validation error and a REST error.

Generated operation methods returns an error if a server responses 404. This error handling is originally in ms-rest-js.
https://github.com/Azure/ms-rest-js/blob/master/lib/policies/deserializationPolicy.ts#L58

The above ms-rest-js code returns an instance of RestError, however, it looks like an instance of normal Error class in the generated operation methods. In short, `aOperationMethod().catch((e) => { console.log(e instanceof RestError) });` shows **false**.

Unfortunately, autorest also generates additional error handlings to validate request parameter by using OpenAPI schema definitions. It throws pure Error instances.

In userland, both of them are instances of Error and also they are not instances of any sub classes. REST error might have adittional properties like statusCode, request and response ... that's all.

Should we consider that it is a bug of autorest.typescript or ms-rest-js?

**Comment by amarzavery** [comment]
We haven't given it a deeper thought. It may be worthwhile to distinguish between the HTTP Errors and Validation Errors thrown by the SDK.
@RikkiGibson @daschult - What do you guys think?

**Comment by RikkiGibson** [comment]
I have seen some cases where I expect the http client to return a RestError but it somehow turns out to be an instance of Error instead. Would like to dig in to it sometime.

**Comment by co3k** [comment]
Is there anyone who knows about what changes a type of Errors? I will create a pull request to fix it when it is clear.

**Comment by RikkiGibson** [comment]
The first thing I'd like to check is something along these lines:

```ts
const testClient = new MyServiceClient({
  requestPolicyFactories: [msRest.deserializationPolicy()]
});

try {
  await testClient.errorOperation();
} catch (err) {
  console.log(err instanceof msRest.RestError);
}
```

Basically checking if one of the default request policies (similar to interceptors) is turning out to re-create the RestError as an Error.

If you'd like to spend time looking into it, you may benefit from looking at https://github.com/Azure/ms-rest-js/blob/master/docs/architectureOverview.md. Otherwise I will add a test for it and make some time to track down the root cause :)

**Comment by co3k** [comment]
Oh, it might be a bug of Babel. https://github.com/babel/babel/issues/3083

I can confirm the issue is solved on my small sample project with the following patch to ms-rest-js.

```diff
diff --git a/lib/restError.ts b/lib/restError.ts
index e312720..06fe213 100644
--- a/lib/restError.ts
+++ b/lib/restError.ts
@@ -21,5 +21,9 @@ export class RestError extends Error {
     this.request = request;
     this.response = response;
     this.body = body;
+
+    // workaround for https://github.com/babel/babel/issues/3083
+    this.constructor = RestError
   }
-}
\ No newline at end of file
+}
+RestError.prototype = Error.prototype
```

**Comment by RikkiGibson** [comment]
Thank you for digging down to the root of this issue! We use TypeScript to compile down to ES5, but it looks like it has the same issue that Babel does.

https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work

We should probably follow the **recommendation** in the linked document.

Would be very grateful for a PR to ms-rest-js that does this.

**Comment by co3k** [comment]
@RikkiGibson Thanks for your helping! I've just created a pull request for fixing this problem to the ms-rest-js repository. https://github.com/Azure/ms-rest-js/pull/220

I close this issue.

**Comment by JameelKhan9** [comment]
@RikkiGibson @co3k Sorry to comment on such an old issue, but I am facing the same issue with RestError imported from @azure/storage-blob. Could you provide any insight into why this would be occurring over there, as it looks like it uses your solution? (https://github.dev/Azure/azure-sdk-for-js/blob/80949a8a07f168c1e45188f52d9ddf09fffa8edc/sdk/core/core-http/src/restError.ts#L1)

```javascript
console.error("Value of `e.name`", e.name);
console.error("Value of `e.__proto__`", e.__proto__);
console.error(
	"Value of `e instanceof RestError`",
	e instanceof RestError
);
console.error(
	"Value of `Object.getPrototypeOf(e)`",
	Object.getPrototypeOf(e)
);
```

```bash
[2022-08-26T06:16:53.310Z] Value of `e.name` RestError
[2022-08-26T06:16:53.310Z] Value of `e.__proto__` [Error]
[2022-08-26T06:16:53.311Z] Value of `e instanceof RestError` false
[2022-08-26T06:16:53.311Z] Value of `Object.getPrototypeOf(e)` [Error]
```

I opened an issue to track this here: https://github.com/Azure/azure-sdk-for-js/issues/23016
