### ISSUE TITLE
Unable to build the library and generate the tarball file

### ISSUE THREAD

**Issue by dev49010** [Azure/autorest.typescript#2343]
I am currently able to generate the source code version of the library from a Swagger file and use it without problems.
I am interested in generating a single file library, the tarball.
The command "npm run pack" should do the job.

The first problem I face is about @azure/dev-tool package that doesn't exist.
As workaround, I deleted its reference from package.json, I cloned azure-sdk-for-js repository, moved into common/tools/dev-tool subfolder, run npm install, then npm install -g.
Now dev-tool is available in the shell.
If I return at api folder and run "npm run pack" again, I get an error on the file dev-tool/src/util/resolveProject.ts startsWith on undefined - isAzureSDKPackage

What is the right procedure to generate the tarball? Thanks

Thanks

**Comment by qiaozha** [comment]
Can you set --azure-sdk-for-js=false ? and see if it works ?

**Comment by dev49010** [comment]
Thanks for the suggestion, I wasn't aware of the existence of that param since it is not in documentation.
Executing 'npm run pack --azure-sdk-for-js=false' doesn't help, is there a specific way to use it?

**Comment by qiaozha** [comment]
no, I mean to set it when generate the code.

**Comment by dev49010** [comment]
I confirm that adding it during code generation changes something.

1) The rollup.config.js file is created
2) package.json has dependencies on rollup rather than @azure/dev-tool

I will try to complete the whole build process and in absence of additional issues I will mark this as resolved.

Thanks

**Comment by dev49010** [comment]
Tarball generated. Then I run 'npm install /pathToTgzFile', a reference has been added automatically into package.json.
The namespace is usable using import statement as usual now.
Perfect.
