### ISSUE TITLE
Generate modular for Sphere.Mgmt and verify its working as expected

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2346]
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sphere/Sphere.Management/main.tsp
pr is here: https://github.com/MaryGao/autorest.typescript/pull/17
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2358
- [ ] https://github.com/Azure/autorest.typescript/issues/2359
- [x] Support @sharedRoute
```

**Comment by kazrael2119** [comment]
model name changes:
1. remove model name XXXOptionalParams but use model name XXXOptions instead
2. remove model XXXNextOptionalParams
3. remove model XXXResponse
4. 
```
remove enum KnownCreatedByType 
remove enum KnownProvisioningState
remove enum KnownOSFeedType
remove enum KnownUpdatePolicy
remove enum AllowCrashDumpCollection
remove enum RegionalDataBoundary
remove enum KnownCapabilityType
remove enum KnownImageType
remove enum KnownCertificateStatus
remove enum KnownOrigin
remove enum KnownActionType

```
6. **new** remove model XXXNextResponse
7. **new** remove model XXXHeaders
8. **new** **excepted** disable flatten

**Comment by MaryGao** [comment]
Close this as the original issue is introduced by non-standard lro and this is fixed in tsp side.
