### ISSUE TITLE
Operation option interface is changed from DataProductsGetOptionalParams to DataProductsGetOptions

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2352]

**Comment by kazrael2119** [comment]
In HLC, the optional parameters will use model XXXOptionalParams as the parameter value like [here](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/networkanalytics/arm-networkanalytics/src/operations/dataProducts.ts#L247), and the model definition code is 
```
export interface DataProductsCreateOptionalParams
  extends coreClient.OperationOptions {
  /** Delay to wait until next poll, in milliseconds. */
  updateIntervalInMs?: number;
  /** A serialized poller which can be used to resume an existing paused Long-Running-Operation. */
  resumeFrom?: string;
}
```

but in Modular, it is changed to XXXOptions, like [here](https://github.com/Azure/autorest.typescript/blob/generate-network-analytics-mgmt-tsp/packages/typespec-test/test/NetworkAnalytics.Management/generated/typespec-ts/src/classic/dataProducts/index.ts#L50), and the model definition code is
```
export interface DataProductsCreateOptions extends OperationOptions {
  /** Delay to wait until next poll, in milliseconds. */
  updateIntervalInMs?: number;
}
```
