### ISSUE TITLE
`user_impersonation` is set as default credential scope in RLC

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2353]

**Comment by joheredi** [comment]
@MaryGao why is this marked as HLC? The title mentions RLC. Also can you please add more details to this issue? How to reproduce, what is the current vs expected output

**Comment by joheredi** [comment]
It seems like this is coming from the `typespec-azure-resource-management` template https://github.com/Azure/typespec-azure/blob/0aecbcf91c68aea11ffcb0d4b5b7d73f44daa560/packages/typespec-azure-resource-manager/src/namespace.ts#L146

It seems weird that if ARM needs the default scope to be `https://management.azure.com/.default` the `typespec-azure-resource-management` doesn't set that as default

**Comment by MaryGao** [comment]
> It seems like this is coming from the `typespec-azure-resource-management` template https://github.com/Azure/typespec-azure/blob/0aecbcf91c68aea11ffcb0d4b5b7d73f44daa560/packages/typespec-azure-resource-manager/src/namespace.ts#L146
> 
> It seems weird that if ARM needs the default scope to be `https://management.azure.com/.default` the `typespec-azure-resource-management` doesn't set that as default

It is the same return in m4 https://github.com/Azure/autorest.typescript/pull/2536#discussion_r1608021911
