### ISSUE TITLE
HLC generates extra non-referenced types/interfaces

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2361]
For HLC, codegen generates extra non-referenced types [ByPass](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/networkanalytics.json#L1443-L1478) and [Versions](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/networkanalytics.json#L2533-L2550) from swagger for networkanalytics,

but modular doesn't generate these two in codes though these two still exist in tsp, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/NetworkAnalytics.Management/main.tsp#L24-L30 and https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/NetworkAnalytics.Management/main.tsp#L97-L112

**Comment by kazrael2119** [comment]
link to https://github.com/Azure/autorest.typescript/issues/2308#issuecomment-1999201392

**Comment by MaryGao** [comment]
We could use usage and access decorator to add these models back.

**Comment by kazrael2119** [comment]
same issue in model [ResourceAccessRules](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/NetworkAnalytics.Management/main.tsp#L90)

**Comment by kazrael2119** [comment]
> For HLC, codegen generates extra non-referenced types [ByPass](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/networkanalytics.json#L1443-L1478) and [Versions](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/networkanalytics.json#L2533-L2550) from swagger for networkanalytics,
> 
> but modular doesn't generate these two in codes though these two still exist in tsp, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/NetworkAnalytics.Management/main.tsp#L24-L30 and https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/NetworkAnalytics.Management/main.tsp#L97-L112

use latest main, they are generated

**Comment by kazrael2119** [comment]
> same issue in model [ResourceAccessRules](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/networkanalytics/NetworkAnalytics.Management/main.tsp#L90)

resolved by adding ```generateOrphanModels: true``` in tspconfig

**Comment by qiaozha** [comment]
we should be able to generate the orphan models without  generateOrphanModels: true
