### ISSUE TITLE
The user-agent is different between HLC and modular

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2385]
in hlc, The userAgentInfo matches the name and version of the package: 
the generated package name is @azure/arm-sphere and the version is 1.0.0, and the userAgentInfo is **azsdk-js-arm-sphere/1.0.0**
https://github.com/kazrael2119/azure-sdk-for-js/blob/029a49c1573be8538a19745587a0cf5019b5e8a8/sdk/sphere/arm-sphere/src/azureSphereManagementClient.ts#L71

but in modular, it doesn't match: 
the generated package name is @azure/arm-sphere and the version is 1.0.0-beta.1, but the userAgentInfo is **azsdk-js-arm-sphere-rest/1.0.0-beta.1**
https://github.com/kazrael2119/azure-sdk-for-js/blob/cd820bc9475252d5184898bb2279075d36645073/sdk/sphere/arm-sphere/src/rest/azureSphereClient.ts#L20

**Comment by joheredi** [comment]
If I understand correctly, the UserAgent that gets set is for the Rest Client not for the modular. But we want to also include in the user agent that this is a Modular library, is that right?

**Comment by joheredi** [comment]
I think we should fix this, although I won't consider this a breaking change

**Breaking Change Categorization**
Bug (Unwanted Breaking Changes):

- [ ] Missing data from the spec in the new implementation.
- [x] Incorrect (Incomplete) results produced by the new implementation.
- [ ] Slight differences in the new implementation that do not improve user experience. If uncertain, categorize as unwanted.

Improvements (Acceptable Breaking Changes):

- [ ] Fixes broken behavior in the new implementation.
- [ ] Offers clear enhancements to user experience.
- [ ] Eliminates or discourages bad patterns.
- [ ] Provides additional functionality.
- [ ] Aligns more closely with TypeSpec standards.

**Comment by MaryGao** [comment]
@joheredi your understanding and categorization is correct.

**Comment by qiaozha** [comment]
[BI report for mgmt plane track2 SDK](https://msit.powerbi.com/groups/de995b1a-16c1-4cc7-a49b-bc9f90bc6acd/reports/8a8582d5-8fdf-4014-8cf9-4d183c5db2c8/ReportSection927ccb84086e7720bff8?experience=power-bi)

The current user agent prefix:
for RLC is: azsdk-js-arm-compute-rest/1.0.0-beta.1
for HLC is: azsdk-js-arm-compute/21.0.1

Proposal 1:
is to keep the rest layer and classical client layer. for Modular API layer, we can use azsdk-js-arm-compute-modular-api/21.0.1

Proposal 2:
Classical client layer: azsdk-js-arm-compute-modular-classic/21.0.1
Api layer:azsdk-js-arm-compute-modular-api/21.0.1
Rest layer: azsdk-js-arm-compute-modular-rest/21.0.1

**Comment by joheredi** [comment]
https://github.com/Azure/autorest.typescript/pull/2616
