### ISSUE TITLE
The content type of put does not match in the recordings

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2393]
If I use playback mode to test the cases with the sdk generated by modular , I will get the request header diff error:
![image](https://github.com/Azure/autorest.typescript/assets/98569699/91feeb9d-fb7f-4e95-a7c6-107b4fd74c7f)

this is a issue found in comparing modular and hlc.
In hlc, the test recording is https://github.com/Azure/azure-sdk-assets/blob/js/servicenetworking/arm-servicenetworking_bb0c85674f/js/sdk/servicenetworking/arm-servicenetworking/recordings/node/servicenetworking_test/recording_trafficcontrollerinterface_create_test.json#L12
we can see it works without  **charset=UTF-8** 

but in modular, only add **charset=UTF-8**, it will pass.
https://github.com/Azure/azure-sdk-for-js/pull/29059/commits/9fb9ecb7ca9d051f602a65889a06c17af618d37a#diff-b5d30781a8e42df28af130c1d4e1b9a9cdb20ff8030bf1cd76ecb71734ab94a7L12

**Comment by joheredi** [comment]
If I understand correctly the diff here is

Track2 Default content-type is `application/json; charset=UTF-8`
Modular Default content-type is `application/json`

I think in this case we should not take this change and go back to `application/json; charset=UTF-8`

**Breaking Change Categorization**
Bug (Unwanted Breaking Changes):

- [ ] Missing data from the spec in the new implementation.
- [ ] Incorrect results produced by the new implementation.
- [x] Slight differences in the new implementation that do not improve user experience. If uncertain, categorize as unwanted.

Improvements (Acceptable Breaking Changes):

- [ ] Fixes broken behavior in the new implementation.
- [] Offers clear enhancements to user experience.
- [ ] Eliminates or discourages bad patterns.
- [ ] Provides additional functionality.
- [ ] Aligns more closely with TypeSpec standards.

**Comment by MaryGao** [comment]
I think the difference is 

Track2 Default content-type is application/json
Modular Default content-type is application/json;charset=UTF-8

And the modular is expected and better than hlc. So I will close this as won't fix.

**Comment by MaryGao** [comment]
NOT BREAKING CHANGE

**Breaking Change Categorization**
Bug (Unwanted Breaking Changes):

- [ ] Missing data from the spec in the new implementation.
- [ ] Incorrect (Incomplete) results produced by the new implementation.
- [ ] Slight differences in the new implementation that do not improve user experience. If uncertain, categorize as unwanted.

Improvements (Acceptable Breaking Changes):

- [ ] Fixes broken behavior in the new implementation.
- [ ] Offers clear enhancements to user experience.
- [ ] Eliminates or discourages bad patterns.
- [ ] Provides additional functionality.
- [x] Aligns more closely with TypeSpec standards.
