### ISSUE TITLE
readonly properties in an interface should mention in their description that this property will not be serialized.

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest.typescript#240]
properties marked as `"readOnly": true` in a swagger spec indicate that this property will not be sent on the wire. It can only be populated by the server. This information should be appended to the description of every readonly property in the model interface. 

When a property on an interface is marked as `readonly` in TS, it means that the value of the property cannot be changed once set. While creating an object of a given type, one can provide the value for the readonly property. In fact, TS would complain if the readonly property is not optional and is not provided by the customer. However, when the sdk serializes the object, it will strip this property. Letting the customer know about this in the description of the property can be valuable.

```ts
interface Foo {
  /**
   * @property {string} x Describes the identifier for Foo.
   * 
   * **NOTE:** This property will not be serialized. It can only be
   * populated by the server.
   */
  readonly id: string;
  y: string;
}
let x1: Foo = {
  y: "",
  id: "some-id"
};

console.log(x1);
```

**Comment by RikkiGibson** [comment]
It's slightly silly that we keep trying to apply the language concept of `readonly` to the Swagger `readOnly` when they simply don't mean the same thing. `readonly` will help users by saying "no, you shouldn't set this"--however this design winds up making immutable domain models (which are highly valuable to lots of users) impractical/unavailable in most target languages.
