### ISSUE TITLE
easm failed to generate apiView

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2404]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3663858&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=1976

**Comment by kazrael2119** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/28322

**Comment by MaryGao** [comment]
@kazrael2119 still have issue to pack package, could you have a fix?
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3675469&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=1985

**Comment by kazrael2119** [comment]
lack of following scripts:
```
    "build:browser": "tsc -p . && dev-tool run bundle",
    "build:node": "tsc -p . && dev-tool run bundle --browser-test false",
    "build:test": "tsc -p . && dev-tool run bundle",
    "build:debug": "tsc -p . && dev-tool run bundle && api-extractor run --local",
    "extract-api": "rimraf review && mkdirp ./review && api-extractor run --local",
    "integration-test": "npm run integration-test:node && npm run integration-test:browser",
    "pack": "npm pack 2>&1",
    "unit-test": "npm run unit-test:node && npm run unit-test:browser",
```

**Comment by kazrael2119** [comment]
Compared with the [easm script](https://github.com/azure-sdk/azure-sdk-for-js/blob/182e7e350293247755f933ec6633e4be902171c0/sdk/easm/defendereasm-rest/package.json#L86) and other mgmt package([@azure/arm-frontdoor](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/frontdoor/arm-frontdoor/package.json#L73)), it was found that the following scripts are missing from the easm script:
```
"prepack": "npm run build",
"pack": "npm pack 2>&1",
"extract-api": "api-extractor run --local",
"integration-test": "npm run integration-test:node && npm run integration-test:browser",
"unit-test": "npm run unit-test:node && npm run unit-test:browser",
```

**Comment by MaryGao** [comment]
@kazrael2119 Could you help add following 4 entries in scripts? @joheredi Not sure any reason we missed them but if failed [ci ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3675469&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=1985).
```
    "extract-api": "rimraf review && mkdirp ./review && api-extractor run --local",
    "integration-test": "npm run integration-test:node && npm run integration-test:browser",
    "pack": "npm pack 2>&1",
    "unit-test": "npm run unit-test:node && npm run unit-test:browser",
```

**Comment by kazrael2119** [comment]
> npm run unit-test:node && npm run unit-test:browser

new missing script
```
"format": "dev-tool run vendored prettier --write --config ../../../.prettierrc.json --ignore-path ../../../.prettierignore \"src/**/*.ts\" \"test/**/*.ts\" \"samples-dev/**/*.ts\" \"*.{js,json}\""
```

**Comment by kazrael2119** [comment]
browser test failed with following message:
![image](https://github.com/Azure/autorest.typescript/assets/98569699/5af461ab-a043-4d32-b1ad-64f56b9ab224)
