### ISSUE TITLE
ignore default value

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2425]
we have guideline that client side should not respect default value, but we have set such default value in HLC and in the serializer and deserilizer we also take care of the default value before. if we don't add such logic, it will be a breaking. but it's a right thing ot not handle the client side default value.

**Comment by qiaozha** [comment]
1. swagger has default value
2. single value enum

**Comment by joheredi** [comment]
We should definetly honor TypeSpec guidance which is `Default values SHOULD NOT be used as client-side default values`. If this causes problems we may need an azure only decorator to set client default value, but out of the box we should not set default values in the client

**Comment by joheredi** [comment]
This is consistent accross languages, we are no longer trying to set default values in the client. @qiaozha feel free to re-open this issue if you want to discuss this further

**Comment by qiaozha** [comment]
I understand this is the consistent across languages, but the point is, track2 will help set the default value, if we don't now, it's a breaking, I think we should have some open discussion to say that this breaking fully awared and accepted ?

**Comment by joheredi** [comment]
**Breaking Change Categorization**
Bug (Unwanted Breaking Changes):

- [ ] Missing data from the spec in the new implementation.
- [ ] Incorrect (Incomplete) results produced by the new implementation.
- [ ] Slight differences in the new implementation that do not improve user experience. If uncertain, categorize as unwanted.

Improvements (Acceptable Breaking Changes):

- [ ] Fixes broken behavior in the new implementation.
- [ ] Offers clear enhancements to user experience.
- [ ] Eliminates or discourages bad patterns.
- [ ] Provides additional functionality.
- [x] Aligns more closely with TypeSpec standards.

**Comment by MaryGao** [comment]
> I understand this is the consistent across languages, but the point is, track2 will help set the default value, if we don't now, it's a breaking, I think we should have some open discussion to say that this breaking fully awared and accepted ?

Agreed! This is quite common in swagger side and would introduce breakings. At least we need to discuss breaking or mitigating.

**Comment by qiaozha** [comment]
we have 117 mgmt plane libraries will be impacted.

**Comment by qiaozha** [comment]
We will re-evaluate the impact on mgmt plane if we get furthur feedback from customers.
