### ISSUE TITLE
Failed to build code for Windows_Latest in pipeline with v18.20.2

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/autorest.typescript#2454]
link: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3709536&view=logs&j=a2410be6-b319-5f72-fd69-b6e40d1c20f1&t=e8f2cc68-4a2c-51b4-64af-043b141dfebc&l=30
![image](https://github.com/Azure/autorest.typescript/assets/80496810/48895e75-31e0-4408-a4c4-2d0880d138c0)

**Comment by MaryGao** [comment]
@v-jiaodi could you revert the change and upgrade the rush version? https://github.com/Azure/azure-sdk-for-js/pull/29389/files#diff-7cf530b920932d4075d799c0aa86e3757def01fb357fcb27ebc090868ceb62dd

**Comment by v-jiaodi** [comment]
Upgrade the rush version: https://github.com/Azure/autorest.typescript/pull/2468
