### ISSUE TITLE
[Bug] RLC doesn't handle the credential generation correctly

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2458]
if we have typespec like this `@useAuth(BearerAuth | ApiKeyAuth<ApiKeyLocation.cookie, "session-id">)` https://github.com/bterlson/typespec-todo/blob/main/main.tsp#L12,  the generated rlc client  is missing credential for it, but modular layer has it.
```ts
export default function createClient(
  endpoint: string,
  options: ClientOptions = {},
): TodoClient {
```

**Comment by MaryGao** [comment]
closed as fixed.
