### ISSUE TITLE
Support marking response headers as required

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.typescript#246]
Right now, [Swagger response headers](https://swagger.io/specification/v2/#headersObject) don't appear to support a `required` attribute like model properties do. We interpret this by creating headers models where all the properties are optional. @fearthecowboy may be able to comment on the tradeoffs here.

This results in a worse user experience because every header appears like it could be absent, even if the spec authors want to guarantee that a given response will always include certain headers.

Can we change the interpretation to instead see all response headers as required/definitely present? Perhaps always including default values for response headers in mappers would help?

**Comment by RikkiGibson** [comment]
@amarzavery @daschult do you have any opinions about the design here? Should we mark response headers as always present or always optional? Or push the decision to the end user with a `--optional-response-headers=false` flag?

**Comment by daschult** [comment]
This seems reasonable. I'd vote we add the flag but default it so that the response headers are marked as required. That gives specific customers (and us) and escape hatch in case we learn this isn't a good idea down the road.

**Comment by RikkiGibson** [comment]
@XiaoningLiu may have thoughts on here as well
