### ISSUE TITLE
extends vs & in TS Generated SDK

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest.typescript#2477]
For the following Typespec definition:

```
model AcsRouterJobEventData extends AcsRouterEventData {
  /** Router Job events Queue Id */
  queueId?: string;
  /** Router Job events Labels */
  labels?: Record<string>;
  /** Router Jobs events Tags */
  tags?: Record<string>;
}
```

Now, If you look at the generated SDK, it looks like the following:

```js
/** Schema of common properties of all Router Job events */
export interface AcsRouterJobEventData extends AcsRouterEventData {
  /** Router Job events Queue Id */
  queueId?: string;
  /** Router Job events Labels */
  labels?: Record<string, string>;
  /** Router Jobs events Tags */
  tags?: Record<string, string>;
}
```

But, If you look at the original swagger generated SDK, you can find a definition as:

```js
/** Schema of common properties of all Router Job events */
export type AcsRouterJobEventData = AcsRouterEventData & {
  /** Router Job events Queue Id */
  queueId: string;
  /** Router Job events Labels */
  labels: { [propertyName: string]: string };
  /** Router Jobs events Tags */
  tags: { [propertyName: string]: string };
};
```

i.e. as you can see the usage of 'extends' vs '&'. Was this design a conscious decision? Because, if the parent and child have overriding properties, the 'extends' will create issues. It would be great if you could change it back to the '&' instead of 'extends'.

@xirzec @lmazuel FYI

**Comment by MaryGao** [comment]
Thanks for reporting this  and I added this into [epic ](https://github.com/Azure/autorest.typescript/issues/2367) and I think we need to discuss this design.

**Comment by qiaozha** [comment]
I think the only case we need to check is how we generate inheritance, for other non-inherited case, I think typespec will report compiler error for this [playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOwoKdXNpbmcgVHlwZVNwZWMuSnNvblPFHTsKCkDELMYOCm5hbWVzcGFjZSDGEXM7Cgptb2RlbCBQZXJzb24gewogIC8qKiBUaGUgcMUTJ3MgZmlyc3QgxDwuICovCiDGEU5hbWU6IHN0cmluZzsK1DhsYc43xBDVNkFnZSBpbiB5ZWFycyB3aGljaCBtdXN0IGJlIGVxdWFsIHRvIG9yIGdyZWF0ZXIgdGhhbiB6ZXJvx1hAbWluVmFsdWUoMCkgYWdlOiBpbnQzMslf5wDcYWRkcmVzc8Y0xw06IEHGCcktTGlzdCBvZiBuaWNr5QC9xzFAdW5pcXVlSXRlbXPFHeQAynM%2F6ADMW13RQmPkAM7mAQ0gb3dux0jEFj86IENhcsQzfQoKxDNSZXNwcmVzZW50IGHtAKnmAZ3nAKTlAZ7zAXwgxAplZXTMEmNpdHnNEG91bnRyyxN9x1xDYXLpAfZLaW5k5wC6xH0gIGtpbmQ6ICJldiIgfCAiaWNl5AJtxixCcmHGLXRoZcoxYsQW8QHgTcVq0Cxg5QCBYMoufQoKYWxpYXMgVGVzdCA96AG4JukBpA%3D%3D&e=%40typespec%2Fjson-schema&options=%7B%7D)

**Comment by sarangan12** [comment]
@qiaozha The compile error found in your playground link happens in Typespec. I am not suggesting to change the code in Typespec. I am interested in how the code generated in Typescript SDK.

**Comment by joheredi** [comment]
Typespec introduced more ways to define relationships among types whereas swagger was limited.  Typespec semantics are close to TypeSpec and I would like we keep as close as possible for example I would expect the following translations

model Foo extends Bar -> interface Foo extends Bar
alias T = Foo & Bar -> type T = Foo & Bar
model Foo {  -> type Foo = Bar & {...}
   ...Bar
}

@qiaozha @MaryGao can you help me check what the current behavior is on the samples I added above?

**Comment by qiaozha** [comment]
I will help take a look today.

**Comment by joheredi** [comment]
This is the current behavior of modular

**Input**
```ts
model Foo {
  name: string;
}

model Bar extends Foo {
  kind: "Bar";
}

model Baz {
  kind: "Baz";
}

alias MyIntersection = Foo & Baz;

model MySpread {
  ...Foo;
  kind: "spread";
}
```

**Output**
```ts
export interface Foo {
  name: string;
}

export interface Bar extends Foo {
  kind: "Bar";
}

export interface Baz {
  kind: "Baz";
}

export interface MySpread {
  name: string;
  kind: "spread";
}

```

**Comment by joheredi** [comment]
I don't have concerns with the current behavior, and & and extends are really equivalent so I wouldn't consider this as a breaking change. It is a change, from previously but `interface` is preferred over type generally

**Comment by joheredi** [comment]
**Breaking Change Categorization**
Bug (Unwanted Breaking Changes):

- [ ] Missing data from the spec in the new implementation.
- [] Incorrect (Incomplete) results produced by the new implementation.
- [ ] Slight differences in the new implementation that do not improve user experience. If uncertain, categorize as unwanted.

Improvements (Acceptable Breaking Changes):

- [ ] Fixes broken behavior in the new implementation.
- [ ] Offers clear enhancements to user experience.
- [ ] Eliminates or discourages bad patterns.
- [ ] Provides additional functionality.
- [x] Aligns more closely with TypeSpec standards.
