### ISSUE TITLE
[Bug] API Version Not Respected in `createClient`

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#2490]
**Description:**
When generating a client that targets a specific API version, the generated `createClient` function does not respect the specified `api-version` flag in `tspconfig.yaml`. Although models and operations for the specific version are generated correctly, `createClient` defaults to the latest version instead of the specified one.

**Relevant Details:**
- TCGC was updated to support targeting specific API versions through the `api-version` flag in `tspconfig.yaml`, as introduced by [this change](https://github.com/Azure/typespec-azure/pull/700/files#diff-3599739b76751d3c27620bc862fbe98c2ba6e0cb2fedfe25b264176b10dfb86e).
- The TypeScript emitter is already utilizing TCGC with this feature support.
- The issue is specifically observed in the generated `createClient` function which continues to use the default (latest) API version.

**Suspected Culprit:**
- The issue might be stemming from how the API version is handled or defaulted in the `createClient` function within the TypeScript Emitter. Specifically, the logic in this [line of code](https://github.com/Azure/autorest.typescript/blob/3b06cf501ad088d58378c15e772a9282a36a1605/packages/rlc-common/src/buildClient.ts#L310) might be ignoring the specified API version.

**Steps to Reproduce:**
1. Configure `tspconfig.yaml` with a specific `api-version`.
2. Generate a client using the Typescript Emitter.
3. Observe that the generated client's `createClient` function defaults to the latest API version instead of using the specified version.

**Expected Behavior:**
The `createClient` function should respect the API version specified in `tspconfig.yaml` and use it instead of defaulting to the latest version.

**Actual Behavior:**
The `createClient` function ignores the specified API version and defaults to the latest version.

**Screenshots/Logs:**
![Issue Screenshot](https://github.com/Azure/autorest.typescript/assets/21109913/6d482ca2-49e1-45db-a18d-0c10bd722afe)

**Environment:**
- Typescript Emitter version: 0.28.0
- Typespec Compiler version: 0.55.0

**Comment by dgetu** [comment]
This was fixed in TCGC in [#801](https://github.com/Azure/typespec-azure/pull/801)

**Comment by dgetu** [comment]
Confirmed fixed by taking a dependency on >=0.42.1
