### ISSUE TITLE
Support `void` type in RLC and modular

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2492]
This is issue found when generating fleet ([tsp here](https://github.com/Azure/azure-rest-api-specs/blob/bce261b592674cd74a6603ea65b8561fb20ed154/specification/containerservice/Fleet.Management/fleet.tsp#L237)) and also in sphere tsp: https://github.com/Azure/autorest.typescript/pull/2498.

![image](https://github.com/Azure/autorest.typescript/assets/9943211/de3b6e45-c92d-4a78-8ba3-86fc16d4fb55)

See the discussion in typespec side https://github.com/microsoft/typespec/issues/3299.

**Comment by MaryGao** [comment]
Case 1: void as request body & void as response

[tsp](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKb3AgdGVzdChAYm9keSDEBTogdm9pZCnGBzs%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D) 

```
op test(@body body: void): void;
```

RLC generated

```ts
// omit the parameter body
export type TestParameters = RequestParameters;

// omit the response body
export interface Test200Response extends HttpResponse {
  status: "200";
}
```

Modular generated

```ts
export async function test(
  context: Client,
  // omit the body parameter
  options: TestOptionalParams = { requestOptions: {} },
): Promise<void> 
```

Case 2: void as response body

[tsp](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKb3AgdGVzdCgpOiB7CiAgQGJvZHkgxAU6IHZvaWQ7Cn07&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)
```
op test(): {
  @body body: void;
};
```

RLC generated

```ts
// omit the response body
export interface Test200Response extends HttpResponse {
  status: "200";
}
```

Modular generated

```ts
export async function test(
  context: Client,
  options: TestOptionalParams = { requestOptions: {} },
): Promise<void> 
```

Case 3: void as normal property in model

[tsp](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgQSB7CiAgZm9vOiB2b2lkOwp9&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

```
model A {
  foo: void;
}
```

**Comment by MaryGao** [comment]
> [microsoft/typespec#3299 (comment)](https://github.com/microsoft/typespec/issues/3299#issuecomment-2099656415)
> 
> ### Case 1: void as request body & void as response
> * void as request body means no body property( this is the case in fleet)
> * void as response means no body
> 
> [tsp](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKb3AgdGVzdChAYm9keSDEBTogdm9pZCnGBzs%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)
> 
> ```
> op test(@body body: void): void;
> ```
> 
> ....


Concluded at May 9
- Case 1: omit the body parameter
- Case 2: omit the body parameter
- Case 3: emit an error

**Comment by kazrael2119** [comment]
We have an actual case about case 3 which fails the JS sdk generation in typespec conversion:
typespec: https://github.com/Azure/azure-rest-api-specs/pull/38573/files#diff-3f12f17bb6c86f457a820260516d30e8141d1835db5ae6a2d848d48fafb84036R65
this service uses customized operation to override the origin one to support [x-ms-parameter-grouping](https://github.com/Azure/azure-rest-api-specs/pull/38573/files#diff-106b216a7e425a5b69f1c89c260cc99f729a0ba2f3386f87cec6f162e1f852efL2959-L2960) in typespec side. And 
```
op usagesListBySubscriptionCustomization(
  ...ApiVersionParameter,
  ...SubscriptionIdParameter,
  ...SubscriptionActionScope,
  ...Azure.ResourceManager.Legacy.Provider,
  ...LocationParameter,

  body: void,

  params: `search-management-request-options`,
): ArmResponse<QuotaUsagesListResult> | CloudError;
```

in this case, we can't add `@body` for body or it will has typespec compile issue:

<img width="434" height="228" alt="Image" src="https://github.com/user-attachments/assets/c369341a-3399-47cb-8df7-1c21db561adc" />

<img width="894" height="55" alt="Image" src="https://github.com/user-attachments/assets/48d25218-a371-4b78-9632-a79973bfa39b" />


So I create a PR to support case 3 in https://github.com/Azure/autorest.typescript/pull/3687
