### ISSUE TITLE
Add Payload contentNegotiation case for modular

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/autorest.typescript#2497]
![image](https://github.com/Azure/autorest.typescript/assets/80496810/d2fbe0d2-f058-484f-9335-bba6e8dd8aa4)

**Comment by qiaozha** [comment]
For this case, we have a dilemma here, if we want to accept customer self defined header value, we lost the type inference as of overload. but if we don't accept, it would be strange customer can set the header but we just ignore it.

**Comment by qiaozha** [comment]
we should go for proposal 3 and maybe log a warrning if possible.
