### ISSUE TITLE
isUnexpected not working if one model is a subset of another model

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2502]
See pr https://github.com/Azure/autorest.typescript/pull/2501/files
Generated code: https://github.com/kazrael2119/autorest.typescript/blob/deviceregistry-modular/packages/typespec-test/test/DeviceRegistry.Management/generated/typespec-ts/src/rest/isUnexpected.ts#L82

In following OperationStatusGetDefaultResponse is a subset of OperationStatusGet200Response so the helper fail to type narrowing.
```ts
export function isUnexpected(
  response: OperationStatusGet200Response | OperationStatusGetDefaultResponse,
): response is OperationStatusGetDefaultResponse;
```
![image](https://github.com/Azure/autorest.typescript/assets/9943211/a48ee015-e552-4661-8866-ffc8bb3da565)

Finally causing the modular code failed to compile.
![image](https://github.com/Azure/autorest.typescript/assets/9943211/361b0604-b7e7-4889-be76-e2d71a5f2b2e)

**Comment by qiaozha** [comment]
need further discussion on the typespec best practice.

**Comment by MaryGao** [comment]
The definition is designed in v3 common models https://github.com/Azure/azure-rest-api-specs/blob/main/specification/deviceregistry/resource-manager/Microsoft.DeviceRegistry/preview/2023-11-01-preview/deviceregistry.json#L192-L204.
