### ISSUE TITLE
Accept strings for date parameters

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.typescript#251]
Some services need to produce date strings in formats other than what is produced by [Date.toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString).

Let's consider widening the Date parameter types to be `Date | string`. In the case where a string is provided, we will just write it to the wire without modification.

**Comment by amarzavery** [comment]
A setting `dateAsString: true | false` will be needed in ms-rest's serializer to support not deserializing dates. Thus ensuring that the precision is preserved.

**Comment by RikkiGibson** [comment]
We want to narrow this flag to `--model-date-time-as-string` because that's the only type that experiences the precision issues (ISO 8601 format).
