### ISSUE TITLE
models under xxxUpdateProperties are not generated with Update suffix

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2530]
rp: deviceregistry
generated code from swagger:
![image](https://github.com/Azure/autorest.typescript/assets/98569699/db683c0c-7d9f-4e0e-a1d0-f0b233760ef4)

generated code from tsp:
![image](https://github.com/Azure/autorest.typescript/assets/98569699/db6da694-20bb-4cf4-a214-14bc5af900d9)

**Comment by MaryGao** [comment]
The issues is tracked in typespec https://github.com/Azure/typespec-azure/issues/688

**Comment by live1206** [comment]
Updating the TypeSpec to disable path model splitting in https://github.com/Azure/azure-rest-api-specs/pull/29319.
So that, swagger and TypeSpec will generate the same models.

**Comment by qiaozha** [comment]
@kazrael2119 Could you help verify if the typepsec change works in our side?
