### ISSUE TITLE
tsp generation doesn't support title config in tspconfig.json

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2537]
failed to add title in tspconfig.yaml to set the package client name
![image](https://github.com/Azure/autorest.typescript/assets/98569699/2865dbbd-e438-4910-a432-4001a7137e00)
generated client name:
![image](https://github.com/Azure/autorest.typescript/assets/98569699/b52e121c-a537-496a-8ffd-a9f8b4a3deab)

**Comment by qiaozha** [comment]
close it as duplicated with #2355
