### ISSUE TITLE
Test wider range of browsers with Karma and Sauce Labs

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.typescript#256]
Right now we have pretty decent automated Chrome testing, but the best coverage is gonna come with setting up karma and using Sauce Labs or similar to actually run automated browser tests on all the major browsers.

Karma at first has appeared more complex/invasive than mocha-chrome but after having fiddled with it a decent amount in outside projects I think it's not so bad.

It will give more credibility to the project to show the badges with CI status for supported browsers in the README.

**Comment by joheredi** [comment]
Extensive browser testing should be done for each specific client, having chrome coverage should be enough for the generator
