### ISSUE TITLE
[TS] [DPG] BearerAuth generates lower case "bearer <key>"

### ISSUE THREAD

**Issue by glharper** [Azure/autorest.typescript#2572]
The BearerAuth keyword in TypeSpec seems to generate the following client code in TS:
```
  if (isKeyCredential(credentials)) {
    client.pipeline.addPolicy({
      name: "customKeyCredentialPolicy",
      async sendRequest(request, next) {
        request.headers.set("Authorization", "bearer " + credentials.key);
        return next(request);
      },
    });
  }
  ```
  That fifth line should be (note capitalized Bearer): ``` 
        request.headers.set("Authorization", "Bearer " + credentials.key);
        ```

**Comment by timovv** [comment]
Related: https://github.com/Azure/autorest.typescript/issues/2109
