### ISSUE TITLE
[App Config] Modular Library Generation Error

### ISSUE THREAD

**Issue by minhanh-phan** [Azure/autorest.typescript#2585]
I am testing the TypeSpec generation for App Configuration service with modular generation. The rest layer generation finishes and the modular generation gives the following error: `Error: Unexpected! Inserting syntax kind of FunctionDeclaration, but ExpressionStatement was inserted.` 

_To reproduce:_
The tspconfig file I use is [here](https://github.com/Azure/azure-rest-api-specs/blob/appconfig/typespec/specification/appconfiguration/AppConfiguration/tspconfig.yaml) and the commit that I use is `e873e9aa3ab8682e53c4a344f62797ec6f63f568`. The initial generation is in [this branch](https://github.com/minhanh-phan/azure-sdk-for-js/tree/appconfig/modular-typespec-gen). The "@azure-tools/typespec-ts" version I use is "0.29.0".

**Comment by joheredi** [comment]
@qiaozha can you help looking into what is causing this issue?
