### ISSUE TITLE
Support `skipEncoding` for path url parameter

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2589]
In swagger we have [x-ms-skip-url-encoding extension ](https://github.com/azure/autorest/blob/main/docs/extensions/readme.md#x-ms-skip-url-encoding) which could set as true|false when the parameter is provided from a source where the value is known to be URL-encoded. 

We need to think on how to support this feature in RLC and Modular.

Please notice there is an [issue ](https://github.com/Azure/typespec-azure/issues/1022)in typespec to track on how to support this in tsp side.

**Comment by ArthurMa1978** [comment]
Part of https://github.com/microsoft/typespec/issues/3736

**Comment by MaryGao** [comment]
Should be supported in https://github.com/Azure/autorest.typescript/issues/2791.
