### ISSUE TITLE
Should we not export PagedResult to top-level index in modular?

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2604]
Model [PagedOperation](https://github.com/Azure/autorest.typescript/pull/2581/files#diff-06d85072cb53905e3ad4e03989c061e6cee9a984459a8fcb2fb5194ad312ff05R331) is used in an [internal function](https://github.com/Azure/autorest.typescript/pull/2581/files#diff-5a425148fc9f31d880b444bce72437298db7e2e151e5d477622e85bdb3aebf38R31) but now it exports to [top-level index](https://github.com/Azure/autorest.typescript/pull/2581/files#diff-5a425148fc9f31d880b444bce72437298db7e2e151e5d477622e85bdb3aebf38R4). 

Considering this is only internal used and we don't need to export them to public.

**Comment by MaryGao** [comment]
similar issue in hlc https://github.com/Azure/autorest.typescript/issues/1698
