### ISSUE TITLE
undocumented in api view

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2610]
Currently, there's a lot of places missing description, causing we have undocumented warning in the api view

Modular api view https://github.com/Azure/autorest.typescript/blob/main/packages/typespec-test/test/anomalyDetector/generated/typespec-ts/review/ai-anomaly-detector.api.md 
RLC api view https://github.com/Azure/autorest.typescript/blob/main/packages/typespec-test/test/authoring/generated/typespec-ts/review/authoring.api.md

**Comment by MaryGao** [comment]
Please include the enum document changes also.

**Comment by qiaozha** [comment]
![image](https://github.com/Azure/autorest.typescript/assets/55688292/b55078b7-7a8f-47ee-9971-67ace5cd3996)

Please consider extensible enum description refine
