### ISSUE TITLE
should generated packge.json bump up the min dependency version of TS to 3.x?

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest.typescript#262]
https://github.com/Azure/autorest.typescript/blob/master/src/vanilla/Templates/PackageJson.cshtml#L24

**Comment by daschult** [comment]
I don't think so. Since we're not relying on any TS 3.0 features (we're not, right?) we should be as backwards compatible as possible. When/If we start relying on TS 3.0 features, then I think it would make sense to force our consumers to move forward.

**Comment by RikkiGibson** [comment]
I am hoping to leverage the new [--build flag](https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/#build-mode) for multi api
