### ISSUE TITLE
Are the TypeSpec Versioning Decorators Supported?

### ISSUE THREAD

**Issue by alfie80** [Azure/autorest.typescript#2630]
Hello team, 

I would like to check if the [TypeSpec versioning decorators](https://typespec.io/docs/libraries/versioning/reference/decorators#@TypeSpec.Versioning.added) are currently supported. If not, do you have a plan when to support it in future? 

Thanks,
Eric

**Comment by lirenhe** [comment]
We support generating the JS SDK from the latest API version.  Please let us know if this could meet your need.
cc @qiaozha

**Comment by alfie80** [comment]
> We support generating the JS SDK from the latest API version. Please let us know if this could meet your need. cc @qiaozha

Thank you @lirenhe for your reply. So I assume specifying specific version to generate the SDK is not supported, right?

**Comment by qiaozha** [comment]
It is supported. you can specify `api-version` in the emitter's configuration of tspconfig.yaml similar like this
![image](https://github.com/Azure/autorest.typescript/assets/55688292/60c266a4-3e7d-4edb-af28-ace754a2e3a8)

**Comment by alfie80** [comment]
> It is supported. you can specify `api-version` in the emitter's configuration of tspconfig.yaml similar like this ![image](https://private-user-images.githubusercontent.com/55688292/344596347-60c266a4-3e7d-4edb-af28-ace754a2e3a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjIwNjgsIm5iZiI6MTcxOTgyMTc2OCwicGF0aCI6Ii81NTY4ODI5Mi8zNDQ1OTYzNDctNjBjMjY2YTQtM2U3ZC00ZWRiLWFmMjgtYWNlNzU0YTJlM2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA4MTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYTIzOTY5Y2JmMTk4NTVmMmM5NmMzYmI0MDE0YzRkOWNhYTRlNGYwZmU1OGNhMDFjYzRhM2FhNGQxMmU4YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fLWtvV-1gqUz96xCl8ceymmhe0wc6yNTgXEswkTaCb0)

That's great! Thank you @qiaozha . I will take a try with that.

**Comment by qiaozha** [comment]
verify on RLC projected versioning.

**Comment by qiaozha** [comment]
Already confirmed supported in both RLC and Modular.

**Comment by alfie80** [comment]
Test results are good. Closing the ticket.
