### ISSUE TITLE
Multi-api generation

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.typescript#265]
- Generate private package.json, tsconfig.json, tsconfig.es.json, etc. when `--multiapi` flag is set
- Generate project root when some kind of flag we define like `--multiapi-root` is set

**Comment by RikkiGibson** [comment]
Revisiting this:

We've found that some Azure services produce lots of large API versions--new versions every 1-2 months and no deprecation strategy adopted at this point. There could grow to be a ridiculous number of API versions actively supported for some services. Ideally we would like to ship one npm package per RP for the sake of user simplicity. We are finding big drawbacks, though:

- the packages can get very large (40 MB+ uncompressed, even without source maps)
- it winds up requiring slightly non-intuitive usage:

```ts
// What we'd ideally prefer for 1-package-per-RP
import { v2018_05_1, latest, hybridProfile2018_05_01 } from "@azure/arm-network";

// What's necessary for practical reasons for 1-package-per-RP
import * as azNetwork from "@azure/arm-network/2018-05-01";

// What we may practically need due to package size concerns: 1-package-per-(RP API version)
import * as azNetwork from "@azure/arm-network-2018-05-01";
import * as azNetworkLatest from "@azure/arm-network-latest"; // "alias" package to latest stable
import * as azNetworkLatest from "@azure/arm-network-preview"; // "alias" package to latest preview
```

It sounds like Go is leaning toward 1-per-(RP API version) way due to the size as well as other constraints imposed by the specific behaviors of Go's new module system. @jhendrixMSFT may wish to comment.

At this moment we are looking at modifying our current approach to use 1-per-(RP API version).

One remaining question I have that folks @salameer @marstr  may wish to weigh in on: should we be judicious about which API versions we publish, just including those which are actually useful to new apps, or should we publish every supported API version under the sun always?

@bterlson

**Comment by marstr** [comment]
It is my strong belief that attempting to be selective about the published API Versions is a short-term fix, and not one that will ultimately drive us towards a scalable, well engineered solution for handling the girth of API Versions that are available to customers.
