### ISSUE TITLE
Paging breakings in Modular

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2696]
This issue would describe the paging breakings and how to move to new paging interface.

**Comment by MaryGao** [comment]
## Breaking changes summary for Paging
The scope for paging breakings are mainly for SDK which is HLC and plan to migrate to Modular. The breakings are because in Modular we adjusted paging interfaces a little for better experience and mainly are three parts:
- Remove the maxpagesize in PageSetting
- Remove the helper `getContinuationToken`

## Remove the maxpagesize in PageSetting

## Remove the helper `getContinuationToken`

**Comment by MaryGao** [comment]
The paging pr is here https://github.com/Azure/autorest.typescript/pull/1996.

**Comment by MaryGao** [comment]
@qiaozha @joheredi Could you help review the breaking change summary?

**Comment by qiaozha** [comment]
why the maxPageSize size still can be accessed by RLC paginate helper ? 
```ts
    const parties = paginate(client, result);

    const lastParty: Party[] = [];
    for await (const party of parties.byPage({maxPageSize:1})) {
      lastParty.push(<Party>party);
    }
```

Another question is, since we don't need to generate RLC code in modular, is it still necessary to keep the core-paging dependency for just Paged definition? We are generating all the other types in pagingTypes.ts now if I understand it correctly?

**Comment by MaryGao** [comment]
> why the maxPageSize size still can be accessed by RLC paginate helper?

The above breaking is mainly for Modular and RLC is still to leverage core-paging interfaces which include maxPageSize but it doesn't work either in RLC.

There is an issue to sync the modular interfaces back to the core-paging https://github.com/Azure/azure-sdk-for-js/issues/27868, I prefer to migrate RLC to core after that.

> is it still necessary to keep the core-paging dependency for just Paged definition?

Yeah, we could remove this dependency now and create an issue for this.

**Comment by MaryGao** [comment]
Closed as fixed.

**Comment by MaryGao** [comment]
These breakings are accepted.
