### ISSUE TITLE
Unable to install/use dotnet framework. Failed to install or start extension '@microsoft.azure/autorest.typescript' (~2.0.12)

### ISSUE THREAD

**Issue by OliverRC** [Azure/autorest.typescript#27]
![image](https://user-images.githubusercontent.com/1888486/37660430-16402e0a-2c5b-11e8-8c59-e28c2505a197.png)

As you can see I already have a later version of .Net Core installed.

**Comment by RikkiGibson** [comment]
Looks like https://www.npmjs.com/package/dotnet-sdk-2.0.0 is the package that's failing to install.
@fearthecowboy any idea what this could be about?

**Comment by fearthecowboy** [comment]
AutoRest can't use a globally installed version of dotnet (as there is no reliable means to bootstrap cross-platform that when it's not there, and an incompatible version is a nightmare) -- so it has to bring it's own along.

Looking at that, `node 8.1.4` is definitely a sketchy version. I know first hand that there were things that didn't work with that one.

Upgrade node to [8.10.0](https://nodejs.org/dist/v8.10.0/node-v8.10.0-x64.msi)

then install autorest and reset the plugins and try again

``` batch
npm install -g autorest
autorest --reset 

```

**Comment by RikkiGibson** [comment]
Feel free to reopen and follow up if this is still an issue @OliverRC

**Comment by vaddimadhavi** [comment]
How was this issue resolved? I am getting the same error. I tried reset and it did not fix it.

**Comment by RikkiGibson** [comment]
@fearthecowboy is there any reason we should not use [`dotnet publish --self-contained`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)

**Comment by fearthecowboy** [comment]
Yes. --self-contained only works for a given platform.  

That's why we have to make the dotnet runtime packages

I did just find out that there is a problem when `npm` is run via `sudo` -- autorest's packages don't like that. 

@vaddimadhavi  -- what version of node are you using, and how are you running `npm`?

**Comment by fearthecowboy** [comment]
Or is that happening on Windows?

**Comment by avjabalpur** [comment]
I got the same error on windows and I have node version  v8.12.0

**Comment by svickers** [comment]
Anybody able to resolve this?  I am having the same issue on the azure pipeline hosted ubuntu agent.

```
   Loading AutoRest core      '/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4387/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4387)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79)
Unable to install/use dotnet framework.
Failed to install or start extension '@microsoft.azure/autorest.csharp' (~2.3.79)
  Error: Package '@microsoft.azure/autorest.csharp' - '2.3.82' failed to install:
  dotnet-2.0.0@1.4.4 postinstall: node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"
Exit status 1
```

**Comment by fearthecowboy** [comment]
@svickers  

hmm. I played around and found a case where I can cause a similar problem on ubuntu...

I think it might be running into a permissions issue; is there something at `$HOME/.net`  ... (maybe done as root?)

nuke the .net folder in the home directiory ( it'll re-create it if necessary) `sudo  rm -rf $HOME/.net` 

Is there anything else happening earlier in the pipeline?

**Comment by nmiodice** [comment]
Thanks @fearthecowboy for your comment as it ultimately led me to a fix locally.

I was able to identify a permissions issue by checkout out a file under `~/.net/`:
```bash
$ cat ~/.net/2.0.0/yarn-error.log
...
Trace:
  Error: EACCES: permission denied, scandir '/home/$USER/.config/yarn/link'
```

Turned out that `/home/$USER/.config` was owned by `root`. The fix was to execute the following:
```bash
$ sudo chown -R $USER:$USER ~/.config
