### ISSUE TITLE
Smoke Test for Windows

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#2723]
@qiaozha and @MaryGao have cached issues where the emitter crashes on Windows, mostly around file system manipulation. It is evident that we need to bring back some validation back to CI to ensure we catch this as soon as possible.

I think running a single smoke test on Windows should give us most of the coverage we need without compromising much on bloating the pipeline, this is my proposal but open to different alternatives:

* Chose a single smoke-test to run the emitter on a Windows environment
   * Just generating and building should good, I don't think checking the git tree for changes offers much value here.
* Add this as a job in the current PR validation pipeline

**Comment by qiaozha** [comment]
@MaryGao could you help take a look at this? thanks
