### ISSUE TITLE
Reduce the size of the generated sdk and the underlying dependencies (ms-rest-js and ms-rest-azure-js)

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#28]
Depends on https://github.com/Azure/autorest.typescript/issues/66.
Depends on https://github.com/Azure/ms-rest-js/issues/97.
> **Estimate: ____(weeks)**
- Investigate if we can find out a way to not have wrapper methods for callback/promise and push all of this to a generic method in the runtime. This generic method gets the method signature of the method that was called, gets the parameters that were actually called on that method, it also gets other information that is required to make a successful request and what it should do upon receiving a response from the pipeline. 
- Another area of improvement is to move away from moment as a dependency. We use it only for validating, [de]serializing Durations. Currently ms-rest-js is around 109 KB in size of which 59KB is just moment. If we can rip out the pieces needed for Duration and create a separate library for that, then we are game. That should considerably bring the sdk size down.

**Comment by XiaoningLiu** [comment]
For the callback/promise, aws-js SDK provides a runtime switch. We can have a look for reference.

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/using-promises.html

**Comment by RikkiGibson** [comment]
It might actually make a measurable difference in bundle size to simplify some validations in generated code to smaller equivalents: e.g. `foo === null || foo === undefined || typeof foo !== 'string'` can be reduced to `typeof foo !== 'string'` (because `typeof null === 'object'` and `typeof undefined === 'undefined'`)
