### ISSUE TITLE
Long running paging

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.typescript#285]
Some operations begin with an LRO followed by paging (i.e. a begin() as well as a next() method must be generated). @jhendrixMSFT may be able to advise on this.

**Comment by jhendrixMSFT** [comment]
See [AppServiceEnvironments_ChangeVnet](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2018-02-01/AppServiceEnvironments.json#L394) for an example of this.
In Go the operation returns a future `AppServiceEnvironmentsChangeVnetFuture`, and that future's result is a page `AppCollectionPage`.
https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2018-02-01/web/appserviceenvironments.go#L48

**Comment by RikkiGibson** [comment]
Find instances using https://github.com/Azure/autorest.typescript/search?q=TODO+coverage

**Comment by joheredi** [comment]
This is already handled by the v6 generator
