### ISSUE TITLE
Unexpected constantPaths is generated in package.json

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2852]
After investigating this issue https://github.com/Azure/azure-sdk-for-js/issues/31229, we found that this is because in package.json, we generate an unexpected constantPaths here: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/mongocluster/arm-mongocluster/package.json#L51-L56

**Comment by MaryGao** [comment]
Relevant to this issue: https://github.com/Azure/azure-sdk-for-js/issues/31229
