### ISSUE TITLE
Unexpected body wrapper are generated in samples in Modular

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2861]
expect sample code:
```
const result = await client.sAPApplicationServerInstances.start(
    "test-rg",
    "X00",
    "app01",
    { startVm: true },
  );
```

current sample code:
```
const result = await client.sAPApplicationServerInstances.start(
    "test-rg",
    "X00",
    "app01",
    { body: { startVm: true } },
  );
```
 
relevant tsp example link:  https://github.com/Azure/azure-rest-api-specs/blob/main/specification/workloads/Workloads.SAPVirtualInstance.Management/examples/2024-09-01/SapVirtualInstances_Start.json#L7

relevant swagger file: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/workloads/resource-manager/Microsoft.Workloads/SAPVirtualInstance/stable/2024-09-01/SAPVirtualInstance.json#L2211-L2217 and https://github.com/Azure/azure-rest-api-specs/blob/main/specification/workloads/resource-manager/Microsoft.Workloads/SAPVirtualInstance/stable/2024-09-01/SAPVirtualInstance.json#L4847-L4858

pr for investigate: https://github.com/Azure/autorest.typescript/pull/2860

**Comment by MaryGao** [comment]
This is not an issue in sample generation but source generation and caused by https://github.com/Azure/autorest.typescript/issues/2827. This could be resolved once that issue is fixed.

**Comment by MaryGao** [comment]
Resolved.
