### ISSUE TITLE
Remove @azure/identity from auto-generated package.json

### ISSUE THREAD

**Issue by mpodwysocki** [Azure/autorest.typescript#2876]
Since we are trying to minimize the number of devDependencies on our projects, we do not need `@azure/identity` since we already have `@azure-tools/test-recorder` and `@azure-tools/test-credential` for ARM packages

**Comment by mpodwysocki** [comment]
Closing for now as they're used in samples-dev

**Comment by qiaozha** [comment]
@mpodwysocki  I notice @maorleger has upgraded the `@azure/identity` dependency to 4.2.1 in this commit https://github.com/Azure/azure-sdk-for-js/commit/2e040fae8a568744d3fde13bf2412eb30a553ffc#diff-d9c5ed339c199478187791eb826ce6f1c6e79775f5990a38f0444db94be06748, but not in the package.json, I wonder if we should upgrade the version in there and update the codegen accordingly if we can't remove it?

**Comment by qiaozha** [comment]
Please ignore the above comment, just notice codegen has already been updated https://github.com/Azure/autorest.typescript/pull/2570
