### ISSUE TITLE
Shall we remove "uglify-js" dependency in codegen package.json generator?

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2910]
I saw that this was removed in sdk repo here: https://github.com/Azure/azure-sdk-for-js/commit/980f3cbb89c8ea956fa8d4011f5af26488c952fb#diff-aaf5b5c571cee741704ea42298f3ba691071402a5fb4312cd21c4dbc1c1c44a5L32

shall we remove it in codegen too?

the script of minify was updated in https://github.com/Azure/autorest.typescript/pull/2895/commits/81d73f531d59d21a3d2c117c8a4cf9fc3b28c070

**Comment by qiaozha** [comment]
@jeremymeng Could you help take a look at this issue? thanks.

**Comment by jeremymeng** [comment]
#2895

**Comment by jeremymeng** [comment]
Yes please, for vendored there's no need to have it in the dev dependency list.
