### ISSUE TITLE
The emitter for JS Modular should work correctly with no tspconfig file

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#2930]
tspconfig is an optional file, it shouldn't be necessary. This is the required scenario for un-branded

Please ensure the following steps would not crash the emitter and generate the correct SDK:

```
tsp init # Chose generic restapi
tsp install
npm install @azure-tools/typespec-ts
tsp compile . --emit @azure-tools/typespec-ts
```

**Comment by qiaozha** [comment]
we need to figure out the default library mode RLC or Modular for unbranding scenario.

**Comment by kazrael2119** [comment]
> tspconfig is an optional file, it shouldn't be necessary. This is the required scenario for un-branded
> 
> Please ensure the following steps would not crash the emitter and generate the correct SDK:
> 
> ```
> tsp init # Chose generic restapi
> tsp install
> npm install @azure-tools/typespec-ts
> tsp compile . --emit @azure-tools/typespec-ts
> ```

this works, and I can build the generated package

**Comment by qiaozha** [comment]
close it as it works. @joheredi  let me know if we should change the default mode for non azure.
