### ISSUE TITLE
Unbranded CodeGen should generate paging operation with Azure Style

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#2932]
TypeSpec already includes the support of Paging operation for unbranded: https://typespec.io/docs/standard-library/pagination/

Based on the current agreement, with `@list`, `@pageItems` and `@nextLink`, we could generate the paging operation similar with Azure style.
Please also ensure related models for paging are added into unbranded core.

**Comment by MaryGao** [comment]
@lirenhe Generating azure-style paging interface should be minor work in unbranded area, but what I may concern is if we don't consider the whole [typespec paging](https://typespec.io/docs/standard-library/pagination/), but only scope to todo case, there may exist breakings in future we have more paging cases. Is this pontential breaking a concern here?

**Comment by lirenhe** [comment]
> [@lirenhe](https://github.com/lirenhe) Generating azure-style paging interface should be minor work in unbranded area, but what I may concern is if we don't consider the whole [typespec paging](https://typespec.io/docs/standard-library/pagination/), but only scope to todo case, there may exist breakings in future we have more paging cases. Is this pontential breaking a concern here?

I suggest you discuss with JS architect about this.  
The unbranded CodeGen will remain in preview even in next March, so I am not too worried about the potential breaking change today.

**Comment by qiaozha** [comment]
blocked by sdk method adoption #2943
