### ISSUE TITLE
Swagger definition referencing common enum results in duplicate typings

### ISSUE THREAD

**Issue by shaunnez** [Azure/autorest.typescript#297]
So nothing to special about what we are doing here. We have an definition of an enum that multiple other definitions utilise via "ref" (e.g. api responses). Swagger file is nice and tidy, however, when utilising autorest typescript I end up getting some weird results. Namely, multiple instances of the exact some enum but with the name incremented. E.g. someEnum{ } ... someEnum1 { }... 
```

"definitions": {
  "fooOrBar": {
    "description": "Shared enum",
    "enum": [
      "foo",
      "bar"
    ],
    "type": "string"
  },
  "someApiResponse": {
    "description": "Some Api Response",
    "type": "object"
    "properties": {
      "foobar": {
        "$ref": "#/definitions/fooOrBar"
      }
    }
  },
  "differentApiResonse": {
    "description": "Another Api Response",
    "type": "object"
    "properties": {
      "foobar": {
        "$ref": "#/definitions/fooOrBar"
      }
    }
  }
}

```
This results in 

```
export enum FooBar {
  Foo = 'foo',
  Bar = 'bar';
}

export enum FooBar1 {
  Foo = 'foo',
  Bar = 'bar'
}

export interface SomeApiResponse {
   foobar?: Foobar
}

export interface DifferentApiResponse {
   foobar?: Foobar1
}
```

As the enum is exactly the same across all the definitions, I'd expect only one enum to be created and shared.

**Comment by RikkiGibson** [comment]
It looks like this is an OpenAPI 3 feature that we don't support just yet.

I'd like to know what happens if you specify [x-ms-enum](https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-enum) on the enum type definition, e.g.
```json
{
  "fooOrBar": {
    "description": "Shared enum",
    "enum": [
      "foo",
      "bar"
    ],
    "type": "string",
    "x-ms-enum": "fooOrBar"
  }
}
```

https://swagger.io/docs/specification/2-0/enums/
https://github.com/Azure/autorest/issues/3003

**Comment by shaunnez** [comment]
x-ms-enum sorted it! Thanks :)

**Comment by RikkiGibson** [comment]
Will consider this resolved. Feel free to follow up if you have any additional questions.

**Comment by joheredi** [comment]
This is fixed in v6
