### ISSUE TITLE
Treat delete as an acceptable property name

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.typescript#298]
Right now we rename operations named `delete` to `deleteMethod` because it's a keyword. It's an allowed name for a property or method, but not a variable or function:
```js
class MyResources {
  delete(resourceId: string) {}; // ok
}
const delete = function (resourceId: string) {}; // nope
```

This name is a bit awkward-looking: `ResourceType.delete()` makes more intuitive sense than `ResourceType.deleteMethod()`. Naming a method `delete` [has precedents in js libraries](https://github.com/axios/axios#axiosdeleteurl-config).

If we ever moved to top-level functions instead of classes per-operation group, `delete` couldn't be the name any more, but that would also be a big breaking change anyway.

If we decide to make this breaking change it should be soon.

**Comment by joheredi** [comment]
This is already handled in v6
