### ISSUE TITLE
Error deserialization for operation groups is broken due to missing mapper export.

### ISSUE THREAD

**Issue by bluecamel** [Azure/autorest.typescript#302]
When an error response definition includes references to other definitions, those referenced definitions are not included in the operation mapper module.

I've attached an example directory that has a simple swagger.yaml and client output.

The command run to create the client was:
```
cd output
autorest --typescript --add-credentials=true --input-file=../swagger.yaml --generate-metadata=true --output-folder=client --package-name="operation-group-error-example" --package-version=0.0.1
```

The output of that command, showing versions:
```
AutoRest code generation utility [version: 2.0.4283; node: v8.11.2]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/root/.autorest/@microsoft.azure_autorest-core@2.0.4289/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4289)
   Installing AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12)
   Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51)
```

In `client/lib/operations/stuffOperations.ts`, `client/lib/models/stuffOperationsMappers.ts` is imported as `Mappers`.  In the `client/lib/models/stuffOperationsMappers.ts` module, you can see that `ErrorResponse` is exported, but `ErrorModel` is not exported.

[operation-group.zip](https://github.com/Azure/autorest.typescript/files/2417027/operation-group.zip)

**Comment by RikkiGibson** [comment]
https://github.com/Azure/autorest.typescript/blob/712f8b8/src/vanilla/Model/MethodGroupTS.cs#L51

Looks like at the time we decided not to collect the model types referenced by an error type and re-export them. I think this is because there were conflicts with models that we embed in the ms-rest-azure-js library which get referenced by the Azure REST API error types.

Defining your own custom property types for error bodies is a totally reasonable use case so I'll try my best to fix this in the near future.

**Comment by bluecamel** [comment]
Thanks a bunch for the response!  I'm working through converting our clients from a modified swagger-codegen setup to autorest, so I'll be posting some similar generation issues that I've been working around.  I'm still working on getting a local environment setup to build autorest.typescript myself, not to mention learning the project, but please let me know how I can help.

**Comment by RikkiGibson** [comment]
@bluecamel please try `autorest --use=@microsoft.azure/autorest.typescript@2.0.541` plus the rest of your usual arguments and see if that resolves the problem.
