### ISSUE TITLE
Remove @resolve and @reject comment annotations

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#304]
Per [jsdoc](http://usejsdoc.org/tags-returns.html) and [one of jsdoc's GitHub issues](https://github.com/jsdoc3/jsdoc/issues/1197), `@resolve` and `@reject` are not supported. The correct thing to do is to just indicate that the return type is `Promise`. We can specify that it is a `Promise<T>`, but we definitely shouldn't be using `@resolve` and `@reject`.

**Comment by RikkiGibson** [comment]
related to #290
