### ISSUE TITLE
Parser chokes on numbers in scientific notation

### ISSUE THREAD

**Issue by runeh** [Azure/autorest.typescript#311]
A field containing scientific notation numbers. For example I consume a document with `"maximum": 90223372036854776e18` , and the json parser complains that it found a string but expected a number.

(Yes, this is a nonsenical number :) )

**Comment by RikkiGibson** [comment]
Is this occurring at generation time or runtime?

**Comment by joheredi** [comment]
This seems to be an issue in M4 impacting v6. Filed https://github.com/Azure/autorest.modelerfour/issues/357
