### ISSUE TITLE
Enum definitions with a single item are not included as referenced.

### ISSUE THREAD

**Issue by bluecamel** [Azure/autorest.typescript#312]
When referencing an enum with only a single value, the associated property is missing from the generated type.

I've attached an example directory that has a simple swagger.yaml and client output.  Any help or known workarounds would be greatly appreciated.

The command run to create the client was:
```
cd output
autorest --typescript --add-credentials=true --input-file=../swagger.yaml --generate-metadata=true --output-folder=client --package-name="enum-single-item" --package-version=0.0.1
```

The output of that command, showing versions:
```
AutoRest code generation utility [version: 2.0.4283; node: v8.9.4]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/bluecamel/.autorest/@microsoft.azure_autorest-core@2.0.4283/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12->2.0.304)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.23->2.1.23)
```

The relevant model definitions:
```
definitions:
  Thing:
    x-ms-enum:
      name: Thing
    type: string
    enum:
      - thinger

  Stuff:
    properties:
      message:
        type: string
      thing:
        $ref: '#/definitions/Thing'
    required:
      - message
      - thing
```

The enum is generated correctly:
```
/**
 * Defines values for Thing.
 * Possible values include: 'thinger'
 * @readonly
 * @enum {string}
 */
export enum Thing {
  Thinger = 'thinger',
}
```

However, the property is missing from the generated interface that references the enum:
```
/**
 * @interface
 * An interface representing Stuff.
 */
export interface Stuff {
  /**
   * @member {string} message
   */
  message: string;
}
```

[enum-single-item.zip](https://github.com/Azure/autorest.typescript/files/2421300/enum-single-item.zip)

**Comment by RikkiGibson** [comment]
I believe this is by design. We interpret an enum with a single case as a constant. The 'thinger' value should be present in the serialized payload.

If you want to force this to be a parameter you may want to try using [x-ms-enum](https://github.com/Azure/autorest/tree/master/docs/extensions#x-ms-enum)

**Comment by bluecamel** [comment]
I must be missing something.  The `Stuff` interface doesn't have the `thing` property, as defined, so how could serialization work?  Regardless, for type safety, we need the property to be on the interface.

Further, what's the significance of the distinction between an enum with one possible value and an enum with two possible values?  From my perspective, it's still meant to restrict input to a set of values, but the set is simply smaller.

I've worked around this for now by adding a bogus value to the enum before generation and removing it after generation.

**Comment by bluecamel** [comment]
Also, if you look at my example, I'm setting `x-ms-enum` already.

**Comment by RikkiGibson** [comment]
I'll consider this resolved as by-design. Please follow up if you have any additional questions.
