### ISSUE TITLE
Inline model definitions with nested allOf references are generated with missing/incorrect properties.

### ISSUE THREAD

**Issue by bluecamel** [Azure/autorest.typescript#313]
I've attached an example directory that has a simple swagger.yaml and client output.

The command run to create the client was:
```
cd output
autorest --typescript --add-credentials=true --input-file=../swagger.yaml --generate-metadata=true --output-folder=client --package-name="nested-allof" --package-version=0.0.1
```

The output of that command, showing versions:
```
AutoRest code generation utility [version: 2.0.4283; node: v8.9.4]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/bluecamel/.autorest/@microsoft.azure_autorest-core@2.0.4283/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12->2.0.304)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.23->2.1.23)
```

Given the following nested model definitions:
```
definitions:
  ThingBaseFields:
    properties:
      thingBaseFieldA:
        type: string
      thingBaseFieldB:
        type: string
    required:
      - thingBaseFieldA
      - thingBaseFieldB

  ThingFields:
    allOf: 
      - $ref: '#/definitions/ThingBaseFields'
      - type: object
        properties:
          thingFieldA:
            type: string
          thingFieldB:
            type: string
        required:
          - thingFieldA
          - thingFieldB

  OtherThingBaseFields:
    properties:
      otherThingBaseFieldA:
        type: string
      otherThingBaseFieldB:
        type: string
    required:
      - otherThingBaseFieldA
      - otherThingBaseFieldB

  AllThings:
    allOf:
      - $ref: '#/definitions/ThingFields'
      - $ref: '#/definitions/OtherThingBaseFields'
```

First, the generated interface for `ThingFields` correctly extends `ThingBaseFields`, however the properties from the inline model (`thingFieldA` and `thingFieldB`) are optional instead of required, as specified:
```
/**
 * @interface
 * An interface representing ThingFields.
 * @extends ThingBaseFields
 */
export interface ThingFields extends ThingBaseFields {
  /**
   * @member {string} [thingFieldA]
   */
  thingFieldA?: string;
  /**
   * @member {string} [thingFieldB]
   */
  thingFieldB?: string;
}
```

Further, the generated interface for `AllThings` includes the properties from the inline model in `ThingFields` (though, again, optional instead of required), but it's missing the properties (`thingBaseFieldA` and `thingBaseFieldB`) from `ThingBaseFields`, which `ThingFields` extends:
```
/**
 * @interface
 * An interface representing AllThings.
 */
export interface AllThings {
  /**
   * @member {string} [thingFieldA]
   */
  thingFieldA?: string;
  /**
   * @member {string} [thingFieldB]
   */
  thingFieldB?: string;
  /**
   * @member {string} otherThingBaseFieldA
   */
  otherThingBaseFieldA: string;
  /**
   * @member {string} otherThingBaseFieldB
   */
  otherThingBaseFieldB: string;
}
```

I'm confused by some ambiguity in the Swagger 2.0 spec that I think is the root of this problem, as far as whether `allOf` should be treated as multi-inheritance or not.  The way autorest.typescript generates interface extensions leads me to believe that the autorest stance favors inheritance, but is not entirely consistent.  For us, true multi-inheritance in this case would be ideal, and should be possible with Typescript, but I suspect that others would disagree.

Regardless, the workaround for this is fairly simple: get rid of the inline model definitions and include it as another reference via `allOf`.

[nested-allof.zip](https://github.com/Azure/autorest.typescript/files/2421437/nested-allof.zip)

**Comment by joheredi** [comment]
This seems to be fixed in v6 here's the output

```typescript
export interface ThingBaseFields {
  thingBaseFieldA: string;
  thingBaseFieldB: string;
}

export interface OtherThingBaseFields {
  otherThingBaseFieldA: string;
  otherThingBaseFieldB: string;
}

export type ThingFields = ThingBaseFields & {
  thingFieldA: string;
  thingFieldB: string;
};

export type AllThings = ThingFields & OtherThingBaseFields & {};
```

**Comment by sarajang** [comment]
> This seems to be fixed in v6 here's the output
> 
> ```ts
> export interface ThingBaseFields {
>   thingBaseFieldA: string;
>   thingBaseFieldB: string;
> }
> 
> export interface OtherThingBaseFields {
>   otherThingBaseFieldA: string;
>   otherThingBaseFieldB: string;
> }
> 
> export type ThingFields = ThingBaseFields & {
>   thingFieldA: string;
>   thingFieldB: string;
> };
> 
> export type AllThings = ThingFields & OtherThingBaseFields & {};
> ```

@joheredi can you please explain what v6 is here?
