### ISSUE TITLE
Response models generated as any

### ISSUE THREAD

**Issue by mazhlekov** [Azure/autorest.typescript#314]
## Using the latest version of @microsoft.azure/autorest.typescript
![image](https://user-images.githubusercontent.com/3295388/46132877-eed1e600-c247-11e8-99b8-7201b6b024a9.png)
![image](https://user-images.githubusercontent.com/3295388/46132902-fa251180-c247-11e8-9fe0-e6c0b3a1354e.png)
![image](https://user-images.githubusercontent.com/3295388/46132927-04471000-c248-11e8-9d39-f828ea8e2888.png)
No types...

### Workaround - removing schema definition for response types 400 and 500
![image](https://user-images.githubusercontent.com/3295388/46133068-512ae680-c248-11e8-805a-2c5c96ad9d65.png)
![image](https://user-images.githubusercontent.com/3295388/46133207-9e0ebd00-c248-11e8-8038-625bbc2375ed.png)
Correct generation of types.

## Using a preview version of @microsoft.azure/autorest.typescript
![image](https://user-images.githubusercontent.com/3295388/46133312-dca47780-c248-11e8-96f6-8e675a25c323.png)
![image](https://user-images.githubusercontent.com/3295388/46133421-18d7d800-c249-11e8-9108-a212f05f70c9.png)
![image](https://user-images.githubusercontent.com/3295388/46133406-0e1d4300-c249-11e8-975f-026924656e2f.png)
![image](https://user-images.githubusercontent.com/3295388/46133442-3016c580-c249-11e8-99b8-082f993e6a76.png)
No types...

### Again the same workaround - removing schema definition for response types 400 and 500
![image](https://user-images.githubusercontent.com/3295388/46133499-589ebf80-c249-11e8-9fc2-a9b6e6e04760.png)
![image](https://user-images.githubusercontent.com/3295388/46133812-1033d180-c24a-11e8-9493-b75e789bfab2.png)
![image](https://user-images.githubusercontent.com/3295388/46133508-5fc5cd80-c249-11e8-9edc-220f4c58777d.png)
Correct generation of types.

We must have schema definition for 400 and 500. The correct implementation should use the model from response type 200. How can I achieve this?

**Comment by RikkiGibson** [comment]
The AutoRest modeler is thinking in C# terms and trying to find a common supertype for the various response schemas.

I'd like to know if the modeler at least gives you the return type for the 200 response if you add `x-ms-error-response` to the 400 and 500 response definitions. See https://github.com/Azure/autorest/blob/master/docs/proposals/generator-specific-settings/improved-exceptions.md

The generator may struggle to give you static type information for the different kinds of error responses, but we should be able to deserialize error payloads based on the schema you provide.

**Comment by mazhlekov** [comment]
Thank you very much, Rikki. x-ms-error-response fixed the issue.

**Comment by RikkiGibson** [comment]
Glad to hear. Please reopen if you have any follow-up questions about this.
