### ISSUE TITLE
**Add support to batch http requests**

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#34]
**Estimate: __ weeks**

The browser has a notion of worker queue that allows around 7-10 requests to be made at any given time. This can severely limit the number of requests that can be made.
A workaround is to BATCH HTTP requests.
Today Azure only supports batching HTTP GET requests. ARM provides a POST API  
`https://management.azure.com/batch?api-version=2015-11-01` where the user can batch upto 20 GET requests as a payload(request body) and ARM sends a response containing all of them in one response body.

We need to implement a simple [debouncer](https://stackoverflow.com/questions/7071472/javascript-timeout-when-no-actions-from-user-for-specified-time) that waits for 100ms or 20 GET requests (whichever happens first) and fires off a batch of calls. 
Example: [private repo](https://msazure.visualstudio.com/One/IaaSExp/_git/AzureUX-portalfx?path=%2Fsrc%2FSDK%2FFramework.Client%2FTypeScript%2FFx%2FAjax.ts&version=GBsimonp%2Fcloudbuild) to get an idea.

**Comment by RikkiGibson** [comment]
The question was raised of whether the 100ms debouncing latency on every GET could negatively affect the user experience overall. **It'll be best to start simple on this** but it might wind up being worth it down the line to track and check how many requests are currently in-flight before deciding to either debounce or simply send the request through.

**Comment by daschult** [comment]
Portal may be able to implement this themselves. Let's check and make sure that they got this working before we close this issue.

**Comment by daschult** [comment]
I verified that Portal is planning on doing this in their own HttpClient, so we're off the hook.
