### ISSUE TITLE
Create MarkdownBuilder

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#341]
This would help with generating our README.md files.

**Comment by billytrend** [comment]
Randomly came across this issue: not sure if you'd find this useful: https://github.com/ts-common/azure-openapi-markdown. We use it in portal for readme manipulation and serialisation. Lmk if you want to chat about it!

**Comment by daschult** [comment]
Thanks for thinking of us, but this isn't quite what we need. We need a way to generate Markdown files from our C#-based generator. The package you've linked is written in TypeScript, so it won't quite work for our needs.

**Comment by billytrend** [comment]
ohh fair, also yeah you're probably just creating them from scratch ? We needed to parse -> manipulate -> serialise which was a bit more involved
