### ISSUE TITLE
Allow LROs in vanilla scenarios

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#348]
The OpenAPI Portal wants to use generated LRO methods, but they don't necessarily want to specify that they're generating an azure client (other customers have expressed a similar view). We should have a way to support LRO methods within our vanilla scenario too.

**Comment by joheredi** [comment]
We may want to explore this at some point as right now LRO is mostly supported for ARM. When working on this, we should push for a well defined common spec for LROs

**Comment by joheredi** [comment]
LRO operations that follow [Microsoft Rest API guildelines](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#13-long-running-operations) should be now supported by the Typescript generator
