### ISSUE TITLE
**Add support for enabling x-ms-client-session-id as a header parameter.**

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#35]
**Estimate: 1 day**
There should be an optional parameter in the client constructor to accept a value for this. If provided then this parameter should be supplied as a request header in all the requests.

Description of the parameter: Used to track the client activity in a given session.

**Comment by XiaoningLiu** [comment]
Hey, a related question. Besides this header, how does current generated js library track the usage data in browsers?

As far as I know, user-agent in browsers is controlled by browsers, and we cannot track library version by this header.

**Comment by RikkiGibson** [comment]
Ah, sorry we missed this comment from way back. We have no scheme for tracking browser usage but we're considering coming up with some extension header (x-ms-rest-version?) to send by default which we can then query for in the standard ARM telemetry.

**Comment by RikkiGibson** [comment]
Regarding the original issue: this definitely smells like a "provide your own pipeline and you can specify whatever headers you want" issue. No work for us to do on our end.
