### ISSUE TITLE
Add tslint rule "no-return-await": true in the generated tslint.json and also in any other place where it is being used manually

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest.typescript#358]
Take a look at the tslint rule [here](https://palantir.github.io/tslint/rules/no-return-await). We should make sure we are not using this pattern in our code.

**Comment by joheredi** [comment]
We should choose which eslint rules we'd like to add to the new version of the generator. The one described above sounds reasonable

**Comment by ramya-rao-a** [comment]
Closing in favor of #1210
