### ISSUE TITLE
**Figure out how to package light clients per resource type per api-version.**

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#36]
**Estimate: __ weeks.**

Networking minified client is around 1MB. That is huge. It would be nice if we can slice the generated client per resource type per api-version. Thus the customer can pick and choose which package they want to load.

**Comment by RikkiGibson** [comment]
The API version thing is more or less an AutoRest config question that Portal maybe should answer for themselves, but the per resource type thing is mostly solved by the a-la-carte operation groups work which is already complete. Therefore I'll close this one.
