### ISSUE TITLE
Generated samples in README.md should instantiate the client by reflecting on the parameters in the constructor

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest.typescript#369]
Today the samples in README.md assume credentials and subscriptionId are the two required parameters for any generated TS Client. It is true for most of the clients generated for Azure. However it is not true for generic TS generator and some dataplane clients like Azure Graph where the second parameter is `tenantId` and **not** `subscriptionId`.

A proper way to do this would be to reflect on the parameters provided to the constructor. The goal is to generate a correct minimal sample. Hence we need to focus only on the required parameters provided to the constructor and use their names and types in proper order to instantiate the client.

Please take a look at [this commit](https://github.com/Azure/azure-sdk-for-js/commit/12ceccf1adb8e31d2861d8b851b10b7d516e2b0b#diff-0b7b5059f3c5825efc4addb4cde450f1) for the manual changes made to the graph sdk to get an idea about the problem.

**Comment by joheredi** [comment]
Consolidating README related issues in https://github.com/Azure/autorest.typescript/issues/594
