### ISSUE TITLE
Fix TypeScript CI failures

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#37]

**Comment by RikkiGibson** [comment]
I'm leaning toward trying to make as many things possible run through ts-node as I've often been second-guessing whether I built the particular TypeScript files in question after editing them. We'll see if this winds up being a good value-for-time though.

**Comment by daschult** [comment]
Maybe time-box it to a single day. I agree that could have good benefits, though.

**Comment by RikkiGibson** [comment]
**Estimating** 2 (more) days.

**Comment by RikkiGibson** [comment]
Resolved by #41
