### ISSUE TITLE
Fix encoding of array query parameters

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#380]
See https://github.com/Azure/autorest.nodejs/issues/61.

**Comment by kpajdzik** [comment]
I think it's all good in TS world - https://github.com/Azure/ms-rest-js/blob/master/lib/serviceClient.ts#L217. @daschult do you agree?

**Comment by daschult** [comment]
Yes, I agree. Using the URLBuilder really made this a lot easier. I'll mark this as closed.
