### ISSUE TITLE
package won't generate

### ISSUE THREAD

**Issue by xuke444** [Azure/autorest.typescript#382]
package would not generate at all for following 2 swaggers

return error
_FATAL: System.NullReferenceException: Object reference not set to an instance of an object.
build.js:132
at AutoRest.TypeScript.Model.MethodTS.get_OptionsParameterModelType() in /home/vsts/work/1/s/src/vanilla/Model/MethodTS.cs:line 135_

[swagger.zip](https://github.com/Azure/autorest.typescript/files/2590817/swagger.zip)

**Comment by joheredi** [comment]
This issue seems to be resolved in the new version of the generator
