### ISSUE TITLE
from form

### ISSUE THREAD

**Issue by xuke444** [Azure/autorest.typescript#383]
form data isn't read correctly.
          {
            "name": "json_definition",
            "in": "formData",
            "required": false,
            "type": "string"
          },
SDK send it as file vs it should be a form parameter
![imgo](https://user-images.githubusercontent.com/40614413/48646841-ddcb6880-e99e-11e8-9a5d-cb77b5e56725.jpg)

![imgo](https://user-images.githubusercontent.com/40614413/48646856-e91e9400-e99e-11e8-82e4-452f1e287675.jpg)

full swagger is here.
[swagger.json.txt](https://github.com/Azure/autorest.typescript/files/2590835/swagger.json.txt)

**Comment by joheredi** [comment]
We need to verify if v6 also presents this issue

**Comment by sarangan12** [comment]
We already have a test case that covers this scenario. Closing this issue
