### ISSUE TITLE
return string

### ISSUE THREAD

**Issue by xuke444** [Azure/autorest.typescript#384]
string return type is not populating.
In sdk call, if a api return plain string, I guess it should be populated to body prop, however it's not, body is always undefined.

        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "format": "uuid",
              "type": "string"
            }
          }
here is full swagger.
[swagger.json.txt](https://github.com/Azure/autorest.typescript/files/2590840/swagger.json.txt)

**Comment by joheredi** [comment]
This issue may be fixed with the new generator. @xuke444 would you mind generating your swagger with the new version and letting me know if it solves the problem?

[Using the new generator](https://github.com/Azure/autorest.typescript/wiki/Generating-with-autorest-for-Typescript-v6)
