### ISSUE TITLE
unsafe header

### ISSUE THREAD

**Issue by KeMicrosoft** [Azure/autorest.typescript#389]
I am starting to get following error in console for all requests I send

Refused to set unsafe header "user-agent"

./node_modules/@azure/ms-rest-js/es/lib/xhrHttpClient.js.XhrHttpClient.sendRequest | @ | xhrHttpClient.js:63
-- | -- | --
  | (anonymous) | @ | deserializationPolicy.js:39
  | step | @ | tslib.es6.js:97
  | (anonymous) | @ | tslib.es6.js:78
  | (anonymous) | @ | tslib.es6.js:71
  | __awaiter | @ | tslib.es6.js:67
  | ./node_modules/@azure/ms-rest-js/es/lib/policies/deserializationPolicy.js.DeserializationPolicy.sendRequest | @ | deserializationPolicy.js:36
  | ./node_modules/@azure/ms-rest-js/es/lib/policies/systemErrorRetryPolicy.js.SystemErrorRetryPolicy.sendRequest | @ | systemErrorRetryPolicy.js:39
  | ./node_modules/@azure/ms-rest-js/es/lib/policies/exponentialRetryPolicy.js.ExponentialRetryPolicy.sendRequest | @ | exponentialRetryPolicy.js:44
  | ./node_modules/@azure/ms-rest-js/es/lib/policies/rpRegistrationPolicy.js.RPRegistrationPolicy.sendRequest | @ | rpRegistrationPolicy.js:22
  | ./node_modules/@azure/ms-rest-js/es/lib/policies/redirectPolicy.js.RedirectPolicy.sendRequest | @ | redirectPolicy.js:24
  | ./node_modules/@azure/ms-rest-js/es/lib/policies/userAgentPolicy.js.UserAgentPolicy.sendRequest | @ | userAgentPolicy.js:50
  | (anonymous) | @ | signingPolicy.js:24
  | Promise.then (async) |   |  
  | ./node_modules/@azure/ms-rest-js/es/lib/policies/signingPolicy.js.SigningPolicy.sendRequest | @ | signingPolicy.js:24
  | ./node_modules/@azure/ms-rest-js/es/lib/policies/generateClientRequestIdPolicy.js.GenerateClientRequestIdPolicy.sendRequest | @ | generateClientRequestIdPolicy.js:25
  | ./node_modules/@azure/ms-rest-js/es/lib/serviceClient.js.ServiceClient.sendRequest | @ | serviceClient.js:72
  | ./node_modules/@azure/ms-rest-js/es/lib/serviceClient.js.ServiceClient.sendOperationRequest | @ | serviceClient.js:194
  | ./node_modules/@azure/arm-storage/esm/operations/storageAccounts.js.StorageAccounts.list | @ | storageAccounts.js:70

**Comment by amarzavery** [comment]
This should not have happened. With the new set of changes, instead of updating the user-agent header, separate set of headers (x-ms-command-name) should have been updated in the browser.
@kpajdzik - Can you take a look at this issue?
