### ISSUE TITLE
Option to generate enum definition

### ISSUE THREAD

**Issue by stevegreatrex** [Azure/autorest.typescript#391]
Since https://github.com/Azure/autorest.typescript/issues/357 was merged it would be useful to optionally output the enum definitions as well as the union type.

e.g.
```typescript
//current
type SomeEnum = 'one' | 'two' | 'three';

//proposed addition (with a better name)
enum SomeEnumOptions = {
  one = 'one',
  two = 'two',
  three = 'three'
}
```
Is this something that you would consider (pending some decisions about names etc)?  If so I will look into what changes are needed.

**Comment by daschult** [comment]
That's definitely something we could do. We chose to switch from enums to just using string unions because we couldn't think of a reason to not do it. Is there a scenario where enums are better for you than a string union?

**Comment by stevegreatrex** [comment]
Generally speaking I like the discoverability of enums, even if the difference is marginal with TS intellisense.

It's also useful to be able to iterate over available options which (I think?) isn't possible with the string union

**Comment by daschult** [comment]
That's very true that you can't iterate over string union options. Okay, we'll look into adding this feature back to the generator.
Is this the type of scenario where you'd want to just change a couple of types to enums but leave others as a string union, or do you think it's an all or nothing scenario for you?

**Comment by XiaoningLiu** [comment]
@daschult We need enum type for Azure Storage SDKs to avoid breaking changes, please bring back this.

**Comment by daschult** [comment]
https://github.com/Azure/autorest.typescript/pull/413 adds the ability to output enum types again by using the `--enum-types` command line argument.
