### ISSUE TITLE
YAML merging does not work

### ISSUE THREAD

**Issue by Hardtack** [Azure/autorest.typescript#412]
There is a syntax `<<` for merging objects in [YAML specification](https://yaml.org/type/merge.html).
But when I try to use this syntax, autorest just emits the errors like following

```
ERROR: Schema violation: Additional properties not allowed: <<
```

I don't know whether it is a standard syntax of YAML or not. But there is a mention about this syntax in [Swagger documentation](https://swagger.io/docs/specification/2-0/enums/). So I think this feature is pretty necessary.

It would be very helpful if you implement this feature :)

Thanks,

**Comment by joheredi** [comment]
@daviwil do you know if M4 supports this?

**Comment by sarangan12** [comment]
@timotheeguerin Can you please take a look into this and let me know if M4 supports this scenario?

**Comment by timotheeguerin** [comment]
Yeah right now this doesn't work. The library doing the yaml parsing doesn't support it.

**Comment by timotheeguerin** [comment]
Added support for it https://github.com/Azure/autorest/pull/4221

**Comment by ramya-rao-a** [comment]
@sarangan12 Is there anything pending to do in the autorest.typescript project to consume the changes from autorest?

**Comment by sarangan12** [comment]
Nope. This issue no longer exists. Closing this issue
