### ISSUE TITLE
Specify typeRoots field in tsconfig

### ISSUE THREAD

**Issue by Hardtack** [Azure/autorest.typescript#417]
I'm trying to build my openapi client on subdirectory under my project.

And the directory structure is like following

```
my-project - This is my root project
├── @company
│    └── openapi    - This is my generated openapi client package
│       ├── LICENSE.txt
│       ├── README.md
│       ├── api.yaml
│       ├── lib
│       ├── node_modules
│       ├── package.json
│       ├── rollup.config.js
│       └── tsconfig.json
├── tsconfig.json
├── node_modules
└── package.json
        
```

There are some typing issues between external libraries that are used in `my-project`, So I'm ignoring them by setting `skipLibCheck` to `true`, and so it's not a problem.

But when I try to build `@company/openapi` package, it try to check type of libraries in `my-project/node_modules`, not only `my-project/@company/openapi/node_modules` so it makes errors.

I tried to figure out why _tsc_ try to check the type of parent's `node_modules` and found that it is an [intended feature](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) and we have to specify the `compilerOptions.typeRoots` field to prevent this feature.

All types we really need check are types under `my-project/@company/openapi/` so generated tsconfig should specify `typeRoots` to be `./node_modules/@types` I think.

Thanks,

**Comment by joheredi** [comment]
Hi @Hardtack thanks for reporting this, I'd like to learn more about your scenario. What errors are you getting?

**Comment by joheredi** [comment]
Closing since we haven't received additional information. Feel free to re-open with additional info
