### ISSUE TITLE
Rethink mapper organization

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.typescript#421]
We've been thinking about our mapper organization lately. Our current approach is to have a single mappers.ts file with all of the mappers for a given service. We then have operationGroupMappers.ts that imports and exports the mappers from the original mappers.ts file that pertain to that operationGroup. A couple of developers from the Azure Portal suggested that we have individual files for each mapper. Dependencies would be handled by importing from the mappers that each mapper depends on. Then each operationGroup would import from the individual mapper files that it needs.

**Comment by kpajdzik** [comment]
@daschult Is that still needed?
