### ISSUE TITLE
How to reduce bundle size and remove functions ?

### ISSUE THREAD

**Issue by bricejar** [Azure/autorest.typescript#423]
Hello,

What is the proper way to reduce the generated library bundle size ? For example, what is a safe way to remove the endpoints one does not need in a particular application ?

**Comment by joheredi** [comment]
Hi @bricejar, the safest way to remove endpoints would be to remove the them and definitions from the SWAGGER file itself and incrementally add the endpoints as you need them.

**Comment by bricejar** [comment]
Thank you !

**Comment by ffMathy** [comment]
@joheredi I feel like the library should be tree-shakeable though, so that it'll work automatically.
