### ISSUE TITLE
Why are Client Model Class Property names created with the first character lower case?

### ISSUE THREAD

**Issue by abhishekgoenka** [Azure/autorest.typescript#430]
I am generating typescript clients using AutoRest. All my properties in model->index.ts are converted to lower case(only first character). Is there any switch to ignore this behavior?

**Comment by Amareis** [comment]
+1, looks ugly
![image](https://user-images.githubusercontent.com/4806617/54084384-af103e00-4351-11e9-962a-5d36fc129145.png)

**Comment by bricejar** [comment]
https://en.wikipedia.org/wiki/Camel_case 

camelCase is a javascript naming convention.

**Comment by RikkiGibson** [comment]
related to #236

**Comment by joheredi** [comment]
This is still an issue in v6, and I think there may be 2 parts:

1) Our rename logic blindly tries to camel case, however Acronyms should be left unchanged
2) There may be some times where users may want to disable re-naming

We'll take this fix in the new generator version

**Comment by sarangan12** [comment]
@joheredi Do you think if a flag is good for this approach? I think we could have names in the same swagger which should be normalized (as is now) and names that should not be normalized (like JWT...) I think the right candidate should be an extension on AutoRest level like "x-ms-normalize-name". Any thoughts???

**Comment by sarangan12** [comment]
I have verified that this issue has been resolved with PT #1250. Closing this issue
