### ISSUE TITLE
HttpOperationResponse.bodyAsJson not available

### ISSUE THREAD

**Issue by christophla** [Azure/autorest.typescript#44]
The generated code references `msRest.HttpOperationResponse.bodyAsJson`, which is not available in the latest version of `ms-rest-js`.

Instead, it appears that it should be referencing:

```
/**
 * The response body as parsed JSON or XML
 */
parsedBody?: {
        [key: string]: any;
    } | Array<any> | string | number | boolean | null | void;
```

**Comment by RikkiGibson** [comment]
Hi @christophla. It looks like I needed to tag a recent release with `@latest`. Please try installing`@microsoft.azure/autorest.typescript@latest` again.

**Comment by RikkiGibson** [comment]
Please reopen if this didn't resolve the problem. Thanks for the heads up about it.
