### ISSUE TITLE
Add option for entry point of the SDK to be a index.ts which export the models and the api

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/autorest.typescript#444]
It would be nice to be able to use the SDK this way
```ts
import {MyModel, MySDK} from "my-sdk"

const sdk = new MySDK();
const model: MyModel = await sdk.getModel()

```

instead of 
```ts
import {Models, MySDK} from "my-sdk"


const sdk = new MySDK();
const model: Models.MyModel = await sdk.getModel()
```
or having to import inside the esm folder
```ts
import { MySDK} from "my-sdk"
import { MyModel } from "my-sdk/esm/models"


const sdk = new MySDK();
const model: MyModel = await sdk.getModel()
```

Just having a `index.ts` generated automaticallly which just does this would solve this problem
```
export * from "./models"
export * from "./mySDK"
```

**Comment by RikkiGibson** [comment]
I think this introduces name conflict issues when a model has the same name as an operation group. Since the Azure APIs tend to use operation groups to group the CRUD for a certain type of resource together this is pretty common.

Any way this could be mitigated?

**Comment by joheredi** [comment]
V6 generator now exposes models this way, please give it a try and let me know if the experience is improved

[Generating with autorest for Typescript v6](https://github.com/Azure/autorest.typescript/wiki/Generating-with-autorest-for-Typescript-v6)
