### ISSUE TITLE
Http Interceptor 

### ISSUE THREAD

**Issue by elielia** [Azure/autorest.typescript#449]
Hi,

I am trying to add a Http Interceptor to my Angular app that will intercept any 401 response. Seems like the generated AutoRest client is using its own HttpClient and therefore this is not possible via the regular way. 
Is there any way to add some custom interceptors to AutoRest?

Thanks

**Comment by amarzavery** [comment]
@elielia - The HttpClient defined in [@azure/ms-rest-js](https://www.npmjs.com/package/@azure/ms-rest-js) has a request pipeline. You can add request policies to the pipeline. These policies will be executed before the request (if applicable) is sent on the wire and after the response is received (if applicable). You can provide request policies by providing an option [requestPolicyFactories](https://github.com/Azure/ms-rest-js/blob/master/lib/serviceClient.ts#L52) to the ServiceClient (Base class of the Autorest generated client from your swagger spec).

You can also provide your own `HttpClient` to the `ServiceClient` as defined [here](https://github.com/Azure/ms-rest-js/blob/master/lib/serviceClient.ts#L56) as long as it satisfies the interface of the [HttpClient](https://github.com/Azure/ms-rest-js/blob/master/lib/httpClient.ts#L9). i.e. it has a [`sendRequest(httpRequest: WebResource): Promise<HttpOperationResponse>;`](https://github.com/Azure/ms-rest-js/blob/master/lib/policies/requestPolicy.ts#L17).

Hope this helps.

**Comment by amarzavery** [comment]
You can create your own HttpClient that implements the [HttpClient interface](https://github.com/Azure/ms-rest-js/blob/master/lib/httpClient.ts#L9). Your HttpClient will be a wrapper on top of Angular HttpClient. The `sendRequest(httpRequest: WebResource): Promise<HttpOperationResponse>` internally calls Angular's [HttpClient.request()](https://angular.io/api/common/http/HttpClient#request).

**Comment by elielia** [comment]
Thanks a lot, I'll give it a go.

**Comment by victor-rocha** [comment]
Hey guys, I think I have pretty much the same need. Basically I need to redirect the user to another url (an external one) in case the response is a 401 (which in my case means that the session is expired). 
Any thoughts?

**Comment by elielia** [comment]
Eventually I provided an **HttpClient** implementation to the **ServiceClient**. It was too difficult for me to implement one from scratch, so I copied one implementation they provide and changed stuff in it. This is my code:

`/**
 * A HttpClient implementation that uses XMLHttpRequest to send HTTP requests.
 */
import {
  HttpClient,
  HttpHeaders,
  HttpOperationResponse,
  RestError,
  TransferProgressEvent,
  WebResource
} from '@azure/ms-rest-js';
import { Router } from '@angular/router';
import { AuthenticationService } from '@app/core';

export class InterceptorHttpClient implements HttpClient {
  router: Router;
  authService: AuthenticationService;

  constructor(router: Router, authService: AuthenticationService) {
    this.router = router;
    this.authService = authService;
  }

  public sendRequest(request: WebResource): Promise<HttpOperationResponse> {
    const xhr = new XMLHttpRequest();

    if (request.proxySettings) {
      throw new Error('HTTP proxy is not supported in browser environment');
    }

    const abortSignal = request.abortSignal;
    if (abortSignal) {
      const listener = () => {
        xhr.abort();
      };
      abortSignal.addEventListener('abort', listener);
      xhr.addEventListener('readystatechange', () => {
        if (xhr.readyState === XMLHttpRequest.DONE) {
          abortSignal.removeEventListener('abort', listener);
        }
      });
    }

    addProgressListener(xhr.upload, request.onUploadProgress);
    addProgressListener(xhr, request.onDownloadProgress);

    if (request.formData) {
      const formData = request.formData;
      const requestForm = new FormData();
      const appendFormValue = (key: string, value: any) => {
        if (value && value.hasOwnProperty('value') && value.hasOwnProperty('options')) {
          requestForm.append(key, value.value, value.options);
        } else {
          requestForm.append(key, value);
        }
      };
      for (const formKey of Object.keys(formData)) {
        const formValue = formData[formKey];
        if (Array.isArray(formValue)) {
          for (let j = 0; j < formValue.length; j++) {
            appendFormValue(formKey, formValue[j]);
          }
        } else {
          appendFormValue(formKey, formValue);
        }
      }

      request.body = requestForm;
      request.formData = undefined;
      const contentType = request.headers.get('Content-Type');
      if (contentType && contentType.indexOf('multipart/form-data') !== -1) {
        // browser will automatically apply a suitable content-type header
        request.headers.remove('Content-Type');
      }
    }

    xhr.open(request.method, request.url);
    xhr.timeout = request.timeout;
    xhr.withCredentials = request.withCredentials;
    for (const header of request.headers.headersArray()) {
      xhr.setRequestHeader(header.name, header.value);
    }
    xhr.responseType = request.streamResponseBody ? 'blob' : 'text';

    let that = this;

    xhr.onreadystatechange = function() {
      if (xhr.status == 401) {
        debugger;
        that.authService.logout().subscribe(() => {
          that.router.navigate(['/login']);
        });
      }
    };
    // tslint:disable-next-line:no-null-keyword
    xhr.send(request.body === undefined ? null : request.body);

    if (request.streamResponseBody) {
      return new Promise((resolve, reject) => {
        xhr.addEventListener('readystatechange', () => {
          // Resolve as soon as headers are loaded
          if (xhr.readyState === XMLHttpRequest.HEADERS_RECEIVED) {
            const blobBody = new Promise<Blob>((resolve, reject) => {
              xhr.addEventListener('load', () => {
                resolve(xhr.response);
              });
              rejectOnTerminalEvent(request, xhr, reject);
            });
            resolve({
              request,
              status: xhr.status,
              headers: parseHeaders(xhr),
              blobBody
            });
          }
        });
        rejectOnTerminalEvent(request, xhr, reject);
      });
    } else {
      return new Promise(function(resolve, reject) {
        xhr.addEventListener('load', () =>
          resolve({
            request,
            status: xhr.status,
            headers: parseHeaders(xhr),
            bodyAsText: xhr.responseText
          })
        );
        rejectOnTerminalEvent(request, xhr, reject);
      });
    }
  }
}

function addProgressListener(xhr: XMLHttpRequestEventTarget, listener?: (progress: TransferProgressEvent) => void) {
  if (listener) {
    xhr.addEventListener('progress', rawEvent =>
      listener({
        loadedBytes: rawEvent.loaded
      })
    );
  }
}

// exported locally for testing
export function parseHeaders(xhr: XMLHttpRequest) {
  const responseHeaders = new HttpHeaders();
  const headerLines = xhr
    .getAllResponseHeaders()
    .trim()
    .split(/[\r\n]+/);
  for (const line of headerLines) {
    const index = line.indexOf(':');
    const headerName = line.slice(0, index);
    const headerValue = line.slice(index + 2);
    responseHeaders.set(headerName, headerValue);
  }
  return responseHeaders;
}

function rejectOnTerminalEvent(request: WebResource, xhr: XMLHttpRequest, reject: (err: any) => void) {
  xhr.addEventListener('error', () =>
    reject(new RestError(`Failed to send request to ${request.url}`, RestError.REQUEST_SEND_ERROR, undefined, request))
  );
  xhr.addEventListener('abort', () =>
    reject(new RestError('The request was aborted', RestError.REQUEST_ABORTED_ERROR, undefined, request))
  );
  xhr.addEventListener('timeout', () =>
    reject(new RestError(`timeout of ${xhr.timeout}ms exceeded`, RestError.REQUEST_SEND_ERROR, undefined, request))
  );
}
`

You can see that in case of 401, I logout the user and redirect to login page.
Hope it helps

**Comment by joheredi** [comment]
Here's an example of how do an intercept policy

```typescript
const interceptPolicy = {
  create: (
    nextPolicy: RequestPolicy,
    options: RequestPolicyOptionsLike
  ): RequestPolicy => {
    return {
      sendRequest: async (
        httpRequest: WebResourceLike
      ): Promise<HttpOperationResponse> => {
        const response = await nextPolicy.sendRequest(httpRequest);

        if (response.status === 401) {
          console.log("Do something on 401, you can also modify the response");
        }

        return response;
      }
    };
  }
};

// requestPolicyFactories is a property of ServiceClientOptions
const client = new YourGeneratedClient({
  requestPolicyFactories: defaultPolicies => {
    // Add the new intercept policy and append all the default policies afterwards
    return [interceptPolicy, ...defaultPolicies];
  }
});
```
