### ISSUE TITLE
Half-required property

### ISSUE THREAD

**Issue by tomasz-grobelny** [Azure/autorest.typescript#450]
Is there any easy way to specify that some property (typically "id") is required when traveling from server to client (hence no possibility to have undefined), but not required when traveling from client to server (it is not yet known and should not be specified)?

**Comment by amarzavery** [comment]
You can mark the property as [`"readOnly": true`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13) in the open api spec. This will ensure that the generated client will not serialize the property while sending the request (even if the user specifies it) and will deserialize the property in the response when the server sends it.

**Comment by amarzavery** [comment]
Has your query been resolved? If yes, then can this issue be closed?
