### ISSUE TITLE
missing parameter for patch operation

### ISSUE THREAD

**Issue by tomasz-grobelny** [Azure/autorest.typescript#452]
I have an operation with following specification:
```json5
      "patch": {
        "tags": ["Leads"],
        "operationId": "Leads_PatchLead",
        "consumes": ["application/json", "application/json-patch+json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "leadId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "patchData",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/JsonPatchDocument[Lead]"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "422": {
            "description": "422",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ValidationError"
              }
            }
          }
        }
      }
```
However the operation that gets produced has this signature:
```js
    patchLead(leadId: string, options?: msRest.RequestOptionsBase): Promise<Models.LeadsPatchLeadResponse>;
    patchLead(leadId: string, callback: msRest.ServiceCallback<any>): void;
    patchLead(leadId: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
    patchLead(leadId: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.LeadsPatchLeadResponse> {
    return this.client.sendOperationRequest(
      {
        leadId,
        options
      },
      patchLeadOperationSpec,
      callback) as Promise<Models.LeadsPatchLeadResponse>;
    }
```
Any thoughts why there is no patchData argument in the generated calls even if it is in operationSpec:

```js
const patchLeadOperationSpec: msRest.OperationSpec = {
  httpMethod: "PATCH",
  path: "AgentAssist.Api/api/leads/{leadId}",
  urlParameters: [
    Parameters.leadId0
  ],
  requestBody: {
    parameterPath: "patchData",
    mapper: {
      ...Mappers.JsonPatchDocumentLead,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    422: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ValidationError"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};


```

**Comment by amarzavery** [comment]
- Can you provide a sample swagger spec for us to reproduce this issue? 
- Please don't name your models with `[]` square brackets in it `JsonPatchDocument[Lead]`

**Comment by tomasz-grobelny** [comment]
I will try to create minimal example and post it here.

As for the second part: the name was generated by ASP.NET WebAPI from signature that looked more or less like this:

    public IActionResult PatchLead(string leadId, [FromBody]JsonPatchDocument<Lead> patchData);

Do you think it might cause the issue?

**Comment by amarzavery** [comment]
I hope that shouldn't be the case. However you can try to generate the client after making that change, just to be sure if that is not causing the issue.

**Comment by tomasz-grobelny** [comment]
Ok, here comes the full example. Download the [swagger.txt](https://github.com/Azure/autorest.typescript/files/3388743/swagger.txt) file and execute this commend:
`autorest --typescript --input-file=swagger.txt --use=@microsoft.azure/autorest.typescript@4.1.1`

Open generated/src/operations/values.ts and have a look at patchLead methods - they should contain patchData parameter but they do not.

**Comment by amarzavery** [comment]
@tomasz-grobelny - I found out the root cause. The body parameter is referring to `"#/definitions/JsonPatchDocument[Lead]"`. You have declared all the properties of this model as `"readOnly": true`. Which means that the user cannot send anything inside the request body while making the request. All the properties of the model `JsonPatchDocument[Lead]` will be populated by the Server in the response. Thus the generator strips that model from being a parameter to the method as it does not want the user to mislead.

```json5
"JsonPatchDocument[Lead]": {
      "type": "object",
      "properties": {
        "Operations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/JsonPatchOperation"
          },
          "readOnly": true
        },
        "HasOperations": {
          "type": "boolean",
          "readOnly": true
        }
      }
    },
```

If you remove `"readOnly": true` from atleast 1 property of the model `"JsonPatchDocument[Lead]"` then you will see the parameter show up in the method definition.

Having a model with all it's properties set to `readOnly: true` in the request body makes no sense.

**Comment by tomasz-grobelny** [comment]
Thanks a lot for the analysis. It seems then that I should look into how the swagger definition is generated. I see that JsonPatch NuGet package that I am using uses JsonPatchFormatter that does custom deserializing logic which is not taken into account at all when generating swagger definition. Seems I need to write custom ISchemaFilter to fix this.

**Comment by tomasz-grobelny** [comment]
As a side note: shouldn't autorest at least generate a warning when this situation occurs? Because now we effectively have an unusable operation.

**Comment by amarzavery** [comment]
Yeah, a warning will definitely help. Will update the generator to issue a warning for such scenarios.
