### ISSUE TITLE
Generate a sample test for every client

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest.typescript#453]
- Once we figure out what packages are needed for tests, coverage, how to setup recording, etc. and how to run them in node and browser, we should have an extra switch `--generate-test-template` that will add right stuff to package.json and generate 1 simple test in the test file. 
- A `README.md` in the test file that explains how to setup environment variables, record, playback tests etc. would be super helpful. 
- This could be a starter kit for new teams onboarding for the first time. It will be a great value add for customers using the vanilla flavor of the TS generator.
- Autogenerating tests for every operation in swagger is a hard problem to solve. However, we can generate one test that does a simple GET _**(The logic that is used to generate one sample in README.md can be used to generate the test as well)**_. It will cut the uphill task for everyone to copy repetitive stuff. Partner teams can simply run npm i, npm test and focus on writing tests.
/cc @daviwil @ramya-rao-a

**Comment by joheredi** [comment]
This is a great idea, however I think that this should be something that needs to live in the repository in which the generator code would live. For exmaple `azure-sdk-for-js` where we get a sample test kickstarted using the tools and frameworks preferred there. If we bring that into this project, we'd be getting opinionated in external tools and frameworks.

I think there are plans to have some scaffolding to kick-start new libraries in  `azure-sdk-for-js`  which will be a great place to generate this template test.

I'm closing the issue, but feel free to reactivate if you disagree
