### ISSUE TITLE
Fix encoding of array query parameters

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.typescript#456]
Azure/azure-sdk-for-node#3445 indicates we're incorrectly encoding query collection separators. I think we should encode the individual array elements and then join with the separator. Not certain.

I'm sure there are autorest tests for array query parameters, but maybe they're doing URL decoding before splitting which results in it happening to work on the autorest.nodejs test server but not certain other servers?

**Comment by amarzavery** [comment]
This was the PR https://github.com/Azure/autorest.nodejs/pull/72 that fixed the issue in the nodes generator. The PR has links to original issues filed in the node sdk repo.

**Comment by joheredi** [comment]
This has been fixed in ms-rest-js and core-http:

https://github.com/Azure/azure-sdk-for-js/pull/8377
