### ISSUE TITLE
Generated code doesn't honor errors defined in swagger

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/autorest.typescript#464]
Hi, this is from storage JS SDK. Related issue is https://github.com/Azure/azure-sdk-for-js/issues/4999.

Storage SDKs use generator to generate what we called protocol layer code. When error happens, for example, Azure Storage REST API returns 500/404 status code in HTTP responses. @azure/ms-rest-js deserialization will throw `RestError` directly, and storage SDK pops error to the top. But this seems incorrect, as the thrown `RestError` should be further deseriazed according to the response headers and bodies, just like swagger defines.

![image](https://user-images.githubusercontent.com/6889160/64310323-3ae9e680-cfd2-11e9-806b-2bf681621f43.png)

For example, when getting properties from non exist blob.

```javascript
    try {
      await blobClient.getProperties();
    } catch (err) {
      console.log(err);
    }
```

![image](https://user-images.githubusercontent.com/6889160/64310126-8a7be280-cfd1-11e9-94aa-c9eeb1ca65fd.png)

We need to retrieve the raw headers to get storage error code by `err.response.headers.get("x-ms-error-code")`.

![image](https://user-images.githubusercontent.com/6889160/64310235-f1010080-cfd1-11e9-8e3a-fafd4cba6c33.png)

The generated code doesn't return errors defined in swagger.

The error thrown should parser error responses and fits the swagger definition correctly. For example, parser `ErrorCode` from `x-ms-error-code` header value. The swagger defines how to parser Azure Storage errors when returned status code is not in the expected list.

![image](https://user-images.githubusercontent.com/6889160/64310323-3ae9e680-cfd2-11e9-806b-2bf681621f43.png)

**Comment by XiaoningLiu** [comment]
@amarzavery Can you take a look?

Another issue is that, the `errorCode` property is generated into wrong place. Just like above swagger samples, the `errorCode` is part of "default" reponses instead of "200". However, in the generated code, `errorCode` is part of "200"'s response models.

For example, we have a RESTful API `Get Blob Properties`. When status code is 200, the generated code will normally return a `BlobGetPropertiesResponse` model includes `BlobGetPropertiesHeaders` . However, `errorCode` is in  the generated `BlobGetPropertiesHeaders` model. 

The trick thing is, when status code is 200, `errorCode` will always be undefined. When status code is not 200, like 500. A `RestError` will be thrown. Caller won't access to the `errorCode` forever.

The expected behaviro is, `errorCode` will be in the generated `StorageError` just like the swagger defines. When API return status code not 200, the thrown `StorageError` could parser the error code from headers.

**Comment by YoDaMa** [comment]
To add to what @xiaoningliu is saying:

Currently the way an Error is handled, the result of a call to a BlockBlobUpload will null and an error will just be thrown. Since these are promises, it will be wrapped in a Try Catch statement:

```
  try {
    let uploadStatus = await uploadStreamToBlockBlob(...);
    console.log('uploadStreamToBlockBlob success');
    await client.notifyBlobUploadStatus(null, uploadStatus);
    return 0;
  }
  catch (err) {
    await client.notifyBlobUploadStatus(err, null);
    return 1;
  }
```

This seems to be an API result of the `errorCode` not being populated in the `uploadStreamToBlockBlob(...)` response. What I would like to know is how fixing this will affect error code handling. If this is 'fixed', will the result be populated on an error, or will it still just throw? I am confused, because it seems like if `uploadStreamToBlockBlob` throws, then the response will not be populated and `err` will be thrown. Is this correct? 


- If that is correct, then `err` will continue to be of type `RestError`. 
- If that is not correct, then I don't know. Will `err` be of type `BlobUploadCommonResponse`.

**Comment by XiaoningLiu** [comment]
Add @ramya-rao-a to take a look

**Comment by XiaoningLiu** [comment]
@ramya-rao-a @sarangan12 #463 belongs to the same topic about error handling, but not same. #463 is aksing to support negative status code. While this issue is about handling error models defined in "default" section of a response in swagger.

**Comment by joheredi** [comment]
https://github.com/Azure/autorest.typescript/issues/283 is tracking this work for v6
