### ISSUE TITLE
Incorrect URL path generated when basePath is defined

### ISSUE THREAD

**Issue by tmarkovski** [Azure/autorest.typescript#466]
My swagger 2.0 spec has `basePath` defined and the generated endpoint takes this into account twice.

    "host": "contoso.azure-api.net",
    "basePath": "/cloud/v1"
    ....
    "paths": {
        "/connections":

When invoking the method from the generated code, it actually tries to call `https://contoso.azure-api.net/cloud/v1/cloud/v1/connections`.
I'm generating the API without any configuration or parameters. Is this a known issue?

**Comment by aranoe** [comment]
This problem is easy to fix, unfortunately i never contributed to github and i just got a permission denied error while trying to push my branch to origin.

Anyway, in `MethodTS.cs` this section needs to be replaced:
```
        [JsonIgnore]
        public string Path
        {
            get
            {
                string path = CodeModelTS.BasePath;
                string relativePath = RelativePath;
                if (!string.IsNullOrEmpty(relativePath))
                {
                    if (!string.IsNullOrEmpty(path))
                    {
                        path += '/';
                    }
                    path += relativePath;
                }
                return path;
            }
        }
```
With this:
```
        [JsonIgnore]
        public string Path
        {
            get
            {
                return RelativePath;
            }
        }
```
Of course you could also delete the `Path` property and replace it with `RelativePath` everywhere (I think there is only one reference tho)

**Comment by tmarkovski** [comment]
Thank you. I'm glad I'm not the only one running into this issue, which seems that it shouldn't have passed basic testing.

The way to send a contribution would be for you to fork this repo, add the fix in a branch, and create Pull Request in this repo for the code in your branch.
I'd be happy to do it for you, but you should try it and get contribution credit.

**Comment by joheredi** [comment]
Would you guys mind trying this with the new version of the generator? I believe it should handle this scenario

[Generating with autorest for Typescript v6](https://github.com/Azure/autorest.typescript/wiki/Generating-with-autorest-for-Typescript-v6)
