### ISSUE TITLE
Customization enhancements

### ISSUE THREAD

**Issue by epignosisx** [Azure/autorest.typescript#467]
Hey folks, great project! I have used autorest a lot to generate C# clients with great success. For the first time I’m trying to create a typescript project for a browser app. The generated client was too much for my needs. In browser land, code size does matter! Here are a few flags that would be useful:

- Option to forgo everything except the model classes (request and response DTOs). In my particular case I just use the `fetch` API to make the calls. We are OK typing out routes, but we have been bitten by misspelled property names. I can mostly get to this state by removing the unwanted files, however, the file where the models are defined have a few imports statements and some other DTOs representing operations.
- Option to define optional fields nullable instead of undefined: `age?: number` becomes `age: number | null`. This is an option that NSwag provides. APIs creates with ASP.NET Core default to returning `null` for empty properties instead of omitting the field altogether which would then match the current `undefined` behavior of the generation.

Please let me know if by any chance these options exist and I miss them or if there is an extensibility I can use to modify the output. Currently I’m removing the unnecessary files and then using the typescript compiler API to transform the file containing the models to remove the everything I’m not interested in and switching optional fields from undefined to null. But needless to say having these features built-in would be very valuable.

**Comment by sarangan12** [comment]
@joheredi Do you think if the Rest Level Client will satisfy the ask here?

**Comment by joheredi** [comment]
Yes this sounds like a candidate use case for Rest Clients. `--rest-level-client` should output a rest client sdk

**Comment by sarangan12** [comment]
The actual requirement has been satisfied with the Rest Level Client by using the argument `--rest-level-client`. No more pending action items on this task. Closing this issue
