### ISSUE TITLE
Optional Parameter in swagger

### ISSUE THREAD

**Issue by mlkmali** [Azure/autorest.typescript#474]
I have generated the client side with autorest in typescript. I have an optional parameter in my json 

"/quotes": {
      "get": {
        "tags": [
          "Market quotes"
        ],
        "summary": "",
        "description": "",
        "operationId": "receiveQuotation",
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "name": "since",
            "in": "query",
            "description": "Timestamp from which we want to retrieved the updated quotes.",
            "required": false,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/QuoteSnapshot"
              }
            }
          },
          "400": {
            "description": "Invalid status value"
          }
        }
      }
    },
How I can implement this optional parameter in my client side?
 const Quotes = await client.receiveQuotation(  ??????????????  ) as Models.QuoteSnapshot[];

**Comment by joheredi** [comment]
Hi @mlkmali would you mind sharing the generation output? Specifically the models/index.js file?

Optional parameters can be passed as part of the options parameter. For instance `await client.receiveQuotation({since: 1000})`

**Comment by joheredi** [comment]
Closing as we have not received response from the author. Please reactivate if you're still facing any problems
