### ISSUE TITLE
multiple response code

### ISSUE THREAD

**Issue by KeXu444** [Azure/autorest.typescript#476]
When multiple response used in swagger
Generated typescript package does not have strong typed response.

        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ImageResponseBase"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ModelErrorResponse"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ModelErrorResponse"
            }
          },
          "500": {
            "description": "Server Error"
          },
          "401": {
            "description": "Unauthorized"
          }
        }

**Comment by joheredi** [comment]
This is a duplicate of #283 where we need to support `x-ms-error-response` extension in the new version of autorest.typescript
