### ISSUE TITLE
[Node.js] Incorrect comment format breaks JsDoc generation

### ISSUE THREAD

**Issue by dend** [Azure/autorest.typescript#477]
As an example:

```javascript
/**
* @class
* Initializes a new instance of the DatabaseAccountsListResult class.
* @constructor
* The List operation response, that contains the database accounts and their
* properties.
*
*/
```

The issue is caused by description followed by `@constructor`. This is not supported by JsDoc. The expected format is as follows:

```javascript
/**
* Initializes a new instance of the DatabaseAccountsListResult class.
*/
class DatabaseAccountsListResult extends Array {
/**
  * The List operation response, that contains the database accounts and their
 * properties.
 */
  constructor() {
    super();
  }
```

The ask is applicable to all documented classes.

cc: @amarzavery

**Comment by joheredi** [comment]
Thanks for reporting this issue, in the latest autorest.typescript v4 comments we have made changes to be more consistent with the JSDoc standard. Let us know if you still face this issue with the latest version
