### ISSUE TITLE
[NodeJs] The node sdk needs to make available discriminators more clear.

### ISSUE THREAD

**Issue by williexu** [Azure/autorest.typescript#478]
Currently, if there is a polymorphic discriminator that a user wants to provide in their request, they are required to look into the `index.js` in their models folder to see the available options.

In addition, children have their discriminators appended to that of their parent: `<ParentDiscriminator>.#<ChildDiscriminator>`, making it confusing what the right values should be.

**Comment by joheredi** [comment]
We need to make sure we provide enough information about discriminators in the documentation to make it easier for the users. Will address this in the new version of autorest

**Comment by joheredi** [comment]
In the new version of the generator, the discriminator property is a string literal union, which provides intelisense on the possible values.

![image](https://user-images.githubusercontent.com/21109913/95503736-9a968c00-0960-11eb-999f-20c573f9be3a.png)

@williexu I hope this is reasonable, please let us know if you have any other suggestions
