### ISSUE TITLE
Property 'code' does not exist on type 'never'

### ISSUE THREAD

**Issue by Kordonme** [Azure/autorest.typescript#479]
I'm getting this compile error in the generated typescript:

```
let internalError = null;
if (parsedErrorResponse.error) internalError = parsedErrorResponse.error;
error.code = internalError ? internalError.code : parsedErrorResponse.code;
error.message = internalError ? internalError.message : parsedErrorResponse.message;
```

Same goes for `internalError.message`. It's easily fixed, but have to do it manually now. Any reason for declaring a variable to be always null?

**Comment by joheredi** [comment]
We think this issue has been fixed with the newest autorest version (v5.0.2) which uses coreHttp instead of msrest.

Please let us know if you still hit this issue after using the latest autorest version. For using this version you can add the flag `--use=@microsoft.azure/autorest.typescript@5.0.2`
