### ISSUE TITLE
Mocking autorest generated typescript library

### ISSUE THREAD

**Issue by andrew-buckley** [Azure/autorest.typescript#48]
Are there plans to provide a way to easily mock the autorest generated typescript client? There was an issue two years ago in the main autorest C# repo but it doesn't look like they will implement it. It would be nice to be able to unit test larger projects without making real API calls.

**Comment by RikkiGibson** [comment]
Hi @andrew-buckley. We're working on some design changes that will make it easy to pass a mock `fetch()` implementation when creating your service client. Hope to have it delivered within a few months.

Depending on your design you might want to try creating a subclass of the service client and any relevant operation groups which performs some mock behavior.

```js
class MockOperationGroup extends MyOperationGroup {
  async myOperation(): Promise<ReturnType> {
    return ...;
  }
}

class MockService extends MyService {
  operationGroup: MyOperationGroup = new MockOperationGroup(this);
}

const serviceClient = new MockService(null, null);
serviceClient.operationGroup.myOperation()...
```

**Comment by amarzavery** [comment]
You can also use [nock.js](https://github.com/node-nock/nock) to record live tests and then playback in CI. We do that all the time for the node sdk. That is way better than mocking the client. You can then have a bot record those tests every time you make updates to the SDK. Travis CI can run tests in playback mode (which means CI run is fast).

- Our simple [test framework](https://github.com/Azure/azure-sdk-for-node/blob/master/test/framework/suite-base.js) that is usable with mocha.
- [an example of storage management mocha tests](https://github.com/Azure/azure-sdk-for-node/blob/master/test/services/storageManagement/storageManagementClient-tests.js) that uses our framework
- corresponding [test recordings](https://github.com/Azure/azure-sdk-for-node/tree/master/test/recordings/storagemanagementservice-tests)
- Supported environment variables for test runs in live, record, playback mode over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/TestModes.md#test-modes).

You can take a look at travis ci jobs for any open/closed PR in the node sdk repo.

**Comment by RikkiGibson** [comment]
Please feel free to reopen if you have any further questions or feedback.
