### ISSUE TITLE
API Response doesn't get deserialized into the response model

### ISSUE THREAD

**Issue by amithegde** [Azure/autorest.typescript#480]
I have an API running at `http://localhost:3000/api/sessionInfo`. Here is the response from the API:

    [
      {
        "UserName": "Jon Snow",
        "TenantName": "some tenant",
        "InstanceName": "some instance",
        "BuildNumber": "1.0.0.2"
      }
    ]

I created a swagger spec for it and generated TypeScript client for it. Swagger spec looks like this:

    {
      "swagger": "2.0",
      "info": {
        "version": "1.0",
        "title": "REST API TEST"
      },
      "host": "localhost",
      "schemes": [
        "http"
      ],
      "paths": {
        "/api/sessionInfo": {
          "get": {
            "tags": [
              "Tenant"
            ],
            "summary": "",
            "operationId": "Tenant_GetSessionInfo",
            "consumes": [],
            "produces": [
              "application/json",
              "text/json",
              "application/xml",
              "text/xml"
            ],
            "parameters": [
              {
                "name": "fields",
                "in": "query",
                "required": false,
                "type": "array",
                "items": {
                  "type": "string"
                },
                "collectionFormat": "multi"
              }
            ],
            "responses": {
              "200": {
                "description": "OK",
                "schema": {
                  "$ref": "#/definitions/SessionInfo"
                }
              }
            },
            "security": [
              {
                "AuthRequirements": [
                  ""
                ]
              }
            ]
          }
        }
      },
      "definitions": {
        "SessionInfo": {
          "type": "object",
          "properties": {
            "UserName": {
              "type": "string"
            },
            "TenantName": {
              "type": "string"
            },
            "InstanceName": {
              "type": "string"
            },
            "BuildNumber": {
              "type": "string"
            }
          }
        }
      }
    }

Generated TypeScript client has a function `getSessionInfo` which returns `Promise<Models.TenantGetSessionInfoResponse>` which looks like this 

    /**
     * Contains response data for the getSessionInfo operation.
     */
    export type TenantGetSessionInfoResponse = SessionInfo & {
      /**
       * The underlying HTTP response.
       */
      _response: msRest.HttpResponse & {
          /**
           * The response body as text (string format)
           */
          bodyAsText: string;
          /**
           * The response body as parsed JSON or XML
           */
          parsedBody: SessionInfo;
        };
    };

When I try to call this API from Angular 8 application and to bind response to a view, the type `TenantGetSessionInfoResponse ` doesn't contain any of the properties of `SessionInfo`.

When I use the `.then` syntax to extract the response from the Promise, I see this response:
![image](https://user-images.githubusercontent.com/816051/69003685-389de580-08bb-11ea-9dcb-acc14cc97199.png)

![image](https://user-images.githubusercontent.com/816051/69003689-50756980-08bb-11ea-8258-032a7f306db3.png)

As you can see, none of the properties of `SessionInfo` are present, though `bodyAsText` has the response in text form.

I tried awaiting on it like this:

    public async callApi2(): Promise<SessionInfo> {
        const response = await this.apiClient.tenant.getSessionInfo();
        console.log('response from async call: ' + response.tenantName);
    
        return response;
    }

which produced same result as well.

- I feel uncomfortable by the the decision to convert `SessionInfo` to `TenantGetSessionInfoResponse` which contains extra payload which is not needed for binding to views and use and any of the higher levels can't make use of `SessionInfo` and need to use `TenantGetSessionInfoResponse`. May be because Typescript is new to me, I find myself uncomfortable with this though. @RikkiGibson might be able to share some details as he implemented #241 

- I don't seem to be able to find a way to deserialize JSON response to `SessionInfo`

I have uploaded a sample application which can reproduce this issue here: https://github.com/amithegde/auto-rest-test

**Comment by joheredi** [comment]
Hi @amithegde, thanks for reaching out. It looks like the service is returning an array of `SessionInfo` objects however the swagger above defines the response as a single SessionInfo object. 

This should define the response as an array:

```json
"responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SessionInfo"
              }
            }
          }
        }
```

Can you please give it a try by adjusting your swagger and let us know if this fixes your issue?
