### ISSUE TITLE
[Test] ExtensibleEnums

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#510]
Full support for extensible enums swagger

[Swagger](https://github.com/Azure/autorest.testserver/blob/master/swagger/extensible-enums-swagger.json)
**Missing scenarios:** 
- [x] [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)
- [x] [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum)
- [x] [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum)
- [x] [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum)

Bug #742 should be addressed when adding this coverage

**Comment by joheredi** [comment]
We should look into @willmtemple's suggestion for representing extensible enums, here's a sample he shared:

```typescript
// Make an unmatchable symbol
declare const __ : unique symbol;
type Primitive =
	| null
	| undefined
	| string
	| number
	| boolean
	| symbol
	| bigint;
// Opaque<T> is a slightly more specific type than T that will not collapse
// subtypes of T when it is put into a union with them
type Opaque<T extends Primitive> = T & { [__]?: never};
type ExtensibleUnion<T extends Base, Base extends Primitive = string> = T | Opaque<Base>;

function foo(input: ExtensibleUnion<"a" | "b">) {
    console.log(input);
}

// If you make a new call to `foo` and open intellisense, it will suggest
// "a" and "b", but any other string is also valid.
foo("a");
foo("b");
foo("c");

```

**Comment by sarangan12** [comment]
code complete with PR https://github.com/Azure/autorest.typescript/pull/763
