### ISSUE TITLE
[Test] Validation swagger

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#521]
https://github.com/Azure/autorest.testserver/blob/master/swagger/validation.json

**Missing Scenarios**
- [ ] [`ConstantsInBody`](https://github.com/Azure/autorest.testserver/search?q=ConstantsInBody)
- [ ] [`ConstantsInPath`](https://github.com/Azure/autorest.testserver/search?q=ConstantsInPath)

**Comment by deyaaeldeen** [comment]
Done.
