### ISSUE TITLE
[Test] Test azure-resource and azure-resource-x

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#524]
- [x] ~~azure-composite-swagger.json~~ (No longer exists)
- [x] azure-parameter-grouping.json
- [x] azure-report.json
- [ ] azure-resource-x.json
- [ ] azure-resource.json
- [x] azure-special-properties.json

**Comment by joheredi** [comment]
@lmazuel there seems to be not test in the test server for these swaggers. Should we keep supporting this extension?

Looking at the [extension documentation](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-azure-resource) it looks like it is expected to extend the described model with some common properties for a resource. Is my understanding correct?

If my understanding is correct, it feels like instead of this being an extension, ARM libraries should have a common Resource definition that they can reference in their swaggers

**Comment by lmazuel** [comment]
Hey @joheredi 
This is the list of Swagger we are using in our Python suite:
https://github.com/Azure/autorest.python/blob/7ebe85056ea090c2e6f30ffc7848ade5015f27cf/tasks.py#L27-L84

It's possible there is extra Swagger in the testserver that doesn't matter.
