### ISSUE TITLE
Move to Gulp 4 or remove Gulp entirely

### ISSUE THREAD

**Issue by daviwil** [Azure/autorest.typescript#526]
Apparently Gulp 3 does not work on Node 12 (https://github.com/gulpjs/gulp/issues/2324) and `autorest.typescript` can't currently be upgraded to Gulp 4 because of a dependency on the `gulp.tasks` API that no longer exists in the new version.  We need to either migrate the Gulp scripts to Gulp 4 APIs or get rid of Gulp usage entirely.

/xref #525 and https://github.com/Azure/ms-rest-js/pull/377

**Comment by joheredi** [comment]
I think we should won't fix this. It looks like this would be a non-trival task and we can probably invest the effort in the new version of the generator. If you feel like we there is a quick way to achieve this feel free to reopen
