### ISSUE TITLE
if x-ms-code-generation-settings name starts with a lowercase letter, codegen will fail

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#531]
![image](https://user-images.githubusercontent.com/55688292/70683537-a7653780-1cdd-11ea-8898-a41c5b38e4f3.png)
As you can see this swagger file has x-ms-code-generation-settings name starts with a lowercase letter.
after the code generation process, 
It will report error like 
`Namespace '"azure-sdk-for-js/sdk/softwareplan/arm-softwareplan/src/models/index"' has no exported member 'softwareplanClientOptions'.ts`
![image](https://user-images.githubusercontent.com/55688292/70683771-9537c900-1cde-11ea-8705-07a8fbe8331b.png)
and the actual export Options is `SoftwareplanOptions`

I think the problem lies in https://github.com/Azure/autorest.typescript/blob/master/src/vanilla/TransformerTS.cs#L341 here.

**Comment by qiaozha** [comment]
@daviwil  Could you please take a look at this issue?

**Comment by ramya-rao-a** [comment]
@joheredi can help here
