### ISSUE TITLE
Infered type any when endpoint has multiple response types

### ISSUE THREAD

**Issue by rtfpessoa** [Azure/autorest.typescript#543]
When I have an endpoint with multiple codes I get any as the type of my response?
Am I doing something wrong? This seems like a pretty standard thing to do, any suggestions on how to overcome this?

If this is a problem, any suggestion on how to fix it? I am available to provide PRs.

Not sure if it matters but I running the latest version with command:

```sh
#!/usr/bin/env bash

set -e

autorest --typescript \
         --add-credentials=true \
         --generate-metadata=true \
         --model-date-time-as-string=false \
         --package-name=api-client \
         --input-file=./swagger.yaml \
         --output-folder=./autorest-out
```
and swagger file is:

```
swagger: '2.0'
info:
  contact:
    email: admin@example.com
  description: 'My Dummy API description'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  title: 'My Dummy API'
  version: '1.0.0'
host: api.example.com
basePath: /
schemes:
  - https
paths:
  '/nice/{param}':
    get:
      produces:
        - application/json
      parameters:
        -
          description: 'param description'
          in: path
          name: param
          required: true
          type: string
      responses:
        200:
          description: 'Nice response'
          schema:
            $ref: '#/definitions/NiceBody'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
      tags:
        - commit
      operationId: getNiceBody
      summary: 'Returns a nice body'

responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: '#/definitions/Error'
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
  NiceBody:
    type: object
    properties:
      name:
        type: string
      age:
        type: number
```

**Comment by joheredi** [comment]
Hi @rtfpessoa, thanks for reporting this. There are 2 issues with the generator here

1) The current version doesn't support multiple error definition, it just supports defining one error case in the "default" response.  We have an issue to support multiple errors #283. #463 also includes some details about this.

2) Also, it doesn't seem to play nice when multiple Success responses are defined, getting `body: any` as a property in the Response type definition. #314 presents a similar problem.

We are currently working on a new version of the Typescript generator in which we will consider the 2 issues above. I have filed #546 to track (2) and will use #283 for (1)

Meanwhile the workaround I can suggest is to define only one **Error** response as `default`. That would get you the right types for the success response.

/cc @ramya-rao-a, @daviwil

**Comment by joheredi** [comment]
I'm closing this issue, feel free to re-activate if the suggestion didn't help with the typings
