### ISSUE TITLE
Typescript: Integrating with react-aad-msal & msal 

### ISSUE THREAD

**Issue by yahorsi** [Azure/autorest.typescript#569]
Hi Guys!

Are there any recommendations on how to integrate generated by autorest client with react-aad-msal & msal? 

react-aad-msal in their docs claims:
"The library components will manage authenticating the user without you needing to think about tokens."

But that does not work. I'm a bit confused how to configure it right as refreshing scenarion should be taken in to account as well.

Thanks
Regards

**Comment by joheredi** [comment]
Hi @yahorsi, thanks for reaching out. Are there any samples you can share with us to understand better what's not working for you? I'm interested specifically in the generated code you're unable to work with

If renew feature is missing in react-aad-msal, I'd suggest filing an issue in their repository as they'll be able to provide support and fix any issues.

**Comment by joheredi** [comment]
Closing since this is not actionable at the moment. If you're still facing the issue, please re-open the issue and if possible, please share some code samples of what's not working correctly with the generated code.
