### ISSUE TITLE
[v6] Support multiple-requests and Content-Types

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#570]
There are some operations that may support multiple different Contet Types on request. We need to add support for this.

Form recognizer has some examples of multiple Content Types [here is an example](https://github.com/ctstone/azure-rest-api-specs/blob/f82a9be5d539eb762a0f3f69cbdc7ba4097d4dd7/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json#L214)

**Comment by chradek** [comment]
It's been a journey, but this has been completed by #582, and improved by #598 and #601.
