### ISSUE TITLE
[v6] Support multiple requests per operation

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#571]
In the latest version of ModelerFour, there is a change which changes the `request: Request` property in the Operation object to `requests: Request[]`

This change breaks autorest.typescript if we update our packages, specifically `@azure-tools/codemodel` and the version of Modeler Four in `readme.md` 

Here's the change of ModelerFour for reference: https://github.com/Azure/autorest.modelerfour/commit/075df14622600bd94426a1f1b684dac81c88508b

**Comment by chradek** [comment]
Fixed in #579 and #582
