### ISSUE TITLE
Arm-Subscriptions SDK sample code in readme is wrong in Azure JS SDK

### ISSUE THREAD

**Issue by LianwMS** [Azure/autorest.typescript#576]
Current sample code does not work. We can use the following as the sample code. or please provide a more suitable one:

```
import * as msRest from "@azure/ms-rest-js";
import * as msRestAzure from "@azure/ms-rest-azure-js";
import * as msRestNodeAuth from "@azure/ms-rest-nodeauth";
import { SubscriptionClient, SubscriptionModels, SubscriptionMappers } from "@azure/arm-subscriptions";
const subscriptionId = process.env["AZURE_SUBSCRIPTION_ID"];
 
msRestNodeAuth.interactiveLogin().then((creds) => {
  const client = new SubscriptionClient(creds);
  client.subscriptions.list().then((result) => {
    console.log("The result is:");
    console.log(result);
  });
}).catch((err) => {
  console.error(err);
});
```

**Comment by joheredi** [comment]
Thanks for bringing this up @LianwMS, we are currently working on a new version of Autorest.Typescript this fix will be included in the new version. I have filed a Work Item to track this work with a reference to this issue to make sure we keep these issues in mind.

I'm closing this Issue in favor of the work item #594
