### ISSUE TITLE
discriminator key error in mapper.ts

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#578]
The swagger definition is here. https://github.com/zachraMSFT/azure-rest-api-specs/blob/ea1d560b9a361801e2bafe30a495843b5fccc99a/specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-10-01/consumption.json 
This is the generated discriminator maps.
![image](https://user-images.githubusercontent.com/55688292/75866436-fedbf500-5e3f-11ea-9b7b-6a002b6913c1.png)
I think the problem is probably in here 
https://github.com/Azure/autorest.typescript/blob/12509e48b39420721dfc344a816c10465260e2b3/src/vanilla/Model/CodeModelTS.cs#L323-L330

**Comment by joheredi** [comment]
Thanks @qiaozha, what would the be the expected discriminator map?

**Comment by qiaozha** [comment]
Actually I am confused why the keys of UsageDetail and ChargeSummary don't like ReservationRecommendation. something like 
```
export const discriminators = {
  'UsageDetail': UsageDetail,
  'UsageDetail.legacy': LegacyUsageDetail,
  'UsageDetail.modern': ModernUsageDetail,
  'ReservationRecommendation': ReservationRecommendation,
  'ReservationRecommendation.legacy': LegacyReservationRecommendation,
  'ReservationRecommendation.Nodern': ModernReservationRecommendation,
  'ChargeSummary': ChargeSummary,
  'ChargeSummary.legacy': LegacyChargeSummary,
  'ChargeSummary.modern': ModernChargeSummary,
}
```

**Comment by clecompt-msft** [comment]
We're seeing this issue as well (as of 5.0.2). It seems to occur when you have the following setup:
`(Ancestor without discriminator)->(Parent with discriminator)->(Child)`
The produced mapping then includes `Ancestor.Parent` and `Ancestor.Child` rather than the expected `Parent` and `Parent.Child` (which is what is required for the discriminator to behave correctly).

**Comment by clecompt-msft** [comment]
An interesting point I just discovered - the nodejs generator actually generates the same discriminator mapping, but the resulting library behaves correctly, so it's possible that something changed in the mapper handling in the underlying library (in the switch to `@azure/core-http`) that caused this scenario to stop working.

**Comment by joheredi** [comment]
@clecompt-msft, @qiaozha we released a new version (5.1.0) that contains a fix for the discriminators. Can you please give it a try and let me know your issues are fixed?

**Comment by clecompt-msft** [comment]
No, I see the same behavior in 5.1.0 as in 5.0.2.

**Comment by joheredi** [comment]
It looks like the fix only went into `v4x`. I've created PR #671 to port the fix to master.
