### ISSUE TITLE
[v6] Add UUID support to enable FormRecognizer

### ISSUE THREAD

**Issue by daviwil** [Azure/autorest.typescript#580]
When attempting to generate a library using the FormRecognizer spec (via @jeremymeng's [swagger config](https://github.com/jeremymeng/azure-sdk-for-js/tree/formrecognizer-t2/sdk/formrecognizer/ai-form-recognizer/swagger/README.md)), the following error is returned:

```
FATAL: Error: Handling of uuid hasn't been implemented yet
```

We need to add support for the `uuid` type to unblock generation of that library.

**Comment by chradek** [comment]
Added in #586
