### ISSUE TITLE
Long Running Operation throwing error with 202 response

### ISSUE THREAD

**Issue by andrew-buckley** [Azure/autorest.typescript#583]
I'm calling into a function that returns a `Promise<LROPoller>` response and I'm wanting to poll for the completed result. However it seems to always throw an error with no context/body even though the API successfully returns with a 202 response.

I'm using:
```
AutoRest code generation utility [cli version: 3.0.6187; node: v10.16.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\andbuc\.autorest\@autorest_core@3.0.6258\node_modules\@autorest\core\dist' (3.0.6258)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~4.2.0->4.2.4)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
```

**Comment by joheredi** [comment]
Hi @andrew-buckley thanks for reaching out. Would you mind sharing your SWAGGER file to help us with the investigation?

**Comment by joheredi** [comment]
Closing since this is no actionable at the moment. If you are still facing this issue, please re-open and share your Swagger if possible so that we can investigate further.
