### ISSUE TITLE
[v6] text/plain response bodies still serialize as JSON

### ISSUE THREAD

**Issue by bterlson** [Azure/autorest.typescript#589]
I have an endpoint with a response body thusly:

```json
        "requestBody": {
          "required": true,
          "content": {
            "text/plain": {
              "schema": {
                "type": "string"
              }
            }
          }
        },
```

When sending data with a string to this endpoint using the generated client, it is still serializing as JSON. I think the default behavior for such an endpoint should be to take strings and use toString on any data inputs that aren't string.

In practice I expect JSON to be submitted to endpoints declaring this content type, but doing the JSON serialization should optional and opt-in.

**Comment by chradek** [comment]
@bterlson Is this still an issue after the change that was made to core-http?

**Comment by bterlson** [comment]
no, but I do have to merge the PR.

**Comment by bterlson** [comment]
https://github.com/Azure/azure-sdk-for-js/pull/7963 is the PR necessary to fix this.
