### ISSUE TITLE
[v6] Multiple requestBody mime types don't work

### ISSUE THREAD

**Issue by bterlson** [Azure/autorest.typescript#591]
Given a requestBody like

```json
        "requestBody": {
          "required": true,
          "content": {
            "text/plain": {
              "schema": {
                "type": "string"
              }
            },
            "application/octet-stream": {
              "schema": {
                "type": "string",
                "format": "binary"
              }
            }
          }
        },
```

I get an error `FATAL: Error: Encountered two operation media types that had unspecified values for contentType`.

**Comment by bterlson** [comment]
Oh whoops, this looks like a duplicate of #570. Feel free to confirm and close!

**Comment by joheredi** [comment]
@chradek, would this issue be fixed by your latest work around multiple media types?

**Comment by chradek** [comment]
Yup! I confirmed with Brian that we were able to generate a client for his model.
