### ISSUE TITLE
[v6] Generate useful README files

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#594]
Auto generate useful Readme files with code samples in Typescript that demonstrates the use of the generated SDK.

We need to make sure generated samples are valid and can be run. Previous Autorest.Typescript had some issues generating invalid samples, see #576 

- [ ] Samples should be generated in Javascript instead of Typescript to help portability

**Comment by joheredi** [comment]
We should consider looking into https://github.com/Azure/autorest.typescript/issues/455 when working on the samples for v6

**Comment by joheredi** [comment]
None of the languages are currently generating heavy readmes here's what the other languages do right now:

**Python**: Readme with general information about Azure Management, nothing specific about the generated library.
**Java**: no README
**C#**: no README

I have started a conversation with the Autorest crew to see if we can reach agreement on consistent Readmes across languages.

I would propose we generate a README with the following information:

**Service Description:** From the swagger
**Supported platforms:** Which node and browser versions are supported
**How to install the package**: npm install @azure/arm-resource-manager

I'm reluctant about generating samples, usually samples are hand-picked and carefully crafted to describe a set of steps that are meaningful for each service. For example a service may be interested to show the following hero scenario 1. authenticate 2. create and entity 3. poll the creation operation until completed 4. list all the entities where another service may have a very different flow.

If we want to provide samples, I think Python's approach is reasonable, where they point users to https://github.com/Azure-Samples/azure-samples-python-management

Python sample README: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/containerservice/azure-mgmt-containerservice/README.md

/cc: @lmazuel, @sarangan12

**Comment by qiaozha** [comment]
Maybe we could at least provide one simple example for customers just like track1 mgmt. SDK?  Otherwise it may cause user's confusion on how to use the track2 SDK once we publish it.  @nickzhums How do you think of it? 
Actually, we also have sample repo for JS mgmt. SDK https://github.com/Azure-Samples/azure-samples-js-management. we can consider to point to this sample repo, but we will only add some samples for ring0 RP due to lack of resources. 
cc @lirenhe

**Comment by nickzhums** [comment]
it will be great if we can show how to authenticate and make a simple request in README for Track 2 package (this is what track 1 package currently has, so would be a bummer if we don't continue it in track 2)

**Comment by sarangan12** [comment]
@qiaozha As discussed in our meeting, I discussed the link idea with the rest of the autorest crew. The general consensus was that the samples link should be pointing towards the samples repository.

**Comment by qiaozha** [comment]
If that's the case, Could you point the sample link of mgmt. plane SDK to https://github.com/Azure-Samples/azure-samples-js-management this repo. Thanks

**Comment by ramya-rao-a** [comment]
@sarangan12 Would the link be passed via a flag to the auto rest command?

**Comment by sarangan12** [comment]
@deyaaeldeen Can you update this issue with the current status? Last week, there were several changes that went into the readme file. Can you please confirm if that resolves this issue?

**Comment by deyaaeldeen** [comment]
code complete with https://github.com/Azure/autorest.typescript/pull/971

Here is an [example](https://github.com/deyaaeldeen/azure-sdk-for-js/blob/382a17102dfd6f7eb2fbb47bbc20e6b51b8b6901/sdk/textanalytics/ai-text-analytics/README.md)
