### ISSUE TITLE
The codes generated by codegen do not retry when a request is throttled

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#597]
The codes of arm-storage generated by codegen do not retry when a request is throttled.
Please refer to https://github.com/Azure/azure-sdk-for-js/issues/7989 for more details.

**Comment by ramya-rao-a** [comment]
@joheredi Would this be the responsibility of the generated code or the runtime (like ms-rest-js or core-http)

**Comment by ramya-rao-a** [comment]
cc @chradek

**Comment by joheredi** [comment]
@chradek, @daviwil feel free to correct me if I'm wrong.

I think retry should be Runtime responsibility. A retry policy can be defined and passed as an option when instantiating the generated client. Storage is doing something similar [here](https://github.com/Azure/azure-sdk-for-js/blob/790bb3f069352b343790ad5763ce9351bf46ab52/sdk/storage/storage-blob/src/policies/StorageRetryPolicy.ts). @dw511214992 would this work for your scenario.

**Comment by chradek** [comment]
I agree with @joheredi on this. The default policy pipeline in core-http/ms-rest-js should be handling throttling errors, and if it isn't we should apply the fix there. The code generated clients should be using the default pipeline.

I think long-term it's interesting to think about how we could customize which pipeline policies are added for an individual client through code generation, but we shouldn't do that until we have an example that's truly unique to a single service.

**Comment by ramya-rao-a** [comment]
cc @richardpark-msft for insights from https://github.com/Azure/azure-sdk-for-js/issues/6408 as that was a linked issue from the upstream issue https://github.com/Azure/azure-sdk-for-js/issues/7989

cc @xirzec and @bterlson for thoughts on policies

**Comment by bterlson** [comment]
Agree, throttlingRetryPolicy should probably be in the default pipeline. @richardpark-msft I believe appconfig has such a policy - do you recall if we discussed adding the policy to core?

**Comment by richardpark-msft** [comment]
> 
> 
> Agree, throttlingRetryPolicy should probably be in the default pipeline. @richardpark-msft I believe appconfig has such a policy - do you recall if we discussed adding the policy to core?

We did talk about it but we put it on hold since the policies and how they were arranged seemed to be in flux. I do believe the general desire was to do it when we figured out the next design.

**Comment by xirzec** [comment]
+1 adding it to the default pipeline with a config argument to turn it off.

Yes this will get reworked eventually, but this seems scoped enough to support now

**Comment by joheredi** [comment]
This seems to an issue with how `ms-rest-js` and possibly `core-http` handle 429 retires. Quoting comment with details form  Azure/azure-sdk-for-js/issues/7989

>  FWIW, the API answers a 429 response which the ThrottlingRetryPolicy handles once with a retry, but when that also returns a 429, it doesn't try again. The API says Retry-After 17, but the request is still rejected with a 429 and another Retry-After 17. I wish the API would return a time that is more likely to work out. That is, I would have liked to see the API drive the retries, so that we could easily burst under 100 requests and throttle back based on meaningful responses from the API. Instead, I'm going to have to use p-throttle to proactively throttle and spread 100 requests out over 5 minutes.

I have filed Azure/ms-rest-js/issues/394, and closing this one. Please feel free to re-open if you think we should handle this somehow in the generator

**Comment by ramya-rao-a** [comment]
@joheredi Wouldnt we need the same issue logged for core-http as well?

**Comment by joheredi** [comment]
Yes, filed Azure/azure-sdk-for-js/issues/9966
