### ISSUE TITLE
[v6] Support string format "time"

### ISSUE THREAD

**Issue by chradek** [Azure/autorest.typescript#612]
A new string format, `time`, is being added to autorest. 

## Background

The idea behind `time` is that it represents time in a way that's completely agnostic to the date.

### What do other SDKs do?
In Python, there is a [datetime.time](https://docs.python.org/2/library/datetime.html#time-objects) class that contains the hours, minutes, seconds, and microseconds fields. Python accepts this type as input from a user and converts it into a string over the wire: `HH:MM:SS.microseconds`.
Python also converts this string into a `datetime.time` object when giving a response back to the user.

### Issues in JavaScript
In JavaScript we only have the `Date` class to represent time. While we can set the relevant fields on it, we can't decouple the time from the date.

### Treat format: "time" as a string.
In this solution, the code generator treats format: "time" (TimeSchema) as a regular string. We can add documentation to the generated types that indicates the format the string should be in.
__Pros__
- Input/Output is human readable
- No changes to core-http required

__Cons__
- User has to parse the string themselves if they want to work with it.

### Create a "Time" interface
With this solution, we create a `Time` (name up for discussion) interface in core-http that looks roughly like:
```ts
interface Time {
  hours: number;
  minutes: number;
  seconds: number;
  microseconds?: number;
}
```
We would need to update core-http to recognize the `time` format and serialize/deserialize the Time object the user passes in appropriately.

__Pros__
- User can work with the components of time with type-safety.

__Cons__
- Changes to core-http required.

## References:
Test swagger update: https://github.com/Azure/autorest.testserver/pull/163

**Comment by richardpark-msft** [comment]
What do other popular cloud SDKs do to represent time?

**Comment by chradek** [comment]
I'd expect this to be modeled as an ObjectSchema with the fields that coincide with the Time interface above, and have the service send that over the wire as JSON...

**Comment by bterlson** [comment]
We will eventually have a `Time` class that represents wall time (see https://github.com/tc39/proposal-temporal). I'm reluctant to create any types that will ultimately conflict.

What about supporting both `string`, and if Temporal exists (e.g. the user has a polyfill or a future runtime supporting the proposal), it's represented as a Temporal.Time? I would prefer for the proposal to reach stage 3 before we support it however.

**Comment by chradek** [comment]
> What about supporting both string, and if Temporal exists (e.g. the user has a polyfill or a future runtime supporting the proposal), it's represented as a Temporal.Time?

I can see supporting that with user input, since we can just convert either type to what needs to be sent over the wire. However, I don't think that works as well with what we return from the response. Because then we'd be telling the user that they need to check if the value is a string or Temporal.Time and handle it appropriately.

**Comment by bterlson** [comment]
Yeah that is true.

**Comment by chradek** [comment]
I could do a string for now, that's definitely the easiest. We can add a flag to autorest.typescript to treat "time" as an interface that aligns with Temporal (or even Temporal itself) in the future if we want to support that for future SDKs.

**Comment by joheredi** [comment]
Support for this was added by PR#614
