### ISSUE TITLE
[v5] PageCompositeType generation drops base model

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#615]
When generating a PageCompsiteType interface, extending from parents defined in swagger is omitted.

For example in [this swagger](https://github.com/Azure/azure-rest-api-specs/blob/0c0880833da9d695140d140071aea579fdc3da38/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2019-06-15/bms.json#L3610-L3627) `ResourceList` is dropped when generating `JobResourceList`

```typescript
export interface JobResourceList extends Array<JobResource> {
}
```

Where it should generate the following in order to honor the swagger definition
```typescript
export interface JobResourceList extends Array<JobResource>, JobResourceList {
}
```
See Issue Azure/azure-sdk-for-js/issues/7630 for more details.

**Comment by ramya-rao-a** [comment]
looks like the PR #616 is approved. Is this something that can we fix for v4?

**Comment by joheredi** [comment]
Yes, I'll create another PR with this fix in v4. I'll merge the approved PR today
