### ISSUE TITLE
[v6] Use @autorest/compare instead of git tree check

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#639]
Recommendation from David as this is more reliable than git tree check. Quote on the benefits from David

> The short version is that it semantically diffs the generated output of AutoRest between two sets of input parameters. I wrote it because using git diff is unreliable because it catches reordering of code output that has no real behavioral change. Comparing the code on an AST level leads to less false positives.

**Comment by sarangan12** [comment]
I agree with @joheredi git diff has not caused any issues until now. We could close this issue
