### ISSUE TITLE
[v6] Unused import in parameters.ts

### ISSUE THREAD

**Issue by ellismg** [Azure/autorest.typescript#668]
I'm running into an issue where AutoRest is generating an import statement for the mappers modules in some generated code, but the import is unused, which causes `tsc` to complain later.

You should be able to reproduce this by running AutoRest against the `README.md` I have here: https://github.com/ellismg/azure-sdk-for-js/tree/ellismg/autorest-typescript-unneeded-import/sdk/eventgrid/eventgrid/swagger

With respect to versions:

```
AutoRest code generation utility [cli version: 3.0.6187; node: v12.16.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\Matt G. Ellis\.autorest\@autorest_core@3.0.6280\node_modules\@autorest\core\dist' (3.0.6280)
   Loading AutoRest extension '@autorest/typescript' (6.0.0-dev.20200505.1->6.0.0-dev.20200505.1)
   Loading AutoRest extension '@autorest/modelerfour' (4.12.301->4.12.301)
```

I'm running this as:

 `autorest --v3 --typescript`

**Comment by joheredi** [comment]
Thanks @ellismg for reporting this issue, I have created a PR with a fix

**Comment by ellismg** [comment]
> I have created a PR with a fix

Awesome, Thanks!  I saw that it was merged - do we publish the dev-builds somewhere so that I can start using the newer generator with the fix?

**Comment by joheredi** [comment]
Yes, we're currently publishing to Github: https://github.com/Azure/autorest.typescript/releases

You can consume the latest PR by updating your readme.md file to point to it, like this

```yaml
use-extension:
  "@autorest/typescript": "6.0.0-dev.20200618.1"
```

**Comment by ellismg** [comment]
Confirmed fixed with the latest version!  Thanks, @joheredi!
