### ISSUE TITLE
[v6] Integrate with @azure/core-https ( Phase 1 )

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#681]
As part of a phased migration from to @azure/core-https we need to integrate with @azure/core-client this integration should be non-disruptive since most of the functionality has been just ported over from @azure/core-http to these 2 libraries.

We may want to add a flag to be able to switch between @azure/core-http and @azure/core-https

**Comment by xirzec** [comment]
@joheredi @sarangan12 we can consider this done, I think?

**Comment by deyaaeldeen** [comment]
Yes this is done now and the flag is `--use-core-v2`.
