### ISSUE TITLE
[v6] Cyclical dependency Client -> Operations -> Client

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#683]
Example:
 **pagingClient.ts**
![image](https://user-images.githubusercontent.com/21109913/86827402-cd21a780-c046-11ea-835a-60add7a48145.png)

**operations/paging.ts**
![image](https://user-images.githubusercontent.com/21109913/86827541-f5a9a180-c046-11ea-81da-c24d8a58100b.png)

**Comment by sarangan12** [comment]
@joheredi Currently, The Operation Class Does not depend on the Client Class. But there is a dependency on ClientContext Class (which is a parent of client class). Do you still think this issue is valid? i.e. Do you think even this dependency chain should be broken?

**Comment by joheredi** [comment]
Yeah I think the circular dependency was fixed when implementing the operation interfaces. This is how dependency looks now

- PagingClient:
   - Paging
   - PagingImpl
       - Paging
       - PagingClientContext
   - PagingClientContext
- PagingImpl
       - Paging
       - PagingClientContext

I don't think there are dependency loops anymore. We can close this issue 😄

**Comment by sarangan12** [comment]
Based on the comment from @joheredi Closing this issue
