### ISSUE TITLE
[v4] Code sample generated in the Readme file should be in JavaScript

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/autorest.typescript#699]
Currently, the code sample generated in the readme file of a generated package is in TypeScript.

To help with copy -> paste -> run code workflow, it is much easier to have the same in JavaScript than TypeScript.

There is a higher probability of TypeScript users knowing JavaScript than the other way around.

Changes would be
- Update the import statements
- Remove all "types"

**Comment by ramya-rao-a** [comment]
cc @joheredi, @sarangan12

**Comment by joheredi** [comment]
I think this makes sense. @ramya-rao-a is this something we'd like fixed for v4, v5 and v6 or only v6?

**Comment by ramya-rao-a** [comment]
Definitely v6

Not really for v5, because it is not really officially used by anyone. And those who use it do not rely on the generated sample.

Yes for v4 if it is trivial to do so. This will help all the Track 1 packages in the azure-sdk-for-js repo

**Comment by joheredi** [comment]
Thanks @ramya-rao-a fixing this in v4 shouldn't be very complex. We can use this issue to track the work in v4 and #594 for v6

**Comment by joheredi** [comment]
For reference, this is a PR with manual changes to generated samples: Azure/azure-sdk-for-js/pull/10356

**Comment by ramya-rao-a** [comment]
This was fixed in #726
