### ISSUE TITLE
The generated readme.md is wrong in creating client

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#700]
On line number 37 the second parameter for `AzureReservationAPI` is of type `AzureReservationAPIModels.AzureReservationAPIOptions` and not a subscriptionId string. Thus either variable type should be updated or we can remove it as it’s an optional field. The same needs to be updated for the html code in README.md file.
![image](https://user-images.githubusercontent.com/40835867/88253734-95249080-cce5-11ea-9ecf-0d5c1ac0e623.png)

**Comment by dw511214992** [comment]
Is there any update on it?

**Comment by dw511214992** [comment]
Thank you @joheredi 
I have fixed it manually in my pull request.

**Comment by joheredi** [comment]
Consolidating README work in https://github.com/Azure/autorest.typescript/issues/700
