### ISSUE TITLE
[v4] Update readme with link to ms-rest-nodeauth and a note on other login options

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/autorest.typescript#721]
The readme of the packages generated using the code generator have the below information around authentication
- Installation instruction for the ms-rest-nodeauth package: `npm install @azure/ms-rest-nodauth`
- Code snippet that shows how to use the `interactiveLogin()` method in the `ms-rest-nodeauth` package

What is missing here is information on the other options for login leading one to believe that interactive login is the only option.

We should add a note with a link to the ms-rest-nodeauth readme which has details on other options. Something like the below just before the node code snippet

> While the below sample shows how to authenticate using interactive login, other options are described in the [readme for @azure/ms-rest-nodeauth](https://www.npmjs.com/package/@azure/ms-rest-nodeauth) package.

Related to https://github.com/Azure/azure-sdk-for-js/issues/10993

**Comment by ramya-rao-a** [comment]
cc @joheredi, @sarangan12, @deyaaeldeen

**Comment by deyaaeldeen** [comment]
I did some investigation and found that the old version of the code generator creates this section in the README.md file [here](https://github.com/deyaaeldeen/autorest.typescript/blob/master/src/vanilla/Model/CodeModelTS.cs#L1068). However, the new version of the code generator (v6) does something different, does not inline instructions about authentication nor shows a sample. Instead it links to a broken link [here](Refer the sample code in the [azure-sdk-for-js-samples](https://github.com/Azure/azure-sdk-for-js-samples) repository.). I think we should be consistent here between the two versions and perhaps regenerate that sdk using v6.

**Comment by ramya-rao-a** [comment]
@deyaaeldeen The entire set of management libraries (the ones whose name start with `@azure/arm-`) are on v4 of the code generator. There are no current plans, atleast for this year, to upgrade them to use v6 which introduces new dependencies for auth.

Therefore, for the time being, it is still beneficial for the v4 code generator to update the readme with the above content.

**Comment by sarangan12** [comment]
I will update the v6 code generator today, @deyaaeldeen If you prefer you can take the v4 generator. Else, I will be happy to change the v4 gen also.

**Comment by deyaaeldeen** [comment]
@ramya-rao-a Thanks for the clarification!

@sarangan12 Sounds good!
