### ISSUE TITLE
[Bug] mappers are missing extension data from model 

### ISSUE THREAD

**Issue by cyptus** [Azure/autorest.typescript#732]
the code model schema data could contain custom extension data on properties which are currently not accessable by generated typescript code.
custom extensions are described by `OpenAPI` specification to follow syntax `x-*` (https://swagger.io/specification/#specification-extensions) 

example api defintion:
```yaml
components:
  schemas:
    Response:
      type: object
      properties:
        fans:
          $ref: '#/components/schemas/FanState'
          x-include: true
```

does generate the following property in `code-model-v1`: 
```json
    {
     "$id": "29",
     "isReadOnly": false,
     "realPath": [
      "fans"
     ],
     "serializedName": "fans",
     "extensions": {
      "x-include": true
     },
     ...
    }
```

and the following `mapper` typescript:
```ts
export const Response: msRest.CompositeMapper = {
  serializedName: "Response",
  type: {
    name: "Composite",
    className: "Response",
    modelProperties: {
      fans: {
        serializedName: "fans",
        type: {
          name: "Composite",
          className: "FanState"
        }
      }
    }
  }
};

```

the generated typescript file should instead make the custom extension data available the mapper file, for example like:
```ts
      fans: {
        serializedName: "fans",
        type: {
          name: "Composite",
          className: "FanState"
        },
        extensions: {
          xInclude: true
        }
      }
```

**Comment by cyptus** [comment]
@joheredi is this going to be addressed?

**Comment by joheredi** [comment]
@cyptus  thanks for bringing this up. I’d like to learn more about your scenario. What is the intended use of the x-include extension? When your response contains it, what’s the expected output/behavior?

Mappers are instructions for the serializer on how to serialize and deserialize data that goes to and from the wire. When we add something to the mapper we need also to tell the dialogue what to do.

**Comment by cyptus** [comment]
thanks for your input @joheredi 
My understanding of the generated typescript files is to get a fully working API client into your codebase.
Sometimes APIs does have custom handling of some data, thats where the x-namespace of extensions comes into play.
MS already uses this for its own custom handling (enum data e.g.), but there are also APIs out there which needs custom handling on their end.

For example our API wants the client to request optional columns explict as an paramteter and does only load this from the database if requested.
This behavoir needs to be communicated to the client and is placed inside the extension information of a column (x-include).
The extension could also contain informations for the frontend like: "this column supports filtering" (x-filter), "this column should be shown as a link to X" (x-link) and so on.

As autorest cannot address every custom behavoir like this, the information for custom handling should be available in the generated mapper files, to be addressed in the codebase which does use the generated client.
Thats why open api added this specifation.

**Comment by joheredi** [comment]
In the `x-include` case what does your server expect to get when `x-include` is true?

**Comment by cyptus** [comment]
In my case: an additional http parameter set to ?include=ColumnName

But this could be anything, custom handlings on APIs will always be custom

**Comment by cyptus** [comment]
@joheredi does this clarify the use-case?

**Comment by joheredi** [comment]
Would you mind sharing your swagger file? I think the scenario you describe should be possible to achieve defining a parameter for your operation called `include`?

Extensions are meant to add functionality to the generator that is not possible to express with the OpenAPI spec. The generators need to be aware of each extension and have logic on how to handle each extension.

Here's a list of the extensions supported by autorest: https://github.com/Azure/autorest/tree/master/docs/extensions
