### ISSUE TITLE
[v6] Autorest should use version from package.json

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#737]
Ported from https://github.com/Azure/azure-sdk-for-js/issues/11590

See https://github.com/Azure/azure-sdk-for-js/pull/10890#discussion_r482319283

Filing this as follow-up as requested.

### Repro steps
* clone this repo
* `npm install -g autorest`
* Change the version in `sdk/textanalytics/ai-text-analytics/package.json`
* Run `autorest` in `sdk/textanalytics/ai-text-analytics/swagger`

### Expected behavior
* Generated code in `sdk/textanalytics/ai-text-analytics/src/generated/generatedClientContext.ts` has version matching change made to package.json

### Actual behavior
* Generated code uses version in  sdk/textanalytics/ai-text-analytics/swagger/README.md

### Notes
* Removing the version from autorest README.md does not help, it then defaults to generating 1.0.0
* This is mostly harmless as generatedClientContext.ts is updated automatically by the versioning tools + //metadata/constantPaths in package.json. So after the version is bumped by this process, the next time someone runs autorest they will see an unexpected diff and probably just edit README.md and the bad version will never get checked in.
* It is possible to keep everything automatically by adding a directive to //metadata/constantPaths for the autorest README.md. That's what I did for schema registry (which led to some surprise that it was necessary and this issue.) It doesn't seem too bad to me so if we decide not to make a fix/feature for this, maybe we should just do that everywhere?

cc @nguerrera  @xirzec

**Comment by ramya-rao-a** [comment]
#1156 tracks the need to generate the //metadata/constantPaths in the package.json file which should cover the 3rd point in the notes above

With that and the automation in place, we should be good here.
