### ISSUE TITLE
[v6] Should avoid name collisions

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#738]
For example [this](https://github.com/Azure/azure-sdk-for-js/blob/a3f90de4dcc0bf9a8b7f4869914410552820fb0f/sdk/api-learn/design-activity/swagger/computation.json#L109) swagger would produce a name collision in operation group and top-level operation. Both called `computation`.

We should generate non colliding names, at the bare minimum `computation` and `computation1` or throw an error indicating that the swagger definition is ambiguous 

//cc: @xirzec

**Comment by daviwil** [comment]
Is this a TypeScript generator issue or is something that modelerfour should handle?  I don't think that generators should have to deal with this unless there are language-specific naming conventions that cause further collisions.

**Comment by joheredi** [comment]
That's a good question, let me debug and see if this is language specific. There are other examples of collisions for example, an operation named client would collide with the private client property in the operation group class, however this instance is TS generator specific

**Comment by joheredi** [comment]
This issue seems related: https://github.com/Azure/autorest.typescript/issues/708

**Comment by sarangan12** [comment]
Code complete with PR https://github.com/Azure/autorest.typescript/pull/779
