### ISSUE TITLE
Add test coverage for Non-string-enums test server scenarios

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#745]
- [ ] [`NonStringEnumsGetFloat`](https://github.com/Azure/autorest.testserver/search?q=NonStringEnumsGetFloat)
- [ ] [`NonStringEnumsGetInt`](https://github.com/Azure/autorest.testserver/search?q=NonStringEnumsGetInt)
- [ ] [`NonStringEnumsPostFloat`](https://github.com/Azure/autorest.testserver/search?q=NonStringEnumsPostFloat)
- [ ] [`NonStringEnumsPostInt`](https://github.com/Azure/autorest.testserver/search?q=NonStringEnumsPostInt)

Bug  https://github.com/Azure/autorest.typescript/issues/742 should be addressed when adding this coverage

**Comment by sarangan12** [comment]
- [X] [`NonStringEnumsGetFloat`](https://github.com/Azure/autorest.testserver/search?q=NonStringEnumsGetFloat) - Already completed [here](https://github.com/Azure/autorest.typescript/blob/v6/test/integration/nonStringEnum.spec.ts#L10)
- [ ] [`NonStringEnumsGetInt`](https://github.com/Azure/autorest.testserver/search?q=NonStringEnumsGetInt)
- [ ] [`NonStringEnumsPostFloat`](https://github.com/Azure/autorest.testserver/search?q=NonStringEnumsPostFloat)
- [ ] [`NonStringEnumsPostInt`](https://github.com/Azure/autorest.testserver/search?q=NonStringEnumsPostInt)

**Comment by sarangan12** [comment]
Related PR: https://github.com/Azure/autorest.typescript/pull/763.
