### ISSUE TITLE
Add coverage for missing xms-error-responses test server scenarios

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#749]
[Swagger](https://github.com/Azure/autorest.testserver/blob/ee473a350ebd680a728acda7d3bbd4334e9826a0/swagger/xms-error-responses.json)
- [ ] [`animalNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=animalNotFoundError)
- [ ] [`expectedNoErrors`](https://github.com/Azure/autorest.testserver/search?q=expectedNoErrors)
- [ ] [`expectedPetHungryError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetHungryError)
- [ ] [`expectedPetSadError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetSadError)
- [ ] [`linkNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=linkNotFoundError)
- [ ] [`intError`](https://github.com/Azure/autorest.testserver/search?q=intError)
- [ ] [`stringError`](https://github.com/Azure/autorest.testserver/search?q=stringError)

**Comment by sarangan12** [comment]
Code complete with this PR https://github.com/Azure/autorest.typescript/pull/765
