### ISSUE TITLE
Add coverage for missing body-array test server scenarios

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#750]
[Swagger](https://github.com/Azure/autorest.testserver/blob/ee473a350ebd680a728acda7d3bbd4334e9826a0/swagger/body-array.json)
- [x] [`getArrayComplexValid`](https://github.com/Azure/autorest.testserver/search?q=getArrayComplexValid)
- [x] [`getArrayDateTimeWithInvalidChars`](https://github.com/Azure/autorest.testserver/search?q=getArrayDateTimeWithInvalidChars)
- [x] [`getArrayDateTimeWithNull`](https://github.com/Azure/autorest.testserver/search?q=getArrayDateTimeWithNull)
- [x] [`putArrayBooleanValid`](https://github.com/Azure/autorest.testserver/search?q=putArrayBooleanValid)
- [x] [`putArrayComplexValid`](https://github.com/Azure/autorest.testserver/search?q=putArrayComplexValid)

**Comment by sarangan12** [comment]
Code complete
