### ISSUE TITLE
[V4] Miscompilation of AzureServiceClientOptions

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/autorest.typescript#762]
When I regenerated the batch sdk here https://github.com/Azure/azure-sdk-for-js/pull/9878, I got this incorrect change:
```
-  constructor(credentials: msRest.ServiceClientCredentials, batchUrl: string, options?: msRestAzure.AzureServiceClientOptions) {​​​​​​​
+  constructor(credentials: msRest.ServiceClientCredentials, batchUrl: string, options?: msRest.AzureServiceClientOptions) {​​​​​​​


```

**Comment by ramya-rao-a** [comment]
@deyaaeldeen Can you share if this is still a problem?

**Comment by deyaaeldeen** [comment]
I did not see it happen since so we can probably close this and we can always re-open if it happens again.
