### ISSUE TITLE
[V6] Generate a mocha stub test suite

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/autorest.typescript#766]
- generate a mocha stub test suite in `test/<service name>Client.spec.ts`.
- add a test script to `package.json` as follows: `"test": "mocha -r esm --require ts-node/register test/*.spec.ts --timeout 1200000 --full-trace"`.
- add to dev dependencies in `package.json` `mocha`, `esm`, and `ts-node`.
- consider generating basic tests for the APIs.

**Comment by ramya-rao-a** [comment]
@joheredi, Is this covered in your recent discussions with @dw511214992 ?

**Comment by dw511214992** [comment]
@deyaaeldeen In https://github.com/Azure/autorest.typescript/pull/1215, I think I also generate some basic test in HLC. Could you please check whether it meets your requirements? thanks

**Comment by joheredi** [comment]
I think this is in the scope of either the issue that @dw511214992 mentioned above or the package onboarding work tracked by https://github.com/Azure/azure-sdk-for-js/issues/18060.

**Comment by ramya-rao-a** [comment]
Either way, we can close this then :)
