### ISSUE TITLE
api-version is missed in operation `listNext`

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#770]
In opeartion `listNext`, the `api-version` is missed in path. you can find the code [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/synapse/arm-synapse/src/operations/workspaces.ts#L471)

**Comment by joheredi** [comment]
Thanks for reporting this issue @dw511214992. I'll take a look

**Comment by joheredi** [comment]
@dw511214992 I would expect the service to return a `nextLink` containing all the info it needs to be called, including the api-version i.e.  `/page/2?api-version=2020-10-22`.

Pulling all the query params from `list()` into `listNext()` can cause conflicts or unintended overrides to other queryParams returned by services in `nextLink`

**Comment by dw511214992** [comment]
hi @joheredi I have seen https://github.com/Azure/autorest.common/pull/58/files is merged. When will it be released? After released, we need to check with service team whether the swagger is ready for release new sdk. And then we need to do release for this js sdk. thanks

**Comment by joheredi** [comment]
I have published a [v4.4.4 of Autorest.Typescript](https://www.npmjs.com/package/@microsoft.azure/autorest.typescript/v/4.4.4) which includes this fix.

@dw511214992 can you please re-generate the library and verify if the issue is resolved?

**Comment by dw511214992** [comment]
@joheredi  I have regenerate the code and the issue should be fixed. A pr is create: https://github.com/Azure/azure-sdk-for-js/pull/12075
