### ISSUE TITLE
Can't correctly import CloudErrorBody if an object is refering to CloudErrorBody directly.

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#777]
If an object is reference to CloudErrorBody directly. the generated SDK will not import CloudErrorBody from @azure/ms-rest-azure-js. Which causing the sdk fail to build https://github.com/Azure/azure-rest-api-specs/pull/11366/files#diff-57b96402ec17bd8f6e8ace7ff8bf6eaba95a6a0130b8aacae30b02ce134f9242R2864-R2872

![image](https://user-images.githubusercontent.com/55688292/97144855-2b15fe80-17a0-11eb-9316-6712e28cedfb.png)

It also seems that there's no definition for CloudErrorBody in @azure/ms-rest-azure-js

**Comment by joheredi** [comment]
Thanks for reporting! I'll take a look and update when I have more information

**Comment by joheredi** [comment]
@qiaozha do you know why CloudErrorBody is being marked as `x-ms-external`? as you said, ms-rest-js doesn't have a definition fro `CloudErrorBody`, this will be fixed if the `x-ms-external` flag is removed from [the definition](https://github.com/Azure/azure-rest-api-specs/blob/e44bedeaf76845d9ef49965cad882c270e4019b1/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2020-11-01/managedClusters.json#L3167).

Looking at other Swaggers it looks like only `CloudError` should be external, but `CloudErrorBody` shouldn't, here's one example:
https://github.com/Azure/azure-rest-api-specs/blob/fa2234010314e10e254a479644327b9cb7643d39/specification/iotcentral/resource-manager/Microsoft.IoTCentral/stable/2018-09-01/iotcentral.json#L640

**Comment by qiaozha** [comment]
I see. Thanks. According to the document here https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-external, the x-ms-external means the schema will not be generated and it will be import from the library ? 
When we remove that x-ms-external flag, it will generate a CloudErrorBody locally. 
![image](https://user-images.githubusercontent.com/55688292/97248040-da53e380-183b-11eb-9312-cd9ff291d6ef.png)

**Comment by joheredi** [comment]
@qiaozha, you are right. Removing the `x-ms-external` from CloudErrorBody definition will stop trying to import it and will generate it locally

**Comment by deyaaeldeen** [comment]
@qiaozha I think this issue is now resolved. Please feel free to reopen it if you think it is not.
