### ISSUE TITLE
Revisit LRO generated operations

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#785]
Revisit LRO generated operations and evaluate if we can align better with the Typescpt SDK guidelines and the hand-written LROs in Azure/azure-sdk-for-js repo. Some examples:

https://github.com/Azure/azure-sdk-for-js/blob/6bcfe0d943662784f196561a5bb48c05460b0b8f/sdk/keyvault/keyvault-certificates/src/index.ts#L693

https://github.com/Azure/azure-sdk-for-js/blob/6bcfe0d943662784f196561a5bb48c05460b0b8f/sdk/formrecognizer/ai-form-recognizer/src/formRecognizerClient.ts#L306

- [x] Support pollingInterval
- [ ] prefix operation with `begin` #785
- [x] Support rehidrating the poller by passing poller state
- [ ] Log polling status at `info` level
- [x] Progress reporting

Guidelines: https://azure.github.io/azure-sdk/typescript_design.html#ts-lro

**Comment by joheredi** [comment]
Received the following feedback from @qiaozha that we should consider.

In addition to providing an operation that returns the poller, it'd be helpful for customers to also have a function that performs the polling internally and just returns the response.

Another thing is that to align with the guidelines we need to rename the operations that return a poller to be prefixed with **begin**

**Comment by joheredi** [comment]
I talked to Brian about adding a function that performs the polling internally and just returns the response.

We would not like to expose a function that returns the Poller result. The reason is that these operations may take days to complete and wrapping them in a function that returns the final result will be misleading and potentially painful for the users. 

Additionally, none of the other languages are currently exposing this method, if we were to implement it, we’d need to do it consistently across generators

**Comment by qiaozha** [comment]
The current track1 SDK is to return the result directly and customers can still use beginXXX to get a poller if they like. https://github.com/Azure/azure-sdk-for-js/blob/b679003645bceac0685826ead6e2df5a02b86322/sdk/compute/arm-compute/src/operations/disks.ts#L40 

Not sure about other languages' SDKs but the Python track2 SDK will return a ARMPoller by default, and azure-mgmt-core will handle that poller. 
https://github.com/Azure/azure-sdk-for-python/blob/0bab49318faf4ef10193c9d99fe7766568430cdd/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2020_09_30/operations/_disks_operations.py#L136. 
![image](https://user-images.githubusercontent.com/55688292/111108654-47baa380-8594-11eb-8140-9b6bfbe9c265.png)
As you can see, if the polling is not set, it will set as true by default and set the poller as ARMPoller.  
In that way, we can say it returns the result directly. @lmazuel @iscai-msft Correct me if I am wrong. Thanks

I guess both ways are fine with me. As long as we don't require the customer to write such kind of logic by default.  As it would be a big breaking changes for our customers.
```
 return this.beginCreateOrUpdate(resourceGroupName,diskName,disk,options)
      .then(lroPoller => lroPoller.pollUntilFinished()) as Promise<Models.DisksCreateOrUpdateResponse>;
```
 
cc @lirenhe @nickzhums

**Comment by deyaaeldeen** [comment]
@qiaozha I opened a separate issue for your request here: https://github.com/Azure/autorest.typescript/issues/938

This issue as originally described is now resolved.
