### ISSUE TITLE
Generate Rush metadata

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#791]
So that generated packages can be plugged into the azure-sdk-for-js easier.

**Comment by ramya-rao-a** [comment]
Don't we do this by now?

**Comment by sarangan12** [comment]
@ramya-rao-a No. We do not update anything related to rush. Actually, I doubt if we will ever support this feature directly in the generator. As a stand alone task, this requirement is outside the generator. I would recommend using a script which does this requirement + invoking the generator command.

**Comment by ramya-rao-a** [comment]
I don't think this task is about updating rush.json files, perhaps this was about rush related things in the generated code?
@joheredi Can you clarify?

**Comment by joheredi** [comment]
Yeah I think this was originally created to update rush.json. However, I agree with Sarangan that this is probably out of the scope of the generator.

@dw511214992 is currently working on an automation tool to onboard generated packages, which updates the rush.json file. I'll close this issue, but feel free to re open if you disagree or would like to discuss further.

**Comment by joheredi** [comment]
This is the issue tracking the tooling work: https://github.com/Azure/azure-sdk-for-js/issues/18060
