### ISSUE TITLE
Test generated code in other node versions

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#797]
Have a test matrix to make sure that the generated code works across node versions

**Comment by ramya-rao-a** [comment]
@joheredi Let's make sure we do this for v4 of the code generator as well as it powers all the management plane libraries at the moment

**Comment by joheredi** [comment]
We already test Node 10, 12 and 14 in CI.  We may need to update to include node 16.
@sarangan12 do you think we still need to port these to v4x as well, now that management is migrating to v6?

**Comment by ramya-rao-a** [comment]
@joheredi, At this point, we can skip v4 as mgmt plane packages will move to v6 in the next few months.

@sarangan12, We can remove Node.js 10 now as it is out of support scope now. And we should add Node.js 16
