### ISSUE TITLE
msRest.URLBuilder not in published ms-rest package

### ISSUE THREAD

**Issue by ProTip** [Azure/autorest.typescript#80]
I'm getting errors from the generated code in regards to URLBuilder not being in ms-rest.

This appears to have been added to ms-rest in the past few days, however the package published to npm is much older.

**Comment by daschult** [comment]
@ProTip You can work around this problem until we solve our releasing process by specifying the following in your command line arguments:
`autorest --typescript --use=@microsoft.azure/autorest.typescript@2.0.176`
That should run the previous version of the TypeScript generator and should get you back in a good state.

**Comment by RikkiGibson** [comment]
Yes, and we'll do some work on our side to ensure that our releases of these interdependent packages are in sync moving forward.

**Comment by daschult** [comment]
The latest preview versions of `ms-rest-js` and `autorest.typescript` both have fixed this problem.
