### ISSUE TITLE
Fix tracing static files

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#814]
#### package.json
- [x] Missing `"@opentelemetry/api": "^0.10.2",` dependency

#### rollup config
- [ ] Missing cjs namedExports
![image](https://user-images.githubusercontent.com/21109913/101538217-9cc19a80-3951-11eb-885d-0a3642db8648.png)

**Comment by sarangan12** [comment]
@joheredi Could you please confirm if this task is already completed? I am able to see the expected changes in the generated code.

**Comment by joheredi** [comment]
Yes this is fixed already #954 added rollup config and  #790 the dependency in package
