### ISSUE TITLE
[v4] Support @azure/identity for authentication

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#815]
Update the v4 code generator to add a constructor overload that takes a TokenCredential instead of ServiceClientCredentials. Internally, this can create the credentials using the code snippet shared in Jon's adapter. This requires the generated code to take dependency on @azure/core-auth

For more context see: https://github.com/Azure/azure-sdk-for-js/issues/11359

**Comment by ramya-rao-a** [comment]
This is done as part of #846
