### ISSUE TITLE
Support Swagger outside the Azure SDK for AutoRest v3

### ISSUE THREAD

**Issue by seaki-msft** [Azure/autorest.typescript#824]
**Describe the issue or request**
We are using AutoRest in our [repo](https://github.com/Azure/Connectors) to translate swagger files into typescript. However, we ran into several issues running AutoRest V3 because swaggers outside the Azure SDK is not supported in AutoRest v3. We use connectors swagger files and here is the [list of swagger files](https://github.com/Azure/Connectors/tree/preview/sdk/swaggers/ms-services/released) 

**An example of error**
Input: [onedriveforbusiness swagger file](https://github.com/Azure/Connectors/blob/preview/sdk/swaggers/ms-services/released/onedriveforbusiness.json)
```
node.exe : An error was encountered while handling a request: Error: There is no known Mapper type for schema type binary
At C:\Users\seaki\AppData\Roaming\npm\autorest.ps1:15 char:3
+   & "node$exe"  "$basedir/node_modules/autorest/entrypoints/app.js" $ ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error was en...ema type binary:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    at Object.getMapperTypeFromSchema 
(C:\Users\seaki\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\transforms\mapperTransforms.js:524:19)
    at getSpecType (C:\Users\seaki\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\transforms\operationTransforms.js:127:43)
    at getMapperForSchema (C:\Users\seaki\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\transforms\operationTransforms.js:324:26)
    at transformOperationResponse 
(C:\Users\seaki\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\transforms\operationTransforms.js:181:15)
    at C:\Users\seaki\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\transforms\operationTransforms.js:234:56
    at Array.map (<anonymous>)
    at transformOperation (C:\Users\seaki\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\transforms\operationTransforms.js:234:40)
    at C:\Users\seaki\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\transforms\operationTransforms.js:275:85
    at Array.map (<anonymous>)
    at transformOperationGroup (C:\Users\seaki\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\transforms\operationTransforms.js:275:68)
FATAL: Error: There is no known Mapper type for schema type binary
  Error: Plugin typescript reported failure.
```

**Comment by joheredi** [comment]
@seaki-msft thanks for bringing this up. I'm looking into this issue I'll come back soon with more information.

**Comment by daviwil** [comment]
@seaki-msft Hey Sean, we recently updated the default versions of several language generators in AutoRest v3, that's why you're getting this error suddenly.  I'd recommend adding the `--v2` parameter to your AutoRest invocations for now until you've been able to test the Connector code generation more thoroughly with the new TypeScript generator.

**Comment by seaki-msft** [comment]
Okay we will add --v2 for now. However, we would like to start using v3; are you planning to support swagger outside the Azure SDK in v3?

**Comment by daviwil** [comment]
I don't think that the TypeScript generator has any limitation for being used in the Azure SDK, I believe the issue you hit must just be a bug in the generator that can be fixed.  Jose is the right person to ask about that though :)

**Comment by sarangan12** [comment]
I can confirm that outside swaggers are supported and there are no restrictions. But, for that the swagger must follow the autorest guidance suggested at https://github.com/Azure/autorest/tree/main/docs. Closing this issue
