### ISSUE TITLE
investigate supporting --client-side-validation

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#829]
Other languages support this flag

>Whether you want the SDK to perform validation on inputs and outputs, based on swagger information. Recommended to be `false` for track 2 code, since we want the network to validate instead. Defaults to `false`.

**Comment by ramya-rao-a** [comment]
@sarangan12 Please check back with the autorest feature crew about this. Do we have cases where this flag was useful? From what I recall the recommendation was always to avoid client side validation and expect the service to throw proper errors for wrong input

**Comment by deyaaeldeen** [comment]
I checked with @lmazuel on this and he said Python has validation behind a flag which defaults to not validate. I also was told that .NET and Java do not do validation.

Validation by default is problematic because the swagger may not be accurate or the service behavior can change for whatever reason anytime.

JS is the outlier here and it does not follow the guidelines.

**Comment by joheredi** [comment]
Thanks for following up @deyaaeldeen! I agree we should disable validation, not even sure if it is worth keeping a flag.
Also, I was trying to find the guideline about no client-side validation but couldn't find it, it may be worth taking the time to add it in the General Guidelines as this seems to apply to all languages

**Comment by deyaaeldeen** [comment]
@joheredi I believe it is this one: https://azure.github.io/azure-sdk/general_implementation.html#general-params-server-validation

**Comment by joheredi** [comment]
Awesome! Thanks Deyaa

**Comment by sarangan12** [comment]
@deyaaeldeen Thanks for the investigation on this issue.

@joheredi I understand that we do not have to support client side validation. I know Python take a slightly different approach of supporting it based on flag) I would recommend that we follow the .NET/Java approach and not implement any validation.

But, I am little confused about the statement: `JS is the outlier here and it does not follow the guidelines.`. Atleast in the v6 generator, we do not support any validations/`client-side-validation` flag. Am I missing something? Is there anything pending on this issue or can it be closed?

**Comment by joheredi** [comment]
@sarangan12 I `core-client` does some client-side validation based on the mappers. For example:

https://github.com/Azure/azure-sdk-for-js/blob/c3136d6b83dcb2d2e105451499404891082bf16d/sdk/core/core-client/src/serializer.ts#L28

I think there are a few client-side validations we do similar to this

**Comment by sarangan12** [comment]
@joheredi Thanks for pointing that. I concur with you that validations should be removed. The correct place for the issue will be the JS repository. I have created an issue https://github.com/Azure/azure-sdk-for-js/issues/19089 for the same (and linked this there). Closing this issue.

**Comment by deyaaeldeen** [comment]
@sarangan12 Thanks for following up on this issue. I think one question remains which is do we still want the auto-generated mappers to include the constraints and is it worth it to remove them?

**Comment by sarangan12** [comment]
@deyaaeldeen My vote is yes. We are translating everything that is provided in the swagger. So, we could continue the same. However, we have made a org decision that we will not *act* upon it i.e. not validate it. I am open to alternative viewpoints too
