### ISSUE TITLE
Broken link in generated README.md

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/autorest.typescript#830]
Version: 6.0.0-dev.20201204.2

The attestation sdk was autogenerated and the `README.md` was generated with the following:
```
#### Sample code

Refer the sample code in the [azure-sdk-for-js-samples](https://github.com/Azure/azure-sdk-for-js-samples) repository.
```

The hyperlink is invalid.

**Comment by sarangan12** [comment]
@deyaaeldeen This issue has been fixed with PR https://github.com/Azure/autorest.typescript/pull/839. If you are Ok with the fix, You can close this bug.
