### ISSUE TITLE
Hide the Client and Client Context Classes (from the Generated Layer) in the docs

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest.typescript#832]
While working on migrating AppConfiguration SDK from old SDK generator to the new V6 generator, @richardpark-msft pointed out that the client and client context classes are showing up in docs. This should be avoided since we do not want the inner workings of the SDK to be exposed (when there is a custom layer)

I agree that the client and client context classes within the generated layer should be hidden. But a few points to discuss before that:

1. **Should such hiding be restricted only to Client and Client Context Classes within the generated layer? Or Should it include all the definitions in models, mappers, parameters, etc?** 

To answer this question, let us see what is happening today in the master branch. In the master branch, only the client and client context classes are hidden. Other definitions (from models, parameters, etc.) are not hidden. 

For example, Let us look at the ```AppConfigurationPutKeyValueOptionalParams``` defined [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/appconfiguration/app-configuration/src/generated/src/models/index.ts). It is not used outside the generated layer. But, it is exposed in docs. Should we continue this behavior? 

My recommendation is, Yes. We should expose everything in the generated layer, except Client and Client Context Class. The reason is since the methods inside the classes are not exposed, the user cannot use the other models that are exposed from the generated layer. Also, it is not possible to determine which object to expose during the SDK generation. If we hide everything, it would be a difficult manual job to expose them later. 

2. **How should we hide them?** 

Again, let us see what is happening today in the master branch. In the master branch, the client and client context files are not hidden explicitly. Take a look [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/appconfiguration/app-configuration/src/generated/src/appConfiguration.ts). It is not exported at the point of definition at line 17. But it is exported separately at the end. 

Though the semantics of this type of export is exactly same as exporting it at the time of definition, ```npm run docs``` considers them as different. If you have ```export``` at the time of definition, then it will be included in the docs. If the export is happening separately from the definition, it will not be included in the docs. I tried searching online. But, could not find much reference o this feature. At this point, it seems more like a bug than a feature. 

So, the correct solution might be adding a hidden tag (in the documentation comments) before the client and client context classes. 

But, I do not want to add this tag flat out for all the packages. Because, in the future we might have packages with no custom layer. So, I have introduced an option has-custom-layer to determine if we need to ad hidden tag.

**Comment by ramya-rao-a** [comment]
cc @joheredi, @deyaaeldeen

**Comment by deyaaeldeen** [comment]
@ramya-rao-a actually @sarangan12 already fixed it here: https://github.com/Azure/autorest.typescript/pull/831 and @joheredi and I reviewed it.

**Comment by sarangan12** [comment]
Code complete with PR https://github.com/Azure/autorest.typescript/pull/831
