### ISSUE TITLE
Enum types generating unexpected union types

### ISSUE THREAD

**Issue by r3dDoX** [Azure/autorest.typescript#837]
We noticed an unexpected behavior in the generation of union types. The following OpenApi spec part:

```
// PrintInfo sits under: components -> schemas, since our specis very big I removed everything around it
{
  "PrintInfo": {
    "title": "PrintInfo",
    "type": "object",
    "properties": {
      "pngData": {
        "type": "string",
        "format": "byte"
      },
      "printMediaType": {
        "type": "string",
        "enum": [
          "ENDLOS",
          "MEHRFAHRTENKARTE"
        ]
      }
    }
  }
}
```
generates the following union type for "printMediaType":

`
export type PrintInfoPrintMediaType = "ENDLOS" | "MEHRFAHRTENKARTE" | string;
`

We expected there to be no " | string" since our enum has two clear values:

`
export type PrintInfoPrintMediaType = "ENDLOS" | "MEHRFAHRTENKARTE";
`

Version Info:
```
AutoRest code generation utility [cli version: 3.0.6322; node: v14.15.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\e527245\.autorest\@autorest_core@3.0.6338\node_modules\@autorest\core\dist' (3.0.6338)
   Loading AutoRest extension '@autorest/typescript' (6.0.0-dev.20201105.2->6.0.0-dev.20201105.2)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)

```

**Comment by sarangan12** [comment]
@r3dDoX Thanks for reporting this issue. I will check and update the issue shortly.

**Comment by sarangan12** [comment]
@r3dDoX Could you please give me the complete swagger? I think some of the ```x-ms-enum``` properties that are defined in the swagger might be missing in the comment above. So, Please provide me the complete swagger file for verification

**Comment by sarangan12** [comment]
@r3dDoX After further analysis, I find that the specific snippet provided in the description will not generate the TS code mentioned in the description. It will generate the following TS Code:

```js
/** PrintInfo */
export interface PrintInfo {
  pngData?: Uint8Array;
  printMediaType?: PrintInfoPrintMediaType;
}

/** Known values of {@link PrintInfoPrintMediaType} that the service accepts. */
export const enum KnownPrintInfoPrintMediaType {
  Endlos = "ENDLOS",
  Mehrfahrtenkarte = "MEHRFAHRTENKARTE"
}

/**
 * Defines values for PrintInfoPrintMediaType. \
 * {@link KnownPrintInfoPrintMediaType} can be used interchangeably with PrintInfoPrintMediaType,
 *  this enum contains the known values that the service supports.
 * ### Know values supported by the service
 * **ENDLOS** \
 * **MEHRFAHRTENKARTE**
 */
export type PrintInfoPrintMediaType = string;
```

I understand this is not the expected value. The expected value is supposed to be:

```
export type PrintInfoPrintMediaType = "ENDLOS" | "MEHRFAHRTENKARTE";
```

Now, this is a bug in modelerfour project and I will work internally to fix it. In the meantime, you could modify the swagger as shown below:

```
{
  "PrintInfo": {
    "title": "PrintInfo",
    "type": "object",
    "properties": {
      "pngData": {
        "type": "string",
        "format": "byte"
      },
      "printMediaType": {
        "type": "string",
        "enum": [
          "ENDLOS",
          "MEHRFAHRTENKARTE"
        ],
       "x-ms-enum": {
              "name": "printMediaType",
              "modelAsString": false,
              values: [
                 {
                "value": "ENLOS",
                "description": "ENLOSE"
                },
                {
                "value": "MEHRFAHRTENKARTE",
                "description": "MEHRFAHRTENKARTE"
                }
              ],
       }
      }
    }
  }
}
```

This will solve your problem for now. I will fix the bug and update this PR soon.

**Comment by sarangan12** [comment]
After further analysis, I have found that this issue is happening in the AutoRest. The TS SDK Generator receives the Code Model from Autorest which sets the ```SchemaType``` of this enum to ```Choice```. It is not correct. It must be ```SealedChoice```. 

I have created an issue https://github.com/Azure/autorest/issues/3797 in the Autorest repository.  Will follow up with the Autorest team to fix the issue and provide an update here.

**Comment by r3dDoX** [comment]
@sarangan12 Thank you for the fast analysis. Sorry that I am slow to respond, I forgot to check my Github Notifications in the last couple days. I will follow the Bug you opened then 👍

**Comment by sarangan12** [comment]
We are following this in the issue https://github.com/Azure/autorest/issues/3797. If this is fixed in autorest, then it will be resolved in Typescript with no further code change. As there are no pending action items, I am closing this issue.
