### ISSUE TITLE
[LRO] LRO operations should support intervalInMs

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#850]
When an operation that returns a poller is generated, its optionalParams should include an optional `intervalInMs` to be passed to the Poller constructor

According to TS guidelines: https://azure.github.io/azure-sdk/typescript_design.html#ts-lro

**Comment by deyaaeldeen** [comment]
Has been resolved by https://github.com/Azure/autorest.typescript/pull/922
