### ISSUE TITLE
ADL for JavaScript (January-June 2021)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/autorest.typescript#862]
This tracks the work for ADL for JavaScript.

**Comment by daviwil** [comment]
"ADL for JavaScript" isn't really necessary, nor is ADL for any particular language.  Everything is going through AutoRest so whether its ADL or Swagger, the code generator doesn't really need to know anything.

**Comment by sarangan12** [comment]
Closing this issue as there are no more action items
