### ISSUE TITLE
Missing body parameter for PUT operation

### ISSUE THREAD

**Issue by sigmer** [Azure/autorest.typescript#872]
We have a PUT operation that requires a body parameter like this,
```
{
  "name": "authorization",
  "description": "An ExpressRoute Circuit Authorization",
  "in": "body",
  "required": true,
  "schema": {
    "$ref": "#/definitions/ExpressRouteAuthorization"
  }
}
```
All the properties on the referenced `ExpressRouteAuthorization` definition are `readonly`. This results in a method signature without this parameter, like:
```typescript
createOrUpdate(resourceGroupName: string, privateCloudName: string, authorizationName: string, options?: msRest.RequestOptionsBase): Promise<Models.AuthorizationsCreateOrUpdateResponse>
```
When I expect:
```typescript
createOrUpdate(resourceGroupName: string, privateCloudName: string, authorizationName: string, authorization: Models.ExpressRouteAuthorization, options?: msRest.RequestOptionsBase): Promise<Models.AuthorizationsCreateOrUpdateResponse>
```

The full swagger is [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/vmware/resource-manager/Microsoft.AVS/stable/2020-03-20/vmware.json).

I realize that since all the properties are `readonly` that the parameter value will just be `{}` but the empty object is in fact what the api needs. This is an ARM api and ARM does not allow an empty body in a resource PUT operation. It needs the resource object in the body and in this case, the resource object sans readonly props is `{}`.

This problem was also discussed in [this issue](https://github.com/Azure/autorest.typescript/issues/452).

Also, [autorest.python](https://github.com/Azure/autorest.python) had the same problem and it has been fixed so that this same swagger spec generates a client that allows for the `{}` body param.

cc @ctaggart

**Comment by sigmer** [comment]
Any thoughts on this? @amarzavery ?

**Comment by sarangan12** [comment]
With the latest v6 generator this issue has been fixed and the signature looks as:

```
async beginCreateOrUpdate(
    resourceGroupName: string,
    privateCloudName: string,
    authorizationName: string,
    authorization: ExpressRouteAuthorization,
    options?: AuthorizationsCreateOrUpdateOptionalParams
  ): Promise<
    PollerLike<
      PollOperationState<AuthorizationsCreateOrUpdateResponse>,
      AuthorizationsCreateOrUpdateResponse
    >
  > {}
```

Closing this issue
