### ISSUE TITLE
Extensible enum and polimophic discriminator?

### ISSUE THREAD

**Issue by jeremymeng** [Azure/autorest.typescript#874]
https://github.com/Azure/azure-sdk-for-js/pull/13363#discussion_r564022242

In Metrics Advisor, the enums are [used as the discriminator for union types][]. With the move to the V6 code gen, the two become incompatible.  @joheredi any ideas?

```diff
-export type DataSourceType = "AzureApplicationInsights" | "AzureBlob" | "AzureCosmosDB" | "AzureDataExplorer" | "AzureDataLakeStorageGen2" | "AzureTable" | "Elasticsearch" | "HttpRequest" | "InfluxDB" | "MongoDB" | "MySql" | "PostgreSql" | "SqlServer";
+export type DataSourceType = string;
```

[used as the discriminator for union types]:https://github.com/Azure/azure-sdk-for-js/blob/241aeb77e8fae0bedca44612349a7a7751cb0620/sdk/metricsadvisor/ai-metrics-advisor/src/generated/models/index.ts#L555-L568

**Comment by KarishmaGhiya** [comment]
https://github.com/Azure/azure-sdk-for-js/pull/14067 reverts the issue we had about string literals. @jeremymeng is there anything else you'd like to be addressed?

**Comment by sarangan12** [comment]
@jeremymeng I have looked into this issue. Here are my observations:

The `dataSourceType` looks like this in the swagger:

```
"dataSourceType": {
    "description": "data source type",
    "enum": [
        "AzureApplicationInsights",
        "AzureBlob",
        "AzureCosmosDB",
        "AzureDataExplorer",
        "AzureDataLakeStorageGen2",
        "AzureEventHubs",
        "AzureLogAnalytics",
        "AzureTable",
        "InfluxDB",
        "MongoDB",
        "MySql",
        "PostgreSql",
        "SqlServer"
    ],
    "type": "string",
    "x-ms-enum": {
        "name": "DataSourceType",
        "modelAsString": true
    }
}
```

As you can see, in the above case, specifically, the `modelAsString` is set to `true`. But, the old generator generated the following code:

```
export type DataSourceType = "AzureApplicationInsights" | "AzureBlob" | "AzureCosmosDB" | "AzureDataExplorer" | "AzureDataLakeStorageGen2" | "AzureTable" | "Elasticsearch" | "HttpRequest" | "InfluxDB" | "MongoDB" | "MySql" | "PostgreSql" | "SqlServer";
```

Now, this is a bug. There has to be a `| string` at the end. Now, if you add that the compiler will just turn it to `string`. That was the reason for the current changes as:

```
export type DataSourceType = string;
```

with `KnownXYZ` values added. So, This code will not be changed. 

As there are no more action items for this task, I am closing this task. If you feel this has to be changed, feel free to reopen the task. Thanks
