### ISSUE TITLE
Use @internal instead of @hidden

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#876]
Quoting from Azure/azure-sdk-for-js/issues/13447

> Please follow the following guidelines:
> 
> * use the `@internal` tag only for definitions that are not exported by `src/index.ts` and you do not want to generate documentation for them on `docs.microsoft.com`
> * use the `@hidden` tag only for definitions that are exported by `src\index.ts` but you still do not want to generate documentation for them on `docs.microsoft.com`
> * do not use both `@internal` and `@hidden` for one definition

**Comment by sarangan12** [comment]
@ramya-rao-a Let me explain:

1. Currently we have a flag `--hide-client` in the generator. If you use this option, there will be a `@internal` tag added for generated client and client context classes. When there is a custom layer, we do not export the generated client and client context classes. So, this abides by the point 1 mentioned in the issue description. 
2. Also, we do not use `@hidden` tags anywhere. So, point 3 mentioned in the issue description is not violated. 
3. The only issue is with one specific scenario. Let us consider Model A which is in the generated layer and there is an override in the custom layer. We will export the one defined in the custom layer. 

So, while generating the docs, the docs should be generated only for Model A generated in the custom layer and should ignore the one defined in the generated layer. Currently, this does not happen. This will happen only if you add `@internal` tag to the models generated in the custom layer. But, that will create other problems (for models which do not have override in the custom layer). 

So, this issue needs further discussion to see if it is possible or worth to do such code change. That is the reason, I am keeping this issue open (but with P3 priority)

**Comment by ramya-rao-a** [comment]
> The only issue is with one specific scenario. Let us consider Model A which is in the generated layer and there is an override in the custom layer. We will export the one defined in the custom layer.

Wouldnt that be the responsibility of the person handwriting the custom layer i.e. to add the internal tag to the generated code?

**Comment by sarangan12** [comment]
Yes. That was my first thought. I was wondering if there is any other way. But, now I see you are also thinking the same. We can close this issue.
