### ISSUE TITLE
Unable to generate right types for list of enums

### ISSUE THREAD

**Issue by clouddra** [Azure/autorest.typescript#88]
Code generation does not work for list of enums.

Given the following parameter definition, (an array of string enum as parameters), 

```json
{
  "parameters": [
    {
      "name": "differentEnum",
      "in": "query",
      "required": false,
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "enum1",
          "enum2",
          "enum3",
          "enum4",
          "enum5"
        ]
      },
      "collectionFormat": "csv"
    }
  ]
}
```
, where the enum values are defined in c# as
```csharp
public enum DifferentEnums
{
    enum1,
    enum2,
    enum3,
    enum4,
    enum5
}
```
`autorest.typescript` generates the following class.

```typescript
export interface SomeMethod extends RequestOptionsBase {
  /**
   * @member {Enum[]} [differentEnum]
   */
  extractors?: Enum[];
}
```
In the generated code, `Enum` is not a valid type.

Instead the correct generated code should be
```typescript
export interface SomeMethod extends RequestOptionsBase {
  /**
   * @member {DifferentEnum[]} [differentEnum]
   */
  extractors?: DifferentEnums[];
}
```
The parameter definition works well in swagger UI so it should not be a problem with the definition file itself.

**Comment by RikkiGibson** [comment]
So it looks like we use TypeScript's string enums feature for named enums of strings. I'm not quite sure what to do in the case of an anonymous enum. Where does the name of the generated enum come from in C#?

**Comment by clouddra** [comment]
The enum is not anonymous (named `DifferentEnums` in C#) and enums work when they are not put in a list. And yes they are generated as string enums when they work.

This works (the enums are properly generated)
```csharp
[HttpGet]
public async Task<IActionResult> GetData(DifferentEnum differentEnum)
```

but this does not
```csharp
[HttpGet]
public async Task<IActionResult> GetData(List<DifferentEnum> differentEnum)
```

**Comment by RikkiGibson** [comment]
Just to clarify, does that mean your actual Swagger has an enum named `DifferentEnum` declared, or that the C# generator is somehow coming up with that name when generating?

**Comment by clouddra** [comment]
My C# code has `DifferentEnum` defined the swagger code produced from `Swashbuckle.AspNetCore` has the enum in `swagger.json` as an `x-ms-enum`

```json
{
  "x-ms-enum": {
    "name": "ExtractorType"
  }
}
```

This is not picked up by autorest.typescript when generating enum arrays. It works for plain `enums` not in a list.

**Comment by clouddra** [comment]
@RikkiGibson here is an sample swagger file (no x-ms-enum) that I have generated.

https://gist.githubusercontent.com/clouddra/067f3b54ab7d2c3916405b44e65e6cee/raw/65c979853d56db24f894f3e7de8c0e36bbf5bb17/example-enum-swagger

**Comment by RikkiGibson** [comment]
That's really helpful. I'll be sure to have a look and see what the generator is doing when I have the chance.

**Comment by RikkiGibson** [comment]
I'm seeing that the enum type defined within the array type doesn't get added to CodeModel.EnumTypes in the AutoRest model.. I wonder why that is. 

When `"x-ms-enum": { "name": "ExtractorType" }` is added to the enum definition, I'm seeing an AutoRest error:

```sh
$ AutoRest --typescript \
    --clear-output-folder \
    --output-folder=test/vanilla/generated/Url \
    --license-header=MICROSOFT_MIT_NO_VERSION \
    --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/url.json \
    --typescript.payload-flattening-threshold=1 \
    --typescript.namespace=Fixtures.Url \
    --use=/Users/rigibson/src/autorest.typescript
AutoRest code generation utility [version: 2.0.4262; node: v9.9.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/rigibson/.autorest/@microsoft.azure_autorest-core@2.0.4279/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4279)
   Loading local AutoRest extension '@microsoft.azure/autorest.typescript' (/Users/rigibson/src/autorest.typescript)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.23->2.1.23)

/node_modules/vscode-jsonrpc/lib/messageReader.js:200
                    throw new Error('Header must provide a Content-Length property.');
                          ^
Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at Socket.<anonymous> (/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at Socket.emit (events.js:185:15)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onread (net.js:581:20)
```

It looks like the C# extension depends on a newer version of the modeler which might have fixed the problem. However when I update the `use-extension` in README.md to be the same as in autorest.csharp I see:
```sh
$ AutoRest --typescript \
    --clear-output-folder \
    --output-folder=test/vanilla/generated/Url \
    --license-header=MICROSOFT_MIT_NO_VERSION \
    --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/url.json \
    --typescript.payload-flattening-threshold=1 \
    --typescript.namespace=Fixtures.Url \
    --use=/Users/rigibson/src/autorest.typescript
AutoRest code generation utility [version: 2.0.4262; node: v9.9.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/rigibson/.autorest/@microsoft.azure_autorest-core@2.0.4279/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4279)
   Loading local AutoRest extension '@microsoft.azure/autorest.typescript' (/Users/rigibson/src/autorest.typescript)
   Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51)
Process() cancelled due to exception : Plugin 'modeler' not found.
  Error: Plugin 'modeler' not found.
```

I tried adding this exact version of the modeler to package.json but that doesn't seem to affect anything. Any idea what could be going amiss here @fearthecowboy (the way the C# generator can properly handle a list of enums while the TypeScript generator can't, and the behavior that arises when updating the modeler version)?

**Comment by RikkiGibson** [comment]
I dug back into this issue for a little while. I'm actually not able to get autorest.csharp to produce the `List<DifferentEnum>`--instead it produces a `List<string>` when I give it basically the parameter definition you've shared, @clouddra.

Can you post or recreate the successful autorest.csharp invocation, console output and config for me so I can try to fix this?

**Comment by RikkiGibson** [comment]
Have looked further into this. It seems like the `string` behavior seen in C# is by design for anonymous string enums and we need to make changes in the TypeScript generator to do something similar.
