### ISSUE TITLE
--use=@autorest.typescript@6.0.0-dev.20210121.2 doesn't load the correct packages 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#881]
![image](https://user-images.githubusercontent.com/55688292/109931847-59828800-7d04-11eb-98c3-75f65852debc.png)

I have done autorest --reset before I tried this. 

I managed to use the full package link to make it loading the correct packages.

**Comment by joheredi** [comment]
@qiaozha can you try the following please

```bash
npm install -g autorest #to install the latest autorest version
autorest --reset
```

Followed by the same command you are running but removing `--use=@autorest.typescript@6.0.0-dev.20210121.2`. We started publishing @autorest/typescript to npmjs.org and Autorest now picks up the latest published version by default.

Please let me know if this resolves your issue

**Comment by deyaaeldeen** [comment]
@qiaozha I followed @joheredi instructions and confirm that I do not see the issue. Please feel free to reopen the issue if it still was not resolved on your end.
