### ISSUE TITLE
Core v2 codegen generated some files with unused import

### ISSUE THREAD

**Issue by jeremymeng** [Azure/autorest.typescript#891]
src/generated/models/index.ts:10:1 - error TS6133: 'coreHttps' is declared but its value is never read.

10 import * as coreHttps from "@azure/core-rest-pipeline";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jeremymeng** [comment]
@sarangan12

**Comment by sarangan12** [comment]
To add more context to this issue, in the file `.\autorest.typescript\test\integration\generated\additionalProperties\src\models\index.ts` we have the imports:

```js
import * as coreClient from "@azure/core-client";
import * as coreHttps from "@azure/core-rest-pipeline";
```

(In the above imports, we need to change the coreHttps, which is a different issue). Here, the `coreHttps` is never used in the code. 

Now, take a look at this file, `.\autorest.typescript\test\integration\generated\bodyFormData\src\models\index.ts`. We have the same imports. But the coreHttps is used as in the following code:

```js
export interface Paths1MqqetpFormdataStreamUploadfilePostRequestbodyContentMultipartFormDataSchema {
  /** File to upload. */
  fileContent: coreHttps.RequestBodyType;
  /** File name to upload. Name has to be spelled exactly as written here. */
  fileName: string;
}
```

**Comment by sarangan12** [comment]
A little more context. In addition to the above scenario, there is another scenario also. In the file, `.\autorest.typescript\test\integration\generated\additionalProperties\src\operations\pets.ts`, you can find the following import:

```js
import * as coreHttps from "@azure/core-rest-pipeline";
```

Now this import is never used in the file. 

Now, let us take a look at this file, `.\autorest.typescript\test\integration\generated\mediaTypesV3\src\operations\fooApi.ts`. We have the same imports. But, the coreHttps is used as in the following code:

```js
postSendOnDefault(
    contentType: "application/octet-stream",
    data: coreHttps.RequestBodyType,
    options?: FooApiPostSendOnDefault$binaryOptionalParams
  ): Promise<FooApiPostSendOnDefaultResponse>;
```

**Comment by deyaaeldeen** [comment]
Code complete
