### ISSUE TITLE
Any way to intercept and modify requests that are fired from the generated api-client?

### ISSUE THREAD

**Issue by talor-hammond** [Azure/autorest.typescript#904]
I want to modify `headers` of each request

For context: It's a matter of being able to add an `Authorization` header to each request, as our back-end checks this Auth header

**Comment by sarangan12** [comment]
@talor-hammond Thanks for raising this issue. You can modify the headers of each request. You could do this by adding a custom policy. A sample of the same could be found [here](https://github.com/Azure/autorest.typescript/blob/main/test/integration/httpInfrastructure.spec.ts#L26) 

In the sample, you could see that the request URL is modified to avoid caching. Similarly, You could modify the headers. Please let me know if you have any more questions. Thanks.

**Comment by sarangan12** [comment]
No more action items pending on this issue. Closing this issue. Feel free to reopen if you encounter the same issue again
