### ISSUE TITLE
Autorest.typescript cannot finish when generating codes

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#920]
When generating codes with codegen, it may fall into endless loop and cannot finish. Please refer to pipeline for details: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=865921&view=logs&j=f38d9a4f-f3b8-55f9-3f85-04d40f5c1fc2&t=ceba0f41-7307-52b4-7c7a-37e724e7c1f1

**Comment by sarangan12** [comment]
This is related to https://github.com/Azure/azure-sdk-for-js/pull/15106. We have already discussed offline and decided that it would be etremely difficult to trace this long running op (it eventually completed succesfully) in V4 generator. The same does not happen in V6. 

Closing this issue.
