### ISSUE TITLE
arm-datafactory SDK generation takes hours to complete

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest.typescript#931]
The arm-datafactory SDK takes several hours to generate the SDK. This must be investigated.

**Command Used**
```
autorest --version=V2 --typescript --license-header=MICROSOFT_MIT_NO_VERSION --use=@microsoft.azure/autorest.typescript@4.4.4 --typescript-sdks-folder=C:\Users\sarajama\Projects\azure-sdk-for-js C:\Users\sarajama\Projects\azure-rest-api-specs\specification\datafactory\resource-manager\readme.md

```

**Comment by ramya-rao-a** [comment]
Let's see if the problem persists in v6, otherwise we can close this issue as we are ramping down investments in v4

**Comment by sarangan12** [comment]
I have verified that this issue does not happen in V6. Can close this issue
