### ISSUE TITLE
[LRO] pollUntilDone to throw on "failed" or "canceled" status.

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#936]
For consistency, we need to throw an error when the LRO returns a "failed" or "canceled" status. We should preserve the response body in the error message.

For reference, this is what Python is doing:
https://github.com/Azure/azure-sdk-for-python/blob/99ba7fa4baf6ee4be4082097315a46f2090e438d/sdk/core/azure-core/azure/core/polling/base_polling.py#L62

**Comment by deyaaeldeen** [comment]
code complete
